## Data analysis
Based on year of 2017, 2019, and 2021.

In [1]:
import pandas as pd
import numpy as np

Import unemployment dataset.

In [2]:
df = pd.read_csv('36100651.csv')

print(df.info())
print(df.head(10))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105840 entries, 0 to 105839
Data columns (total 17 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   REF_DATE         105840 non-null  int64
 1   GEO              105840 non-null  object
 2   DGUID            105840 non-null  object
 3   Sector           105840 non-null  object
 4   Characteristics  105840 non-null  object
 5   Indicators       105840 non-null  object
 6   UOM              105840 non-null  object
 7   UOM_ID           105840 non-null  int64
 8   SCALAR_FACTOR    105840 non-null  object
 9   SCALAR_ID        105840 non-null  int64
 10  VECTOR           105840 non-null  object
 11  COORDINATE       105840 non-null  object
 12  VALUE            102816 non-null  float64
 13  STATUS           3024 non-null    object
 14  SYMBOL           0 non-null       float64
 15  TERMINATED       0 non-null       float64
 16  DECIMALS         105840 non-null  int64
dtypes: float64(3), int64(4), object(10)
memory usage: 13.7+ MB
None
   REF_DATE     GEO           DGUID                         Sector  \
0      2010  Canada  2016A000011124  Total non-profit institutions
1      2010  Canada  2016A000011124  Total non-profit institutions
2      2010  Canada  2016A000011124  Total non-profit institutions
3      2010  Canada  2016A000011124  Total non-profit institutions
4      2010  Canada  2016A000011124  Total non-profit institutions
5      2010  Canada  2016A000011124  Total non-profit institutions
6      2010  Canada  2016A000011124  Total non-profit institutions
7      2010  Canada  2016A000011124  Total non-profit institutions
8      2010  Canada  2016A000011124  Total non-profit institutions
9      2010  Canada  2016A000011124  Total non-profit institutions

    Characteristics                         Indicators      UOM  UOM_ID  \
0    Male employees                     Number of jobs     Jobs     190
1    Male employees                       Hours worked    Hours     152
2    Male employees                 Wages and salaries  Dollars      81
3    Male employees        Average annual hours worked    Hours     152
4    Male employees        Average weekly hours worked    Hours     152
5    Male employees  Average annual wages and salaries  Dollars      81
6    Male employees                Average hourly wage  Dollars      81
7  Female employees                     Number of jobs     Jobs     190
8  Female employees                       Hours worked    Hours     152
9  Female employees                 Wages and salaries  Dollars      81

  SCALAR_FACTOR  SCALAR_ID       VECTOR COORDINATE       VALUE STATUS  SYMBOL  \
0         units          0  v1273033811    1.1.1.1   642584.00    NaN     NaN
1     thousands          3  v1273033812    1.1.1.2  1048516.00    NaN     NaN
2      millions          6  v1273033813    1.1.1.3    30805.00    NaN     NaN
3         units          0  v1273033814    1.1.1.4     1632.00    NaN     NaN
4         units          0  v1273033815    1.1.1.5       31.00    NaN     NaN
5         units          0  v1273033816    1.1.1.6    47940.00    NaN     NaN
6         units          0  v1273033817    1.1.1.7       29.38    NaN     NaN
7         units          0  v1273033909    1.1.2.1  1500394.00    NaN     NaN
8     thousands          3  v1273033910    1.1.2.2  2331018.00    NaN     NaN
9      millions          6  v1273033911    1.1.2.3    60943.00    NaN     NaN

   TERMINATED  DECIMALS
0         NaN         0
1         NaN         0
2         NaN         0
3         NaN         0
4         NaN         0
5         NaN         0
6         NaN         2
7         NaN         0
8         NaN         0
9         NaN         0

Filter only the essential part of the dataset.

In [3]:
print("Grab the only the essential part of database.")
df_sorted = df[['REF_DATE','GEO','Sector','Characteristics','Indicators','UOM','SCALAR_FACTOR','VALUE']]
print(df_sorted.head(20))

print(df_sorted.info())
grouped = df.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.size]))

Grab the only the essential part of database.
    REF_DATE     GEO                         Sector      Characteristics  \
0       2010  Canada  Total non-profit institutions       Male employees
1       2010  Canada  Total non-profit institutions       Male employees
2       2010  Canada  Total non-profit institutions       Male employees
3       2010  Canada  Total non-profit institutions       Male employees
4       2010  Canada  Total non-profit institutions       Male employees
5       2010  Canada  Total non-profit institutions       Male employees
6       2010  Canada  Total non-profit institutions       Male employees
7       2010  Canada  Total non-profit institutions     Female employees
8       2010  Canada  Total non-profit institutions     Female employees
9       2010  Canada  Total non-profit institutions     Female employees
10      2010  Canada  Total non-profit institutions     Female employees
11      2010  Canada  Total non-profit institutions     Female employees
12      2010  Canada  Total non-profit institutions     Female employees
13      2010  Canada  Total non-profit institutions     Female employees
14      2010  Canada  Total non-profit institutions  Immigrant employees
15      2010  Canada  Total non-profit institutions  Immigrant employees
16      2010  Canada  Total non-profit institutions  Immigrant employees
17      2010  Canada  Total non-profit institutions  Immigrant employees
18      2010  Canada  Total non-profit institutions  Immigrant employees
19      2010  Canada  Total non-profit institutions  Immigrant employees

                           Indicators      UOM SCALAR_FACTOR       VALUE
0                      Number of jobs     Jobs         units   642584.00
1                        Hours worked    Hours     thousands  1048516.00
2                  Wages and salaries  Dollars      millions    30805.00
3         Average annual hours worked    Hours         units     1632.00
4         Average weekly hours worked    Hours         units       31.00
5   Average annual wages and salaries  Dollars         units    47940.00
6                 Average hourly wage  Dollars         units       29.38
7                      Number of jobs     Jobs         units  1500394.00
8                        Hours worked    Hours     thousands  2331018.00
9                  Wages and salaries  Dollars      millions    60943.00
10        Average annual hours worked    Hours         units     1554.00
11        Average weekly hours worked    Hours         units       30.00
12  Average annual wages and salaries  Dollars         units    40618.00
13                Average hourly wage  Dollars         units       26.14
14                     Number of jobs     Jobs         units   503236.00
15                       Hours worked    Hours     thousands   802251.00
16                 Wages and salaries  Dollars      millions    22212.00
17        Average annual hours worked    Hours         units     1594.00
18        Average weekly hours worked    Hours         units       31.00
19  Average annual wages and salaries  Dollars         units    44138.00
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105840 entries, 0 to 105839
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   REF_DATE         105840 non-null  int64
 1   GEO              105840 non-null  object
 2   Sector           105840 non-null  object
 3   Characteristics  105840 non-null  object
 4   Indicators       105840 non-null  object
 5   UOM              105840 non-null  object
 6   SCALAR_FACTOR    105840 non-null  object
 7   VALUE            102816 non-null  float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.5+ MB
None
                                   size
Characteristics
15 to 24 years                     5880
25 to 34 years                     5880
35 to 44 years                     5880
45 to 54 years                     5880
55 to 64 years                     5880
65 years old and over              5880
College diploma                    5880
Female employees                   5880
High school diploma and less       5880
Immigrant employees                5880
Indigenous identity employees      5880
Male employees                     5880
Non-immigrant employees            5880
Non-indigenous identity employees  5880
Not a visible minority             5880
Trade certificate                  5880
University degree and higher       5880
Visible minority                   5880

Grabbing the data preivous from 2016.

In [4]:
print("Grabbing the data previous from 2016.")
df_below_2016_year = df_sorted.loc[
    (df_sorted['REF_DATE'] == 2014) |
    (df_sorted['REF_DATE'] == 2015) |
    (df_sorted['REF_DATE'] == 2016)
]
print(df_below_2016_year.head(20))
print(df_below_2016_year.info())
grouped = df_below_2016_year.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_below_2016_year.index))

Grabbing the data previous from 2016.
       REF_DATE     GEO                         Sector      Characteristics  \
35280      2014  Canada  Total non-profit institutions       Male employees
35281      2014  Canada  Total non-profit institutions       Male employees
35282      2014  Canada  Total non-profit institutions       Male employees
35283      2014  Canada  Total non-profit institutions       Male employees
35284      2014  Canada  Total non-profit institutions       Male employees
35285      2014  Canada  Total non-profit institutions       Male employees
35286      2014  Canada  Total non-profit institutions       Male employees
35287      2014  Canada  Total non-profit institutions     Female employees
35288      2014  Canada  Total non-profit institutions     Female employees
35289      2014  Canada  Total non-profit institutions     Female employees
35290      2014  Canada  Total non-profit institutions     Female employees
35291      2014  Canada  Total non-profit institutions     Female employees
35292      2014  Canada  Total non-profit institutions     Female employees
35293      2014  Canada  Total non-profit institutions     Female employees
35294      2014  Canada  Total non-profit institutions  Immigrant employees
35295      2014  Canada  Total non-profit institutions  Immigrant employees
35296      2014  Canada  Total non-profit institutions  Immigrant employees
35297      2014  Canada  Total non-profit institutions  Immigrant employees
35298      2014  Canada  Total non-profit institutions  Immigrant employees
35299      2014  Canada  Total non-profit institutions  Immigrant employees

                              Indicators      UOM SCALAR_FACTOR       VALUE
35280                     Number of jobs     Jobs         units   685232.00
35281                       Hours worked    Hours     thousands  1103789.00
35282                 Wages and salaries  Dollars      millions    35465.00
35283        Average annual hours worked    Hours         units     1611.00
35284        Average weekly hours worked    Hours         units       31.00
35285  Average annual wages and salaries  Dollars         units    51756.00
35286                Average hourly wage  Dollars         units       32.13
35287                     Number of jobs     Jobs         units  1599293.00
35288                       Hours worked    Hours     thousands  2458766.00
35289                 Wages and salaries  Dollars      millions    68843.00
35290        Average annual hours worked    Hours         units     1537.00
35291        Average weekly hours worked    Hours         units       30.00
35292  Average annual wages and salaries  Dollars         units    43046.00
35293                Average hourly wage  Dollars         units       28.00
35294                     Number of jobs     Jobs         units   552297.00
35295                       Hours worked    Hours     thousands   869845.00
35296                 Wages and salaries  Dollars      millions    25741.00
35297        Average annual hours worked    Hours         units     1575.00
35298        Average weekly hours worked    Hours         units       30.00
35299  Average annual wages and salaries  Dollars         units    46607.00
<class 'pandas.core.frame.DataFrame'>
Index: 26460 entries, 35280 to 61739
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         26460 non-null  int64
 1   GEO              26460 non-null  object
 2   Sector           26460 non-null  object
 3   Characteristics  26460 non-null  object
 4   Indicators       26460 non-null  object
 5   UOM              26460 non-null  object
 6   SCALAR_FACTOR    26460 non-null  object
 7   VALUE            25704 non-null  float64
dtypes: float64(1), int64(1), object(6)
memory usage: 1.8+ MB
None
                   sum  size
REF_DATE
2014      2.203758e+08  8820
2015      2.248252e+08  8820
2016      2.287389e+08  8820
The total number of this one is  26460

Grabbing the data from 2017, 2019, and 2021.

In [5]:
print("Grabbing the data from 2017, 2019, and 2021.")
df_by_year = df_sorted.loc[
    (df_sorted['REF_DATE'] == 2017) |
    (df_sorted['REF_DATE'] == 2019) |
    (df_sorted['REF_DATE'] == 2021)
]
print(df_by_year.head(20))
print(df_by_year.info())
grouped = df_by_year.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_by_year.index))

grouped = df_by_year.groupby(['GEO'])
print(grouped['VALUE'].agg([np.sum, np.size]))

print("You can ignore below for now")

Grabbing the data from 2017, 2019, and 2021.
       REF_DATE     GEO                         Sector      Characteristics  \
61740      2017  Canada  Total non-profit institutions       Male employees
61741      2017  Canada  Total non-profit institutions       Male employees
61742      2017  Canada  Total non-profit institutions       Male employees
61743      2017  Canada  Total non-profit institutions       Male employees
61744      2017  Canada  Total non-profit institutions       Male employees
61745      2017  Canada  Total non-profit institutions       Male employees
61746      2017  Canada  Total non-profit institutions       Male employees
61747      2017  Canada  Total non-profit institutions     Female employees
61748      2017  Canada  Total non-profit institutions     Female employees
61749      2017  Canada  Total non-profit institutions     Female employees
61750      2017  Canada  Total non-profit institutions     Female employees
61751      2017  Canada  Total non-profit institutions     Female employees
61752      2017  Canada  Total non-profit institutions     Female employees
61753      2017  Canada  Total non-profit institutions     Female employees
61754      2017  Canada  Total non-profit institutions  Immigrant employees
61755      2017  Canada  Total non-profit institutions  Immigrant employees
61756      2017  Canada  Total non-profit institutions  Immigrant employees
61757      2017  Canada  Total non-profit institutions  Immigrant employees
61758      2017  Canada  Total non-profit institutions  Immigrant employees
61759      2017  Canada  Total non-profit institutions  Immigrant employees

                              Indicators      UOM SCALAR_FACTOR       VALUE
61740                     Number of jobs     Jobs         units   714167.00
61741                       Hours worked    Hours     thousands  1140737.00
61742                 Wages and salaries  Dollars      millions    38502.00
61743        Average annual hours worked    Hours         units     1597.00
61744        Average weekly hours worked    Hours         units       31.00
61745  Average annual wages and salaries  Dollars         units    53912.00
61746                Average hourly wage  Dollars         units       33.75
61747                     Number of jobs     Jobs         units  1665533.00
61748                       Hours worked    Hours     thousands  2556840.00
61749                 Wages and salaries  Dollars      millions    75370.00
61750        Average annual hours worked    Hours         units     1535.00
61751        Average weekly hours worked    Hours         units       30.00
61752  Average annual wages and salaries  Dollars         units    45253.00
61753                Average hourly wage  Dollars         units       29.48
61754                     Number of jobs     Jobs         units   606032.00
61755                       Hours worked    Hours     thousands   950520.00
61756                 Wages and salaries  Dollars      millions    29414.00
61757        Average annual hours worked    Hours         units     1568.00
61758        Average weekly hours worked    Hours         units       30.00
61759  Average annual wages and salaries  Dollars         units    48536.00
<class 'pandas.core.frame.DataFrame'>
Index: 26460 entries, 61740 to 105839
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         26460 non-null  int64
 1   GEO              26460 non-null  object
 2   Sector           26460 non-null  object
 3   Characteristics  26460 non-null  object
 4   Indicators       26460 non-null  object
 5   UOM              26460 non-null  object
 6   SCALAR_FACTOR    26460 non-null  object
 7   VALUE            25704 non-null  float64
dtypes: float64(1), int64(1), object(6)
memory usage: 1.8+ MB
None
                   sum  size
REF_DATE
2017      2.299223e+08  8820
2019      2.404879e+08  8820
2021      2.496811e+08  8820
The total number of this one is  26460
                                    sum  size
GEO
Alberta                    4.448243e+07  1890
British Columbia           4.906279e+07  1890
Canada                     2.839632e+08  1890
Manitoba                   2.402617e+07  1890
New Brunswick              1.727295e+07  1890
Newfoundland and Labrador  1.654912e+07  1890
Northwest Territories      1.562757e+07  1890
Nova Scotia                1.985692e+07  1890
Nunavut                    1.866912e+07  1890
Ontario                    1.077189e+08  1890
Prince Edward Island       1.122717e+07  1890
Quebec                     7.742105e+07  1890
Saskatchewan               2.135077e+07  1890
Yukon                      1.286330e+07  1890
You can ignore below for now

Sorted the data from above, Average worked hours worked from all province.

In [6]:
df_hours_worked = df_by_year.loc[
    (df_by_year['Indicators'] == 'Average annual hours worked') 
]
grouped = df_hours_worked.groupby(['GEO'])
print(grouped['VALUE'].agg([np.sum, np.mean, np.std, np.size]))
print("The total number of this one is ",len(df_hours_worked.index))

                                sum         mean         std  size
GEO
Alberta                    421125.0  1559.722222  214.374166   270
British Columbia           403872.0  1495.822222  210.223261   270
Canada                     411363.0  1523.566667  226.577808   270
Manitoba                   414961.0  1536.892593  220.703033   270
New Brunswick              439174.0  1626.570370  240.608601   270
Newfoundland and Labrador  423965.0  1643.275194  281.608149   270
Northwest Territories      396757.0  1537.817829  256.593597   270
Nova Scotia                420763.0  1558.381481  237.281739   270
Nunavut                    387650.0  1656.623932  235.799516   270
Ontario                    419076.0  1552.133333  241.749980   270
Prince Edward Island       400908.0  1553.906977  264.634038   270
Quebec                     393964.0  1459.125926  229.279814   270
Saskatchewan               406946.0  1507.207407  216.752599   270
Yukon                      336817.0  1439.388889  252.854278   270
The total number of this one is  3780

Average annual hours sorted by province in 2017

In [11]:
df_2017_hours_worked = df_by_year.loc[
    (df_by_year['Indicators'] == 'Average annual hours worked') &
    (df_by_year['REF_DATE'] == 2017)
]
grouped = df_2017_hours_worked.groupby(['GEO'])
print(grouped['VALUE'].agg([np.sum, np.mean, np.std, np.size]))
print("The total number of this one is ",len(df_2017_hours_worked.index))

                                sum         mean         std  size
GEO
Alberta                    139471.0  1549.677778  209.517896    90
British Columbia           133998.0  1488.866667  211.975576    90
Canada                     136334.0  1514.822222  228.635355    90
Manitoba                   138686.0  1540.955556  225.058889    90
New Brunswick              145989.0  1622.100000  244.732004    90
Newfoundland and Labrador  141626.0  1646.813953  286.243356    90
Northwest Territories      134051.0  1558.732558  272.641563    90
Nova Scotia                138988.0  1544.311111  238.652898    90
Nunavut                    127275.0  1631.730769  231.943157    90
Ontario                    139528.0  1550.311111  245.275797    90
Prince Edward Island       130236.0  1514.372093  275.617811    90
Quebec                     129571.0  1439.677778  229.399942    90
Saskatchewan               132854.0  1476.155556  214.770267    90
Yukon                      112782.0  1445.923077  247.766216    90
The total number of this one is  1260

Average annual hours sorted by province in 2019

In [12]:
df_2019_hours_worked = df_by_year.loc[
    (df_by_year['Indicators'] == 'Average annual hours worked') &
    (df_by_year['REF_DATE'] == 2019)
]
grouped = df_2019_hours_worked.groupby(['GEO'])
print(grouped['VALUE'].agg([np.sum, np.mean, np.std, np.size]))
print("The total number of this one is ",len(df_2019_hours_worked.index))

                                sum         mean         std  size
GEO
Alberta                    139497.0  1549.966667  219.827995    90
British Columbia           134722.0  1496.911111  210.412737    90
Canada                     136761.0  1519.566667  228.559635    90
Manitoba                   136637.0  1518.188889  221.022084    90
New Brunswick              148104.0  1645.600000  243.517565    90
Newfoundland and Labrador  141198.0  1641.837209  285.133647    90
Northwest Territories      133945.0  1557.500000  249.557950    90
Nova Scotia                141902.0  1576.688889  238.005507    90
Nunavut                    129411.0  1659.115385  227.063581    90
Ontario                    138316.0  1536.844444  242.078124    90
Prince Edward Island       133448.0  1551.720930  260.965702    90
Quebec                     131906.0  1465.622222  233.630967    90
Saskatchewan               136679.0  1518.655556  217.908091    90
Yukon                      111600.0  1430.769231  260.450405    90
The total number of this one is  1260

Average annual hours sorted by province in 2021

In [13]:
df_2021_hours_worked = df_by_year.loc[
    (df_by_year['Indicators'] == 'Average annual hours worked') &
    (df_by_year['REF_DATE'] == 2021)
]
grouped = df_2021_hours_worked.groupby(['GEO'])
print(grouped['VALUE'].agg([np.sum, np.mean, np.std, np.size]))
print("The total number of this one is ",len(df_2021_hours_worked.index))

                                sum         mean         std  size
GEO
Alberta                    142157.0  1579.522222  214.673634    90
British Columbia           135152.0  1501.688889  210.434043    90
Canada                     138268.0  1536.311111  224.487814    90
Manitoba                   139638.0  1551.533333  217.105070    90
New Brunswick              145081.0  1612.011111  234.910908    90
Newfoundland and Labrador  141141.0  1641.174419  276.621984    90
Northwest Territories      128761.0  1497.220930  244.857913    90
Nova Scotia                139873.0  1554.144444  236.672749    90
Nunavut                    130964.0  1679.025641  248.496621    90
Ontario                    141232.0  1569.244444  239.467401    90
Prince Edward Island       137224.0  1595.627907  253.625108    90
Quebec                     132487.0  1472.077778  226.023178    90
Saskatchewan               137413.0  1526.811111  216.551205    90
Yukon                      112435.0  1441.474359  253.221413    90
The total number of this one is  1260