## Data analysis for employment in non-profit organization

Divided by four datasets instead of two datasets and then later into another two datasets.

Import all requirement,

In [5]:
import pandas as pd
import numpy as np
import ydata_profiling as pp  
from ydata_profiling import ProfileReport 
import warnings
import os

warnings.filterwarnings('ignore')

Import unemployment dataset.

In [6]:
df = pd.read_csv('36100651.csv')

print(df.info())
print(df.head(10))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105840 entries, 0 to 105839
Data columns (total 17 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   REF_DATE         105840 non-null  int64
 1   GEO              105840 non-null  object
 2   DGUID            105840 non-null  object
 3   Sector           105840 non-null  object
 4   Characteristics  105840 non-null  object
 5   Indicators       105840 non-null  object
 6   UOM              105840 non-null  object
 7   UOM_ID           105840 non-null  int64
 8   SCALAR_FACTOR    105840 non-null  object
 9   SCALAR_ID        105840 non-null  int64
 10  VECTOR           105840 non-null  object
 11  COORDINATE       105840 non-null  object
 12  VALUE            102816 non-null  float64
 13  STATUS           3024 non-null    object
 14  SYMBOL           0 non-null       float64
 15  TERMINATED       0 non-null       float64
 16  DECIMALS         105840 non-null  int64
dtypes: float64(3), int64(4), object(10)
memory usage: 13.7+ MB
None
   REF_DATE     GEO           DGUID                         Sector  \
0      2010  Canada  2016A000011124  Total non-profit institutions
1      2010  Canada  2016A000011124  Total non-profit institutions
2      2010  Canada  2016A000011124  Total non-profit institutions
3      2010  Canada  2016A000011124  Total non-profit institutions
4      2010  Canada  2016A000011124  Total non-profit institutions
5      2010  Canada  2016A000011124  Total non-profit institutions
6      2010  Canada  2016A000011124  Total non-profit institutions
7      2010  Canada  2016A000011124  Total non-profit institutions
8      2010  Canada  2016A000011124  Total non-profit institutions
9      2010  Canada  2016A000011124  Total non-profit institutions

    Characteristics                         Indicators      UOM  UOM_ID  \
0    Male employees                     Number of jobs     Jobs     190
1    Male employees                       Hours worked    Hours     152
2    Male employees                 Wages and salaries  Dollars      81
3    Male employees        Average annual hours worked    Hours     152
4    Male employees        Average weekly hours worked    Hours     152
5    Male employees  Average annual wages and salaries  Dollars      81
6    Male employees                Average hourly wage  Dollars      81
7  Female employees                     Number of jobs     Jobs     190
8  Female employees                       Hours worked    Hours     152
9  Female employees                 Wages and salaries  Dollars      81

  SCALAR_FACTOR  SCALAR_ID       VECTOR COORDINATE       VALUE STATUS  SYMBOL  \
0         units          0  v1273033811    1.1.1.1   642584.00    NaN     NaN
1     thousands          3  v1273033812    1.1.1.2  1048516.00    NaN     NaN
2      millions          6  v1273033813    1.1.1.3    30805.00    NaN     NaN
3         units          0  v1273033814    1.1.1.4     1632.00    NaN     NaN
4         units          0  v1273033815    1.1.1.5       31.00    NaN     NaN
5         units          0  v1273033816    1.1.1.6    47940.00    NaN     NaN
6         units          0  v1273033817    1.1.1.7       29.38    NaN     NaN
7         units          0  v1273033909    1.1.2.1  1500394.00    NaN     NaN
8     thousands          3  v1273033910    1.1.2.2  2331018.00    NaN     NaN
9      millions          6  v1273033911    1.1.2.3    60943.00    NaN     NaN

   TERMINATED  DECIMALS
0         NaN         0
1         NaN         0
2         NaN         0
3         NaN         0
4         NaN         0
5         NaN         0
6         NaN         2
7         NaN         0
8         NaN         0
9         NaN         0

Filter only the essential columns of the original dataset.

In [7]:
print("Grab the only the essential part of database.")

# From the original, 
# DGUID, UOM_ID, SCALAR_ID, VECTOR, COORDINATE, STATUS, SYMBOL, TERMINATED, and DECIMALS columns are removed.

df_sorted = df[['REF_DATE','GEO','Sector','Characteristics','Indicators','UOM','SCALAR_FACTOR','VALUE']]

print(df_sorted.head(20))
print(df_sorted.info())

print("Sort by Characteristics")
grouped = df_sorted.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.size]))

print("Sort by Indicator")
grouped = df_sorted.groupby(['Indicators'])
print(grouped['VALUE'].agg([np.size]))

Grab the only the essential part of database.
    REF_DATE     GEO                         Sector      Characteristics  \
0       2010  Canada  Total non-profit institutions       Male employees
1       2010  Canada  Total non-profit institutions       Male employees
2       2010  Canada  Total non-profit institutions       Male employees
3       2010  Canada  Total non-profit institutions       Male employees
4       2010  Canada  Total non-profit institutions       Male employees
5       2010  Canada  Total non-profit institutions       Male employees
6       2010  Canada  Total non-profit institutions       Male employees
7       2010  Canada  Total non-profit institutions     Female employees
8       2010  Canada  Total non-profit institutions     Female employees
9       2010  Canada  Total non-profit institutions     Female employees
10      2010  Canada  Total non-profit institutions     Female employees
11      2010  Canada  Total non-profit institutions     Female employees
12      2010  Canada  Total non-profit institutions     Female employees
13      2010  Canada  Total non-profit institutions     Female employees
14      2010  Canada  Total non-profit institutions  Immigrant employees
15      2010  Canada  Total non-profit institutions  Immigrant employees
16      2010  Canada  Total non-profit institutions  Immigrant employees
17      2010  Canada  Total non-profit institutions  Immigrant employees
18      2010  Canada  Total non-profit institutions  Immigrant employees
19      2010  Canada  Total non-profit institutions  Immigrant employees

                           Indicators      UOM SCALAR_FACTOR       VALUE
0                      Number of jobs     Jobs         units   642584.00
1                        Hours worked    Hours     thousands  1048516.00
2                  Wages and salaries  Dollars      millions    30805.00
3         Average annual hours worked    Hours         units     1632.00
4         Average weekly hours worked    Hours         units       31.00
5   Average annual wages and salaries  Dollars         units    47940.00
6                 Average hourly wage  Dollars         units       29.38
7                      Number of jobs     Jobs         units  1500394.00
8                        Hours worked    Hours     thousands  2331018.00
9                  Wages and salaries  Dollars      millions    60943.00
10        Average annual hours worked    Hours         units     1554.00
11        Average weekly hours worked    Hours         units       30.00
12  Average annual wages and salaries  Dollars         units    40618.00
13                Average hourly wage  Dollars         units       26.14
14                     Number of jobs     Jobs         units   503236.00
15                       Hours worked    Hours     thousands   802251.00
16                 Wages and salaries  Dollars      millions    22212.00
17        Average annual hours worked    Hours         units     1594.00
18        Average weekly hours worked    Hours         units       31.00
19  Average annual wages and salaries  Dollars         units    44138.00
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105840 entries, 0 to 105839
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   REF_DATE         105840 non-null  int64
 1   GEO              105840 non-null  object
 2   Sector           105840 non-null  object
 3   Characteristics  105840 non-null  object
 4   Indicators       105840 non-null  object
 5   UOM              105840 non-null  object
 6   SCALAR_FACTOR    105840 non-null  object
 7   VALUE            102816 non-null  float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.5+ MB
None
Sort by Characteristics
                                   size
Characteristics
15 to 24 years                     5880
25 to 34 years                     5880
35 to 44 years                     5880
45 to 54 years                     5880
55 to 64 years                     5880
65 years old and over              5880
College diploma                    5880
Female employees                   5880
High school diploma and less       5880
Immigrant employees                5880
Indigenous identity employees      5880
Male employees                     5880
Non-immigrant employees            5880
Non-indigenous identity employees  5880
Not a visible minority             5880
Trade certificate                  5880
University degree and higher       5880
Visible minority                   5880
Sort by Indicator
                                    size
Indicators
Average annual hours worked        15120
Average annual wages and salaries  15120
Average hourly wage                15120
Average weekly hours worked        15120
Hours worked                       15120
Number of jobs                     15120
Wages and salaries                 15120

Check for the missing value from the sorted dataset done above.
* Notice there is missing value in this dataset.

In [8]:
print("Original database null counter")
print(df.isnull().sum())
print("\n Modified dataset null counter.")
print(df_sorted.isnull().sum())

Original database null counter
REF_DATE                0
GEO                     0
DGUID                   0
Sector                  0
Characteristics         0
Indicators              0
UOM                     0
UOM_ID                  0
SCALAR_FACTOR           0
SCALAR_ID               0
VECTOR                  0
COORDINATE              0
VALUE                3024
STATUS             102816
SYMBOL             105840
TERMINATED         105840
DECIMALS                0
dtype: int64

 Modified dataset null counter.
REF_DATE              0
GEO                   0
Sector                0
Characteristics       0
Indicators            0
UOM                   0
SCALAR_FACTOR         0
VALUE              3024
dtype: int64

Dropping missing value from the sorted dataset.

In [9]:
df_sorted_na = df_sorted.dropna()

Check now if there's still a missing data inside modified sorted dataset done above.

In [10]:
print("Modified dataset modification after removing missing value and it's total counter")
print(df_sorted_na.isnull().sum())
# print(df_sorted_na.head(20))

print(df_sorted_na.info())
grouped = df_sorted_na.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.size]))

grouped = df_sorted_na.groupby(['Indicators'])
print(grouped['VALUE'].agg([np.size]))

Modified dataset modification after removing missing value and it's total counter
REF_DATE           0
GEO                0
Sector             0
Characteristics    0
Indicators         0
UOM                0
SCALAR_FACTOR      0
VALUE              0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Index: 102816 entries, 0 to 105839
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   REF_DATE         102816 non-null  int64
 1   GEO              102816 non-null  object
 2   Sector           102816 non-null  object
 3   Characteristics  102816 non-null  object
 4   Indicators       102816 non-null  object
 5   UOM              102816 non-null  object
 6   SCALAR_FACTOR    102816 non-null  object
 7   VALUE            102816 non-null  float64
dtypes: float64(1), int64(1), object(6)
memory usage: 7.1+ MB
None
                                   size
Characteristics
15 to 24 years                     5376
25 to 34 years                     5880
35 to 44 years                     5880
45 to 54 years                     5880
55 to 64 years                     5880
65 years old and over              5376
College diploma                    5880
Female employees                   5880
High school diploma and less       5880
Immigrant employees                5544
Indigenous identity employees      5544
Male employees                     5880
Non-immigrant employees            5544
Non-indigenous identity employees  5544
Not a visible minority             5880
Trade certificate                  5544
University degree and higher       5544
Visible minority                   5880
                                    size
Indicators
Average annual hours worked        14688
Average annual wages and salaries  14688
Average hourly wage                14688
Average weekly hours worked        14688
Hours worked                       14688
Number of jobs                     14688
Wages and salaries                 14688

Panda Profiling for original dataset (CSV file),

In [11]:
# https://medium.com/analytics-vidhya/pandas-profiling-5ecd0b977ecd

pp = ProfileReport(df, title="Pandas Profiling Report")
pp_df = pp.to_html()

f = open("df_NoMod.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

Summarize dataset:   5%|▍         | 1/22 [00:01<00:41,  1.97s/it, Describe variable:REF_DATE]

Summarize dataset: 100%|██████████| 31/31 [00:08<00:00,  3.73it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:07<00:00,  7.20s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.10s/it]

Panda Profiling for sorted dataset,

In [12]:
pp_sorted = ProfileReport(df_sorted, title="Pandas Profiling Report with Columns Sorted")
pp_df_sorted = pp_sorted.to_html()

f = open("df_Sorted.html", "a") # Expert modifying data into html file.
f.write(pp_df_sorted)
f.close()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Summarize dataset: 100%|██████████| 21/21 [00:04<00:00,  4.71it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.68s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.00s/it]

Panda Profiling for modified sorted dataset (missing data removed),

In [13]:
pp = ProfileReport(df_sorted_na, title="Pandas Profiling Report with Columned Sorted and NA Removed")
pp_df_sorted = pp.to_html()

f = open("df_Sorted-no-na.html", "a") # Expert modifying data into html file.
f.write(pp_df_sorted)
f.close()

Summarize dataset: 100%|██████████| 21/21 [00:04<00:00,  4.68it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.32s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.89it/s]

In [14]:
# Differences should be, there will be less data to work on.
# Particularly business non-profit organizations and community organizations haven't given more accurate data (more missing values).

Next step, I will filtered the dataset by all the 'Indicators' given below. All of them done with modified sorted dataset (filtered missing value)
* Notice there will be seven indicators data inside.
* Notice there will be divided by seven datasets based on indicators.

In [15]:
# All columns
print(df_sorted_na.info())

# All indicators
grouped = df_sorted_na.groupby(['Indicators'])
print(grouped['VALUE'].agg([np.size]))

<class 'pandas.core.frame.DataFrame'>
Index: 102816 entries, 0 to 105839
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   REF_DATE         102816 non-null  int64
 1   GEO              102816 non-null  object
 2   Sector           102816 non-null  object
 3   Characteristics  102816 non-null  object
 4   Indicators       102816 non-null  object
 5   UOM              102816 non-null  object
 6   SCALAR_FACTOR    102816 non-null  object
 7   VALUE            102816 non-null  float64
dtypes: float64(1), int64(1), object(6)
memory usage: 11.1+ MB
None
                                    size
Indicators
Average annual hours worked        14688
Average annual wages and salaries  14688
Average hourly wage                14688
Average weekly hours worked        14688
Hours worked                       14688
Number of jobs                     14688
Wages and salaries                 14688

Average annual hours worked from modified sorted dataset.

In [16]:
# Average annual hours worked        15120
print("\nAverage annual hours worked")
df_AvgAnnHrsWrk = df_sorted_na.loc[
    (df_sorted_na['Indicators'] == 'Average annual hours worked')
]
# grouped = df_AvgAnnHrsWrk.groupby(['GEO'])
grouped = df_AvgAnnHrsWrk.groupby(['Indicators'])
print(grouped['VALUE'].agg([np.sum, np.mean, np.std, np.size]))
print("The total number of this one is ",len(df_AvgAnnHrsWrk.index))

Average annual hours worked
                                    sum         mean         std   size
Indicators
Average annual hours worked  22787494.0  1551.436138  252.784087  14688
The total number of this one is  14688

Panda Profiling only for "Average annual hours worked"

In [17]:
pp = ProfileReport(df_AvgAnnHrsWrk, title="Average annual hours worked")
pp_df = pp.to_html()

f = open("Average annual hours worked.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Summarize dataset: 100%|██████████| 21/21 [00:01<00:00, 11.05it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.20s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.03it/s]

Average annual wages and salaries from modified sorted dataset. (Mention above)

In [18]:
# Average annual wages and salaries  15120
print("\nAverage annual wages and salaries")
df_AvgAnnWages = df_sorted_na.loc[
    (df_sorted_na['Indicators'] == 'Average annual wages and salaries')
]
grouped = df_AvgAnnWages.groupby(['Indicators'])
print(grouped['VALUE'].agg([np.sum, np.mean, np.std, np.size]))
print("The total number of this one is ",len(df_AvgAnnWages.index))

Average annual wages and salaries
                                           sum          mean           std  \
Indicators
Average annual wages and salaries  643404649.0  43804.782748  16620.351087

                                    size
Indicators
Average annual wages and salaries  14688
The total number of this one is  14688

Panda Profiling only for "Average annual wages and salaries"

In [19]:
pp = ProfileReport(df_AvgAnnWages, title="Average annual wages and salaries")
pp_df = pp.to_html()

f = open("Average annual wages and salaries.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

Summarize dataset: 100%|██████████| 21/21 [00:01<00:00, 12.15it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:02<00:00,  2.97s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.01it/s]

Average hourly wage from modified sorted dataset. (Mentions above)

In [20]:
# Average hourly wage                15120
print("\nAverage hourly wage")
df_AvgHrsWages = df_sorted_na.loc[
    (df_sorted_na['Indicators'] == 'Average hourly wage')
]
grouped = df_AvgHrsWages.groupby(['Indicators'])
print(grouped['VALUE'].agg([np.sum, np.mean, np.std, np.size]))
print("The total number of this one is ",len(df_AvgHrsWages.index))

Average hourly wage
                           sum       mean       std   size
Indicators
Average hourly wage  408702.58  27.825611  8.601721  14688
The total number of this one is  14688

Panda Profiling only for "Average hourly wages"

In [21]:
pp = ProfileReport(df_AvgHrsWages, title="Average hourly wage")
pp_df = pp.to_html()

f = open("Average hourly wages.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Summarize dataset: 100%|██████████| 21/21 [00:01<00:00, 11.72it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.17s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.03it/s]

Average weekly hours worked from modified sorted dataset.

In [22]:
# Average weekly hours worked        15120
print("\nAverage weekly hours worked")
df_AvgWeekHrsWrked = df_sorted_na.loc[
    (df_sorted_na['Indicators'] == 'Average weekly hours worked')
]
grouped = df_AvgWeekHrsWrked.groupby(['Indicators'])
print(grouped['VALUE'].agg([np.sum, np.mean, np.std, np.size]))
print("The total number of this one is ",len(df_AvgWeekHrsWrked.index))

Average weekly hours worked
                                  sum       mean      std   size
Indicators
Average weekly hours worked  438169.0  29.831767  4.86689  14688
The total number of this one is  14688

Panda Profiling only for "Average weekly hours worked"

In [23]:
pp = ProfileReport(df_AvgWeekHrsWrked, title="Average weekly hours worked")
pp_df = pp.to_html()

f = open("Average weekly hours worked.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

Summarize dataset: 100%|██████████| 21/21 [00:01<00:00, 11.16it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.09s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.98it/s]

Hours worked from modified sorted dataset.
* Notice, Skewed left.

In [24]:
# Hours worked                       15120
print("\nHours worked")
df_Hrs_Wrked = df_sorted_na.loc[
    (df_sorted_na['Indicators'] == 'Hours worked')
]
grouped = df_Hrs_Wrked.groupby(['Indicators'])
print(grouped['VALUE'].agg([np.sum, np.mean, np.std, np.size]))
print(grouped['VALUE'].agg([np.amin, np.amax]))
print("The total number of this one is ",len(df_Hrs_Wrked.index))

Hours worked
                       sum          mean            std   size
Indicators
Hours worked  1.227872e+09  83596.946283  253684.449101  14688
              amin       amax
Indicators
Hours worked   6.0  3857813.0
The total number of this one is  14688

Panda Profiling only for "Hours worked" (Skewed left, noticed)

In [25]:
pp = ProfileReport(df_Hrs_Wrked, title="Hours Worked")
pp_df = pp.to_html()

f = open("Hours worked.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

Summarize dataset:   8%|▊         | 1/13 [00:00<00:01,  9.42it/s, Describe variable:VALUE]

Summarize dataset: 100%|██████████| 21/21 [00:01<00:00, 10.59it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.15s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.15it/s]

Number of jobs from modified sorted dataset.
* Notice, skewed left.

In [26]:
# Number of jobs                     15120
print("\nNumber of jobs")
df_NumOfJob = df_sorted_na.loc[
    (df_sorted_na['Indicators'] == 'Number of jobs')
]
grouped = df_NumOfJob.groupby(['Indicators'])
print(grouped['VALUE'].agg([np.sum, np.mean, np.std, np.size]))
print(grouped['VALUE'].agg([np.amin, np.amax]))
print("The total number of this one is ",len(df_NumOfJob.index))

Number of jobs
                        sum          mean            std   size
Indicators
Number of jobs  784942325.0  53441.062432  161120.806948  14688
                amin       amax
Indicators
Number of jobs  11.0  2428289.0
The total number of this one is  14688

Panda Profiling only for "Number of the jobs" (Stewed toward left)

In [27]:
pp = ProfileReport(df_NumOfJob, title="Number of jobs")
pp_df = pp.to_html()

f = open("Number of jobs.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

Summarize dataset: 100%|██████████| 21/21 [00:01<00:00, 11.04it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:02<00:00,  2.89s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.21it/s]

Wages and salaries from modified sorted dataset.

* Noticed skewed left.

In [28]:
# Wages and salaries                 15120
print("\nWages and salaries")
df_WagesAndSalaries = df_sorted_na.loc[
    (df_sorted_na['Indicators'] == 'Wages and salaries')
]
grouped = df_WagesAndSalaries.groupby(['Indicators'])
print(grouped['VALUE'].agg([np.sum, np.mean, np.std, np.size]))
print(grouped['VALUE'].agg([np.amin, np.amax]))
print("The total number of this one is ",len(df_WagesAndSalaries.index))

Wages and salaries
                           sum         mean          std   size
Indicators
Wages and salaries  36498479.0  2484.918233  7977.441388  14688
                    amin      amax
Indicators
Wages and salaries   0.0  132601.0
The total number of this one is  14688

Panda Profiling only for "Wages and salaries" (Strewed toward left)

In [29]:
pp = ProfileReport(df_WagesAndSalaries, title="Wages and Salaries")
pp_df = pp.to_html()

f = open("Wages and salaries.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Summarize dataset: 100%|██████████| 21/21 [00:01<00:00, 12.17it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.25s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.03it/s]

For next step, I will divide each Indicators dataset into three different datasets.<br />
They are 2013-2015, 2016-2018, 2019-2021.<br />
I have dataset prepared before 2010-2012. However, it will not be used after this section, there's too much to analysis to do.<br />
It will also demonstrate here why.
Originally, I used divide dataset into 2016-2017, 2018-2019, and 2020-2021 from dataset that was divided from 2016 and up.

In [30]:
print("There are seven Indicators to analysis,")
grouped = df_sorted_na.groupby('Indicators')
print(grouped['VALUE'].agg([np.size]))

print("\nThe data inside between 2010-2013, there's are # number of data and I will be repeating this seven more time.,")
df_Avg_Sample = df_AvgAnnHrsWrk.loc[
    (df_AvgAnnHrsWrk['REF_DATE'] == 2010) |
    (df_AvgAnnHrsWrk['REF_DATE'] == 2011) |
    (df_AvgAnnHrsWrk['REF_DATE'] == 2012)
]

grouped = df_Avg_Sample.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.size]))

print("\nTo data inside above 2013 and split into three datasets, I need to repeat this analysis for "+str(7*3)+" (7x3) times.")
print("\nThis is also total of spliting into "+str(7*3)+" datasets.")

df_Avg_Sample_2013 = df_AvgAnnHrsWrk.loc[
    (df_AvgAnnHrsWrk['REF_DATE'] == 2013) |
    (df_AvgAnnHrsWrk['REF_DATE'] == 2014) |
    (df_AvgAnnHrsWrk['REF_DATE'] == 2015)
]

df_Avg_Sample_2016 = df_AvgAnnHrsWrk.loc[
    (df_AvgAnnHrsWrk['REF_DATE'] == 2016) |
    (df_AvgAnnHrsWrk['REF_DATE'] == 2017) |
    (df_AvgAnnHrsWrk['REF_DATE'] == 2018)
]

df_Avg_Sample_2019 = df_AvgAnnHrsWrk.loc[
    (df_AvgAnnHrsWrk['REF_DATE'] == 2019) |
    (df_AvgAnnHrsWrk['REF_DATE'] == 2020) |
    (df_AvgAnnHrsWrk['REF_DATE'] == 2021)
]

grouped = df_Avg_Sample_2013.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.size]))

grouped = df_Avg_Sample_2016.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.size]))

grouped = df_Avg_Sample_2019.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.size]))

There are seven Indicators to analysis,
                                    size
Indicators
Average annual hours worked        14688
Average annual wages and salaries  14688
Average hourly wage                14688
Average weekly hours worked        14688
Hours worked                       14688
Number of jobs                     14688
Wages and salaries                 14688

The data inside between 2010-2013, there's are # number of data and I will be repeating this seven more time.,
          size
REF_DATE
2010      1224
2011      1224
2012      1224

To data inside above 2013 and split into three datasets, I need to repeat this analysis for 21 (7x3) times.

This is also total of spliting into 21 datasets.
          size
REF_DATE
2013      1224
2014      1224
2015      1224
          size
REF_DATE
2016      1224
2017      1224
2018      1224
          size
REF_DATE
2019      1224
2020      1224
2021      1224

Grabbing the year (REF_DATE) from 2010, 2013, 2016, 2018, and 2019 individually for "Average annual hours worked".

In [31]:
# 2010-2012
df_AvgAnnHrsWrk_2010 = df_AvgAnnHrsWrk.loc[
    (df_AvgAnnHrsWrk['REF_DATE'] == 2010) |
    (df_AvgAnnHrsWrk['REF_DATE'] == 2011) |
    (df_AvgAnnHrsWrk['REF_DATE'] == 2012)
]

grouped = df_AvgAnnHrsWrk_2010.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

                sum  size
REF_DATE
2010      1905000.0  1224
2011      1909823.0  1224
2012      1915650.0  1224

In [32]:
print("Grabbing the data from 2013, 2016, and 2019.")

# 2013 - 2015
df_AvgAnnHrsWrk_2013 = df_AvgAnnHrsWrk.loc[
    (df_AvgAnnHrsWrk['REF_DATE'] == 2013) |
    (df_AvgAnnHrsWrk['REF_DATE'] == 2014) |
    (df_AvgAnnHrsWrk['REF_DATE'] == 2015)
]

# 2016 - 2018
df_AvgAnnHrsWrk_2016 = df_AvgAnnHrsWrk.loc[
    (df_AvgAnnHrsWrk['REF_DATE'] == 2016) |
    (df_AvgAnnHrsWrk['REF_DATE'] == 2017) |
    (df_AvgAnnHrsWrk['REF_DATE'] == 2018)
]

# 20109- 2021
df_AvgAnnHrsWrk_2019 = df_AvgAnnHrsWrk.loc[
    (df_AvgAnnHrsWrk['REF_DATE'] == 2019) |
    (df_AvgAnnHrsWrk['REF_DATE'] == 2020) |
    (df_AvgAnnHrsWrk['REF_DATE'] == 2021)
]

grouped = df_AvgAnnHrsWrk_2013.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

grouped = df_AvgAnnHrsWrk_2016.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

grouped = df_AvgAnnHrsWrk_2019.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

Grabbing the data from 2013, 2016, and 2019.
                sum  size
REF_DATE
2013      1906851.0  1224
2014      1898034.0  1224
2015      1907286.0  1224
                sum  size
REF_DATE
2016      1899738.0  1224
2017      1881389.0  1224
2018      1894227.0  1224
                sum  size
REF_DATE
2019      1894126.0  1224
2020      1873544.0  1224
2021      1901826.0  1224

Panda Profiling for year 2016, 2018, and 2020 for "Average annual hours worked".

In [33]:
# 2016-2017
pp = ProfileReport(df_AvgAnnHrsWrk_2013, title="Average annual hours worked 2013")
pp_df = pp.to_html()

f = open("Average annual hours worked 2016.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

# 2017 - 2019
pp = ProfileReport(df_AvgAnnHrsWrk_2016, title="Average annual hours worked 2016")
pp_df = pp.to_html()

f = open("Average annual hours worked 2018.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

# 2020 - 2021
pp = ProfileReport(df_AvgAnnHrsWrk_2019, title="Average annual hours worked 2019")
pp_df = pp.to_html()

f = open("Average annual hours worked 2020.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

Summarize dataset:  23%|██▎       | 3/13 [00:00<00:00, 11.96it/s, Describe variable:UOM]

Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 14.43it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.02s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.30it/s]
Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 16.61it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.10s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.59it/s]
Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 14.17it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.28s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.36it/s]

Grabbing the year (REF_DATE) from 2010, 2013, 2016, and 2019 individually for "Average annual wages and salaries".

In [34]:
# 2010 - 2012
df_AvgAnnWages_2010 = df_AvgAnnWages.loc[
    (df_AvgAnnWages['REF_DATE'] == 2010) |
    (df_AvgAnnWages['REF_DATE'] == 2011) |
    (df_AvgAnnWages['REF_DATE'] == 2012)
]

grouped = df_AvgAnnWages_2010.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

                 sum  size
REF_DATE
2010      48093832.0  1224
2011      49165720.0  1224
2012      50085622.0  1224

In [35]:
print("Grabbing the data from 2017, 2019, and 2021.")

# 2013 - 2015
df_AvgAnnWages_2013 = df_AvgAnnWages.loc[
    (df_AvgAnnWages['REF_DATE'] == 2013) |
    (df_AvgAnnWages['REF_DATE'] == 2014) |
    (df_AvgAnnWages['REF_DATE'] == 2015)
]

# 2016 - 2018
df_AvgAnnWages_2016 = df_AvgAnnWages.loc[
    (df_AvgAnnWages['REF_DATE'] == 2016) |
    (df_AvgAnnWages['REF_DATE'] == 2017) |
    (df_AvgAnnWages['REF_DATE'] == 2018)
]

# 2019 - 2021
df_AvgAnnWages_2019 = df_AvgAnnWages.loc[
    (df_AvgAnnWages['REF_DATE'] == 2019) |
    (df_AvgAnnWages['REF_DATE'] == 2020) |
    (df_AvgAnnWages['REF_DATE'] == 2021)
]

grouped = df_AvgAnnWages_2013.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

grouped = df_AvgAnnWages_2016.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

grouped = df_AvgAnnWages_2019.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

Grabbing the data from 2017, 2019, and 2021.
                 sum  size
REF_DATE
2013      50598135.0  1224
2014      51805889.0  1224
2015      52715143.0  1224
                 sum  size
REF_DATE
2016      53166285.0  1224
2017      53965359.0  1224
2018      55525920.0  1224
                 sum  size
REF_DATE
2019      56997121.0  1224
2020      60597775.0  1224
2021      60687848.0  1224

Panda Profiling for year 2013, 2016, and 2019 for "Average annual wages and salaries".

In [36]:
pp = ProfileReport(df_AvgAnnWages_2013, title="Average annual wages and salaries 2013")
pp_df = pp.to_html()

f = open("Average annual wages and salaries 2013.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

pp = ProfileReport(df_AvgAnnWages_2016, title="Average annual wages and salaries 2016")
pp_df = pp.to_html()

f = open("Average annual wages and salaries 2016.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

pp = ProfileReport(df_AvgAnnWages_2019, title="Average annual wages and salaries 2019")
pp_df = pp.to_html()

f = open("Average annual wages and salaries 2019.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

Summarize dataset:  23%|██▎       | 3/13 [00:00<00:00, 10.31it/s, Describe variable:Characteristics]

Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 14.75it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.03s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.50it/s]
Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 13.16it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:02<00:00,  2.90s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.37it/s]
Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 16.52it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.07s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.44it/s]

Grabbing the year (REF_DATE) from 2010, 2013, 2016, and 2019 individually for "Average hourly wages".

In [37]:
# 2010 - 2012
df_AvgHrsWages_2010 = df_AvgHrsWages.loc[
    (df_AvgHrsWages['REF_DATE'] == 2010) |
    (df_AvgHrsWages['REF_DATE'] == 2011) |
    (df_AvgHrsWages['REF_DATE'] == 2012)
]

grouped = df_AvgHrsWages_2010.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

               sum  size
REF_DATE
2010      30453.20  1224
2011      31053.73  1224
2012      31511.37  1224

In [38]:
print("Grabbing the data from 2013, 2016, and 2019.")

# 2013 - 2015
df_AvgHrsWages_2013 = df_AvgHrsWages.loc[
    (df_AvgHrsWages['REF_DATE'] == 2013) |
    (df_AvgHrsWages['REF_DATE'] == 2014) |
    (df_AvgHrsWages['REF_DATE'] == 2015)
]

# 2016 - 2018
df_AvgHrsWages_2016 = df_AvgHrsWages.loc[
    (df_AvgHrsWages['REF_DATE'] == 2016) |
    (df_AvgHrsWages['REF_DATE'] == 2017) |
    (df_AvgHrsWages['REF_DATE'] == 2018)
]

# 2019 - 2021
df_AvgHrsWages_2019 = df_AvgHrsWages.loc[
    (df_AvgHrsWages['REF_DATE'] == 2019) |
    (df_AvgHrsWages['REF_DATE'] == 2020) |
    (df_AvgHrsWages['REF_DATE'] == 2021)
]

grouped = df_AvgHrsWages_2013.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

grouped = df_AvgHrsWages_2016.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

grouped = df_AvgHrsWages_2019.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

Grabbing the data from 2013, 2016, and 2019.
               sum  size
REF_DATE
2013      31932.19  1224
2014      32916.44  1224
2015      33362.79  1224
               sum  size
REF_DATE
2016      33756.84  1224
2017      34571.41  1224
2018      35356.16  1224
               sum  size
REF_DATE
2019      36293.34  1224
2020      38980.38  1224
2021      38514.73  1224

Panda Profiling for year 2013, 2016, and 2019 for "Average hourly wages".

In [39]:
pp = ProfileReport(df_AvgHrsWages_2013, title="Average hourly wage 2013")
pp_df = pp.to_html()

f = open("Average hourly wages 2013.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

pp = ProfileReport(df_AvgHrsWages_2016, title="Average hourly wage 2016")
pp_df = pp.to_html()

f = open("Average hourly wages 2016.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

pp = ProfileReport(df_AvgHrsWages_2019, title="Average hourly wage 2019")
pp_df = pp.to_html()

f = open("Average hourly wages 2019.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 14.87it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.24s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.31it/s]
Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 16.09it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.12s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.41it/s]
Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 17.37it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.26s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.49it/s]

Grabbing the year (REF_DATE) from 2010, 2013, 2016, and 2019 individually for "Average weekly hours worked".

In [40]:
# 2010 - 2012
df_AvgWeekHrsWrked_2010 = df_AvgWeekHrsWrked.loc[
    (df_AvgWeekHrsWrked['REF_DATE'] == 2010) |
    (df_AvgWeekHrsWrked['REF_DATE'] == 2011) |
    (df_AvgWeekHrsWrked['REF_DATE'] == 2012)
]

grouped = df_AvgWeekHrsWrked_2010.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

              sum  size
REF_DATE
2010      36645.0  1224
2011      36732.0  1224
2012      36842.0  1224

In [41]:
print("Grabbing the data from 2013, 2016, and 2019.")

# 2013 - 2015
df_AvgWeekHrsWrked_2013 = df_AvgWeekHrsWrked.loc[
    (df_AvgWeekHrsWrked['REF_DATE'] == 2013) |
    (df_AvgWeekHrsWrked['REF_DATE'] == 2014) |
    (df_AvgWeekHrsWrked['REF_DATE'] == 2015)
]

# 2016 - 2018
df_AvgWeekHrsWrked_2016 = df_AvgWeekHrsWrked.loc[
    (df_AvgWeekHrsWrked['REF_DATE'] == 2016) |
    (df_AvgWeekHrsWrked['REF_DATE'] == 2017) |
    (df_AvgWeekHrsWrked['REF_DATE'] == 2018)
]

# 2019 - 2021
df_AvgWeekHrsWrked_2019 = df_AvgWeekHrsWrked.loc[
    (df_AvgWeekHrsWrked['REF_DATE'] == 2019) |
    (df_AvgWeekHrsWrked['REF_DATE'] == 2020) |
    (df_AvgWeekHrsWrked['REF_DATE'] == 2021)
]

grouped = df_AvgWeekHrsWrked_2013.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

grouped = df_AvgWeekHrsWrked_2016.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

grouped = df_AvgWeekHrsWrked_2019.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

Grabbing the data from 2013, 2016, and 2019.
              sum  size
REF_DATE
2013      36671.0  1224
2014      36483.0  1224
2015      36678.0  1224
              sum  size
REF_DATE
2016      36541.0  1224
2017      36170.0  1224
2018      36416.0  1224
              sum  size
REF_DATE
2019      36400.0  1224
2020      36036.0  1224
2021      36555.0  1224

Panda Profiling for year 2013, 2016, and 2019 for "Average weekly hours worked".

In [42]:
pp = ProfileReport(df_AvgWeekHrsWrked_2013, title="Average weekly hours worked 2013")
pp_df = pp.to_html()

f = open("Average weekly hours worked 2013.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

pp = ProfileReport(df_AvgWeekHrsWrked_2016, title="Average weekly hours worked 2016")
pp_df = pp.to_html()

f = open("Average weekly hours worked 2016.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

pp = ProfileReport(df_AvgWeekHrsWrked_2019, title="Average weekly hours worked 2019")
pp_df = pp.to_html()

f = open("Average weekly hours worked 2019.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 16.52it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:02<00:00,  2.93s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.41it/s]
Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 15.84it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.09s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.53it/s]
Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 16.00it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.22s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.23it/s]

Grabbing the year (REF_DATE) from 2010, 2013, 2016, and 2019 individually for "hours worked".

In [43]:
# 2010 - 2012
df_Hrs_Wrked_2010 = df_Hrs_Wrked.loc[
    (df_Hrs_Wrked['REF_DATE'] == 2010) |
    (df_Hrs_Wrked['REF_DATE'] == 2011) |
    (df_Hrs_Wrked['REF_DATE'] == 2012)
]

grouped = df_Hrs_Wrked_2010.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

                 sum  size
REF_DATE
2010      94217881.0  1224
2011      95953248.0  1224
2012      97724232.0  1224

In [44]:
print("Grabbing the data from 2013, 2016, and 2019.")

# 2013 - 2015
df_Hrs_Wrked_2013 = df_Hrs_Wrked.loc[
    (df_Hrs_Wrked['REF_DATE'] == 2013) |
    (df_Hrs_Wrked['REF_DATE'] == 2014) |
    (df_Hrs_Wrked['REF_DATE'] == 2015)
]

# 2016 - 2018
df_Hrs_Wrked_2016 = df_Hrs_Wrked.loc[
    (df_Hrs_Wrked['REF_DATE'] == 2016) |
    (df_Hrs_Wrked['REF_DATE'] == 2017) |
    (df_Hrs_Wrked['REF_DATE'] == 2018)
]

# 2019 - 2021
df_Hrs_Wrked_2019 = df_Hrs_Wrked.loc[
    (df_Hrs_Wrked['REF_DATE'] == 2019) |
    (df_Hrs_Wrked['REF_DATE'] == 2020) |
    (df_Hrs_Wrked['REF_DATE'] == 2021)
]

grouped = df_Hrs_Wrked_2013.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

grouped = df_Hrs_Wrked_2016.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

grouped = df_Hrs_Wrked_2019.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

Grabbing the data from 2013, 2016, and 2019.
                  sum  size
REF_DATE
2013       98935086.0  1224
2014       99777902.0  1224
2015      101927894.0  1224
                  sum  size
REF_DATE
2016      103980992.0  1224
2017      103906357.0  1224
2018      106885614.0  1224
                  sum  size
REF_DATE
2019      108384508.0  1224
2020      103897606.0  1224
2021      112280627.0  1224

Panda Profiling for year 2013, 2016, and 2019 for "hours worked".

In [45]:
pp = ProfileReport(df_Hrs_Wrked_2013, title="Hours Worked 2013")
pp_df = pp.to_html()

f = open("Hours worked 2013.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

pp = ProfileReport(df_Hrs_Wrked_2016, title="Hours Worked 2016")
pp_df = pp.to_html()

f = open("Hours worked 2016.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

pp = ProfileReport(df_Hrs_Wrked_2019, title="Hours Worked 2019")
pp_df = pp.to_html()

f = open("Hours worked 2019.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

Summarize dataset:  23%|██▎       | 3/13 [00:00<00:00, 12.90it/s, Describe variable:UOM]

Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 13.73it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.15s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.29it/s]
Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 16.34it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.29s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.26it/s]
Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 15.06it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.21s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.30it/s]

Grabbing the year (REF_DATE) from 2010, 2013, 2016, and 2019 individually for "Number of jobs".

In [46]:
# 2010 - 2012
df_NumOfJob_2010 = df_NumOfJob.loc[
    (df_NumOfJob['REF_DATE'] == 2010) |
    (df_NumOfJob['REF_DATE'] == 2011) |
    (df_NumOfJob['REF_DATE'] == 2012)
]

grouped = df_NumOfJob_2010.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

                 sum  size
REF_DATE
2010      59793067.0  1224
2011      61122016.0  1224
2012      61949430.0  1224

In [47]:
print("Grabbing the data from 2013, 2016, and 2019.")

# 2013 - 2015
df_NumOfJob_2013 = df_NumOfJob.loc[
    (df_NumOfJob['REF_DATE'] == 2013) |
    (df_NumOfJob['REF_DATE'] == 2014) |
    (df_NumOfJob['REF_DATE'] == 2015)
]

# 2016 - 2018
df_NumOfJob_2016 = df_NumOfJob.loc[
    (df_NumOfJob['REF_DATE'] == 2016) |
    (df_NumOfJob['REF_DATE'] == 2017) |
    (df_NumOfJob['REF_DATE'] == 2018)
]

# 2019 - 2021
df_NumOfJob_2019 = df_NumOfJob.loc[
    (df_NumOfJob['REF_DATE'] == 2019) |
    (df_NumOfJob['REF_DATE'] == 2020) |
    (df_NumOfJob['REF_DATE'] == 2021)
]

grouped = df_NumOfJob_2013.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

grouped = df_NumOfJob_2016.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

grouped = df_NumOfJob_2019.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

Grabbing the data from 2013, 2016, and 2019.
                 sum  size
REF_DATE
2013      63161481.0  1224
2014      63980381.0  1224
2015      65239031.0  1224
                 sum  size
REF_DATE
2016      66578386.0  1224
2017      66979678.0  1224
2018      68215341.0  1224
                 sum  size
REF_DATE
2019      69702012.0  1224
2020      67249987.0  1224
2021      70971515.0  1224

Panda Profiling for year 2013, 2016, and 2019for "Number of jobs".

In [48]:
pp = ProfileReport(df_NumOfJob_2013, title="Number of jobs 2013")
pp_df = pp.to_html()

f = open("Number of jobs 2013.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

pp = ProfileReport(df_NumOfJob_2016, title="Number of jobs 2016")
pp_df = pp.to_html()

f = open("Number of jobs 2016.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

pp = ProfileReport(df_NumOfJob_2019, title="Number of jobs 2019")
pp_df = pp.to_html()

f = open("Number of jobs 2019.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

Summarize dataset:   8%|▊         | 1/13 [00:00<00:02,  5.62it/s, Describe variable:Sector]

Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 14.47it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.31s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.45it/s]
Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 16.02it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.05s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.30it/s]
Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 16.09it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.38s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.50it/s]

Grabbing the year (REF_DATE) from 2010, 2013, 2016, and 2019 individually for "Wages and Salaries".

In [49]:
# 2010 - 2012
df_WagesAndSalaries_2010 = df_WagesAndSalaries.loc[
    (df_WagesAndSalaries['REF_DATE'] == 2010) |
    (df_WagesAndSalaries['REF_DATE'] == 2011) |
    (df_WagesAndSalaries['REF_DATE'] == 2012)
]

grouped = df_WagesAndSalaries_2010.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

                sum  size
REF_DATE
2010      2489681.0  1224
2011      2604921.0  1224
2012      2687510.0  1224

In [50]:
print("Grabbing the data from 2013, 2016, and 2019.")

# 2013 - 2015
df_WagesAndSalaries_2013 = df_WagesAndSalaries.loc[
    (df_WagesAndSalaries['REF_DATE'] == 2013) |
    (df_WagesAndSalaries['REF_DATE'] == 2014) |
    (df_WagesAndSalaries['REF_DATE'] == 2015)
]

# 2016 - 2018
df_WagesAndSalaries_2016 = df_WagesAndSalaries.loc[
    (df_WagesAndSalaries['REF_DATE'] == 2016) |
    (df_WagesAndSalaries['REF_DATE'] == 2017) |
    (df_WagesAndSalaries['REF_DATE'] == 2018)
]

# 2019 - 2021
df_WagesAndSalaries_2019 = df_WagesAndSalaries.loc[
    (df_WagesAndSalaries['REF_DATE'] == 2019) |
    (df_WagesAndSalaries['REF_DATE'] == 2020) |
    (df_WagesAndSalaries['REF_DATE'] == 2021)
]

grouped = df_WagesAndSalaries_2013.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

grouped = df_WagesAndSalaries_2016.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

grouped = df_WagesAndSalaries_2019.groupby(['REF_DATE'])
print(grouped['VALUE'].agg([np.sum, np.size]))

Grabbing the data from 2013, 2016, and 2019.
                sum  size
REF_DATE
2013      2746199.0  1224
2014      2844225.0  1224
2015      2965770.0  1224
                sum  size
REF_DATE
2016      3043217.0  1224
2017      3118809.0  1224
2018      3263527.0  1224
                sum  size
REF_DATE
2019      3437480.0  1224
2020      3532888.0  1224
2021      3764252.0  1224

Panda Profiling for year 2013, 2016, and 2019 for "Wages and Salaries".

In [51]:
pp = ProfileReport(df_WagesAndSalaries_2013, title="Wages and Salaries 2013")
pp_df = pp.to_html()

f = open("Wages and Salaries 2013.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

pp = ProfileReport(df_WagesAndSalaries_2016, title="Wages and Salaries 2016")
pp_df = pp.to_html()

f = open("Wages and Salaries 2016.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

pp = ProfileReport(df_WagesAndSalaries_2019, title="Wages and Salaries 2019")
pp_df = pp.to_html()

f = open("Wages and Salaries 2019.html", "a")  # Expert into html file without modifying any columns in dataset.
f.write(pp_df)
f.close()

Summarize dataset:   8%|▊         | 1/13 [00:00<00:00, 13.02it/s, Describe variable:VALUE]

Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 14.22it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.14s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.46it/s]
Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 16.79it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.27s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.37it/s]
Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 17.76it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.18s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.45it/s]

For next step, I will filtered it by the following group, "age group", "gender level", "education level", "immigrant level" and "Aboriginal status".
* I have comment, analysis of whole dataset, 2010-2013 (originally, before 2016).
* I have analysis two training and testing set. (2013-2015), (2016-2018), (2019-2021)
* There's also other characteristics there as well but I decided to drop them as well.

Filtered for "Average annual hours worked" by following: "Age group", "Gender level", "Education level", and "Immigration status".<br />
"Aboriginal status" has been commented.

In [52]:
# Dataset year in 2010 inside Average Annual Hours Worked

# print("\nAge group in Alberta")
# df_AvgAnnHrsWrk_2010_ByAge = df_AvgAnnHrsWrk_2010.loc[
#     (df_AvgAnnHrsWrk_2010['Characteristics'] == '15 to 24 years') |
#     (df_AvgAnnHrsWrk_2010['Characteristics'] == '25 to 34 years') |
#     (df_AvgAnnHrsWrk_2010['Characteristics'] == '35 to 44 years') |
#     (df_AvgAnnHrsWrk_2010['Characteristics'] == '45 to 54 years') |
#     (df_AvgAnnHrsWrk_2010['Characteristics'] == '55 to 64 years') |
#     (df_AvgAnnHrsWrk_2010['Characteristics'] == '65 years old and over')]
# # print(df_AvgAnnHrsWrk_2010_ByAge.head(20))
# grouped = df_AvgAnnHrsWrk_2010_ByAge.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("Total size : ",len(df_AvgAnnHrsWrk_2010_ByAge.index))

# print("\nGender group in Alberta")
# df_AvgAnnHrsWrk_2010_ByGender = df_AvgAnnHrsWrk_2010.loc[
#     (df_AvgAnnHrsWrk_2010['Characteristics'] == 'Female employees') |
#     (df_AvgAnnHrsWrk_2010['Characteristics'] == 'Male employees')
# ]
# # print(df_AvgAnnHrsWrk_2010_ByGender.head(20))
# grouped = df_AvgAnnHrsWrk_2010_ByGender.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("Total size : ",len(df_AvgAnnHrsWrk_2010_ByGender.index))

# print("\nEducation group in Alberta")
# df_AvgAnnHrsWrk_2010_ByEducation = df_AvgAnnHrsWrk_2010.loc[
#     (df_AvgAnnHrsWrk_2010['Characteristics'] == 'High school diploma and less') |
#     (df_AvgAnnHrsWrk_2010['Characteristics'] == 'Trade certificate') |
#     (df_AvgAnnHrsWrk_2010['Characteristics'] == 'University degree and higher')
# ]
# # print(df_AvgAnnHrsWrk_2010_ByEducation.head(20))
# grouped = df_AvgAnnHrsWrk_2010_ByEducation.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("Total size : ",len(df_AvgAnnHrsWrk_2010_ByEducation.index))

# print("\nImmigrant group in Alberta")
# df_AvgAnnHrsWrk_2010_ByImmigrant = df_AvgAnnHrsWrk_2010.loc[
#     (df_AvgAnnHrsWrk_2010['Characteristics'] == 'Immigrant employees') |
#     (df_AvgAnnHrsWrk_2010['Characteristics'] == 'Non-immigrant employees')
# ]
# # print(df_AvgAnnHrsWrk_2010_ByImmigrant.head(20))
# grouped = df_AvgAnnHrsWrk_2010_ByImmigrant.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("Total size : ",len(df_AvgAnnHrsWrk_2010_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_AvgAnnHrkWrk_2010_ByIndigenous = df_AvgAnnHrsWrk_2010.loc[
#     (df_AvgAnnHrsWrk_2010['Characteristics'] == 'Indigenous identity employees') |
#     (df_AvgAnnHrsWrk_2010['Characteristics'] == 'Non-indigenous identity employees')
# ]
# print(df_AvgAnnHrkWrk_2010_ByIndigenous.head(20))
# # grouped = df_AvgAnnHrkWrk_2010_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgAnnHrkWrk_2010_ByIndigenous.index))

In [53]:
# Dataset year in 2013 inside Average Annual Hours Worked

print("\nAge group in Alberta")
df_AvgAnnHrsWrk_2013_ByAge = df_AvgAnnHrsWrk_2013.loc[
    (df_AvgAnnHrsWrk_2013['Characteristics'] == '15 to 24 years') |
    (df_AvgAnnHrsWrk_2013['Characteristics'] == '25 to 34 years') |
    (df_AvgAnnHrsWrk_2013['Characteristics'] == '35 to 44 years') |
    (df_AvgAnnHrsWrk_2013['Characteristics'] == '45 to 54 years') |
    (df_AvgAnnHrsWrk_2013['Characteristics'] == '55 to 64 years') |
    (df_AvgAnnHrsWrk_2013['Characteristics'] == '65 years old and over')]
# print(df_AvgAnnHrsWrk_2013_ByAge.head(20))
grouped = df_AvgAnnHrsWrk_2013_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("Total size : ",len(df_AvgAnnHrsWrk_2013_ByAge.index))

print("\nGender group in Alberta")
df_AvgAnnHrsWrk_2013_ByGender = df_AvgAnnHrsWrk_2013.loc[
    (df_AvgAnnHrsWrk_2013['Characteristics'] == 'Female employees') |
    (df_AvgAnnHrsWrk_2013['Characteristics'] == 'Male employees')
]
# print(df_AvgAnnHrsWrk_2013_ByGender.head(20))
grouped = df_AvgAnnHrsWrk_2013_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("Total size : ",len(df_AvgAnnHrsWrk_2013_ByGender.index))

print("\nEducation group in Alberta")
df_AvgAnnHrsWrk_2013_ByEducation = df_AvgAnnHrsWrk_2013.loc[
    (df_AvgAnnHrsWrk_2013['Characteristics'] == 'High school diploma and less') |
    (df_AvgAnnHrsWrk_2013['Characteristics'] == 'Trade certificate') |
    (df_AvgAnnHrsWrk_2013['Characteristics'] == 'University degree and higher')
]
# print(df_AvgAnnHrsWrk_2013_ByEducation.head(20))
grouped = df_AvgAnnHrsWrk_2013_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("Total size : ",len(df_AvgAnnHrsWrk_2013_ByEducation.index))

print("\nImmigrant group in Alberta")
df_AvgAnnHrsWrk_2013_ByImmigrant = df_AvgAnnHrsWrk_2013.loc[
    (df_AvgAnnHrsWrk_2013['Characteristics'] == 'Immigrant employees') |
    (df_AvgAnnHrsWrk_2013['Characteristics'] == 'Non-immigrant employees')
]
# print(df_AvgAnnHrsWrk_2013_ByImmigrant.head(20))
grouped = df_AvgAnnHrsWrk_2013_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("Total size : ",len(df_AvgAnnHrsWrk_2013_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_AvgAnnHrsWrk_2013_ByIndigenous = df_AvgAnnHrsWrk_2013.loc[
#     (df_AvgAnnHrsWrk_2013['Characteristics'] == 'Indigenous identity employees') |
#     (df_AvgAnnHrsWrk_2013['Characteristics'] == 'Non-indigenous identity employees')
# ]
# print(df_AvgAnnHrsWrk_2013_ByIndigenous.head(20))
# # grouped = df_AvgAnnHrsWrk_2013_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgAnnHrsWrk_2013_ByIndigenous.index))

Age group in Alberta
                            sum  size
Characteristics
15 to 24 years         172087.0   192
25 to 34 years         340647.0   210
35 to 44 years         377140.0   210
45 to 54 years         387957.0   210
55 to 64 years         352301.0   210
65 years old and over  207070.0   192
Total size :  1224

Gender group in Alberta
                       sum  size
Characteristics
Female employees  322203.0   210
Male employees    351902.0   210
Total size :  420

Education group in Alberta
                                   sum  size
Characteristics
High school diploma and less  277682.0   210
Trade certificate             313663.0   198
University degree and higher  347222.0   198
Total size :  606

Immigrant group in Alberta
                              sum  size
Characteristics
Immigrant employees      326890.0   198
Non-immigrant employees  312119.0   198
Total size :  396

In [54]:
# Dataset year in 2016 inside Average Annual Hours Worked

print("\nAge group in Alberta")
df_AvgAnnHrsWrk_2016_ByAge = df_AvgAnnHrsWrk_2016.loc[
    (df_AvgAnnHrsWrk_2016['Characteristics'] == '15 to 24 years') |
    (df_AvgAnnHrsWrk_2016['Characteristics'] == '25 to 34 years') |
    (df_AvgAnnHrsWrk_2016['Characteristics'] == '35 to 44 years') |
    (df_AvgAnnHrsWrk_2016['Characteristics'] == '45 to 54 years') |
    (df_AvgAnnHrsWrk_2016['Characteristics'] == '55 to 64 years') |
    (df_AvgAnnHrsWrk_2016['Characteristics'] == '65 years old and over')]
# print(df_AvgAnnHrsWrk_2016_ByAge.head(20))
grouped = df_AvgAnnHrsWrk_2016_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("Total size : ",len(df_AvgAnnHrsWrk_2016_ByAge.index))

print("\nGender group in Alberta")
df_AvgAnnHrsWrk_2016_ByGender = df_AvgAnnHrsWrk_2016.loc[
    (df_AvgAnnHrsWrk_2016['Characteristics'] == 'Female employees') |
    (df_AvgAnnHrsWrk_2016['Characteristics'] == 'Male employees')
]
# print(df_AvgAnnHrsWrk_2016_ByGender.head(20))
grouped = df_AvgAnnHrsWrk_2016_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("Total size : ",len(df_AvgAnnHrsWrk_2016_ByGender.index))

print("\nEducation group in Alberta")
df_AvgAnnHrsWrk_2016_ByEducation = df_AvgAnnHrsWrk_2016.loc[
    (df_AvgAnnHrsWrk_2016['Characteristics'] == 'High school diploma and less') |
    (df_AvgAnnHrsWrk_2016['Characteristics'] == 'Trade certificate') |
    (df_AvgAnnHrsWrk_2016['Characteristics'] == 'University degree and higher')
]
# print(df_AvgAnnHrsWrk_2016_ByEducation.head(20))
grouped = df_AvgAnnHrsWrk_2016_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("Total size : ",len(df_AvgAnnHrsWrk_2016_ByEducation.index))

print("\nImmigrant group in Alberta")
df_AvgAnnHrsWrk_2016_ByImmigrant = df_AvgAnnHrsWrk_2016.loc[
    (df_AvgAnnHrsWrk_2016['Characteristics'] == 'Immigrant employees') |
    (df_AvgAnnHrsWrk_2016['Characteristics'] == 'Non-immigrant employees')
]
# print(df_AvgAnnHrsWrk_2016_ByImmigrant.head(20))
grouped = df_AvgAnnHrsWrk_2016_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("Total size : ",len(df_AvgAnnHrsWrk_2016_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_AvgAnnHrsWrk_2016_ByIndigenous = df_AvgAnnHrsWrk_2016.loc[
#     (df_AvgAnnHrsWrk_2016['Characteristics'] == 'Indigenous identity employees') |
#     (df_AvgAnnHrsWrk_2016['Characteristics'] == 'Non-indigenous identity employees')
# ]
# print(df_AvgAnnHrsWrk_2016_ByIndigenous.head(20))
# # grouped = df_AvgAnnHrsWrk_2016_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgAnnHrsWrk_2016_ByIndigenous.index))

Age group in Alberta
                            sum  size
Characteristics
15 to 24 years         176153.0   192
25 to 34 years         337302.0   210
35 to 44 years         373702.0   210
45 to 54 years         385915.0   210
55 to 64 years         350828.0   210
65 years old and over  206428.0   192
Total size :  1224

Gender group in Alberta
                       sum  size
Characteristics
Female employees  321687.0   210
Male employees    346749.0   210
Total size :  420

Education group in Alberta
                                   sum  size
Characteristics
High school diploma and less  276370.0   210
Trade certificate             307989.0   198
University degree and higher  343664.0   198
Total size :  606

Immigrant group in Alberta
                              sum  size
Characteristics
Immigrant employees      321592.0   198
Non-immigrant employees  310173.0   198
Total size :  396

In [55]:
# Dataset year in 2019 inside Average Annual Hours Worked

print("\nAge group in Alberta")
df_AvgAnnHrsWrk_2019_ByAge = df_AvgAnnHrsWrk_2019.loc[
    (df_AvgAnnHrsWrk_2019['Characteristics'] == '15 to 24 years') |
    (df_AvgAnnHrsWrk_2019['Characteristics'] == '25 to 34 years') |
    (df_AvgAnnHrsWrk_2019['Characteristics'] == '35 to 44 years') |
    (df_AvgAnnHrsWrk_2019['Characteristics'] == '45 to 54 years') |
    (df_AvgAnnHrsWrk_2019['Characteristics'] == '55 to 64 years') |
    (df_AvgAnnHrsWrk_2019['Characteristics'] == '65 years old and over')]
# print(df_AvgAnnHrsWrk_2019_ByAge.head(20))
grouped = df_AvgAnnHrsWrk_2019_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("Total size : ",len(df_AvgAnnHrsWrk_2019_ByAge.index))

print("\nGender group in Alberta")
df_AvgAnnHrsWrk_2019_ByGender = df_AvgAnnHrsWrk_2019.loc[
    (df_AvgAnnHrsWrk_2019['Characteristics'] == 'Female employees') |
    (df_AvgAnnHrsWrk_2019['Characteristics'] == 'Male employees')
]
# print(df_AvgAnnHrsWrk_2019_ByGender.head(20))
grouped = df_AvgAnnHrsWrk_2019_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("Total size : ",len(df_AvgAnnHrsWrk_2019_ByGender.index))

print("\nEducation group in Alberta")
df_AvgAnnHrsWrk_2019_ByEducation = df_AvgAnnHrsWrk_2019.loc[
    (df_AvgAnnHrsWrk_2019['Characteristics'] == 'High school diploma and less') |
    (df_AvgAnnHrsWrk_2019['Characteristics'] == 'Trade certificate') |
    (df_AvgAnnHrsWrk_2019['Characteristics'] == 'University degree and higher')
]
# print(df_AvgAnnHrsWrk_2019_ByEducation.head(20))
grouped = df_AvgAnnHrsWrk_2019_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("Total size : ",len(df_AvgAnnHrsWrk_2019_ByEducation.index))

print("\nImmigrant group in Alberta")
df_AvgAnnHrsWrk_2019_ByImmigrant = df_AvgAnnHrsWrk_2019.loc[
    (df_AvgAnnHrsWrk_2019['Characteristics'] == 'Immigrant employees') |
    (df_AvgAnnHrsWrk_2019['Characteristics'] == 'Non-immigrant employees')
]
# print(df_AvgAnnHrsWrk_2019_ByImmigrant.head(20))
grouped = df_AvgAnnHrsWrk_2019_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("Total size : ",len(df_AvgAnnHrsWrk_2019_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_AvgAnnHrsWrk_2019_ByIndigenous = df_AvgAnnHrsWrk_2019.loc[
#     (df_AvgAnnHrsWrk_2019['Characteristics'] == 'Indigenous identity employees') |
#     (df_AvgAnnHrsWrk_2019['Characteristics'] == 'Non-indigenous identity employees')
# ]
# print(df_AvgAnnHrsWrk_2019_ByIndigenous.head(20))
# # grouped = df_AvgAnnHrkWrk_2010_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgAnnHrsWrk_2019_ByIndigenous.index))

Age group in Alberta
                            sum  size
Characteristics
15 to 24 years         179872.0   192
25 to 34 years         333662.0   210
35 to 44 years         371386.0   210
45 to 54 years         384987.0   210
55 to 64 years         351843.0   210
65 years old and over  206760.0   192
Total size :  1224

Gender group in Alberta
                       sum  size
Characteristics
Female employees  323755.0   210
Male employees    343101.0   210
Total size :  420

Education group in Alberta
                                   sum  size
Characteristics
High school diploma and less  275636.0   210
Trade certificate             306174.0   198
University degree and higher  341795.0   198
Total size :  606

Immigrant group in Alberta
                              sum  size
Characteristics
Immigrant employees      318818.0   198
Non-immigrant employees  310245.0   198
Total size :  396

Filtered for "Average annual wages and salaries" by following: "Age group", "Gender level", "Education level", and "Immigration status".<br />
"Aboriginal status" has been commented.

In [56]:
# # Dataset year in 2010 inside Average annual wages and salaries

# print("\nAge group in Alberta")
# df_AvgAnnWages_2010_ByAge = df_AvgAnnWages_2010.loc[
#     (df_AvgAnnWages_2010['Characteristics'] == '15 to 24 years') |
#     (df_AvgAnnWages_2010['Characteristics'] == '25 to 34 years') |
#     (df_AvgAnnWages_2010['Characteristics'] == '35 to 44 years') |
#     (df_AvgAnnWages_2010['Characteristics'] == '45 to 54 years') |
#     (df_AvgAnnWages_2010['Characteristics'] == '55 to 64 years') |
#     (df_AvgAnnWages_2010['Characteristics'] == '65 years old and over')]
# # print(df_AvgAnnWages_2010_ByAge.head(20))
# grouped = df_AvgAnnWages_2010_ByAge.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgAnnWages_2010_ByAge.index))

# print("\nGender group in Alberta")
# df_AvgAnnWages_2010_ByGender = df_AvgAnnWages_2010.loc[
#     (df_AvgAnnWages_2010['Characteristics'] == 'Female employees') |
#     (df_AvgAnnWages_2010['Characteristics'] == 'Male employees')
# ]
# # print(df_AvgAnnWages_2010_ByGender.head(20))
# grouped = df_AvgAnnWages_2010_ByGender.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgAnnWages_2010_ByGender.index))

# print("\nEducation group in Alberta")
# df_AvgAnnWages_2010_ByEducation = df_AvgAnnWages_2010.loc[
#     (df_AvgAnnWages_2010['Characteristics'] == 'High school diploma and less') |
#     (df_AvgAnnWages_2010['Characteristics'] == 'Trade certificate') |
#     (df_AvgAnnWages_2010['Characteristics'] == 'University degree and higher')
# ]
# # print(df_AvgAnnWages_2010_ByEducation.head(20))
# grouped = df_AvgAnnWages_2010_ByEducation.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgAnnWages_2010_ByEducation.index))

# print("\nImmigrant group in Alberta")
# df_AvgAnnWages_2010_ByImmigrant = df_AvgAnnWages_2010.loc[
#     (df_AvgAnnWages_2010['Characteristics'] == 'Immigrant employees') |
#     (df_AvgAnnWages_2010['Characteristics'] == 'Non-immigrant employees')
# ]
# # print(df_AvgAnnWages_2010_ByImmigrant.head(20))
# grouped = df_AvgAnnWages_2010_ByImmigrant.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgAnnWages_2010_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_AvgAnnWages_2010_ByIndigenous = df_AvgAnnWages_2010.loc[
#     (df_AvgAnnWages_2010['Characteristics'] == 'Indigenous identity employees') |
#     (df_AvgAnnWages_2010['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_AvgAnnHrk_ByIndigenous.head(20))
# grouped = df_AvgAnnWages_2010_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgAnnWages_2010_ByIndigenous.index))

In [57]:
# Dataset year in 2013 inside Average annual wages and salaries

print("\nAge group in Alberta")
df_AvgAnnWages_2013_ByAge = df_AvgAnnWages_2013.loc[
    (df_AvgAnnWages_2013['Characteristics'] == '15 to 24 years') |
    (df_AvgAnnWages_2013['Characteristics'] == '25 to 34 years') |
    (df_AvgAnnWages_2013['Characteristics'] == '35 to 44 years') |
    (df_AvgAnnWages_2013['Characteristics'] == '45 to 54 years') |
    (df_AvgAnnWages_2013['Characteristics'] == '55 to 64 years') |
    (df_AvgAnnWages_2013['Characteristics'] == '65 years old and over')]
# print(df_AvgAnnWages_2013_ByAge.head(20))
grouped = df_AvgAnnWages_2013_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgAnnWages_2013_ByAge.index))

print("\nGender group in Alberta")
df_AvgAnnWages_2013_ByGender = df_AvgAnnWages_2013.loc[
    (df_AvgAnnWages_2013['Characteristics'] == 'Female employees') |
    (df_AvgAnnWages_2013['Characteristics'] == 'Male employees')
]
# print(df_AvgAnnWages_2013_ByGender.head(20))
grouped = df_AvgAnnWages_2013_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgAnnWages_2013_ByGender.index))

print("\nEducation group in Alberta")
df_AvgAnnWages_2013_ByEducation = df_AvgAnnWages_2013.loc[
    (df_AvgAnnWages_2013['Characteristics'] == 'High school diploma and less') |
    (df_AvgAnnWages_2013['Characteristics'] == 'Trade certificate') |
    (df_AvgAnnWages_2013['Characteristics'] == 'University degree and higher')
]
# print(df_AvgAnnWages_2013_ByEducation.head(20))
grouped = df_AvgAnnWages_2013_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgAnnWages_2013_ByEducation.index))

print("\nImmigrant group in Alberta")
df_AvgAnnWages_2013_ByImmigrant = df_AvgAnnWages_2013.loc[
    (df_AvgAnnWages_2013['Characteristics'] == 'Immigrant employees') |
    (df_AvgAnnWages_2013['Characteristics'] == 'Non-immigrant employees')
]
# print(df_AvgAnnWages_2013_ByImmigrant.head(20))
grouped = df_AvgAnnWages_2013_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgAnnWages_2013_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_AvgAnnWages_2013_ByIndigenous = df_AvgAnnWages_2013.loc[
#     (df_AvgAnnWages_2013['Characteristics'] == 'Indigenous identity employees') |
#     (df_AvgAnnWages_2013['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_AvgAnnHrk_ByIndigenous.head(20))
# grouped = df_AvgAnnWages_2013_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgAnnWages_2013_ByIndigenous.index))

Age group in Alberta
                              sum  size
Characteristics
15 to 24 years          2784616.0   192
25 to 34 years          7953813.0   210
35 to 44 years         10794086.0   210
45 to 54 years         11596540.0   210
55 to 64 years         11087673.0   210
65 years old and over   5949938.0   192
The total number of this one is  1224

Gender group in Alberta
                         sum  size
Characteristics
Female employees   8352873.0   210
Male employees    10560729.0   210
The total number of this one is  420

Education group in Alberta
                                     sum  size
Characteristics
High school diploma and less   5903675.0   210
Trade certificate              7603798.0   198
University degree and higher  11213834.0   198
The total number of this one is  606

Immigrant group in Alberta
                               sum  size
Characteristics
Immigrant employees      8818758.0   198
Non-immigrant employees  8495409.0   198
The total number of this one is  396

In [58]:
# Dataset year in 2016 inside Average annual wages and salaries

print("\nAge group in Alberta")
df_AvgAnnWages_2016_ByAge = df_AvgAnnWages_2016.loc[
    (df_AvgAnnWages_2016['Characteristics'] == '15 to 24 years') |
    (df_AvgAnnWages_2016['Characteristics'] == '25 to 34 years') |
    (df_AvgAnnWages_2016['Characteristics'] == '35 to 44 years') |
    (df_AvgAnnWages_2016['Characteristics'] == '45 to 54 years') |
    (df_AvgAnnWages_2016['Characteristics'] == '55 to 64 years') |
    (df_AvgAnnWages_2016['Characteristics'] == '65 years old and over')]
# print(df_AvgAnnWages_2016_ByAge.head(20))
grouped = df_AvgAnnWages_2016_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgAnnWages_2016_ByAge.index))

print("\nGender group in Alberta")
df_AvgAnnWages_2016_ByGender = df_AvgAnnWages_2016.loc[
    (df_AvgAnnWages_2016['Characteristics'] == 'Female employees') |
    (df_AvgAnnWages_2016['Characteristics'] == 'Male employees')
]
# print(df_AvgAnnWages_2016_ByGender.head(20))
grouped = df_AvgAnnWages_2016_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgAnnWages_2016_ByGender.index))

print("\nEducation group in Alberta")
df_AvgAnnWages_2016_ByEducation = df_AvgAnnWages_2016.loc[
    (df_AvgAnnWages_2016['Characteristics'] == 'High school diploma and less') |
    (df_AvgAnnWages_2016['Characteristics'] == 'Trade certificate') |
    (df_AvgAnnWages_2016['Characteristics'] == 'University degree and higher')
]
# print(df_AvgAnnWages_2016_ByEducation.head(20))
grouped = df_AvgAnnWages_2016_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgAnnWages_2016_ByEducation.index))

print("\nImmigrant group in Alberta")
df_AvgAnnWages_2016_ByImmigrant = df_AvgAnnWages_2016.loc[
    (df_AvgAnnWages_2016['Characteristics'] == 'Immigrant employees') |
    (df_AvgAnnWages_2016['Characteristics'] == 'Non-immigrant employees')
]
# print(df_AvgAnnWages_2016_ByImmigrant.head(20))
grouped = df_AvgAnnWages_2016_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgAnnWages_2016_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_AvgAnnWages_2016_ByIndigenous = df_AvgAnnWages_2016.loc[
#     (df_AvgAnnWages_2016['Characteristics'] == 'Indigenous identity employees') |
#     (df_AvgAnnWages_2016['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_AvgAnnHrk_ByIndigenous.head(20))
# grouped = df_AvgAnnWages_2016_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgAnnWages_2016_ByIndigenous.index))

Age group in Alberta
                              sum  size
Characteristics
15 to 24 years          3060129.0   192
25 to 34 years          8325679.0   210
35 to 44 years         11269609.0   210
45 to 54 years         12276948.0   210
55 to 64 years         11610535.0   210
65 years old and over   6249361.0   192
The total number of this one is  1224

Gender group in Alberta
                         sum  size
Characteristics
Female employees   8890302.0   210
Male employees    10887008.0   210
The total number of this one is  420

Education group in Alberta
                                     sum  size
Characteristics
High school diploma and less   6237814.0   210
Trade certificate              7881695.0   198
University degree and higher  11672583.0   198
The total number of this one is  606

Immigrant group in Alberta
                               sum  size
Characteristics
Immigrant employees      9093448.0   198
Non-immigrant employees  8954165.0   198
The total number of this one is  396

In [59]:
# Dataset year in 2019 inside Average annual wages and salaries

print("\nAge group in Alberta")
df_AvgAnnWages_2019_ByAge = df_AvgAnnWages_2019.loc[
    (df_AvgAnnWages_2019['Characteristics'] == '15 to 24 years') |
    (df_AvgAnnWages_2019['Characteristics'] == '25 to 34 years') |
    (df_AvgAnnWages_2019['Characteristics'] == '35 to 44 years') |
    (df_AvgAnnWages_2019['Characteristics'] == '45 to 54 years') |
    (df_AvgAnnWages_2019['Characteristics'] == '55 to 64 years') |
    (df_AvgAnnWages_2019['Characteristics'] == '65 years old and over')]
# print(df_AvgAnnWages_2019_ByAge.head(20))
grouped = df_AvgAnnWages_2019_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgAnnWages_2019_ByAge.index))

print("\nGender group in Alberta")
df_AvgAnnWages_2019_ByGender = df_AvgAnnWages_2019.loc[
    (df_AvgAnnWages_2019['Characteristics'] == 'Female employees') |
    (df_AvgAnnWages_2019['Characteristics'] == 'Male employees')
]
# print(df_AvgAnnWages_2019_ByGender.head(20))
grouped = df_AvgAnnWages_2019_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgAnnWages_2019_ByGender.index))

print("\nEducation group in Alberta")
df_AvgAnnWages_2019_ByEducation = df_AvgAnnWages_2019.loc[
    (df_AvgAnnWages_2019['Characteristics'] == 'High school diploma and less') |
    (df_AvgAnnWages_2019['Characteristics'] == 'Trade certificate') |
    (df_AvgAnnWages_2019['Characteristics'] == 'University degree and higher')
]
# print(df_AvgAnnWages_2019_ByEducation.head(20))
grouped = df_AvgAnnWages_2019_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgAnnWages_2019_ByEducation.index))

print("\nImmigrant group in Alberta")
df_AvgAnnWages_2019_ByImmigrant = df_AvgAnnWages_2019.loc[
    (df_AvgAnnWages_2019['Characteristics'] == 'Immigrant employees') |
    (df_AvgAnnWages_2019['Characteristics'] == 'Non-immigrant employees')
]
# print(df_AvgAnnWages_2019_ByImmigrant.head(20))
grouped = df_AvgAnnWages_2019_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgAnnWages_2019_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_AvgAnnWages_2019_ByIndigenous = df_AvgAnnWages_2019.loc[
#     (df_AvgAnnWages_2019['Characteristics'] == 'Indigenous identity employees') |
#     (df_AvgAnnWages_2019['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_AvgAnnHrk_ByIndigenous.head(20))
# grouped = df_AvgAnnWages_2019_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgAnnWages_2019_ByIndigenous.index))

Age group in Alberta
                              sum  size
Characteristics
15 to 24 years          3482308.0   192
25 to 34 years          9108041.0   210
35 to 44 years         12296655.0   210
45 to 54 years         13595377.0   210
55 to 64 years         12592232.0   210
65 years old and over   6840988.0   192
The total number of this one is  1224

Gender group in Alberta
                         sum  size
Characteristics
Female employees   9929829.0   210
Male employees    11755264.0   210
The total number of this one is  420

Education group in Alberta
                                     sum  size
Characteristics
High school diploma and less   6915927.0   210
Trade certificate              8609637.0   198
University degree and higher  12581443.0   198
The total number of this one is  606

Immigrant group in Alberta
                               sum  size
Characteristics
Immigrant employees      9838690.0   198
Non-immigrant employees  9799014.0   198
The total number of this one is  396

Filtered for "Average hourly wage" by following: "Age group", "Gender level", "Education level", and "Immigration status". <br />
"Aboriginal status" has been commented.

In [60]:
# # Dataset year of 2010 inside "Average hourly wage"

# print("\nAge group in Alberta")
# df_AvgHrsWages_2010_ByAge = df_AvgHrsWages_2010.loc[
#     (df_AvgHrsWages_2010['Characteristics'] == '15 to 24 years') |
#     (df_AvgHrsWages_2010['Characteristics'] == '25 to 34 years') |
#     (df_AvgHrsWages_2010['Characteristics'] == '35 to 44 years') |
#     (df_AvgHrsWages_2010['Characteristics'] == '45 to 54 years') |
#     (df_AvgHrsWages_2010['Characteristics'] == '55 to 64 years') |
#     (df_AvgHrsWages_2010['Characteristics'] == '65 years old and over')]
# # print(df_AvgHrsWages_2010_ByAge.head(20))
# grouped = df_AvgHrsWages_2010_ByAge.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgHrsWages_2010_ByAge.index))

# print("\nGender group in Alberta")
# df_AvgHrsWages_2010_ByGender = df_AvgHrsWages_2010.loc[
#     (df_AvgHrsWages_2010['Characteristics'] == 'Female employees') |
#     (df_AvgHrsWages_2010['Characteristics'] == 'Male employees')
# ]
# # print(df_AvgHrsWages_2010_ByGender.head(20))
# grouped = df_AvgHrsWages_2010_ByGender.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgHrsWages_2010_ByGender.index))

# print("\nEducation group in Alberta")
# df_AvgHrsWages_2010_ByEducation = df_AvgHrsWages_2010.loc[
#     (df_AvgHrsWages_2010['Characteristics'] == 'High school diploma and less') |
#     (df_AvgHrsWages_2010['Characteristics'] == 'Trade certificate') |
#     (df_AvgHrsWages_2010['Characteristics'] == 'University degree and higher')
# ]
# # print(df_AvgHrsWages_2010_ByEducation.head(20))
# grouped = df_AvgHrsWages_2010_ByEducation.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgHrsWages_2010_ByEducation.index))

# print("\nImmigrant group in Alberta")
# df_AvgHrsWages_2010_ByImmigrant = df_AvgHrsWages_2010.loc[
#     (df_AvgHrsWages_2010['Characteristics'] == 'Immigrant employees') |
#     (df_AvgHrsWages_2010['Characteristics'] == 'Non-immigrant employees')
# ]
# # print(df_AvgHrsWages_2010_ByImmigrant.head(20))
# grouped = df_AvgHrsWages_2010_ByImmigrant.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgHrsWages_2010_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_AvgHrsWages_2010_ByIndigenous = df_AvgHrsWages_2010.loc[
#     (df_AvgHrsWages_2010['Characteristics'] == 'Indigenous identity employees') |
#     (df_AvgHrsWages_2010['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_AvgHrsWages_2010_ByIndigenous.head(20))
# grouped = df_AvgHrsWages_2010_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgHrsWages_2010_ByIndigenous.index))

In [61]:
# Dataset year of 2013 inside "Average hourly wage"

print("\nAge group in Alberta")
df_AvgHrsWages_2013_ByAge = df_AvgHrsWages_2013.loc[
    (df_AvgHrsWages_2013['Characteristics'] == '15 to 24 years') |
    (df_AvgHrsWages_2013['Characteristics'] == '25 to 34 years') |
    (df_AvgHrsWages_2013['Characteristics'] == '35 to 44 years') |
    (df_AvgHrsWages_2013['Characteristics'] == '45 to 54 years') |
    (df_AvgHrsWages_2013['Characteristics'] == '55 to 64 years') |
    (df_AvgHrsWages_2013['Characteristics'] == '65 years old and over')]
# print(df_AvgHrsWages_2013_ByAge.head(20))
grouped = df_AvgHrsWages_2013_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgHrsWages_2013_ByAge.index))

print("\nGender group in Alberta")
df_AvgHrsWages_2013_ByGender = df_AvgHrsWages_2013.loc[
    (df_AvgHrsWages_2013['Characteristics'] == 'Female employees') |
    (df_AvgHrsWages_2013['Characteristics'] == 'Male employees')
]
# print(df_AvgHrsWages_2013_ByGender.head(20))
grouped = df_AvgHrsWages_2013_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgHrsWages_2013_ByGender.index))

print("\nEducation group in Alberta")
df_AvgHrsWages_2013_ByEducation = df_AvgHrsWages_2013.loc[
    (df_AvgHrsWages_2013['Characteristics'] == 'High school diploma and less') |
    (df_AvgHrsWages_2013['Characteristics'] == 'Trade certificate') |
    (df_AvgHrsWages_2013['Characteristics'] == 'University degree and higher')
]
# print(df_AvgHrsWages_2013_ByEducation.head(20))
grouped = df_AvgHrsWages_2013_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgHrsWages_2013_ByEducation.index))

print("\nImmigrant group in Alberta")
df_AvgHrsWages_2013_ByImmigrant = df_AvgHrsWages_2013.loc[
    (df_AvgHrsWages_2013['Characteristics'] == 'Immigrant employees') |
    (df_AvgHrsWages_2013['Characteristics'] == 'Non-immigrant employees')
]
# print(df_AvgHrsWages_2013_ByImmigrant.head(20))
grouped = df_AvgHrsWages_2013_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgHrsWages_2013_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_AvgHrsWages_2013_ByIndigenous = df_AvgHrsWages_2013.loc[
#     (df_AvgHrsWages_2013['Characteristics'] == 'Indigenous identity employees') |
#     (df_AvgHrsWages_2013['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_AvgHrsWages_2013_ByIndigenous.head(20))
# grouped = df_AvgHrsWages_2013_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgHrsWages_2013_ByIndigenous.index))

Age group in Alberta
                           sum  size
Characteristics
15 to 24 years         3089.01   192
25 to 34 years         4937.02   210
35 to 44 years         6053.85   210
45 to 54 years         6297.06   210
55 to 64 years         6605.48   210
65 years old and over  5475.51   192
The total number of this one is  1224

Gender group in Alberta
                      sum  size
Characteristics
Female employees  5447.57   210
Male employees    6321.74   210
The total number of this one is  420

Education group in Alberta
                                  sum  size
Characteristics
High school diploma and less  4434.80   210
Trade certificate             4774.81   198
University degree and higher  6415.25   198
The total number of this one is  606

Immigrant group in Alberta
                             sum  size
Characteristics
Immigrant employees      5306.29   198
Non-immigrant employees  5402.47   198
The total number of this one is  396

In [62]:
# Dataset year in 2017 inside "Average hourly wage"

print("\nAge group in Alberta")
df_AvgHrsWages_2016_ByAge = df_AvgHrsWages_2016.loc[
    (df_AvgHrsWages_2016['Characteristics'] == '15 to 24 years') |
    (df_AvgHrsWages_2016['Characteristics'] == '25 to 34 years') |
    (df_AvgHrsWages_2016['Characteristics'] == '35 to 44 years') |
    (df_AvgHrsWages_2016['Characteristics'] == '45 to 54 years') |
    (df_AvgHrsWages_2016['Characteristics'] == '55 to 64 years') |
    (df_AvgHrsWages_2016['Characteristics'] == '65 years old and over')]
# print(df_AvgHrsWages_2016_ByAge.head(20))
grouped = df_AvgHrsWages_2016_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgHrsWages_2016_ByAge.index))

print("\nGender group in Alberta")
df_AvgHrsWages_2016_ByGender = df_AvgHrsWages_2016.loc[
    (df_AvgHrsWages_2016['Characteristics'] == 'Female employees') |
    (df_AvgHrsWages_2016['Characteristics'] == 'Male employees')
]
# print(df_AvgHrsWages_2016_ByGender.head(20))
grouped = df_AvgHrsWages_2016_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgHrsWages_2016_ByGender.index))

print("\nEducation group in Alberta")
df_AvgHrsWages_2016_ByEducation = df_AvgHrsWages_2016.loc[
    (df_AvgHrsWages_2016['Characteristics'] == 'High school diploma and less') |
    (df_AvgHrsWages_2016['Characteristics'] == 'Trade certificate') |
    (df_AvgHrsWages_2016['Characteristics'] == 'University degree and higher')
]
# print(df_AvgHrsWages_2016_ByEducation.head(20))
grouped = df_AvgHrsWages_2016_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgHrsWages_2016_ByEducation.index))

print("\nImmigrant group in Alberta")
df_AvgHrsWages_2016_ByImmigrant = df_AvgHrsWages_2016.loc[
    (df_AvgHrsWages_2016['Characteristics'] == 'Immigrant employees') |
    (df_AvgHrsWages_2016['Characteristics'] == 'Non-immigrant employees')
]
# print(df_AvgHrsWages_2016_ByImmigrant.head(20))
grouped = df_AvgHrsWages_2016_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgHrsWages_2016_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_AvgAnnHrk_ByIndigenous = df_AvgHrsWages_2016.loc[
#     (df_AvgHrsWages_2016['Characteristics'] == 'Indigenous identity employees') |
#     (df_AvgHrsWages_2016['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_AvgAnnHrk_ByIndigenous.head(20))
# grouped = df_AvgAnnHrk_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgAnnHrk_ByIndigenous.index))

Age group in Alberta
                           sum  size
Characteristics
15 to 24 years         3305.36   192
25 to 34 years         5214.72   210
35 to 44 years         6375.48   210
45 to 54 years         6704.45   210
55 to 64 years         6934.64   210
65 years old and over  5778.32   192
The total number of this one is  1224

Gender group in Alberta
                      sum  size
Characteristics
Female employees  5805.97   210
Male employees    6607.99   210
The total number of this one is  420

Education group in Alberta
                                  sum  size
Characteristics
High school diploma and less  4707.09   210
Trade certificate             5053.86   198
University degree and higher  6739.74   198
The total number of this one is  606

Immigrant group in Alberta
                             sum  size
Characteristics
Immigrant employees      5560.78   198
Non-immigrant employees  5726.37   198
The total number of this one is  396

In [63]:
# Dataset year in 2019 inside "Average hourly wage"

print("\nAge group in Alberta")
df_AvgHrsWages_2019_ByAge = df_AvgHrsWages_2019.loc[
    (df_AvgHrsWages_2019['Characteristics'] == '15 to 24 years') |
    (df_AvgHrsWages_2019['Characteristics'] == '25 to 34 years') |
    (df_AvgHrsWages_2019['Characteristics'] == '35 to 44 years') |
    (df_AvgHrsWages_2019['Characteristics'] == '45 to 54 years') |
    (df_AvgHrsWages_2019['Characteristics'] == '55 to 64 years') |
    (df_AvgHrsWages_2019['Characteristics'] == '65 years old and over')]
# print(df_AvgHrsWages_2019_ByAge.head(20))
grouped = df_AvgHrsWages_2019_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgHrsWages_2019_ByAge.index))

print("\nGender group in Alberta")
df_AvgHrsWages_2019_ByGender = df_AvgHrsWages_2019.loc[
    (df_AvgHrsWages_2019['Characteristics'] == 'Female employees') |
    (df_AvgHrsWages_2019['Characteristics'] == 'Male employees')
]
# print(df_AvgHrsWages_2019_ByGender.head(20))
grouped = df_AvgHrsWages_2019_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgHrsWages_2019_ByGender.index))

print("\nEducation group in Alberta")
df_AvgHrsWages_2019_ByEducation = df_AvgHrsWages_2019.loc[
    (df_AvgHrsWages_2019['Characteristics'] == 'High school diploma and less') |
    (df_AvgHrsWages_2019['Characteristics'] == 'Trade certificate') |
    (df_AvgHrsWages_2019['Characteristics'] == 'University degree and higher')
]
# print(df_AvgHrsWages_2019_ByEducation.head(20))
grouped = df_AvgHrsWages_2019_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgHrsWages_2019_ByEducation.index))

print("\nImmigrant group in Alberta")
df_AvgHrsWages_2019_ByImmigrant = df_AvgHrsWages_2019.loc[
    (df_AvgHrsWages_2019['Characteristics'] == 'Immigrant employees') |
    (df_AvgHrsWages_2019['Characteristics'] == 'Non-immigrant employees')
]
# print(df_AvgHrsWages_2019_ByImmigrant.head(20))
grouped = df_AvgHrsWages_2019_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgHrsWages_2019_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_AvgHrsWages_2019_ByIndigenous = df_AvgHrsWages_2019.loc[
#     (df_AvgHrsWages_2019['Characteristics'] == 'Indigenous identity employees') |
#     (df_AvgHrsWages_2019['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_AvgHrsWages_2019_ByIndigenous.head(20))
# grouped = df_AvgHrsWages_2019_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgHrsWages_2019_ByIndigenous.index))

Age group in Alberta
                           sum  size
Characteristics
15 to 24 years         3689.12   192
25 to 34 years         5759.41   210
35 to 44 years         6991.24   210
45 to 54 years         7451.95   210
55 to 64 years         7475.92   210
65 years old and over  6329.58   192
The total number of this one is  1224

Gender group in Alberta
                      sum  size
Characteristics
Female employees  6439.32   210
Male employees    7203.15   210
The total number of this one is  420

Education group in Alberta
                                  sum  size
Characteristics
High school diploma and less  5242.44   210
Trade certificate             5569.30   198
University degree and higher  7296.08   198
The total number of this one is  606

Immigrant group in Alberta
                             sum  size
Characteristics
Immigrant employees      6065.65   198
Non-immigrant employees  6267.15   198
The total number of this one is  396

Filtered for "Average weekly hours worked" by following: "Age group", "Gender level", "Education level", and "Immigration status".<br />
"Aboriginal status" has been commented.

In [64]:
# # Dataset year in 2010 inside "Average weekly hours worked"

# print("\nAge group in Alberta")
# df_AvgWeekHrsWrked_2010_ByAge = df_AvgWeekHrsWrked_2010.loc[
#     (df_AvgWeekHrsWrked_2010['Characteristics'] == '15 to 24 years') |
#     (df_AvgWeekHrsWrked_2010['Characteristics'] == '25 to 34 years') |
#     (df_AvgWeekHrsWrked_2010['Characteristics'] == '35 to 44 years') |
#     (df_AvgWeekHrsWrked_2010['Characteristics'] == '45 to 54 years') |
#     (df_AvgWeekHrsWrked_2010['Characteristics'] == '55 to 64 years') |
#     (df_AvgWeekHrsWrked_2010['Characteristics'] == '65 years old and over')]
# # print(df_AvgWeekHrsWrked_2010_ByAge.head(20))
# grouped = df_AvgWeekHrsWrked_2010_ByAge.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgWeekHrsWrked_2010_ByAge.index))

# print("\nGender group in Alberta")
# df_AvgWeekHrsWrked_2010_ByGender = df_AvgWeekHrsWrked_2010.loc[
#     (df_AvgWeekHrsWrked_2010['Characteristics'] == 'Female employees') |
#     (df_AvgWeekHrsWrked_2010['Characteristics'] == 'Male employees')
# ]
# # print(df_AvgWeekHrsWrked_2010_ByGender.head(20))
# grouped = df_AvgWeekHrsWrked_2010_ByGender.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgWeekHrsWrked_2010_ByGender.index))

# print("\nEducation group in Alberta")
# df_AvgWeekHrsWrked_2010_ByEducation = df_AvgWeekHrsWrked_2010.loc[
#     (df_AvgWeekHrsWrked_2010['Characteristics'] == 'High school diploma and less') |
#     (df_AvgWeekHrsWrked_2010['Characteristics'] == 'Trade certificate') |
#     (df_AvgWeekHrsWrked_2010['Characteristics'] == 'University degree and higher')
# ]
# # print(df_AvgWeekHrsWrked_2010_ByEducation.head(20))
# grouped = df_AvgWeekHrsWrked_2010_ByEducation.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgWeekHrsWrked_2010_ByEducation.index))

# print("\nImmigrant group in Alberta")
# df_AvgWeekHrsWrked_2010_ByImmigrant = df_AvgWeekHrsWrked_2010.loc[
#     (df_AvgWeekHrsWrked_2010['Characteristics'] == 'Immigrant employees') |
#     (df_AvgWeekHrsWrked_2010['Characteristics'] == 'Non-immigrant employees')
# ]
# # print(df_AvgWeekHrsWrked_2010_ByImmigrant.head(20))
# grouped = df_AvgWeekHrsWrked_2010_ByImmigrant.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgWeekHrsWrked_2010_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_AvgWeekHrsWrked_2010_ByIndigenous = df_AvgWeekHrsWrked_2010.loc[
#     (df_AvgWeekHrsWrked_2010['Characteristics'] == 'Indigenous identity employees') |
#     (df_AvgWeekHrsWrked_2010['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_AvgWeekHrsWrked_2010_ByIndigenous.head(20))
# grouped = df_AvgWeekHrsWrked_2010_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgWeekHrsWrked_2010_ByIndigenous.index))

In [65]:
# Dataset year in 2013 inside "Average weekly hours worked"

print("\nAge group in Alberta")
df_AvgWeekHrsWrked_2013_ByAge = df_AvgWeekHrsWrked_2013.loc[
    (df_AvgWeekHrsWrked_2013['Characteristics'] == '15 to 24 years') |
    (df_AvgWeekHrsWrked_2013['Characteristics'] == '25 to 34 years') |
    (df_AvgWeekHrsWrked_2013['Characteristics'] == '35 to 44 years') |
    (df_AvgWeekHrsWrked_2013['Characteristics'] == '45 to 54 years') |
    (df_AvgWeekHrsWrked_2013['Characteristics'] == '55 to 64 years') |
    (df_AvgWeekHrsWrked_2013['Characteristics'] == '65 years old and over')]
# print(df_AvgWeekHrsWrked_2013_ByAge.head(20))
grouped = df_AvgWeekHrsWrked_2013_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgWeekHrsWrked_2013_ByAge.index))

print("\nGender group in Alberta")
df_AvgWeekHrsWrked_2013_ByGender = df_AvgWeekHrsWrked_2013.loc[
    (df_AvgWeekHrsWrked_2013['Characteristics'] == 'Female employees') |
    (df_AvgWeekHrsWrked_2013['Characteristics'] == 'Male employees')
]
# print(df_AvgWeekHrsWrked_2013_ByGender.head(20))
grouped = df_AvgWeekHrsWrked_2013_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgWeekHrsWrked_2013_ByGender.index))

print("\nEducation group in Alberta")
df_AvgWeekHrsWrked_2013_ByEducation = df_AvgWeekHrsWrked_2013.loc[
    (df_AvgWeekHrsWrked_2013['Characteristics'] == 'High school diploma and less') |
    (df_AvgWeekHrsWrked_2013['Characteristics'] == 'Trade certificate') |
    (df_AvgWeekHrsWrked_2013['Characteristics'] == 'University degree and higher')
]
# print(df_AvgWeekHrsWrked_2013_ByEducation.head(20))
grouped = df_AvgWeekHrsWrked_2013_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgWeekHrsWrked_2013_ByEducation.index))

print("\nImmigrant group in Alberta")
df_AvgWeekHrsWrked_2013_ByImmigrant = df_AvgWeekHrsWrked_2013.loc[
    (df_AvgWeekHrsWrked_2013['Characteristics'] == 'Immigrant employees') |
    (df_AvgWeekHrsWrked_2013['Characteristics'] == 'Non-immigrant employees')
]
# print(df_AvgWeekHrsWrked_2013_ByImmigrant.head(20))
grouped = df_AvgWeekHrsWrked_2013_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgWeekHrsWrked_2013_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_AvgWeekHrsWrked_2013_ByIndigenous = df_AvgWeekHrsWrked_2013.loc[
#     (df_AvgWeekHrsWrked_2013['Characteristics'] == 'Indigenous identity employees') |
#     (df_AvgWeekHrsWrked_2013['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_AvgWeekHrsWrked_2013_ByIndigenous.head(20))
# grouped = df_AvgWeekHrsWrked_2013_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgWeekHrsWrked_2013_ByIndigenous.index))

Age group in Alberta
                          sum  size
Characteristics
15 to 24 years         3314.0   192
25 to 34 years         6556.0   210
35 to 44 years         7256.0   210
45 to 54 years         7454.0   210
55 to 64 years         6780.0   210
65 years old and over  3983.0   192
The total number of this one is  1224

Gender group in Alberta
                     sum  size
Characteristics
Female employees  6196.0   210
Male employees    6768.0   210
The total number of this one is  420

Education group in Alberta
                                 sum  size
Characteristics
High school diploma and less  5334.0   210
Trade certificate             6034.0   198
University degree and higher  6681.0   198
The total number of this one is  606

Immigrant group in Alberta
                            sum  size
Characteristics
Immigrant employees      6278.0   198
Non-immigrant employees  6001.0   198
The total number of this one is  396

In [66]:
# Dataset year in 2016 inside "Average weekly hours worked"

print("\nAge group in Alberta")
df_AvgWeekHrsWrked_2016_ByAge = df_AvgWeekHrsWrked_2016.loc[
    (df_AvgWeekHrsWrked_2016['Characteristics'] == '15 to 24 years') |
    (df_AvgWeekHrsWrked_2016['Characteristics'] == '25 to 34 years') |
    (df_AvgWeekHrsWrked_2016['Characteristics'] == '35 to 44 years') |
    (df_AvgWeekHrsWrked_2016['Characteristics'] == '45 to 54 years') |
    (df_AvgWeekHrsWrked_2016['Characteristics'] == '55 to 64 years') |
    (df_AvgWeekHrsWrked_2016['Characteristics'] == '65 years old and over')]
# print(df_AvgWeekHrsWrked_2016_ByAge.head(20))
grouped = df_AvgWeekHrsWrked_2016_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgWeekHrsWrked_2016_ByAge.index))

print("\nGender group in Alberta")
df_AvgWeekHrsWrked_2016_ByGender = df_AvgWeekHrsWrked_2016.loc[
    (df_AvgWeekHrsWrked_2016['Characteristics'] == 'Female employees') |
    (df_AvgWeekHrsWrked_2016['Characteristics'] == 'Male employees')
]
# print(df_AvgWeekHrsWrked_2016_ByGender.head(20))
grouped = df_AvgWeekHrsWrked_2016_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgWeekHrsWrked_2016_ByGender.index))

print("\nEducation group in Alberta")
df_AvgWeekHrsWrked_2016_ByEducation = df_AvgWeekHrsWrked_2016.loc[
    (df_AvgWeekHrsWrked_2016['Characteristics'] == 'High school diploma and less') |
    (df_AvgWeekHrsWrked_2016['Characteristics'] == 'Trade certificate') |
    (df_AvgWeekHrsWrked_2016['Characteristics'] == 'University degree and higher')
]
# print(df_AvgWeekHrsWrked_2016_ByEducation.head(20))
grouped = df_AvgWeekHrsWrked_2016_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgWeekHrsWrked_2016_ByEducation.index))

print("\nImmigrant group in Alberta")
df_AvgWeekHrsWrked_2016_ByImmigrant = df_AvgWeekHrsWrked_2016.loc[
    (df_AvgWeekHrsWrked_2016['Characteristics'] == 'Immigrant employees') |
    (df_AvgWeekHrsWrked_2016['Characteristics'] == 'Non-immigrant employees')
]
# print(df_AvgWeekHrsWrked_2016_ByImmigrant.head(20))
grouped = df_AvgWeekHrsWrked_2016_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgWeekHrsWrked_2016_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_AvgWeekHrsWrked_2016_ByIndigenous = df_AvgWeekHrsWrked_2016.loc[
#     (df_AvgWeekHrsWrked_2016['Characteristics'] == 'Indigenous identity employees') |
#     (df_AvgWeekHrsWrked_2016['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_AvgAnnHrk_ByIndigenous.head(20))
# grouped = df_AvgWeekHrsWrked_2016_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgWeekHrsWrked_2016_ByIndigenous.index))

Age group in Alberta
                          sum  size
Characteristics
15 to 24 years         3387.0   192
25 to 34 years         6489.0   210
35 to 44 years         7185.0   210
45 to 54 years         7415.0   210
55 to 64 years         6748.0   210
65 years old and over  3965.0   192
The total number of this one is  1224

Gender group in Alberta
                     sum  size
Characteristics
Female employees  6184.0   210
Male employees    6668.0   210
The total number of this one is  420

Education group in Alberta
                                 sum  size
Characteristics
High school diploma and less  5315.0   210
Trade certificate             5922.0   198
University degree and higher  6604.0   198
The total number of this one is  606

Immigrant group in Alberta
                            sum  size
Characteristics
Immigrant employees      6185.0   198
Non-immigrant employees  5968.0   198
The total number of this one is  396

In [67]:
# Dataset year in 2019 inside "Average weekly hours worked"

print("\nAge group in Alberta")
df_AvgWeekHrsWrked_2019_ByAge = df_AvgWeekHrsWrked_2019.loc[
    (df_AvgWeekHrsWrked_2019['Characteristics'] == '15 to 24 years') |
    (df_AvgWeekHrsWrked_2019['Characteristics'] == '25 to 34 years') |
    (df_AvgWeekHrsWrked_2019['Characteristics'] == '35 to 44 years') |
    (df_AvgWeekHrsWrked_2019['Characteristics'] == '45 to 54 years') |
    (df_AvgWeekHrsWrked_2019['Characteristics'] == '55 to 64 years') |
    (df_AvgWeekHrsWrked_2019['Characteristics'] == '65 years old and over')]
# print(df_AvgWeekHrsWrked_2019_ByAge.head(20))
grouped = df_AvgWeekHrsWrked_2019_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgWeekHrsWrked_2019_ByAge.index))

print("\nGender group in Alberta")
df_AvgWeekHrsWrked_2019_ByGender = df_AvgWeekHrsWrked_2019.loc[
    (df_AvgWeekHrsWrked_2019['Characteristics'] == 'Female employees') |
    (df_AvgWeekHrsWrked_2019['Characteristics'] == 'Male employees')
]
# print(df_AvgWeekHrsWrked_2019_ByGender.head(20))
grouped = df_AvgWeekHrsWrked_2019_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgWeekHrsWrked_2019_ByGender.index))

print("\nEducation group in Alberta")
df_AvgWeekHrsWrked_2019_ByEducation = df_AvgWeekHrsWrked_2019.loc[
    (df_AvgWeekHrsWrked_2019['Characteristics'] == 'High school diploma and less') |
    (df_AvgWeekHrsWrked_2019['Characteristics'] == 'Trade certificate') |
    (df_AvgWeekHrsWrked_2019['Characteristics'] == 'University degree and higher')
]
# print(df_AvgWeekHrsWrked_2019_ByEducation.head(20))
grouped = df_AvgWeekHrsWrked_2019_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgWeekHrsWrked_2019_ByEducation.index))

print("\nImmigrant group in Alberta")
df_AvgWeekHrsWrked_2019_ByImmigrant = df_AvgWeekHrsWrked_2019.loc[
    (df_AvgWeekHrsWrked_2019['Characteristics'] == 'Immigrant employees') |
    (df_AvgWeekHrsWrked_2019['Characteristics'] == 'Non-immigrant employees')
]
# print(df_AvgWeekHrsWrked_2019_ByImmigrant.head(20))
grouped = df_AvgWeekHrsWrked_2019_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_AvgWeekHrsWrked_2019_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_AvgWeekHrsWrked_2019_ByIndigenous = df_AvgWeekHrsWrked_2019.loc[
#     (df_AvgWeekHrsWrked_2019['Characteristics'] == 'Indigenous identity employees') |
#     (df_AvgWeekHrsWrked_2019['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_AvgWeekHrsWrked_2019_ByIndigenous.head(20))
# grouped = df_AvgWeekHrsWrked_2019_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_AvgWeekHrsWrked_2019_ByIndigenous.index))

Age group in Alberta
                          sum  size
Characteristics
15 to 24 years         3465.0   192
25 to 34 years         6413.0   210
35 to 44 years         7139.0   210
45 to 54 years         7406.0   210
55 to 64 years         6765.0   210
65 years old and over  3969.0   192
The total number of this one is  1224

Gender group in Alberta
                     sum  size
Characteristics
Female employees  6219.0   210
Male employees    6590.0   210
The total number of this one is  420

Education group in Alberta
                                 sum  size
Characteristics
High school diploma and less  5303.0   210
Trade certificate             5889.0   198
University degree and higher  6568.0   198
The total number of this one is  606

Immigrant group in Alberta
                            sum  size
Characteristics
Immigrant employees      6133.0   198
Non-immigrant employees  5961.0   198
The total number of this one is  396

Filtered for "Hours worked" by following: "Age group", "Gender level", "Education level", and "Immigration status".<br />
"Aboriginal status" has been commented.

In [68]:
# # Dataset year in 2010 inside "Hours Worked"

# print("\nAge group in Alberta")
# df_Hrs_Wrked_2010_ByAge = df_Hrs_Wrked_2010.loc[
#     (df_Hrs_Wrked_2010['Characteristics'] == '15 to 24 years') |
#     (df_Hrs_Wrked_2010['Characteristics'] == '25 to 34 years') |
#     (df_Hrs_Wrked_2010['Characteristics'] == '35 to 44 years') |
#     (df_Hrs_Wrked_2010['Characteristics'] == '45 to 54 years') |
#     (df_Hrs_Wrked_2010['Characteristics'] == '55 to 64 years') |
#     (df_Hrs_Wrked_2010['Characteristics'] == '65 years old and over')]
# # print(df_Hrs_Wrked_2010_ByAge.head(20))
# grouped = df_Hrs_Wrked_2010_ByAge.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_Hrs_Wrked_2010_ByAge.index))

# print("\nGender group in Alberta")
# df_Hrs_Wrked_2010_ByGender = df_Hrs_Wrked_2010.loc[
#     (df_Hrs_Wrked_2010['Characteristics'] == 'Female employees') |
#     (df_Hrs_Wrked_2010['Characteristics'] == 'Male employees')
# ]
# # print(df_Hrs_Wrked_2010_ByGender.head(20))
# grouped = df_Hrs_Wrked_2010_ByGender.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_Hrs_Wrked_2010_ByGender.index))

# print("\nEducation group in Alberta")
# df_Hrs_Wrked_2010_ByEducation = df_Hrs_Wrked_2010.loc[
#     (df_Hrs_Wrked_2010['Characteristics'] == 'High school diploma and less') |
#     (df_Hrs_Wrked_2010['Characteristics'] == 'Trade certificate') |
#     (df_Hrs_Wrked_2010['Characteristics'] == 'University degree and higher')
# ]
# # print(df_Hrs_Wrked_2010_ByEducation.head(20))
# grouped = df_Hrs_Wrked_2010_ByEducation.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_Hrs_Wrked_2010_ByEducation.index))

# print("\nImmigrant group in Alberta")
# df_Hrs_Wrked_2010_ByImmigrant = df_Hrs_Wrked_2010.loc[
#     (df_Hrs_Wrked_2010['Characteristics'] == 'Immigrant employees') |
#     (df_Hrs_Wrked_2010['Characteristics'] == 'Non-immigrant employees')
# ]
# # print(df_Hrs_Wrked_2010_ByImmigrant.head(20))
# grouped = df_Hrs_Wrked_2010_ByImmigrant.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_Hrs_Wrked_2010_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_Hrs_Wrked_2010_ByIndigenous = df_Hrs_Wrked_2010.loc[
#     (df_Hrs_Wrked_2010['Characteristics'] == 'Indigenous identity employees') |
#     (df_Hrs_Wrked_2010['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_Hrs_Wrked_2010_ByIndigenous.head(20))
# grouped = df_Hrs_Wrked_2010_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_Hrs_Wrked_2010_ByIndigenous.index))

In [69]:
# Dataset year in 2013 inside "Hours Worked"

print("\nAge group in Alberta")
df_Hrs_Wrked_2013_ByAge = df_Hrs_Wrked_2013.loc[
    (df_Hrs_Wrked_2013['Characteristics'] == '15 to 24 years') |
    (df_Hrs_Wrked_2013['Characteristics'] == '25 to 34 years') |
    (df_Hrs_Wrked_2013['Characteristics'] == '35 to 44 years') |
    (df_Hrs_Wrked_2013['Characteristics'] == '45 to 54 years') |
    (df_Hrs_Wrked_2013['Characteristics'] == '55 to 64 years') |
    (df_Hrs_Wrked_2013['Characteristics'] == '65 years old and over')]
# print(df_Hrs_Wrked_2013_ByAge.head(20))
grouped = df_Hrs_Wrked_2013_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_Hrs_Wrked_2013_ByAge.index))

print("\nGender group in Alberta")
df_Hrs_Wrked_2013_ByGender = df_Hrs_Wrked_2013.loc[
    (df_Hrs_Wrked_2013['Characteristics'] == 'Female employees') |
    (df_Hrs_Wrked_2013['Characteristics'] == 'Male employees')
]
# print(df_Hrs_Wrked_2013_ByGender.head(20))
grouped = df_Hrs_Wrked_2013_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_Hrs_Wrked_2013_ByGender.index))

print("\nEducation group in Alberta")
df_Hrs_Wrked_2013_ByEducation = df_Hrs_Wrked_2013.loc[
    (df_Hrs_Wrked_2013['Characteristics'] == 'High school diploma and less') |
    (df_Hrs_Wrked_2013['Characteristics'] == 'Trade certificate') |
    (df_Hrs_Wrked_2013['Characteristics'] == 'University degree and higher')
]
# print(df_Hrs_Wrked_2013_ByEducation.head(20))
grouped = df_Hrs_Wrked_2013_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_Hrs_Wrked_2013_ByEducation.index))

print("\nImmigrant group in Alberta")
df_Hrs_Wrked_2013_ByImmigrant = df_Hrs_Wrked_2013.loc[
    (df_Hrs_Wrked_2013['Characteristics'] == 'Immigrant employees') |
    (df_Hrs_Wrked_2013['Characteristics'] == 'Non-immigrant employees')
]
# print(df_Hrs_Wrked_2013_ByImmigrant.head(20))
grouped = df_Hrs_Wrked_2013_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_Hrs_Wrked_2013_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_Hrs_Wrked_2013_ByIndigenous = df_Hrs_Wrked_2013.loc[
#     (df_Hrs_Wrked_2013['Characteristics'] == 'Indigenous identity employees') |
#     (df_Hrs_Wrked_2013['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_Hrs_Wrked_2013_ByIndigenous.head(20))
# grouped = df_Hrs_Wrked_2013_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_Hrs_Wrked_2013_ByIndigenous.index))

Age group in Alberta
                              sum  size
Characteristics
15 to 24 years          3107754.0   192
25 to 34 years         10595996.0   210
35 to 44 years         11379938.0   210
45 to 54 years         13158896.0   210
55 to 64 years          9899434.0   210
65 years old and over   1974184.0   192
The total number of this one is  1224

Gender group in Alberta
                         sum  size
Characteristics
Female employees  34086022.0   210
Male employees    16032036.0   210
The total number of this one is  420

Education group in Alberta
                                     sum  size
Characteristics
High school diploma and less   9259138.0   210
Trade certificate              3736455.0   198
University degree and higher  23601210.0   198
The total number of this one is  606

Immigrant group in Alberta
                                sum  size
Characteristics
Immigrant employees      12147236.0   198
Non-immigrant employees  37962608.0   198
The total number of this one is  396

In [70]:
# Dataset year in 2016 inside "Hours Worked"

print("\nAge group in Alberta")
df_Hrs_Wrked_2016_ByAge = df_Hrs_Wrked_2016.loc[
    (df_Hrs_Wrked_2016['Characteristics'] == '15 to 24 years') |
    (df_Hrs_Wrked_2016['Characteristics'] == '25 to 34 years') |
    (df_Hrs_Wrked_2016['Characteristics'] == '35 to 44 years') |
    (df_Hrs_Wrked_2016['Characteristics'] == '45 to 54 years') |
    (df_Hrs_Wrked_2016['Characteristics'] == '55 to 64 years') |
    (df_Hrs_Wrked_2016['Characteristics'] == '65 years old and over')]
# print(df_Hrs_Wrked_2016_ByAge.head(20))
grouped = df_Hrs_Wrked_2016_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_Hrs_Wrked_2016_ByAge.index))

print("\nGender group in Alberta")
df_Hrs_Wrked_2016_ByGender = df_Hrs_Wrked_2016.loc[
    (df_Hrs_Wrked_2016['Characteristics'] == 'Female employees') |
    (df_Hrs_Wrked_2016['Characteristics'] == 'Male employees')
]
# print(df_Hrs_Wrked_2016_ByGender.head(20))
grouped = df_Hrs_Wrked_2016_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_Hrs_Wrked_2016_ByGender.index))

print("\nEducation group in Alberta")
df_Hrs_Wrked_2016_ByEducation = df_Hrs_Wrked_2016.loc[
    (df_Hrs_Wrked_2016['Characteristics'] == 'High school diploma and less') |
    (df_Hrs_Wrked_2016['Characteristics'] == 'Trade certificate') |
    (df_Hrs_Wrked_2016['Characteristics'] == 'University degree and higher')
]
# print(df_Hrs_Wrked_2016_ByEducation.head(20))
grouped = df_Hrs_Wrked_2016_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_Hrs_Wrked_2016_ByEducation.index))

print("\nImmigrant group in Alberta")
df_Hrs_Wrked_2016_ByImmigrant = df_Hrs_Wrked_2016.loc[
    (df_Hrs_Wrked_2016['Characteristics'] == 'Immigrant employees') |
    (df_Hrs_Wrked_2016['Characteristics'] == 'Non-immigrant employees')
]
# print(df_Hrs_Wrked_2016_ByImmigrant.head(20))
grouped = df_Hrs_Wrked_2016_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_Hrs_Wrked_2016_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_Hrs_Wrked_2016_ByIndigenous = df_Hrs_Wrked_2016.loc[
#     (df_Hrs_Wrked_2016['Characteristics'] == 'Indigenous identity employees') |
#     (df_Hrs_Wrked_2016['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_AvgAnnHrk_ByIndigenous.head(20))
# grouped = df_Hrs_Wrked_2016_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_Hrs_Wrked_2016_ByIndigenous.index))

Age group in Alberta
                              sum  size
Characteristics
15 to 24 years          3211600.0   192
25 to 34 years         11296322.0   210
35 to 44 years         12146992.0   210
45 to 54 years         13070232.0   210
55 to 64 years         10422244.0   210
65 years old and over   2324345.0   192
The total number of this one is  1224

Gender group in Alberta
                         sum  size
Characteristics
Female employees  35855312.0   210
Male employees    16618598.0   210
The total number of this one is  420

Education group in Alberta
                                     sum  size
Characteristics
High school diploma and less   9485452.0   210
Trade certificate              3558304.0   198
University degree and higher  25474813.0   198
The total number of this one is  606

Immigrant group in Alberta
                                sum  size
Characteristics
Immigrant employees      13361296.0   198
Non-immigrant employees  39103961.0   198
The total number of this one is  396

In [71]:
# Dataset year in 2019 inside "Hour Worked"

print("\nAge group in Alberta")
df_Hrs_Wrked_2019_ByAge = df_Hrs_Wrked_2019.loc[
    (df_Hrs_Wrked_2019['Characteristics'] == '15 to 24 years') |
    (df_Hrs_Wrked_2019['Characteristics'] == '25 to 34 years') |
    (df_Hrs_Wrked_2019['Characteristics'] == '35 to 44 years') |
    (df_Hrs_Wrked_2019['Characteristics'] == '45 to 54 years') |
    (df_Hrs_Wrked_2019['Characteristics'] == '55 to 64 years') |
    (df_Hrs_Wrked_2019['Characteristics'] == '65 years old and over')]
# print(df_Hrs_Wrked_2019_ByAge.head(20))
grouped = df_Hrs_Wrked_2019_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_Hrs_Wrked_2019_ByAge.index))

print("\nGender group in Alberta")
df_Hrs_Wrked_2019_ByGender = df_Hrs_Wrked_2019.loc[
    (df_Hrs_Wrked_2019['Characteristics'] == 'Female employees') |
    (df_Hrs_Wrked_2019['Characteristics'] == 'Male employees')
]
# print(df_Hrs_Wrked_2019_ByGender.head(20))
grouped = df_Hrs_Wrked_2019_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_Hrs_Wrked_2019_ByGender.index))

print("\nEducation group in Alberta")
df_Hrs_Wrked_2019_ByEducation = df_Hrs_Wrked_2019.loc[
    (df_Hrs_Wrked_2019['Characteristics'] == 'High school diploma and less') |
    (df_Hrs_Wrked_2019['Characteristics'] == 'Trade certificate') |
    (df_Hrs_Wrked_2019['Characteristics'] == 'University degree and higher')
]
# print(df_Hrs_Wrked_2019_ByEducation.head(20))
grouped = df_Hrs_Wrked_2019_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_Hrs_Wrked_2019_ByEducation.index))

print("\nImmigrant group in Alberta")
df_Hrs_Wrked_2019_ByImmigrant = df_Hrs_Wrked_2019.loc[
    (df_Hrs_Wrked_2019['Characteristics'] == 'Immigrant employees') |
    (df_Hrs_Wrked_2019['Characteristics'] == 'Non-immigrant employees')
]
# print(df_Hrs_Wrked_2019_ByImmigrant.head(20))
grouped = df_Hrs_Wrked_2019_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_Hrs_Wrked_2019_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_Hrs_Wrked_2019_ByIndigenous = df_Hrs_Wrked_2019.loc[
#     (df_Hrs_Wrked_2019['Characteristics'] == 'Indigenous identity employees') |
#     (df_Hrs_Wrked_2019['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_Hrs_Wrked_2019_ByIndigenous.head(20))
# grouped = df_Hrs_Wrked_2019_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_Hrs_Wrked_2019_ByIndigenous.index))

Age group in Alberta
                              sum  size
Characteristics
15 to 24 years          3132171.0   192
25 to 34 years         11857576.0   210
35 to 44 years         12919606.0   210
45 to 54 years         12974580.0   210
55 to 64 years         10690620.0   210
65 years old and over   2528517.0   192
The total number of this one is  1224

Gender group in Alberta
                         sum  size
Characteristics
Female employees  37193214.0   210
Male employees    16912308.0   210
The total number of this one is  420

Education group in Alberta
                                     sum  size
Characteristics
High school diploma and less   9285900.0   210
Trade certificate              3449203.0   198
University degree and higher  27393105.0   198
The total number of this one is  606

Immigrant group in Alberta
                                sum  size
Characteristics
Immigrant employees      14355944.0   198
Non-immigrant employees  39740524.0   198
The total number of this one is  396

Filtered for "Number of jobs" by following: "Age group", "Gender level", "Education level", and "Immigration status".<br />
"Aboriginal status" has been commented.

In [72]:
# # Dataset year in 2010 inside "Number of jobs"

# print("\nAge group in Alberta")
# df_NumOfJob_2010_ByAge = df_NumOfJob_2010.loc[
#     (df_NumOfJob_2010['Characteristics'] == '15 to 24 years') |
#     (df_NumOfJob_2010['Characteristics'] == '25 to 34 years') |
#     (df_NumOfJob_2010['Characteristics'] == '35 to 44 years') |
#     (df_NumOfJob_2010['Characteristics'] == '45 to 54 years') |
#     (df_NumOfJob_2010['Characteristics'] == '55 to 64 years') |
#     (df_NumOfJob_2010['Characteristics'] == '65 years old and over')]
# # print(df_NumOfJob_2010_ByAge.head(20))
# grouped = df_NumOfJob_2010_ByAge.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_NumOfJob_2010_ByAge.index))

# print("\nGender group in Alberta")
# df_NumOfJob_2010_ByGender = df_NumOfJob_2010.loc[
#     (df_NumOfJob_2010['Characteristics'] == 'Female employees') |
#     (df_NumOfJob_2010['Characteristics'] == 'Male employees')
# ]
# # print(df_NumOfJob_2010_ByGender.head(20))
# grouped = df_NumOfJob_2010_ByGender.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_NumOfJob_2010_ByGender.index))

# print("\nEducation group in Alberta")
# df_NumOfJob_2010_ByEducation = df_NumOfJob_2010.loc[
#     (df_NumOfJob_2010['Characteristics'] == 'High school diploma and less') |
#     (df_NumOfJob_2010['Characteristics'] == 'Trade certificate') |
#     (df_NumOfJob_2010['Characteristics'] == 'University degree and higher')
# ]
# # print(df_NumOfJob_2010_ByEducation.head(20))
# grouped = df_NumOfJob_2010_ByEducation.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_NumOfJob_2010_ByEducation.index))

# print("\nImmigrant group in Alberta")
# df_NumOfJob_2010_ByImmigrant = df_NumOfJob_2010.loc[
#     (df_NumOfJob_2010['Characteristics'] == 'Immigrant employees') |
#     (df_NumOfJob_2010['Characteristics'] == 'Non-immigrant employees')
# ]
# # print(df_NumOfJob_2010_ByImmigrant.head(20))
# grouped = df_NumOfJob_2010_ByImmigrant.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_NumOfJob_2010_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_NumOfJob_2010_ByIndigenous = df_NumOfJob_2010.loc[
#     (df_NumOfJob_2010['Characteristics'] == 'Indigenous identity employees') |
#     (df_NumOfJob_2010['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_NumOfJob_2010_ByIndigenous.head(20))
# grouped = df_NumOfJob_2010_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_NumOfJob_2010_ByIndigenous.index))

In [73]:
# Dataset year in 2013 inside "Number of jobs"

print("\nAge group in Alberta")
df_NumOfJob_2013_ByAge = df_NumOfJob_2013.loc[
    (df_NumOfJob_2013['Characteristics'] == '15 to 24 years') |
    (df_NumOfJob_2013['Characteristics'] == '25 to 34 years') |
    (df_NumOfJob_2013['Characteristics'] == '35 to 44 years') |
    (df_NumOfJob_2013['Characteristics'] == '45 to 54 years') |
    (df_NumOfJob_2013['Characteristics'] == '55 to 64 years') |
    (df_NumOfJob_2013['Characteristics'] == '65 years old and over')]
# print(df_NumOfJob_2013_ByAge.head(20))
grouped = df_NumOfJob_2013_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_NumOfJob_2013_ByAge.index))

print("\nGender group in Alberta")
df_NumOfJob_2013_ByGender = df_NumOfJob_2013.loc[
    (df_NumOfJob_2013['Characteristics'] == 'Female employees') |
    (df_NumOfJob_2013['Characteristics'] == 'Male employees')
]
# print(df_NumOfJob_2013_ByGender.head(20))
grouped = df_NumOfJob_2013_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_NumOfJob_2013_ByGender.index))

print("\nEducation group in Alberta")
df_NumOfJob_2013_ByEducation = df_NumOfJob_2013.loc[
    (df_NumOfJob_2013['Characteristics'] == 'High school diploma and less') |
    (df_NumOfJob_2013['Characteristics'] == 'Trade certificate') |
    (df_NumOfJob_2013['Characteristics'] == 'University degree and higher')
]
# print(df_NumOfJob_2013_ByEducation.head(20))
grouped = df_NumOfJob_2013_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_NumOfJob_2013_ByEducation.index))

print("\nImmigrant group in Alberta")
df_NumOfJob_2013_ByImmigrant = df_NumOfJob_2013.loc[
    (df_NumOfJob_2013['Characteristics'] == 'Immigrant employees') |
    (df_NumOfJob_2013['Characteristics'] == 'Non-immigrant employees')
]
# print(df_NumOfJob_2013_ByImmigrant.head(20))
grouped = df_NumOfJob_2013_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_NumOfJob_2013_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_NumOfJob_2013_ByIndigenous = df_NumOfJob_2013.loc[
#     (df_NumOfJob_2013['Characteristics'] == 'Indigenous identity employees') |
#     (df_NumOfJob_2013['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_NumOfJob_2013_ByIndigenous.head(20))
# grouped = df_NumOfJob_2013_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_NumOfJob_2013_ByIndigenous.index))

Age group in Alberta
                             sum  size
Characteristics
15 to 24 years         3475038.0   192
25 to 34 years         6767092.0   210
35 to 44 years         6596518.0   210
45 to 54 years         7311054.0   210
55 to 64 years         6008488.0   210
65 years old and over  1910168.0   192
The total number of this one is  1224

Gender group in Alberta
                         sum  size
Characteristics
Female employees  22196810.0   210
Male employees     9873690.0   210
The total number of this one is  420

Education group in Alberta
                                     sum  size
Characteristics
High school diploma and less   7081390.0   210
Trade certificate              2417879.0   198
University degree and higher  14192344.0   198
The total number of this one is  606

Immigrant group in Alberta
                                sum  size
Characteristics
Immigrant employees       7694218.0   198
Non-immigrant employees  24370675.0   198
The total number of this one is  396

In [74]:
# Dataset year in 2016 inside "Number of jobs"

print("\nAge group in Alberta")
df_NumOfJob_2016_ByAge = df_NumOfJob_2016.loc[
    (df_NumOfJob_2016['Characteristics'] == '15 to 24 years') |
    (df_NumOfJob_2016['Characteristics'] == '25 to 34 years') |
    (df_NumOfJob_2016['Characteristics'] == '35 to 44 years') |
    (df_NumOfJob_2016['Characteristics'] == '45 to 54 years') |
    (df_NumOfJob_2016['Characteristics'] == '55 to 64 years') |
    (df_NumOfJob_2016['Characteristics'] == '65 years old and over')]
# print(df_NumOfJob_2016_ByAge.head(20))
grouped = df_NumOfJob_2016_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_NumOfJob_2016_ByAge.index))

print("\nGender group in Alberta")
df_NumOfJob_2016_ByGender = df_NumOfJob_2016.loc[
    (df_NumOfJob_2016['Characteristics'] == 'Female employees') |
    (df_NumOfJob_2016['Characteristics'] == 'Male employees')
]
# print(df_NumOfJob_2016_ByGender.head(20))
grouped = df_NumOfJob_2016_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_NumOfJob_2016_ByGender.index))

print("\nEducation group in Alberta")
df_NumOfJob_2016_ByEducation = df_NumOfJob_2016.loc[
    (df_NumOfJob_2016['Characteristics'] == 'High school diploma and less') |
    (df_NumOfJob_2016['Characteristics'] == 'Trade certificate') |
    (df_NumOfJob_2016['Characteristics'] == 'University degree and higher')
]
# print(df_NumOfJob_2016_ByEducation.head(20))
grouped = df_NumOfJob_2016_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_NumOfJob_2016_ByEducation.index))

print("\nImmigrant group in Alberta")
df_NumOfJob_2016_ByImmigrant = df_NumOfJob_2016.loc[
    (df_NumOfJob_2016['Characteristics'] == 'Immigrant employees') |
    (df_NumOfJob_2016['Characteristics'] == 'Non-immigrant employees')
]
# print(df_NumOfJob_2016_ByImmigrant.head(20))
grouped = df_NumOfJob_2016_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_NumOfJob_2016_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_NumOfJob_2016_ByIndigenous = df_NumOfJob_2016.loc[
#     (df_NumOfJob_2016['Characteristics'] == 'Indigenous identity employees') |
#     (df_NumOfJob_2016['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_NumOfJob_2016_ByIndigenous.head(20))
# grouped = df_NumOfJob_2016_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_NumOfJob_2016_ByIndigenous.index))

Age group in Alberta
                             sum  size
Characteristics
15 to 24 years         3568591.0   192
25 to 34 years         7218822.0   210
35 to 44 years         7058062.0   210
45 to 54 years         7243040.0   210
55 to 64 years         6305020.0   210
65 years old and over  2240484.0   192
The total number of this one is  1224

Gender group in Alberta
                         sum  size
Characteristics
Female employees  23313522.0   210
Male employees    10322788.0   210
The total number of this one is  420

Education group in Alberta
                                     sum  size
Characteristics
High school diploma and less   7346224.0   210
Trade certificate              2312220.0   198
University degree and higher  15322286.0   198
The total number of this one is  606

Immigrant group in Alberta
                                sum  size
Characteristics
Immigrant employees       8481252.0   198
Non-immigrant employees  25149138.0   198
The total number of this one is  396

In [75]:
# Dataset year in 2019 inside "Number of jobs"

print("\nAge group in Alberta")
df_NumOfJob_2019_ByAge = df_NumOfJob_2019.loc[
    (df_NumOfJob_2019['Characteristics'] == '15 to 24 years') |
    (df_NumOfJob_2019['Characteristics'] == '25 to 34 years') |
    (df_NumOfJob_2019['Characteristics'] == '35 to 44 years') |
    (df_NumOfJob_2019['Characteristics'] == '45 to 54 years') |
    (df_NumOfJob_2019['Characteristics'] == '55 to 64 years') |
    (df_NumOfJob_2019['Characteristics'] == '65 years old and over')]
# print(df_NumOfJob_2019_ByAge.head(20))
grouped = df_NumOfJob_2019_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_NumOfJob_2019_ByAge.index))

print("\nGender group in Alberta")
df_NumOfJob_2019_ByGender = df_NumOfJob_2019.loc[
    (df_NumOfJob_2019['Characteristics'] == 'Female employees') |
    (df_NumOfJob_2019['Characteristics'] == 'Male employees')
]
# print(df_NumOfJob_2019_ByGender.head(20))
grouped = df_NumOfJob_2019_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_NumOfJob_2019_ByGender.index))

print("\nEducation group in Alberta")
df_NumOfJob_2019_ByEducation = df_NumOfJob_2019.loc[
    (df_NumOfJob_2019['Characteristics'] == 'High school diploma and less') |
    (df_NumOfJob_2019['Characteristics'] == 'Trade certificate') |
    (df_NumOfJob_2019['Characteristics'] == 'University degree and higher')
]
# print(df_NumOfJob_2019_ByEducation.head(20))
grouped = df_NumOfJob_2019_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_NumOfJob_2019_ByEducation.index))

print("\nImmigrant group in Alberta")
df_NumOfJob_2019_ByImmigrant = df_NumOfJob_2019.loc[
    (df_NumOfJob_2019['Characteristics'] == 'Immigrant employees') |
    (df_NumOfJob_2019['Characteristics'] == 'Non-immigrant employees')
]
# print(df_NumOfJob_2019_ByImmigrant.head(20))
grouped = df_NumOfJob_2019_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_NumOfJob_2019_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_NumOfJob_2019_ByIndigenous = df_NumOfJob_2019.loc[
#     (df_NumOfJob_2019['Characteristics'] == 'Indigenous identity employees') |
#     (df_NumOfJob_2019['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_NumOfJob_2019_ByIndigenous.head(20))
# grouped = df_NumOfJob_2019_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_NumOfJob_2019_ByIndigenous.index))

Age group in Alberta
                             sum  size
Characteristics
15 to 24 years         3414206.0   192
25 to 34 years         7615612.0   210
35 to 44 years         7559436.0   210
45 to 54 years         7201656.0   210
55 to 64 years         6451160.0   210
65 years old and over  2416851.0   192
The total number of this one is  1224

Gender group in Alberta
                         sum  size
Characteristics
Female employees  24112770.0   210
Male employees    10548592.0   210
The total number of this one is  420

Education group in Alberta
                                     sum  size
Characteristics
High school diploma and less   7204888.0   210
Trade certificate              2245738.0   198
University degree and higher  16513042.0   198
The total number of this one is  606

Immigrant group in Alberta
                                sum  size
Characteristics
Immigrant employees       9133147.0   198
Non-immigrant employees  25522127.0   198
The total number of this one is  396

Filtered for "Wages and Salaries" by following: "Age group", "Gender level", "Education level", and "Immigration status". <br />
"Aboriginal status" has been commented.

In [76]:
# # Dataset year in 2010 inside "Wages and Salaries"

# print("\nAge group in Alberta")
# df_WagesAndSalaries_2010_ByAge = df_WagesAndSalaries_2010.loc[
#     (df_WagesAndSalaries_2010['Characteristics'] == '15 to 24 years') |
#     (df_WagesAndSalaries_2010['Characteristics'] == '25 to 34 years') |
#     (df_WagesAndSalaries_2010['Characteristics'] == '35 to 44 years') |
#     (df_WagesAndSalaries_2010['Characteristics'] == '45 to 54 years') |
#     (df_WagesAndSalaries_2010['Characteristics'] == '55 to 64 years') |
#     (df_WagesAndSalaries_2010['Characteristics'] == '65 years old and over')]
# # print(df_WagesAndSalaries_2010_ByAge.head(20))
# grouped = df_WagesAndSalaries_2010_ByAge.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_WagesAndSalaries_2010_ByAge.index))

# print("\nGender group in Alberta")
# df_WagesAndSalaries_2010_ByGender = df_WagesAndSalaries_2010.loc[
#     (df_WagesAndSalaries_2010['Characteristics'] == 'Female employees') |
#     (df_WagesAndSalaries_2010['Characteristics'] == 'Male employees')
# ]
# # print(df_WagesAndSalaries_2010_ByGender.head(20))
# grouped = df_WagesAndSalaries_2010_ByGender.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_WagesAndSalaries_2010_ByGender.index))

# print("\nEducation group in Alberta")
# df_WagesAndSalaries_2010_ByEducation = df_WagesAndSalaries_2010.loc[
#     (df_WagesAndSalaries_2010['Characteristics'] == 'High school diploma and less') |
#     (df_WagesAndSalaries_2010['Characteristics'] == 'Trade certificate') |
#     (df_WagesAndSalaries_2010['Characteristics'] == 'University degree and higher')
# ]
# # print(df_WagesAndSalaries_2010_ByEducation.head(20))
# grouped = df_WagesAndSalaries_2010_ByEducation.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_WagesAndSalaries_2010_ByEducation.index))

# print("\nImmigrant group in Alberta")
# df_WagesAndSalaries_2010_ByImmigrant = df_WagesAndSalaries_2010.loc[
#     (df_WagesAndSalaries_2010['Characteristics'] == 'Immigrant employees') |
#     (df_WagesAndSalaries_2010['Characteristics'] == 'Non-immigrant employees')
# ]
# # print(df_WagesAndSalaries_2010_ByImmigrant.head(20))
# grouped = df_WagesAndSalaries_2010_ByImmigrant.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_WagesAndSalaries_2010_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_WagesAndSalaries_2010_ByIndigenous = df_WagesAndSalaries_2010.loc[
#     (df_WagesAndSalaries_2010['Characteristics'] == 'Indigenous identity employees') |
#     (df_WagesAndSalaries_2010['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_WagesAndSalaries_2010_ByIndigenous.head(20))
# grouped = df_WagesAndSalaries_2010_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_WagesAndSalaries_2010_ByIndigenous.index))

In [77]:
# Dataset year in 2013 inside "Wages and Salaries"

print("\nAge group in Alberta")
df_WagesAndSalaries_2013_ByAge = df_WagesAndSalaries_2013.loc[
    (df_WagesAndSalaries_2013['Characteristics'] == '15 to 24 years') |
    (df_WagesAndSalaries_2013['Characteristics'] == '25 to 34 years') |
    (df_WagesAndSalaries_2013['Characteristics'] == '35 to 44 years') |
    (df_WagesAndSalaries_2013['Characteristics'] == '45 to 54 years') |
    (df_WagesAndSalaries_2013['Characteristics'] == '55 to 64 years') |
    (df_WagesAndSalaries_2013['Characteristics'] == '65 years old and over')]
# print(df_WagesAndSalaries_2013_ByAge.head(20))
grouped = df_WagesAndSalaries_2013_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_WagesAndSalaries_2013_ByAge.index))

print("\nGender group in Alberta")
df_WagesAndSalaries_2013_ByGender = df_WagesAndSalaries_2013.loc[
    (df_WagesAndSalaries_2013['Characteristics'] == 'Female employees') |
    (df_WagesAndSalaries_2013['Characteristics'] == 'Male employees')
]
# print(df_WagesAndSalaries_2013_ByGender.head(20))
grouped = df_WagesAndSalaries_2013_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_WagesAndSalaries_2013_ByGender.index))

print("\nEducation group in Alberta")
df_WagesAndSalaries_2013_ByEducation = df_WagesAndSalaries_2013.loc[
    (df_WagesAndSalaries_2013['Characteristics'] == 'High school diploma and less') |
    (df_WagesAndSalaries_2013['Characteristics'] == 'Trade certificate') |
    (df_WagesAndSalaries_2013['Characteristics'] == 'University degree and higher')
]
# print(df_WagesAndSalaries_2013_ByEducation.head(20))
grouped = df_WagesAndSalaries_2013_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_WagesAndSalaries_2013_ByEducation.index))

print("\nImmigrant group in Alberta")
df_WagesAndSalaries_2013_ByImmigrant = df_WagesAndSalaries_2013.loc[
    (df_WagesAndSalaries_2013['Characteristics'] == 'Immigrant employees') |
    (df_WagesAndSalaries_2013['Characteristics'] == 'Non-immigrant employees')
]
# print(df_WagesAndSalaries_2013_ByImmigrant.head(20))
grouped = df_WagesAndSalaries_2013_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_WagesAndSalaries_2013_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_WagesAndSalaries_2013_ByIndigenous = df_WagesAndSalaries_2013.loc[
#     (df_WagesAndSalaries_2013['Characteristics'] == 'Indigenous identity employees') |
#     (df_WagesAndSalaries_2013['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_WagesAndSalaries_2013_ByIndigenous.head(20))
# grouped = df_WagesAndSalaries_2013_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_WagesAndSalaries_2013_ByIndigenous.index))

Age group in Alberta
                            sum  size
Characteristics
15 to 24 years          51983.0   192
25 to 34 years         252992.0   210
35 to 44 years         334759.0   210
45 to 54 years         410954.0   210
55 to 64 years         313103.0   210
65 years old and over   62434.0   192
The total number of this one is  1224

Gender group in Alberta
                       sum  size
Characteristics
Female employees  926997.0   210
Male employees    499293.0   210
The total number of this one is  420

Education group in Alberta
                                   sum  size
Characteristics
High school diploma and less  191721.0   210
Trade certificate              86569.0   198
University degree and higher  793734.0   198
The total number of this one is  606

Immigrant group in Alberta
                               sum  size
Characteristics
Immigrant employees       348492.0   198
Non-immigrant employees  1077526.0   198
The total number of this one is  396

In [78]:
# Dataset year in 2016 inside "Wages and Salaries"

print("\nAge group in Alberta")
df_WagesAndSalaries_2016_ByAge = df_WagesAndSalaries_2016.loc[
    (df_WagesAndSalaries_2016['Characteristics'] == '15 to 24 years') |
    (df_WagesAndSalaries_2016['Characteristics'] == '25 to 34 years') |
    (df_WagesAndSalaries_2016['Characteristics'] == '35 to 44 years') |
    (df_WagesAndSalaries_2016['Characteristics'] == '45 to 54 years') |
    (df_WagesAndSalaries_2016['Characteristics'] == '55 to 64 years') |
    (df_WagesAndSalaries_2016['Characteristics'] == '65 years old and over')]
# print(df_WagesAndSalaries_2016_ByAge.head(20))
grouped = df_WagesAndSalaries_2016_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_WagesAndSalaries_2016_ByAge.index))

print("\nGender group in Alberta")
df_WagesAndSalaries_2016_ByGender = df_WagesAndSalaries_2016.loc[
    (df_WagesAndSalaries_2016['Characteristics'] == 'Female employees') |
    (df_WagesAndSalaries_2016['Characteristics'] == 'Male employees')
]
# print(df_WagesAndSalaries_2016_ByGender.head(20))
grouped = df_WagesAndSalaries_2016_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_WagesAndSalaries_2016_ByGender.index))

print("\nEducation group in Alberta")
df_WagesAndSalaries_2016_ByEducation = df_WagesAndSalaries_2016.loc[
    (df_WagesAndSalaries_2016['Characteristics'] == 'High school diploma and less') |
    (df_WagesAndSalaries_2016['Characteristics'] == 'Trade certificate') |
    (df_WagesAndSalaries_2016['Characteristics'] == 'University degree and higher')
]
# print(df_WagesAndSalaries_2016_ByEducation.head(20))
grouped = df_WagesAndSalaries_2016_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_WagesAndSalaries_2016_ByEducation.index))

print("\nImmigrant group in Alberta")
df_WagesAndSalaries_2016_ByImmigrant = df_WagesAndSalaries_2016.loc[
    (df_WagesAndSalaries_2016['Characteristics'] == 'Immigrant employees') |
    (df_WagesAndSalaries_2016['Characteristics'] == 'Non-immigrant employees')
]
# print(df_WagesAndSalaries_2016_ByImmigrant.head(20))
grouped = df_WagesAndSalaries_2016_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_WagesAndSalaries_2016_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_WagesAndSalaries_2016_ByIndigenous = df_WagesAndSalaries_2016.loc[
#     (df_WagesAndSalaries_2016['Characteristics'] == 'Indigenous identity employees') |
#     (df_WagesAndSalaries_2016['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_WagesAndSalaries_2016_ByIndigenous.head(20))
# grouped = df_WagesAndSalaries_2016_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_WagesAndSalaries_2016_ByIndigenous.index))

Age group in Alberta
                            sum  size
Characteristics
15 to 24 years          56990.0   192
25 to 34 years         285555.0   210
35 to 44 years         376045.0   210
45 to 54 years         431853.0   210
55 to 64 years         344362.0   210
65 years old and over   76349.0   192
The total number of this one is  1224

Gender group in Alberta
                        sum  size
Characteristics
Female employees  1026881.0   210
Male employees     544329.0   210
The total number of this one is  420

Education group in Alberta
                                   sum  size
Characteristics
High school diploma and less  207705.0   210
Trade certificate              86692.0   198
University degree and higher  896636.0   198
The total number of this one is  606

Immigrant group in Alberta
                               sum  size
Characteristics
Immigrant employees       400833.0   198
Non-immigrant employees  1170079.0   198
The total number of this one is  396

In [79]:
# Dataset year in 2019 inside "Wages and Salaries"

print("\nAge group in Alberta")
df_WagesAndSalaries_2019_ByAge = df_WagesAndSalaries_2019.loc[
    (df_WagesAndSalaries_2019['Characteristics'] == '15 to 24 years') |
    (df_WagesAndSalaries_2019['Characteristics'] == '25 to 34 years') |
    (df_WagesAndSalaries_2019['Characteristics'] == '35 to 44 years') |
    (df_WagesAndSalaries_2019['Characteristics'] == '45 to 54 years') |
    (df_WagesAndSalaries_2019['Characteristics'] == '55 to 64 years') |
    (df_WagesAndSalaries_2019['Characteristics'] == '65 years old and over')]
# print(df_WagesAndSalaries_2019_ByAge.head(20))
grouped = df_WagesAndSalaries_2019_ByAge.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_WagesAndSalaries_2019_ByAge.index))

print("\nGender group in Alberta")
df_WagesAndSalaries_2019_ByGender = df_WagesAndSalaries_2019.loc[
    (df_WagesAndSalaries_2019['Characteristics'] == 'Female employees') |
    (df_WagesAndSalaries_2019['Characteristics'] == 'Male employees')
]
# print(df_WagesAndSalaries_2019_ByGender.head(20))
grouped = df_WagesAndSalaries_2019_ByGender.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_WagesAndSalaries_2019_ByGender.index))

print("\nEducation group in Alberta")
df_WagesAndSalaries_2019_ByEducation = df_WagesAndSalaries_2019.loc[
    (df_WagesAndSalaries_2019['Characteristics'] == 'High school diploma and less') |
    (df_WagesAndSalaries_2019['Characteristics'] == 'Trade certificate') |
    (df_WagesAndSalaries_2019['Characteristics'] == 'University degree and higher')
]
# print(df_WagesAndSalaries_2019_ByEducation.head(20))
grouped = df_WagesAndSalaries_2019_ByEducation.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_WagesAndSalaries_2019_ByEducation.index))

print("\nImmigrant group in Alberta")
df_WagesAndSalaries_2019_ByImmigrant = df_WagesAndSalaries_2019.loc[
    (df_WagesAndSalaries_2019['Characteristics'] == 'Immigrant employees') |
    (df_WagesAndSalaries_2019['Characteristics'] == 'Non-immigrant employees')
]
# print(df_WagesAndSalaries_2019_ByImmigrant.head(20))
grouped = df_WagesAndSalaries_2019_ByImmigrant.groupby(['Characteristics'])
print(grouped['VALUE'].agg([np.sum, np.size]))
print("The total number of this one is ",len(df_WagesAndSalaries_2019_ByImmigrant.index))

# print("\nIndigenous group in Alberta")
# df_WagesAndSalaries_2019_ByIndigenous = df_WagesAndSalaries_2019.loc[
#     (df_WagesAndSalaries_2019['Characteristics'] == 'Indigenous identity employees') |
#     (df_WagesAndSalaries_2019['Characteristics'] == 'Non-indigenous identity employees')
# ]
# # print(df_WagesAndSalaries_2019_ByIndigenous.head(20))
# grouped = df_WagesAndSalaries_2019_ByIndigenous.groupby(['Characteristics'])
# print(grouped['VALUE'].agg([np.sum, np.size]))
# print("The total number of this one is ",len(df_WagesAndSalaries_2019_ByIndigenous.index))

Age group in Alberta
                            sum  size
Characteristics
15 to 24 years          63069.0   192
25 to 34 years         334200.0   210
35 to 44 years         441049.0   210
45 to 54 years         474202.0   210
55 to 64 years         386319.0   210
65 years old and over   90513.0   192
The total number of this one is  1224

Gender group in Alberta
                        sum  size
Characteristics
Female employees  1179670.0   210
Male employees     609748.0   210
The total number of this one is  420

Education group in Alberta
                                    sum  size
Characteristics
High school diploma and less   226638.0   210
Trade certificate               93374.0   198
University degree and higher  1052815.0   198
The total number of this one is  606

Immigrant group in Alberta
                               sum  size
Characteristics
Immigrant employees       473697.0   198
Non-immigrant employees  1315368.0   198
The total number of this one is  396

Final output for Average annual hours worked

In [80]:
# dfa_Target_To_Analysis = [df_AvgAnnHrsWrk_2010_ByAge, df_AvgAnnHrsWrk_2010_ByEducation, df_AvgAnnHrsWrk_2010_ByEducation, df_AvgAnnHrsWrk_2010_ByImmigrant]
# for df_Target_To_Analysis in dfa_Target_To_Analysis:
#       grouped = df_Target_To_Analysis.groupby(['Characteristics'])
#       print("Year of 2010")
#       print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
#       print("Overall,")
#       print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
#       print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
#       print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
#             np.median(df_Target_To_Analysis['VALUE']),"/",
#             np.max(df_Target_To_Analysis['VALUE']))
#       print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
#       print("Total size : ",len(df_Target_To_Analysis.index))

# print()
dfa_Target_To_Analysis = [df_AvgAnnHrsWrk_2013_ByAge, df_AvgAnnHrsWrk_2013_ByEducation, df_AvgAnnHrsWrk_2013_ByEducation, df_AvgAnnHrsWrk_2013_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2013")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

print()
dfa_Target_To_Analysis = [df_AvgAnnHrsWrk_2016_ByAge, df_AvgAnnHrsWrk_2016_ByEducation, df_AvgAnnHrsWrk_2016_ByEducation, df_AvgAnnHrsWrk_2016_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2016")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

print()
dfa_Target_To_Analysis = [df_AvgAnnHrsWrk_2019_ByAge, df_AvgAnnHrsWrk_2019_ByEducation, df_AvgAnnHrsWrk_2019_ByEducation, df_AvgAnnHrsWrk_2019_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2020")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

Year of 2013
                            sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         172087.0   896.286458   462.0   906.0  1108.0   192
25 to 34 years         340647.0  1622.128571  1236.0  1615.0  1946.0   210
35 to 44 years         377140.0  1795.904762  1477.0  1760.5  2183.0   210
45 to 54 years         387957.0  1847.414286  1523.0  1834.5  2294.0   210
55 to 64 years         352301.0  1677.623810  1390.0  1680.5  2000.0   210
65 years old and over  207070.0  1078.489583   724.0  1078.0  1500.0   192
Overall,
Sum :  1837202.0
Mean :  1500.9820261437908
Min/median/max : 462.0 / 1649.5 / 2294.0
Skewnewss :  -0.5937132979460663
Total size :  1224
Year of 2013
                                   sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  277682.0  1322.295238  1065.0  1323.5  1645.0
Trade certificate             313663.0  1584.156566  1092.0  1581.0  1904.0
University degree and higher  347222.0  1753.646465  1527.0  1735.0  2063.0

                              size
Characteristics
High school diploma and less   210
Trade certificate              198
University degree and higher   198
Overall,
Sum :  938567.0
Mean :  1548.7904290429042
Min/median/max : 1065.0 / 1566.0 / 2063.0
Skewnewss :  -0.08200385461497713
Total size :  606
Year of 2013
                                   sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  277682.0  1322.295238  1065.0  1323.5  1645.0
Trade certificate             313663.0  1584.156566  1092.0  1581.0  1904.0
University degree and higher  347222.0  1753.646465  1527.0  1735.0  2063.0

                              size
Characteristics
High school diploma and less   210
Trade certificate              198
University degree and higher   198
Overall,
Sum :  938567.0
Mean :  1548.7904290429042
Min/median/max : 1065.0 / 1566.0 / 2063.0
Skewnewss :  -0.08200385461497713
Total size :  606
Year of 2013
                              sum         mean    amin  median    amax  size
Characteristics
Immigrant employees      326890.0  1650.959596  1333.0  1614.0  2500.0   198
Non-immigrant employees  312119.0  1576.358586  1275.0  1579.5  1727.0   198
Overall,
Sum :  639009.0
Mean :  1613.659090909091
Min/median/max : 1275.0 / 1589.0 / 2500.0
Skewnewss :  2.4308057363102553
Total size :  396

Year of 2016
                            sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         176153.0   917.463542   691.0   924.5  1185.0   192
25 to 34 years         337302.0  1606.200000  1311.0  1602.5  1967.0   210
35 to 44 years         373702.0  1779.533333  1436.0  1761.0  2156.0   210
45 to 54 years         385915.0  1837.690476  1575.0  1821.5  2312.0   210
55 to 64 years         350828.0  1670.609524  1410.0  1677.0  2000.0   210
65 years old and over  206428.0  1075.145833   701.0  1068.5  1424.0   192
Overall,
Sum :  1830328.0
Mean :  1495.3660130718954
Min/median/max : 691.0 / 1642.5 / 2312.0
Skewnewss :  -0.5756313431709856
Total size :  1224
Year of 2016
                                   sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  276370.0  1316.047619  1066.0  1310.5  1615.0
Trade certificate             307989.0  1555.500000   888.0  1547.0  1833.0
University degree and higher  343664.0  1735.676768  1563.0  1711.5  2095.0

                              size
Characteristics
High school diploma and less   210
Trade certificate              198
University degree and higher   198
Overall,
Sum :  928023.0
Mean :  1531.3910891089108
Min/median/max : 888.0 / 1546.0 / 2095.0
Skewnewss :  -0.12073761892929726
Total size :  606
Year of 2016
                                   sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  276370.0  1316.047619  1066.0  1310.5  1615.0
Trade certificate             307989.0  1555.500000   888.0  1547.0  1833.0
University degree and higher  343664.0  1735.676768  1563.0  1711.5  2095.0

                              size
Characteristics
High school diploma and less   210
Trade certificate              198
University degree and higher   198
Overall,
Sum :  928023.0
Mean :  1531.3910891089108
Min/median/max : 888.0 / 1546.0 / 2095.0
Skewnewss :  -0.12073761892929726
Total size :  606
Year of 2016
                              sum         mean    amin  median    amax  size
Characteristics
Immigrant employees      321592.0  1624.202020  1353.0  1594.5  2458.0   198
Non-immigrant employees  310173.0  1566.530303  1321.0  1563.0  1764.0   198
Overall,
Sum :  631765.0
Mean :  1595.3661616161617
Min/median/max : 1321.0 / 1575.5 / 2458.0
Skewnewss :  2.2802810869717547
Total size :  396

Year of 2020
                            sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         179872.0   936.833333   713.0   927.5  1281.0   192
25 to 34 years         333662.0  1588.866667  1292.0  1576.0  1870.0   210
35 to 44 years         371386.0  1768.504762  1424.0  1757.0  2092.0   210
45 to 54 years         384987.0  1833.271429  1541.0  1826.5  2191.0   210
55 to 64 years         351843.0  1675.442857  1377.0  1675.0  2071.0   210
65 years old and over  206760.0  1076.875000   565.0  1076.5  1415.0   192
Overall,
Sum :  1828510.0
Mean :  1493.8807189542483
Min/median/max : 565.0 / 1633.0 / 2191.0
Skewnewss :  -0.5829393561867995
Total size :  1224
Year of 2020
                                   sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  275636.0  1312.552381  1054.0  1307.5  1667.0
Trade certificate             306174.0  1546.333333   789.0  1547.5  1808.0
University degree and higher  341795.0  1726.237374  1536.0  1706.5  2043.0

                              size
Characteristics
High school diploma and less   210
Trade certificate              198
University degree and higher   198
Overall,
Sum :  923605.0
Mean :  1524.1006600660066
Min/median/max : 789.0 / 1545.0 / 2043.0
Skewnewss :  -0.1568377438071896
Total size :  606
Year of 2020
                                   sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  275636.0  1312.552381  1054.0  1307.5  1667.0
Trade certificate             306174.0  1546.333333   789.0  1547.5  1808.0
University degree and higher  341795.0  1726.237374  1536.0  1706.5  2043.0

                              size
Characteristics
High school diploma and less   210
Trade certificate              198
University degree and higher   198
Overall,
Sum :  923605.0
Mean :  1524.1006600660066
Min/median/max : 789.0 / 1545.0 / 2043.0
Skewnewss :  -0.1568377438071896
Total size :  606
Year of 2020
                              sum         mean    amin  median    amax  size
Characteristics
Immigrant employees      318818.0  1610.191919  1336.0  1589.0  2250.0   198
Non-immigrant employees  310245.0  1566.893939  1315.0  1570.0  1767.0   198
Overall,
Sum :  629063.0
Mean :  1588.5429292929293
Min/median/max : 1315.0 / 1580.0 / 2250.0
Skewnewss :  1.6694520665533967
Total size :  396

Final output for "Average annual wages and salaries"

In [81]:
# dfa_Target_To_Analysis = [df_AvgAnnWages_2010_ByAge, df_AvgAnnWages_2010_ByEducation, df_AvgAnnWages_2010_ByEducation, df_AvgAnnWages_2010_ByImmigrant]
# for df_Target_To_Analysis in dfa_Target_To_Analysis:
#       grouped = df_Target_To_Analysis.groupby(['Characteristics'])
#       print("Year of 2010")
#       print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
#       print("Overall,")
#       print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
#       print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
#       print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
#             np.median(df_Target_To_Analysis['VALUE']),"/",
#             np.max(df_Target_To_Analysis['VALUE']))
#       print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
#       print("Total size : ",len(df_Target_To_Analysis.index))

# print()
dfa_Target_To_Analysis = [df_AvgAnnWages_2013_ByAge, df_AvgAnnWages_2013_ByEducation, df_AvgAnnWages_2013_ByEducation, df_AvgAnnWages_2013_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2013")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

print()
dfa_Target_To_Analysis = [df_AvgAnnWages_2016_ByAge, df_AvgAnnWages_2016_ByEducation, df_AvgAnnWages_2016_ByEducation, df_AvgAnnWages_2016_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2016")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

print()
dfa_Target_To_Analysis = [df_AvgAnnWages_2019_ByAge, df_AvgAnnWages_2019_ByEducation, df_AvgAnnWages_2019_ByEducation, df_AvgAnnWages_2019_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2020")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

Year of 2013
                              sum          mean     amin   median      amax  \
Characteristics
15 to 24 years          2784616.0  14503.208333   8769.0  13954.0   24898.0
25 to 34 years          7953813.0  37875.300000  23433.0  36952.5   69687.0
35 to 44 years         10794086.0  51400.409524  33680.0  50296.0   92783.0
45 to 54 years         11596540.0  55221.619048  30761.0  53607.0   87000.0
55 to 64 years         11087673.0  52798.442857  28716.0  49704.0  105273.0
65 years old and over   5949938.0  30989.260417  14168.0  28631.0   81488.0

                       size
Characteristics
15 to 24 years          192
25 to 34 years          210
35 to 44 years          210
45 to 54 years          210
55 to 64 years          210
65 years old and over   192
Overall,
Sum :  50166666.0
Mean :  40985.83823529412
Min/median/max : 8769.0 / 40621.5 / 105273.0
Skewnewss :  0.4232112184871187
Total size :  1224
Year of 2013
                                     sum          mean     amin   median  \
Characteristics
High school diploma and less   5903675.0  28112.738095  13589.0  26733.0
Trade certificate              7603798.0  38403.020202  19906.0  36236.5
University degree and higher  11213834.0  56635.525253  34291.0  54820.5

                                  amax  size
Characteristics
High school diploma and less   53361.0   210
Trade certificate              81722.0   198
University degree and higher  113502.0   198
Overall,
Sum :  24721307.0
Mean :  40794.23597359736
Min/median/max : 13589.0 / 37830.5 / 113502.0
Skewnewss :  1.455121842324225
Total size :  606
Year of 2013
                                     sum          mean     amin   median  \
Characteristics
High school diploma and less   5903675.0  28112.738095  13589.0  26733.0
Trade certificate              7603798.0  38403.020202  19906.0  36236.5
University degree and higher  11213834.0  56635.525253  34291.0  54820.5

                                  amax  size
Characteristics
High school diploma and less   53361.0   210
Trade certificate              81722.0   198
University degree and higher  113502.0   198
Overall,
Sum :  24721307.0
Mean :  40794.23597359736
Min/median/max : 13589.0 / 37830.5 / 113502.0
Skewnewss :  1.455121842324225
Total size :  606
Year of 2013
                               sum          mean     amin   median      amax  \
Characteristics
Immigrant employees      8818758.0  44539.181818  19120.0  41988.0  105045.0
Non-immigrant employees  8495409.0  42906.106061  25240.0  42114.0   77319.0

                         size
Characteristics
Immigrant employees       198
Non-immigrant employees   198
Overall,
Sum :  17314167.0
Mean :  43722.643939393936
Min/median/max : 19120.0 / 42075.5 / 105045.0
Skewnewss :  1.2953139714251634
Total size :  396

Year of 2016
                              sum          mean     amin   median      amax  \
Characteristics
15 to 24 years          3060129.0  15938.171875   9794.0  14568.5   39963.0
25 to 34 years          8325679.0  39646.090476  24832.0  38644.5   68600.0
35 to 44 years         11269609.0  53664.804762  36704.0  52497.5   89097.0
45 to 54 years         12276948.0  58461.657143  36047.0  57665.0   94580.0
55 to 64 years         11610535.0  55288.261905  30816.0  52292.0  113680.0
65 years old and over   6249361.0  32548.755208  17359.0  30546.5   73364.0

                       size
Characteristics
15 to 24 years          192
25 to 34 years          210
35 to 44 years          210
45 to 54 years          210
55 to 64 years          210
65 years old and over   192
Overall,
Sum :  52792261.0
Mean :  43130.93218954248
Min/median/max : 9794.0 / 42923.0 / 113680.0
Skewnewss :  0.4135401347803788
Total size :  1224
Year of 2016
                                     sum          mean     amin   median  \
Characteristics
High school diploma and less   6237814.0  29703.876190  15835.0  28089.0
Trade certificate              7881695.0  39806.540404  22892.0  38112.5
University degree and higher  11672583.0  58952.439394  37846.0  57291.0

                                  amax  size
Characteristics
High school diploma and less   55242.0   210
Trade certificate              79053.0   198
University degree and higher  112032.0   198
Overall,
Sum :  25792092.0
Mean :  42561.207920792076
Min/median/max : 15835.0 / 39694.5 / 112032.0
Skewnewss :  1.365731094541449
Total size :  606
Year of 2016
                                     sum          mean     amin   median  \
Characteristics
High school diploma and less   6237814.0  29703.876190  15835.0  28089.0
Trade certificate              7881695.0  39806.540404  22892.0  38112.5
University degree and higher  11672583.0  58952.439394  37846.0  57291.0

                                  amax  size
Characteristics
High school diploma and less   55242.0   210
Trade certificate              79053.0   198
University degree and higher  112032.0   198
Overall,
Sum :  25792092.0
Mean :  42561.207920792076
Min/median/max : 15835.0 / 39694.5 / 112032.0
Skewnewss :  1.365731094541449
Total size :  606
Year of 2016
                               sum          mean     amin   median      amax  \
Characteristics
Immigrant employees      9093448.0  45926.505051  20646.0  44409.5  104174.0
Non-immigrant employees  8954165.0  45223.055556  28408.0  44274.5   79641.0

                         size
Characteristics
Immigrant employees       198
Non-immigrant employees   198
Overall,
Sum :  18047613.0
Mean :  45574.780303030304
Min/median/max : 20646.0 / 44352.5 / 104174.0
Skewnewss :  1.1947096122148104
Total size :  396

Year of 2020
                              sum          mean     amin   median      amax  \
Characteristics
15 to 24 years          3482308.0  18137.020833  11093.0  16653.5   45844.0
25 to 34 years          9108041.0  43371.623810  26534.0  42901.0   75429.0
35 to 44 years         12296655.0  58555.500000  37336.0  56960.5   95714.0
45 to 54 years         13595377.0  64739.890476  39455.0  64274.5  103580.0
55 to 64 years         12592232.0  59963.009524  33296.0  56266.0  133071.0
65 years old and over   6840988.0  35630.145833  18187.0  34170.0   76577.0

                       size
Characteristics
15 to 24 years          192
25 to 34 years          210
35 to 44 years          210
45 to 54 years          210
55 to 64 years          210
65 years old and over   192
Overall,
Sum :  57915601.0
Mean :  47316.66748366013
Min/median/max : 11093.0 / 47033.5 / 133071.0
Skewnewss :  0.4846905588925664
Total size :  1224
Year of 2020
                                     sum          mean     amin   median  \
Characteristics
High school diploma and less   6915927.0  32932.985714  17828.0  31071.0
Trade certificate              8609637.0  43483.015152  25221.0  42431.0
University degree and higher  12581443.0  63542.641414  38860.0  62574.0

                                  amax  size
Characteristics
High school diploma and less   73020.0   210
Trade certificate              72854.0   198
University degree and higher  121264.0   198
Overall,
Sum :  28107007.0
Mean :  46381.199669967
Min/median/max : 17828.0 / 43075.0 / 121264.0
Skewnewss :  1.273924834730388
Total size :  606
Year of 2020
                                     sum          mean     amin   median  \
Characteristics
High school diploma and less   6915927.0  32932.985714  17828.0  31071.0
Trade certificate              8609637.0  43483.015152  25221.0  42431.0
University degree and higher  12581443.0  63542.641414  38860.0  62574.0

                                  amax  size
Characteristics
High school diploma and less   73020.0   210
Trade certificate              72854.0   198
University degree and higher  121264.0   198
Overall,
Sum :  28107007.0
Mean :  46381.199669967
Min/median/max : 17828.0 / 43075.0 / 121264.0
Skewnewss :  1.273924834730388
Total size :  606
Year of 2020
                               sum          mean     amin   median     amax  \
Characteristics
Immigrant employees      9838690.0  49690.353535  23144.0  48933.5  98074.0
Non-immigrant employees  9799014.0  49489.969697  29956.0  49313.5  85472.0

                         size
Characteristics
Immigrant employees       198
Non-immigrant employees   198
Overall,
Sum :  19637704.0
Mean :  49590.16161616162
Min/median/max : 23144.0 / 49016.0 / 98074.0
Skewnewss :  0.9303937237175556
Total size :  396

Final output for "Average hourly wage"

In [82]:
# dfa_Target_To_Analysis = [df_AvgHrsWages_2010_ByAge, df_AvgHrsWages_2010_ByEducation, df_AvgHrsWages_2010_ByEducation, df_AvgHrsWages_2010_ByImmigrant]
# for df_Target_To_Analysis in dfa_Target_To_Analysis:
#       grouped = df_Target_To_Analysis.groupby(['Characteristics'])
#       print("Year of 2010")
#       print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
#       print("Overall,")
#       print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
#       print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
#       print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
#             np.median(df_Target_To_Analysis['VALUE']),"/",
#             np.max(df_Target_To_Analysis['VALUE']))
#       print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
#       print("Total size : ",len(df_Target_To_Analysis.index))

# print()
dfa_Target_To_Analysis = [df_AvgHrsWages_2013_ByAge, df_AvgHrsWages_2013_ByEducation, df_AvgHrsWages_2013_ByEducation, df_AvgHrsWages_2013_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2013")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

print()
dfa_Target_To_Analysis = [df_AvgHrsWages_2016_ByAge, df_AvgHrsWages_2016_ByEducation, df_AvgHrsWages_2016_ByEducation, df_AvgHrsWages_2016_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2016")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

print()
dfa_Target_To_Analysis = [df_AvgHrsWages_2019_ByAge, df_AvgHrsWages_2019_ByEducation, df_AvgHrsWages_2019_ByEducation, df_AvgHrsWages_2019_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2019")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

Year of 2013
                           sum       mean   amin  median   amax  size
Characteristics
15 to 24 years         3089.01  16.088594  11.70  15.375  26.00   192
25 to 34 years         4937.02  23.509619  15.07  22.835  47.75   210
35 to 44 years         6053.85  28.827857  17.22  28.400  54.92   210
45 to 54 years         6297.06  29.986000  16.89  29.935  50.43   210
55 to 64 years         6605.48  31.454667  16.73  29.800  63.50   210
65 years old and over  5475.51  28.518281  15.90  27.170  69.41   192
Overall,
Sum :  32457.93
Mean :  26.517916666666668
Min/median/max : 11.7 / 25.675 / 69.41
Skewnewss :  1.0223945014335014
Total size :  1224
Year of 2013
                                  sum       mean   amin  median   amax  size
Characteristics
High school diploma and less  4434.80  21.118095  12.76  20.295  35.57   210
Trade certificate             4774.81  24.115202  14.10  23.015  43.26   198
University degree and higher  6415.25  32.400253  18.40  31.705  68.02   198
Overall,
Sum :  15624.86
Mean :  25.783597359735975
Min/median/max : 12.76 / 23.46 / 68.02
Skewnewss :  1.619049492933764
Total size :  606
Year of 2013
                                  sum       mean   amin  median   amax  size
Characteristics
High school diploma and less  4434.80  21.118095  12.76  20.295  35.57   210
Trade certificate             4774.81  24.115202  14.10  23.015  43.26   198
University degree and higher  6415.25  32.400253  18.40  31.705  68.02   198
Overall,
Sum :  15624.86
Mean :  25.783597359735975
Min/median/max : 12.76 / 23.46 / 68.02
Skewnewss :  1.619049492933764
Total size :  606
Year of 2013
                             sum       mean   amin  median   amax  size
Characteristics
Immigrant employees      5306.29  26.799444  13.35  25.330  56.37   198
Non-immigrant employees  5402.47  27.285202  16.38  26.565  52.22   198
Overall,
Sum :  10708.76
Mean :  27.042323232323234
Min/median/max : 13.35 / 26.134999999999998 / 56.37
Skewnewss :  0.9100751567756702
Total size :  396

Year of 2016
                           sum       mean   amin  median   amax  size
Characteristics
15 to 24 years         3305.36  17.215417  12.66  16.300  33.72   192
25 to 34 years         5214.72  24.832000  16.17  24.090  46.15   210
35 to 44 years         6375.48  30.359429  18.07  29.740  53.12   210
45 to 54 years         6704.45  31.925952  19.16  31.625  56.39   210
55 to 64 years         6934.64  33.022095  17.98  31.125  63.53   210
65 years old and over  5778.32  30.095417  17.79  28.675  63.78   192
Overall,
Sum :  34312.97
Mean :  28.033472222222223
Min/median/max : 12.66 / 27.494999999999997 / 63.78
Skewnewss :  0.9400525873183367
Total size :  1224
Year of 2016
                                  sum       mean   amin  median   amax  size
Characteristics
High school diploma and less  4707.09  22.414714  14.10   21.38  38.43   210
Trade certificate             5053.86  25.524545  16.93   24.69  44.18   198
University degree and higher  6739.74  34.039091  20.12   32.94  66.29   198
Overall,
Sum :  16500.69
Mean :  27.22886138613861
Min/median/max : 14.1 / 25.125 / 66.29
Skewnewss :  1.5725239182893158
Total size :  606
Year of 2016
                                  sum       mean   amin  median   amax  size
Characteristics
High school diploma and less  4707.09  22.414714  14.10   21.38  38.43   210
Trade certificate             5053.86  25.524545  16.93   24.69  44.18   198
University degree and higher  6739.74  34.039091  20.12   32.94  66.29   198
Overall,
Sum :  16500.69
Mean :  27.22886138613861
Min/median/max : 14.1 / 25.125 / 66.29
Skewnewss :  1.5725239182893158
Total size :  606
Year of 2016
                             sum       mean   amin  median   amax  size
Characteristics
Immigrant employees      5560.78  28.084747  14.23   26.82  57.56   198
Non-immigrant employees  5726.37  28.921061  17.85   28.02  52.15   198
Overall,
Sum :  11287.150000000001
Mean :  28.502904040404044
Min/median/max : 14.23 / 27.575 / 57.56
Skewnewss :  1.0078903310307468
Total size :  396

Year of 2019
                           sum       mean   amin  median   amax  size
Characteristics
15 to 24 years         3689.12  19.214167  12.95  18.775  36.37   192
25 to 34 years         5759.41  27.425762  17.01  27.010  45.91   210
35 to 44 years         6991.24  33.291619  19.42  32.680  58.12   210
45 to 54 years         7451.95  35.485476  21.54  34.965  64.54   210
55 to 64 years         7475.92  35.599619  19.42  33.800  64.92   210
65 years old and over  6329.58  32.966563  18.32  32.140  66.63   192
Overall,
Sum :  37697.22
Mean :  30.79838235294118
Min/median/max : 12.95 / 30.425 / 66.63
Skewnewss :  0.8175005207452904
Total size :  1224
Year of 2019
                                  sum       mean   amin  median   amax  size
Characteristics
High school diploma and less  5242.44  24.964000  15.69  23.600  44.52   210
Trade certificate             5569.30  28.127778  17.63  27.370  44.58   198
University degree and higher  7296.08  36.848889  21.80  36.385  69.52   198
Overall,
Sum :  18107.82
Mean :  29.88089108910891
Min/median/max : 15.69 / 27.8 / 69.52
Skewnewss :  1.32266748675931
Total size :  606
Year of 2019
                                  sum       mean   amin  median   amax  size
Characteristics
High school diploma and less  5242.44  24.964000  15.69  23.600  44.52   210
Trade certificate             5569.30  28.127778  17.63  27.370  44.58   198
University degree and higher  7296.08  36.848889  21.80  36.385  69.52   198
Overall,
Sum :  18107.82
Mean :  29.88089108910891
Min/median/max : 15.69 / 27.8 / 69.52
Skewnewss :  1.32266748675931
Total size :  606
Year of 2019
                             sum       mean   amin  median   amax  size
Characteristics
Immigrant employees      6065.65  30.634596  16.93  29.925  60.18   198
Non-immigrant employees  6267.15  31.652273  19.24  31.000  55.32   198
Overall,
Sum :  12332.8
Mean :  31.143434343434343
Min/median/max : 16.93 / 30.795 / 60.18
Skewnewss :  0.8277016858447296
Total size :  396

Final output for "Average weekly hours worked"

In [83]:
# dfa_Target_To_Analysis = [df_AvgWeekHrsWrked_2010_ByAge, df_AvgWeekHrsWrked_2010_ByEducation, df_AvgWeekHrsWrked_2010_ByEducation, df_AvgWeekHrsWrked_2010_ByImmigrant]
# for df_Target_To_Analysis in dfa_Target_To_Analysis:
#       grouped = df_Target_To_Analysis.groupby(['Characteristics'])
#       print("Year of 2010")
#       print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
#       print("Overall,")
#       print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
#       print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
#       print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
#             np.median(df_Target_To_Analysis['VALUE']),"/",
#             np.max(df_Target_To_Analysis['VALUE']))
#       print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
#       print("Total size : ",len(df_Target_To_Analysis.index))

# print()
dfa_Target_To_Analysis = [df_AvgWeekHrsWrked_2013_ByAge, df_AvgWeekHrsWrked_2013_ByEducation, df_AvgWeekHrsWrked_2013_ByEducation, df_AvgWeekHrsWrked_2013_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2013")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

print()
dfa_Target_To_Analysis = [df_AvgWeekHrsWrked_2016_ByAge, df_AvgWeekHrsWrked_2016_ByEducation, df_AvgWeekHrsWrked_2016_ByEducation, df_AvgWeekHrsWrked_2016_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2016")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

print()
dfa_Target_To_Analysis = [df_AvgWeekHrsWrked_2019_ByAge, df_AvgWeekHrsWrked_2019_ByEducation, df_AvgWeekHrsWrked_2019_ByEducation, df_AvgWeekHrsWrked_2019_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2019")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

Year of 2013
                          sum       mean  amin  median  amax  size
Characteristics
15 to 24 years         3314.0  17.260417   9.0    17.0  21.0   192
25 to 34 years         6556.0  31.219048  24.0    31.0  37.0   210
35 to 44 years         7256.0  34.552381  28.0    34.0  42.0   210
45 to 54 years         7454.0  35.495238  29.0    35.0  44.0   210
55 to 64 years         6780.0  32.285714  27.0    32.0  38.0   210
65 years old and over  3983.0  20.744792  14.0    21.0  29.0   192
Overall,
Sum :  35343.0
Mean :  28.875
Min/median/max : 9.0 / 32.0 / 44.0
Skewnewss :  -0.5948697613902876
Total size :  1224
Year of 2013
                                 sum       mean  amin  median  amax  size
Characteristics
High school diploma and less  5334.0  25.400000  20.0    25.0  32.0   210
Trade certificate             6034.0  30.474747  21.0    30.0  37.0   198
University degree and higher  6681.0  33.742424  29.0    33.0  40.0   198
Overall,
Sum :  18049.0
Mean :  29.783828382838283
Min/median/max : 20.0 / 30.0 / 40.0
Skewnewss :  -0.07010943032755414
Total size :  606
Year of 2013
                                 sum       mean  amin  median  amax  size
Characteristics
High school diploma and less  5334.0  25.400000  20.0    25.0  32.0   210
Trade certificate             6034.0  30.474747  21.0    30.0  37.0   198
University degree and higher  6681.0  33.742424  29.0    33.0  40.0   198
Overall,
Sum :  18049.0
Mean :  29.783828382838283
Min/median/max : 20.0 / 30.0 / 40.0
Skewnewss :  -0.07010943032755414
Total size :  606
Year of 2013
                            sum       mean  amin  median  amax  size
Characteristics
Immigrant employees      6278.0  31.707071  26.0    31.0  48.0   198
Non-immigrant employees  6001.0  30.308081  25.0    30.0  33.0   198
Overall,
Sum :  12279.0
Mean :  31.007575757575758
Min/median/max : 25.0 / 31.0 / 48.0
Skewnewss :  2.4359038835445643
Total size :  396

Year of 2016
                          sum       mean  amin  median  amax  size
Characteristics
15 to 24 years         3387.0  17.640625  13.0    18.0  23.0   192
25 to 34 years         6489.0  30.900000  25.0    31.0  38.0   210
35 to 44 years         7185.0  34.214286  28.0    34.0  41.0   210
45 to 54 years         7415.0  35.309524  30.0    35.0  44.0   210
55 to 64 years         6748.0  32.133333  27.0    32.0  38.0   210
65 years old and over  3965.0  20.651042  13.0    21.0  27.0   192
Overall,
Sum :  35189.0
Mean :  28.749183006535947
Min/median/max : 13.0 / 32.0 / 44.0
Skewnewss :  -0.5799811137221278
Total size :  1224
Year of 2016
                                 sum       mean  amin  median  amax  size
Characteristics
High school diploma and less  5315.0  25.309524  20.0    25.0  31.0   210
Trade certificate             5922.0  29.909091  17.0    30.0  35.0   198
University degree and higher  6604.0  33.353535  30.0    33.0  40.0   198
Overall,
Sum :  17841.0
Mean :  29.440594059405942
Min/median/max : 17.0 / 30.0 / 40.0
Skewnewss :  -0.12138085477404481
Total size :  606
Year of 2016
                                 sum       mean  amin  median  amax  size
Characteristics
High school diploma and less  5315.0  25.309524  20.0    25.0  31.0   210
Trade certificate             5922.0  29.909091  17.0    30.0  35.0   198
University degree and higher  6604.0  33.353535  30.0    33.0  40.0   198
Overall,
Sum :  17841.0
Mean :  29.440594059405942
Min/median/max : 17.0 / 30.0 / 40.0
Skewnewss :  -0.12138085477404481
Total size :  606
Year of 2016
                            sum       mean  amin  median  amax  size
Characteristics
Immigrant employees      6185.0  31.237374  26.0    31.0  47.0   198
Non-immigrant employees  5968.0  30.141414  25.0    30.0  34.0   198
Overall,
Sum :  12153.0
Mean :  30.689393939393938
Min/median/max : 25.0 / 30.0 / 47.0
Skewnewss :  2.188536649520565
Total size :  396

Year of 2019
                          sum       mean  amin  median  amax  size
Characteristics
15 to 24 years         3465.0  18.046875  14.0    18.0  25.0   192
25 to 34 years         6413.0  30.538095  25.0    30.0  36.0   210
35 to 44 years         7139.0  33.995238  27.0    34.0  40.0   210
45 to 54 years         7406.0  35.266667  30.0    35.0  42.0   210
55 to 64 years         6765.0  32.214286  26.0    32.0  40.0   210
65 years old and over  3969.0  20.671875  11.0    21.0  27.0   192
Overall,
Sum :  35157.0
Mean :  28.723039215686274
Min/median/max : 11.0 / 31.0 / 42.0
Skewnewss :  -0.578814861266804
Total size :  1224
Year of 2019
                                 sum       mean  amin  median  amax  size
Characteristics
High school diploma and less  5303.0  25.252381  20.0    25.0  32.0   210
Trade certificate             5889.0  29.742424  15.0    30.0  35.0   198
University degree and higher  6568.0  33.171717  30.0    33.0  39.0   198
Overall,
Sum :  17760.0
Mean :  29.306930693069308
Min/median/max : 15.0 / 30.0 / 39.0
Skewnewss :  -0.18790375522922004
Total size :  606
Year of 2019
                                 sum       mean  amin  median  amax  size
Characteristics
High school diploma and less  5303.0  25.252381  20.0    25.0  32.0   210
Trade certificate             5889.0  29.742424  15.0    30.0  35.0   198
University degree and higher  6568.0  33.171717  30.0    33.0  39.0   198
Overall,
Sum :  17760.0
Mean :  29.306930693069308
Min/median/max : 15.0 / 30.0 / 39.0
Skewnewss :  -0.18790375522922004
Total size :  606
Year of 2019
                            sum       mean  amin  median  amax  size
Characteristics
Immigrant employees      6133.0  30.974747  26.0    31.0  43.0   198
Non-immigrant employees  5961.0  30.106061  25.0    30.0  34.0   198
Overall,
Sum :  12094.0
Mean :  30.54040404040404
Min/median/max : 25.0 / 30.0 / 43.0
Skewnewss :  1.6446273199481087
Total size :  396

Final output for "Hours Worked"

In [84]:
# dfa_Target_To_Analysis = [df_Hrs_Wrked_2010_ByAge, df_Hrs_Wrked_2010_ByEducation, df_Hrs_Wrked_2010_ByEducation, df_Hrs_Wrked_2010_ByImmigrant]
# for df_Target_To_Analysis in dfa_Target_To_Analysis:
#       grouped = df_Target_To_Analysis.groupby(['Characteristics'])
#       print("Year of 2010")
#       print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
#       print("Overall,")
#       print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
#       print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
#       print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
#             np.median(df_Target_To_Analysis['VALUE']),"/",
#             np.max(df_Target_To_Analysis['VALUE']))
#       print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
#       print("Total size : ",len(df_Target_To_Analysis.index))

# print()
dfa_Target_To_Analysis = [df_Hrs_Wrked_2013_ByAge, df_Hrs_Wrked_2013_ByEducation, df_Hrs_Wrked_2013_ByEducation, df_Hrs_Wrked_2013_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2013")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

print()
dfa_Target_To_Analysis = [df_Hrs_Wrked_2016_ByAge, df_Hrs_Wrked_2016_ByEducation, df_Hrs_Wrked_2016_ByEducation, df_Hrs_Wrked_2016_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2016")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

print()
dfa_Target_To_Analysis = [df_Hrs_Wrked_2019_ByAge, df_Hrs_Wrked_2019_ByEducation, df_Hrs_Wrked_2019_ByEducation, df_Hrs_Wrked_2019_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2019")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

Year of 2013
                              sum          mean  amin   median      amax  size
Characteristics
15 to 24 years          3107754.0  16186.218750   6.0   3910.0  216618.0   192
25 to 34 years         10595996.0  50457.123810  32.0   9133.5  770449.0   210
35 to 44 years         11379938.0  54190.180952  32.0   9535.5  826253.0   210
45 to 54 years         13158896.0  62661.409524  29.0  10672.5  955066.0   210
55 to 64 years          9899434.0  47140.161905  20.0   8386.5  728243.0   210
65 years old and over   1974184.0  10282.208333  26.0   2329.0  146525.0   192
Overall,
Sum :  50116202.0
Mean :  40944.609477124184
Min/median/max : 6.0 / 6028.0 / 955066.0
Skewnewss :  5.157256992066241
Total size :  1224
Year of 2013
                                     sum           mean  amin   median  \
Characteristics
High school diploma and less   9259138.0   44091.133333  54.0  11595.5
Trade certificate              3736455.0   18870.984848  26.0   3668.5
University degree and higher  23601210.0  119198.030303  99.0  21519.0

                                   amax  size
Characteristics
High school diploma and less   642541.0   210
Trade certificate              276386.0   198
University degree and higher  1729001.0   198
Overall,
Sum :  36596803.0
Mean :  60390.76402640264
Min/median/max : 26.0 / 8103.0 / 1729001.0
Skewnewss :  6.272807085792226
Total size :  606
Year of 2013
                                     sum           mean  amin   median  \
Characteristics
High school diploma and less   9259138.0   44091.133333  54.0  11595.5
Trade certificate              3736455.0   18870.984848  26.0   3668.5
University degree and higher  23601210.0  119198.030303  99.0  21519.0

                                   amax  size
Characteristics
High school diploma and less   642541.0   210
Trade certificate              276386.0   198
University degree and higher  1729001.0   198
Overall,
Sum :  36596803.0
Mean :  60390.76402640264
Min/median/max : 26.0 / 8103.0 / 1729001.0
Skewnewss :  6.272807085792226
Total size :  606
Year of 2013
                                sum           mean   amin   median       amax  \
Characteristics
Immigrant employees      12147236.0   61349.676768   41.0   6201.0   899418.0
Non-immigrant employees  37962608.0  191730.343434  305.0  48064.5  2732791.0

                         size
Characteristics
Immigrant employees       198
Non-immigrant employees   198
Overall,
Sum :  50109844.0
Mean :  126540.0101010101
Min/median/max : 41.0 / 20475.5 / 2732791.0
Skewnewss :  5.319178387971915
Total size :  396

Year of 2016
                              sum          mean  amin   median      amax  size
Characteristics
15 to 24 years          3211600.0  16727.083333  15.0   4100.0  225988.0   192
25 to 34 years         11296322.0  53792.009524  40.0   9922.5  824205.0   210
35 to 44 years         12146992.0  57842.819048  39.0  10902.5  892149.0   210
45 to 54 years         13070232.0  62239.200000  33.0  11328.5  946775.0   210
55 to 64 years         10422244.0  49629.733333  24.0   9417.5  754767.0   210
65 years old and over   2324345.0  12105.963542  27.0   2658.5  168451.0   192
Overall,
Sum :  52471735.0
Mean :  42869.06454248366
Min/median/max : 15.0 / 6214.5 / 946775.0
Skewnewss :  5.082886547778594
Total size :  1224
Year of 2016
                                     sum           mean  amin   median  \
Characteristics
High school diploma and less   9485452.0   45168.819048  68.0  11567.5
Trade certificate              3558304.0   17971.232323  20.0   3397.0
University degree and higher  25474813.0  128660.671717  88.0  22610.0

                                   amax  size
Characteristics
High school diploma and less   650689.0   210
Trade certificate              263036.0   198
University degree and higher  1887922.0   198
Overall,
Sum :  38518569.0
Mean :  63561.99504950495
Min/median/max : 20.0 / 8101.0 / 1887922.0
Skewnewss :  6.358954163111494
Total size :  606
Year of 2016
                                     sum           mean  amin   median  \
Characteristics
High school diploma and less   9485452.0   45168.819048  68.0  11567.5
Trade certificate              3558304.0   17971.232323  20.0   3397.0
University degree and higher  25474813.0  128660.671717  88.0  22610.0

                                   amax  size
Characteristics
High school diploma and less   650689.0   210
Trade certificate              263036.0   198
University degree and higher  1887922.0   198
Overall,
Sum :  38518569.0
Mean :  63561.99504950495
Min/median/max : 20.0 / 8101.0 / 1887922.0
Skewnewss :  6.358954163111494
Total size :  606
Year of 2016
                                sum           mean   amin   median       amax  \
Characteristics
Immigrant employees      13361296.0   67481.292929   42.0   6713.0   992945.0
Non-immigrant employees  39103961.0  197494.752525  258.0  48202.5  2811247.0

                         size
Characteristics
Immigrant employees       198
Non-immigrant employees   198
Overall,
Sum :  52465257.0
Mean :  132488.02272727274
Min/median/max : 42.0 / 21940.5 / 2811247.0
Skewnewss :  5.234421190105478
Total size :  396

Year of 2019
                              sum          mean  amin   median      amax  size
Characteristics
15 to 24 years          3132171.0  16313.390625  29.0   3859.5  228566.0   192
25 to 34 years         11857576.0  56464.647619  32.0  10166.5  888764.0   210
35 to 44 years         12919606.0  61521.933333  33.0  10825.0  971688.0   210
45 to 54 years         12974580.0  61783.714286  31.0  10600.5  966480.0   210
55 to 64 years         10690620.0  50907.714286  25.0   8934.0  794712.0   210
65 years old and over   2528517.0  13169.359375  30.0   2913.5  183461.0   192
Overall,
Sum :  54103070.0
Mean :  44201.8545751634
Min/median/max : 25.0 / 6420.5 / 971688.0
Skewnewss :  5.111311073923015
Total size :  1224
Year of 2019
                                     sum           mean  amin   median  \
Characteristics
High school diploma and less   9285900.0   44218.571429  61.0  11984.5
Trade certificate              3449203.0   17420.217172  20.0   3080.0
University degree and higher  27393105.0  138349.015152  96.0  23963.5

                                   amax  size
Characteristics
High school diploma and less   658441.0   210
Trade certificate              260168.0   198
University degree and higher  2065714.0   198
Overall,
Sum :  40128208.0
Mean :  66218.16501650165
Min/median/max : 20.0 / 7837.0 / 2065714.0
Skewnewss :  6.531158889782265
Total size :  606
Year of 2019
                                     sum           mean  amin   median  \
Characteristics
High school diploma and less   9285900.0   44218.571429  61.0  11984.5
Trade certificate              3449203.0   17420.217172  20.0   3080.0
University degree and higher  27393105.0  138349.015152  96.0  23963.5

                                   amax  size
Characteristics
High school diploma and less   658441.0   210
Trade certificate              260168.0   198
University degree and higher  2065714.0   198
Overall,
Sum :  40128208.0
Mean :  66218.16501650165
Min/median/max : 20.0 / 7837.0 / 2065714.0
Skewnewss :  6.531158889782265
Total size :  606
Year of 2019
                                sum           mean   amin   median       amax  \
Characteristics
Immigrant employees      14355944.0   72504.767677   44.0   7122.0  1084033.0
Non-immigrant employees  39740524.0  200709.717172  264.0  48444.5  2949643.0

                         size
Characteristics
Immigrant employees       198
Non-immigrant employees   198
Overall,
Sum :  54096468.0
Mean :  136607.24242424243
Min/median/max : 44.0 / 22542.5 / 2949643.0
Skewnewss :  5.210924241138901
Total size :  396

Final output for "Number of jobs"

In [85]:
# dfa_Target_To_Analysis = [df_NumOfJob_2010_ByAge, df_NumOfJob_2010_ByEducation, df_NumOfJob_2010_ByEducation, df_NumOfJob_2010_ByImmigrant]
# for df_Target_To_Analysis in dfa_Target_To_Analysis:
#       grouped = df_Target_To_Analysis.groupby(['Characteristics'])
#       print("Year of 2010")
#       print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
#       print("Overall,")
#       print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
#       print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
#       print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
#             np.median(df_Target_To_Analysis['VALUE']),"/",
#             np.max(df_Target_To_Analysis['VALUE']))
#       print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
#       print("Total size : ",len(df_Target_To_Analysis.index))

# print()
dfa_Target_To_Analysis = [df_NumOfJob_2013_ByAge, df_NumOfJob_2013_ByEducation, df_NumOfJob_2013_ByEducation, df_NumOfJob_2013_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2013")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

print()
dfa_Target_To_Analysis = [df_NumOfJob_2016_ByAge, df_NumOfJob_2016_ByEducation, df_NumOfJob_2016_ByEducation, df_NumOfJob_2016_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2016")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

print()
dfa_Target_To_Analysis = [df_NumOfJob_2019_ByAge, df_NumOfJob_2019_ByEducation, df_NumOfJob_2019_ByEducation, df_NumOfJob_2019_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2019")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

Year of 2013
                             sum          mean  amin  median      amax  size
Characteristics
15 to 24 years         3475038.0  18099.156250  13.0  4155.0  241122.0   192
25 to 34 years         6767092.0  32224.247619  17.0  5538.0  495502.0   210
35 to 44 years         6596518.0  31411.990476  18.0  5526.0  481136.0   210
45 to 54 years         7311054.0  34814.542857  14.0  5827.0  530812.0   210
55 to 64 years         6008488.0  28611.847619  11.0  4965.5  441682.0   210
65 years old and over  1910168.0   9948.791667  18.0  2144.5  138944.0   192
Overall,
Sum :  32068358.0
Mean :  26199.63888888889
Min/median/max : 11.0 / 4155.0 / 530812.0
Skewnewss :  4.8267095355895036
Total size :  1224
Year of 2013
                                     sum          mean  amin   median  \
Characteristics
High school diploma and less   7081390.0  33720.904762  36.0   7954.5
Trade certificate              2417879.0  12211.510101  16.0   2158.0
University degree and higher  14192344.0  71678.505051  50.0  12500.5

                                   amax  size
Characteristics
High school diploma and less   490482.0   210
Trade certificate              178883.0   198
University degree and higher  1044725.0   198
Overall,
Sum :  23691613.0
Mean :  39095.07095709571
Min/median/max : 16.0 / 5470.0 / 1044725.0
Skewnewss :  5.897742004006696
Total size :  606
Year of 2013
                                     sum          mean  amin   median  \
Characteristics
High school diploma and less   7081390.0  33720.904762  36.0   7954.5
Trade certificate              2417879.0  12211.510101  16.0   2158.0
University degree and higher  14192344.0  71678.505051  50.0  12500.5

                                   amax  size
Characteristics
High school diploma and less   490482.0   210
Trade certificate              178883.0   198
University degree and higher  1044725.0   198
Overall,
Sum :  23691613.0
Mean :  39095.07095709571
Min/median/max : 16.0 / 5470.0 / 1044725.0
Skewnewss :  5.897742004006696
Total size :  606
Year of 2013
                                sum           mean   amin   median       amax  \
Characteristics
Immigrant employees       7694218.0   38859.686869   20.0   3598.0   569900.0
Non-immigrant employees  24370675.0  123084.217172  192.0  29397.0  1754860.0

                         size
Characteristics
Immigrant employees       198
Non-immigrant employees   198
Overall,
Sum :  32064893.0
Mean :  80971.95202020202
Min/median/max : 20.0 / 12524.0 / 1754860.0
Skewnewss :  5.310500968392142
Total size :  396

Year of 2016
                             sum          mean  amin  median      amax  size
Characteristics
15 to 24 years         3568591.0  18586.411458  17.0  4338.0  246749.0   192
25 to 34 years         7218822.0  34375.342857  22.0  6063.0  527094.0   210
35 to 44 years         7058062.0  33609.819048  22.0  6157.5  516879.0   210
45 to 54 years         7243040.0  34490.666667  16.0  6123.0  525300.0   210
55 to 64 years         6305020.0  30023.904762  12.0  5590.0  453209.0   210
65 years old and over  2240484.0  11669.187500  21.0  2432.5  162525.0   192
Overall,
Sum :  33634019.0
Mean :  27478.773692810457
Min/median/max : 12.0 / 4444.5 / 527094.0
Skewnewss :  4.775599421631397
Total size :  1224
Year of 2016
                                     sum          mean  amin   median  \
Characteristics
High school diploma and less   7346224.0  34982.019048  45.0   8309.5
Trade certificate              2312220.0  11677.878788  13.0   2042.0
University degree and higher  15322286.0  77385.282828  42.0  13038.0

                                   amax  size
Characteristics
High school diploma and less   501836.0   210
Trade certificate              170641.0   198
University degree and higher  1133182.0   198
Overall,
Sum :  24980730.0
Mean :  41222.32673267327
Min/median/max : 13.0 / 5457.0 / 1133182.0
Skewnewss :  5.973175820588759
Total size :  606
Year of 2016
                                     sum          mean  amin   median  \
Characteristics
High school diploma and less   7346224.0  34982.019048  45.0   8309.5
Trade certificate              2312220.0  11677.878788  13.0   2042.0
University degree and higher  15322286.0  77385.282828  42.0  13038.0

                                   amax  size
Characteristics
High school diploma and less   501836.0   210
Trade certificate              170641.0   198
University degree and higher  1133182.0   198
Overall,
Sum :  24980730.0
Mean :  41222.32673267327
Min/median/max : 13.0 / 5457.0 / 1133182.0
Skewnewss :  5.973175820588759
Total size :  606
Year of 2016
                                sum           mean   amin   median       amax  \
Characteristics
Immigrant employees       8481252.0   42834.606061   19.0   4048.5   626191.0
Non-immigrant employees  25149138.0  127015.848485  161.0  29819.5  1796966.0

                         size
Characteristics
Immigrant employees       198
Non-immigrant employees   198
Overall,
Sum :  33630390.0
Mean :  84925.22727272728
Min/median/max : 19.0 / 13979.5 / 1796966.0
Skewnewss :  5.226871514642094
Total size :  396

Year of 2019
                             sum          mean  amin  median      amax  size
Characteristics
15 to 24 years         3414206.0  17782.322917  24.0  4022.0  247960.0   192
25 to 34 years         7615612.0  36264.819048  19.0  6267.5  564788.0   210
35 to 44 years         7559436.0  35997.314286  18.0  6322.0  561685.0   210
45 to 54 years         7201656.0  34293.600000  16.0  5847.0  529125.0   210
55 to 64 years         6451160.0  30719.809524  13.0  5371.5  472689.0   210
65 years old and over  2416851.0  12587.765625  25.0  2729.0  173157.0   192
Overall,
Sum :  34658921.0
Mean :  28316.111928104576
Min/median/max : 13.0 / 4637.5 / 564788.0
Skewnewss :  4.838307897340021
Total size :  1224
Year of 2019
                                     sum          mean  amin   median  \
Characteristics
High school diploma and less   7204888.0  34308.990476  40.0   8564.5
Trade certificate              2245738.0  11342.111111  13.0   1865.5
University degree and higher  16513042.0  83399.202020  47.0  13812.5

                                   amax  size
Characteristics
High school diploma and less   506866.0   210
Trade certificate              167537.0   198
University degree and higher  1230063.0   198
Overall,
Sum :  25963668.0
Mean :  42844.33663366337
Min/median/max : 13.0 / 5005.0 / 1230063.0
Skewnewss :  6.169027793480176
Total size :  606
Year of 2019
                                     sum          mean  amin   median  \
Characteristics
High school diploma and less   7204888.0  34308.990476  40.0   8564.5
Trade certificate              2245738.0  11342.111111  13.0   1865.5
University degree and higher  16513042.0  83399.202020  47.0  13812.5

                                   amax  size
Characteristics
High school diploma and less   506866.0   210
Trade certificate              167537.0   198
University degree and higher  1230063.0   198
Overall,
Sum :  25963668.0
Mean :  42844.33663366337
Min/median/max : 13.0 / 5005.0 / 1230063.0
Skewnewss :  6.169027793480176
Total size :  606
Year of 2019
                                sum           mean   amin   median       amax  \
Characteristics
Immigrant employees       9133147.0   46127.005051   22.0   4384.0   677236.0
Non-immigrant employees  25522127.0  128899.631313  163.0  30374.0  1866156.0

                         size
Characteristics
Immigrant employees       198
Non-immigrant employees   198
Overall,
Sum :  34655274.0
Mean :  87513.31818181818
Min/median/max : 22.0 / 14330.0 / 1866156.0
Skewnewss :  5.199524609584711
Total size :  396

Final output for "Wages and Salaries"

In [86]:
# dfa_Target_To_Analysis = [df_WagesAndSalaries_2010_ByAge, df_WagesAndSalaries_2010_ByEducation, df_WagesAndSalaries_2010_ByEducation, df_WagesAndSalaries_2010_ByImmigrant]
# for df_Target_To_Analysis in dfa_Target_To_Analysis:
#       grouped = df_Target_To_Analysis.groupby(['Characteristics'])
#       print("Year of 2010")
#       print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
#       print("Overall,")
#       print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
#       print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
#       print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
#             np.median(df_Target_To_Analysis['VALUE']),"/",
#             np.max(df_Target_To_Analysis['VALUE']))
#       print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
#       print("Total size : ",len(df_Target_To_Analysis.index))

# print()
dfa_Target_To_Analysis = [df_WagesAndSalaries_2013_ByAge, df_WagesAndSalaries_2013_ByEducation, df_WagesAndSalaries_2013_ByEducation, df_WagesAndSalaries_2013_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2013")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

print()
dfa_Target_To_Analysis = [df_WagesAndSalaries_2016_ByAge, df_WagesAndSalaries_2016_ByEducation, df_WagesAndSalaries_2016_ByEducation, df_WagesAndSalaries_2016_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2016")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

print()
dfa_Target_To_Analysis = [df_WagesAndSalaries_2019_ByAge, df_WagesAndSalaries_2019_ByEducation, df_WagesAndSalaries_2019_ByEducation, df_WagesAndSalaries_2019_ByImmigrant]
for df_Target_To_Analysis in dfa_Target_To_Analysis:
      grouped = df_Target_To_Analysis.groupby(['Characteristics'])
      print("Year of 2019")
      print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
      print("Overall,")
      print("Sum : ",np.sum(df_Target_To_Analysis['VALUE']))
      print("Mean : ",np.mean(df_Target_To_Analysis['VALUE']))
      print("Min/median/max :",np.min(df_Target_To_Analysis['VALUE']),"/",
            np.median(df_Target_To_Analysis['VALUE']),"/",
            np.max(df_Target_To_Analysis['VALUE']))
      print("Skewnewss : ",df_Target_To_Analysis['VALUE'].skew())
      print("Total size : ",len(df_Target_To_Analysis.index))

Year of 2013
                            sum         mean  amin  median     amax  size
Characteristics
15 to 24 years          51983.0   270.744792   0.0    62.5   3770.0   192
25 to 34 years         252992.0  1204.723810   1.0   193.5  19337.0   210
35 to 44 years         334759.0  1594.090476   1.0   249.5  25471.0   210
45 to 54 years         410954.0  1956.923810   1.0   285.5  30946.0   210
55 to 64 years         313103.0  1490.966667   1.0   228.0  24134.0   210
65 years old and over   62434.0   325.177083   1.0    56.5   4980.0   192
Overall,
Sum :  1426225.0
Mean :  1165.2165032679738
Min/median/max : 0.0 / 131.5 / 30946.0
Skewnewss :  5.458155190569106
Total size :  1224
Year of 2013
                                   sum         mean  amin  median     amax  \
Characteristics
High school diploma and less  191721.0   912.957143   2.0   223.0  13803.0
Trade certificate              86569.0   437.217172   1.0    97.5   6363.0
University degree and higher  793734.0  4008.757576   3.0   676.0  61165.0

                              size
Characteristics
High school diploma and less   210
Trade certificate              198
University degree and higher   198
Overall,
Sum :  1072024.0
Mean :  1769.016501650165
Min/median/max : 1.0 / 194.0 / 61165.0
Skewnewss :  7.058651252598137
Total size :  606
Year of 2013
                                   sum         mean  amin  median     amax  \
Characteristics
High school diploma and less  191721.0   912.957143   2.0   223.0  13803.0
Trade certificate              86569.0   437.217172   1.0    97.5   6363.0
University degree and higher  793734.0  4008.757576   3.0   676.0  61165.0

                              size
Characteristics
High school diploma and less   210
Trade certificate              198
University degree and higher   198
Overall,
Sum :  1072024.0
Mean :  1769.016501650165
Min/median/max : 1.0 / 194.0 / 61165.0
Skewnewss :  7.058651252598137
Total size :  606
Year of 2013
                               sum         mean  amin  median     amax  size
Characteristics
Immigrant employees       348492.0  1760.060606   1.0   161.0  27151.0   198
Non-immigrant employees  1077526.0  5442.050505   9.0  1200.5  81487.0   198
Overall,
Sum :  1426018.0
Mean :  3601.0555555555557
Min/median/max : 1.0 / 472.0 / 81487.0
Skewnewss :  5.40064585441906
Total size :  396

Year of 2016
                            sum         mean  amin  median     amax  size
Characteristics
15 to 24 years          56990.0   296.822917   0.0    67.5   4250.0   192
25 to 34 years         285555.0  1359.785714   1.0   220.5  21911.0   210
35 to 44 years         376045.0  1790.690476   1.0   271.0  28840.0   210
45 to 54 years         431853.0  2056.442857   1.0   292.0  32326.0   210
55 to 64 years         344362.0  1639.819048   1.0   241.5  25923.0   210
65 years old and over   76349.0   397.651042   1.0    73.0   5823.0   192
Overall,
Sum :  1571154.0
Mean :  1283.6225490196077
Min/median/max : 0.0 / 147.5 / 32326.0
Skewnewss :  5.350182768055304
Total size :  1224
Year of 2016
                                   sum         mean  amin  median     amax  \
Characteristics
High school diploma and less  207705.0   989.071429   2.0   243.0  14711.0
Trade certificate              86692.0   437.838384   1.0    87.5   6433.0
University degree and higher  896636.0  4528.464646   3.0   798.0  69317.0

                              size
Characteristics
High school diploma and less   210
Trade certificate              198
University degree and higher   198
Overall,
Sum :  1191033.0
Mean :  1965.40099009901
Min/median/max : 1.0 / 205.0 / 69317.0
Skewnewss :  7.079129163046304
Total size :  606
Year of 2016
                                   sum         mean  amin  median     amax  \
Characteristics
High school diploma and less  207705.0   989.071429   2.0   243.0  14711.0
Trade certificate              86692.0   437.838384   1.0    87.5   6433.0
University degree and higher  896636.0  4528.464646   3.0   798.0  69317.0

                              size
Characteristics
High school diploma and less   210
Trade certificate              198
University degree and higher   198
Overall,
Sum :  1191033.0
Mean :  1965.40099009901
Min/median/max : 1.0 / 205.0 / 69317.0
Skewnewss :  7.079129163046304
Total size :  606
Year of 2016
                               sum         mean  amin  median     amax  size
Characteristics
Immigrant employees       400833.0  2024.409091   1.0   187.0  31105.0   198
Non-immigrant employees  1170079.0  5909.489899   9.0  1324.0  87968.0   198
Overall,
Sum :  1570912.0
Mean :  3966.949494949495
Min/median/max : 1.0 / 519.0 / 87968.0
Skewnewss :  5.320716824931746
Total size :  396

Year of 2019
                            sum         mean  amin  median     amax  size
Characteristics
15 to 24 years          63069.0   328.484375   1.0    69.0   4797.0   192
25 to 34 years         334200.0  1591.428571   1.0   236.5  25966.0   210
35 to 44 years         441049.0  2100.233333   2.0   314.5  34223.0   210
45 to 54 years         474202.0  2258.104762   1.0   317.0  36376.0   210
55 to 64 years         386319.0  1839.614286   1.0   260.5  29595.0   210
65 years old and over   90513.0   471.421875   1.0    88.0   6876.0   192
Overall,
Sum :  1789352.0
Mean :  1461.888888888889
Min/median/max : 1.0 / 160.5 / 36376.0
Skewnewss :  5.308031050696339
Total size :  1224
Year of 2019
                                    sum         mean  amin  median     amax  \
Characteristics
High school diploma and less   226638.0  1079.228571   2.0   260.5  16432.0
Trade certificate               93374.0   471.585859   1.0    85.5   7213.0
University degree and higher  1052815.0  5317.247475   4.0   931.5  81938.0

                              size
Characteristics
High school diploma and less   210
Trade certificate              198
University degree and higher   198
Overall,
Sum :  1372827.0
Mean :  2265.391089108911
Min/median/max : 1.0 / 215.5 / 81938.0
Skewnewss :  7.125641720633304
Total size :  606
Year of 2019
                                    sum         mean  amin  median     amax  \
Characteristics
High school diploma and less   226638.0  1079.228571   2.0   260.5  16432.0
Trade certificate               93374.0   471.585859   1.0    85.5   7213.0
University degree and higher  1052815.0  5317.247475   4.0   931.5  81938.0

                              size
Characteristics
High school diploma and less   210
Trade certificate              198
University degree and higher   198
Overall,
Sum :  1372827.0
Mean :  2265.391089108911
Min/median/max : 1.0 / 215.5 / 81938.0
Skewnewss :  7.125641720633304
Total size :  606
Year of 2019
                               sum         mean  amin  median      amax  size
Characteristics
Immigrant employees       473697.0  2392.409091   1.0   216.5   36981.0   198
Non-immigrant employees  1315368.0  6643.272727  10.0  1452.5  100851.0   198
Overall,
Sum :  1789065.0
Mean :  4517.840909090909
Min/median/max : 1.0 / 578.0 / 100851.0
Skewnewss :  5.266660488336198
Total size :  396

In [87]:
print("Final steps, by sorting out by provinces.")

# -- sum          mean           std  size
# -- GEO                                                                    
# -- Alberta                     2193966.0   2031.450000   2695.836034  1080
# -- British Columbia            2401296.0   2223.422222   2804.925187  1080
# -- Canada                     18252439.0  16900.406481  22232.852533  1080
# -- Manitoba                     767802.0    710.927778    915.637659  1080
# -- New Brunswick                359320.0    332.703704    530.962762  1080
# -- Newfoundland and Labrador    315895.0    306.099806    482.634908  1032
# -- Northwest Territories         42804.0     41.476744     51.817046  1032
# -- Nova Scotia                  531805.0    492.412037    757.119411  1080
# -- Nunavut                       14235.0     15.208333     14.752372   936
# -- Ontario                     6601634.0   6112.624074   7594.433779  1080
# -- Prince Edward Island          77931.0     75.514535    121.297367  1032
# -- Quebec                      4271657.0   3955.237963   5580.294544  1080
# -- Saskatchewan                 650781.0    602.575000    876.896377  1080
# -- Yukon                         16914.0     18.070513     20.188135   936
# -- The total number of this one is  14688

Final steps, by sorting out by provinces.

As final step, I am classifying the data by province. This is the final step, and this is where I will get the final result with.<br />
For this step, I will use class methods to avoid duplicated and repeatitive steps to do programming.<br />
For the complex of the analysis, only the dataset of 2013-2015, 2016-2018, 2019-2021 will be used. <br />
However, 2010-2012 one will get commented.

In [88]:
print("With year of 2013 and above (three dataset), I will have to analyize, "+str(7*3*4*14)+" times.")
print("\nUse the year from 2010 to 2021 (four dataasets), I will have to analyize, "+str(7*4*4*14)+" times!")

With year of 2013 and above (three dataset), I will have to analyize, 1176 times.

Use the year from 2010 to 2021 (four dataasets), I will have to analyize, 1568 times!

Main class for Province Analysis:

In [89]:
# https://www.w3schools.com/python/python_classes.asp
# https://www.w3schools.com/python/python_for_loops.asp
# https://www.educba.com/multidimensional-array-in-python/

class ProvinceAnalysis:

    # Province :
    # -- ['Alberta',  'British Columbia',    'Canada' , 'Manitoba' , 'New Brunswick' 
    # 'Newfoundland and Labrador', 'Northwest Territories' , 'Nova Scotia' , 'Nunavut'
    # 'Ontario' , 'Prince Edward Island', 'Quebec', 'Saskatchewan', 'Yukon']

    def __init__(self, df, pd, np, pp):
        self.df = df
        self.province = ['Alberta',  'British Columbia', 'Canada', 'Manitoba', 
                        'New Brunswick', 'Newfoundland and Labrador', 
                        'Northwest Territories' , 'Nova Scotia' , 'Nunavut',
                        'Ontario' , 'Prince Edward Island', 'Quebec', 
                        'Saskatchewan', 'Yukon'
                        ]
        self.indicator = ["Average annual hours worked",
                        "Average annual wages and salaries",
                        "Average hourly wage",
                        "Average weekly hours worked",
                        "Hours Worked",
                        "Number of jobs",
                        "Wages and Salaries"]
        self.characteristic = ["Age group", "Gender", "Education Level", "Immigrant status", "Aboriginal status"]
        self.year = ["2010",
                    "below 2015",
                    "above 2016",
                    "2013",
                    "2016",
                    "2019"]
        self.pd = pd
        self.np = np
        self.pp = pp
        self.df_ByProvince = []
        for x in self.province:
            df_sorted = df.loc[df['GEO'] == x]
            self.df_ByProvince.append(df_sorted)

    def outputProvince(self, province_id):
        print(self.province[province_id])

    def outputIndicator(self, indicator_id):
        print(self.province[indicator_id])

    def outputCharacteristic(self, cha_id):
        print(self.province[cha_id])

    def outputYear(self, year_id):
        print(self.province[year_id])

    def outputAnalysis(self, province_id):
        print("\nGrab the dataset only in " + str(self.province[province_id]))
        grouped = self.df_ByProvince[province_id].groupby(['Characteristics'])
        print(grouped['VALUE'].agg([np.sum, np.mean, np.min, np.median, np.max, np.size]))
        print("")
        print("Overall,")
        print("Sum : ",np.sum(self.df_ByProvince[province_id]['VALUE']))
        print("Mean : ",np.mean(self.df_ByProvince[province_id]['VALUE']))
        print("Min/median/max :",np.min(self.df_ByProvince[province_id]['VALUE']),"/",
            np.median(self.df_ByProvince[province_id]['VALUE']),"/",
            np.max(self.df_ByProvince[province_id]['VALUE']))
        print("Skewnewss : ",self.df_ByProvince[province_id]['VALUE'].skew())
        print("Total size : ",len(self.df_ByProvince[province_id].index))

    def outputAnalysisSimple(self, province_id):
        print("\nGrab the dataset only in " + str(self.province[province_id]))
        grouped = self.df_ByProvince[province_id].groupby(['Characteristics'])
        print(grouped['VALUE'].agg([self.np.sum, self.np.mean, self.np.size]))

    def outputList(self, province_id, num):
        print("\nGrab the dataset only in " + str(self.province[province_id]))
        print(self.df_ByProvince[province_id].head(num))
        print(self.df_ByProvince[province_id].info())

    def outputPandaProfiling(self, province_id, indicator_id, type_id):

        fileName = str(self.indicator[indicator_id]) + " " + str(self.year[type_id])+" in " + str(self.province[province_id]) + ".html"
        
        pp = ProfileReport(self.df_ByProvince[province_id])
        pp_df = pp.to_html()

        print("File name will be saved under "+str(fileName))
        f = open(fileName, "a")  # Expert into html file without modifying any columns in dataset.
        f.write(pp_df)
        f.close()

Filtered by provinces by "Average annual hours worked"

In [90]:
# By Average annual hours worked categories by provinces.

# df_AvgAnnHrsWrk_ByAge_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_ByAge, pd, np, pp)
# df_AvgAnnHrsWrk_2010_ByAge_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge, pd, np, pp)
df_AvgAnnHrsWrk_2013_ByAge_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge, pd, np, pp)
df_AvgAnnHrsWrk_2016_ByAge_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge, pd, np, pp)
df_AvgAnnHrsWrk_2019_ByAge_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge, pd, np, pp)

# df_AvgAnnHrsWrk_ByGender_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_ByGender, pd, np, pp)
# df_AvgAnnHrsWrk_2010_ByGender_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGender, pd, np, pp)
df_AvgAnnHrsWrk_2013_ByGender_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender, pd, np, pp)
df_AvgAnnHrsWrk_2016_ByGender_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender, pd, np, pp)
df_AvgAnnHrsWrk_2019_ByGender_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender, pd, np, pp)

# df_AvgAnnHrsWrk_ByEducation_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_ByEducation, pd, np, pp)
# df_AvgAnnHrsWrk_2010_ByEducation_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation, pd, np, pp)
df_AvgAnnHrsWrk_2013_ByEducation_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation, pd, np, pp)
df_AvgAnnHrsWrk_2016_ByEducation_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation, pd, np, pp)
df_AvgAnnHrsWrk_2019_ByEducation_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation, pd, np, pp)

# df_AvgAnnHrsWrk_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_ByImmigrant, pd, np, pp)
# df_AvgAnnHrsWrk_2010_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByImmigrant, pd, np, pp)
df_AvgAnnHrsWrk_2013_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByImmigrant, pd, np, pp)
df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant, pd, np, pp)
df_AvgAnnHrsWrk_2019_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByImmigrant, pd, np, pp)

# df_AvgAnnHrsWrk_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_ByIndigenous, pd, np, pp)
# df_AvgAnnHrsWrk_2010_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByIndigenous, pd, np, pp)
# df_AvgAnnHrsWrk_2013_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByIndigenous, pd, np, pp)
# df_AvgAnnHrsWrk_2016_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByIndigenous, pd, np, pp)
# df_AvgAnnHrsWrk_2019_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByIndigenous, pd, np, pp)

Filtered by provinces by "Average wages and salaries"

In [91]:
# By Average annual wages and salaries worked categories by provinces.

# df_AvgAnnWages_ByAge_Provinces = ProvinceAnalysis(df_AvgAnnWages_ByAge, pd, np, pp)
# df_AvgAnnWages_2010_ByAge_Provinces = ProvinceAnalysis(df_AvgAnnWages_2010_ByAge, pd, np, pp)
df_AvgAnnWages_2013_ByAge_Provinces = ProvinceAnalysis(df_AvgAnnWages_2013_ByAge, pd, np, pp)
df_AvgAnnWages_2016_ByAge_Provinces = ProvinceAnalysis(df_AvgAnnWages_2016_ByAge, pd, np, pp)
df_AvgAnnWages_2019_ByAge_Provinces = ProvinceAnalysis(df_AvgAnnWages_2019_ByAge, pd, np, pp)

# df_AvgAnnWages_ByGender_Provinces = ProvinceAnalysis(df_AvgAnnWages_ByGender, pd, np, pp)
# df_AvgAnnWages_2010_ByGender_Provinces = ProvinceAnalysis(df_AvgAnnWages_2010_ByGender, pd, np, pp)
df_AvgAnnWages_2013_ByGender_Provinces = ProvinceAnalysis(df_AvgAnnWages_2013_ByGender, pd, np, pp)
df_AvgAnnWages_2016_ByGender_Provinces = ProvinceAnalysis(df_AvgAnnWages_2016_ByGender, pd, np, pp)
df_AvgAnnWages_2019_ByGender_Provinces = ProvinceAnalysis(df_AvgAnnWages_2019_ByGender, pd, np, pp)

# df_AvgAnnWages_ByEducation_Provinces = ProvinceAnalysis(df_AvgAnnWages_ByEducation, pd, np, pp)
# df_AvgAnnWages_2010_ByEducation_Provinces = ProvinceAnalysis(df_AvgAnnWages_2010_ByEducation, pd, np, pp)
df_AvgAnnWages_2013_ByEducation_Provinces = ProvinceAnalysis(df_AvgAnnWages_2013_ByEducation, pd, np, pp)
df_AvgAnnWages_2016_ByEducation_Provinces = ProvinceAnalysis(df_AvgAnnWages_2016_ByEducation, pd, np, pp)
df_AvgAnnWages_2019_ByEducation_Provinces = ProvinceAnalysis(df_AvgAnnWages_2019_ByEducation, pd, np, pp)

# df_AvgAnnWages_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgAnnWages_ByImmigrant, pd, np, pp)
# df_AvgAnnWages_2010_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgAnnWages_2010_ByImmigrant, pd, np, pp)
df_AvgAnnWages_2013_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgAnnWages_2013_ByImmigrant, pd, np, pp)
df_AvgAnnWages_2016_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgAnnWages_2016_ByImmigrant, pd, np, pp)
df_AvgAnnWages_2019_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgAnnWages_2019_ByImmigrant, pd, np, pp)

# df_AvgAnnWages_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgAnnWages_ByIndigenous, pd, np, pp)
# df_AvgAnnWages_2010_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgAnnWages_2010_ByIndigenous, pd, np, pp)
# df_AvgAnnWages_2013_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgAnnWages_2013_ByIndigenous, pd, np, pp)
# df_AvgAnnWages_2016_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgAnnWages_2016_ByIndigenous, pd, np, pp)
# df_AvgAnnWages_2019_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgAnnWages_2019_ByIndigenous, pd, np, pp)

Filtered by provinces by "Average hourly wage"

In [92]:
# By Average hourly wages and salaries worked categories by provinces.

# df_AvgHrsWages_ByAge_Provinces = ProvinceAnalysis(df_AvgHrsWages_ByAge, pd, np, pp)
# df_AvgHrsWages_2010_ByAge_Provinces = ProvinceAnalysis(df_AvgHrsWages_2010_ByAge, pd, np, pp)
df_AvgHrsWages_2013_ByAge_Provinces = ProvinceAnalysis(df_AvgHrsWages_2013_ByAge, pd, np, pp)
df_AvgHrsWages_2016_ByAge_Provinces = ProvinceAnalysis(df_AvgHrsWages_2016_ByAge, pd, np, pp)
df_AvgHrsWages_2019_ByAge_Provinces = ProvinceAnalysis(df_AvgHrsWages_2019_ByAge, pd, np, pp)

# df_AvgHrsWages_ByGender_Provinces = ProvinceAnalysis(df_AvgHrsWages_ByGender, pd, np, pp)
# df_AvgHrsWages_2010_ByGender_Provinces = ProvinceAnalysis(df_AvgHrsWages_2010_ByGender, pd, np, pp)
df_AvgHrsWages_2013_ByGender_Provinces = ProvinceAnalysis(df_AvgHrsWages_2013_ByGender, pd, np, pp)
df_AvgHrsWages_2016_ByGender_Provinces = ProvinceAnalysis(df_AvgHrsWages_2016_ByGender, pd, np, pp)
df_AvgHrsWages_2019_ByGender_Provinces = ProvinceAnalysis(df_AvgHrsWages_2019_ByGender, pd, np, pp)

# df_AvgHrsWages_ByEducation_Provinces = ProvinceAnalysis(df_AvgHrsWages_ByEducation, pd, np, pp)
# df_AvgHrsWages_2010_ByEducation_Provinces = ProvinceAnalysis(df_AvgHrsWages_2010_ByEducation, pd, np, pp)
df_AvgHrsWages_2013_ByEducation_Provinces = ProvinceAnalysis(df_AvgHrsWages_2013_ByEducation, pd, np, pp)
df_AvgHrsWages_2016_ByEducation_Provinces = ProvinceAnalysis(df_AvgHrsWages_2016_ByEducation, pd, np, pp)
df_AvgHrsWages_2019_ByEducation_Provinces = ProvinceAnalysis(df_AvgHrsWages_2019_ByEducation, pd, np, pp)

# df_AvgHrsWages_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgHrsWages_ByImmigrant, pd, np, pp)
# df_AvgHrsWages_2010_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgHrsWages_2010_ByImmigrant, pd, np, pp)
df_AvgHrsWages_2013_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgHrsWages_2013_ByImmigrant, pd, np, pp)
df_AvgHrsWages_2016_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgHrsWages_2016_ByImmigrant, pd, np, pp)
df_AvgHrsWages_2019_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgHrsWages_2019_ByImmigrant, pd, np, pp)

# df_AvgHrsWages_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgHrsWages_ByIndigenous, pd, np, pp)
# df_AvgHrsWages_2010_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgHrsWages_2010_ByIndigenous, pd, np, pp)
# df_AvgHrsWages_2013_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgHrsWages_2013_ByIndigenous, pd, np, pp)
# df_AvgHrsWages_2016_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgHrsWages_2016_ByIndigenous, pd, np, pp)
# df_AvgHrsWages_2019_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgHrsWages_2019_ByIndigenous, pd, np, pp)

Filtered by provinces by "Average weekly hours worked"

In [93]:
# By Average annual wages and salaries worked categories by provinces.

# df_AvgWeekHrsWrked_ByAge_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_ByAge, pd, np, pp)
# df_AvgWeekHrsWrked_2010_ByAge_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2010_ByAge, pd, np, pp)
df_AvgWeekHrsWrked_2013_ByAge_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2013_ByAge, pd, np, pp)
df_AvgWeekHrsWrked_2016_ByAge_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2016_ByAge, pd, np, pp)
df_AvgWeekHrsWrked_2019_ByAge_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2019_ByAge, pd, np, pp)

# df_AvgWeekHrsWrked_ByGender_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_ByGender, pd, np, pp)
# df_AvgWeekHrsWrked_2010_ByGender_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2010_ByGender, pd, np, pp)
df_AvgWeekHrsWrked_2013_ByGender_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2013_ByGender, pd, np, pp)
df_AvgWeekHrsWrked_2016_ByGender_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2016_ByGender, pd, np, pp)
df_AvgWeekHrsWrked_2019_ByGender_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2019_ByGender, pd, np, pp)

# df_AvgWeekHrsWrked_ByEducation_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_ByEducation, pd, np, pp)
# df_AvgWeekHrsWrked_2010_ByEducation_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2010_ByEducation, pd, np, pp)
df_AvgWeekHrsWrked_2013_ByEducation_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2013_ByEducation, pd, np, pp)
df_AvgWeekHrsWrked_2016_ByEducation_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2016_ByEducation, pd, np, pp)
df_AvgWeekHrsWrked_2019_ByEducation_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2019_ByEducation, pd, np, pp)

# df_AvgWeekHrsWrked_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_ByImmigrant, pd, np, pp)
# df_AvgWeekHrsWrked_2010_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2010_ByImmigrant, pd, np, pp)
df_AvgWeekHrsWrked_2013_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2013_ByImmigrant, pd, np, pp)
df_AvgWeekHrsWrked_2016_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2016_ByImmigrant, pd, np, pp)
df_AvgWeekHrsWrked_2019_ByImmigrant_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2019_ByImmigrant, pd, np, pp)

# df_AvgWeekHrsWrked_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_ByIndigenous, pd, np, pp)
# df_AvgWeekHrsWrked_2010_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2010_ByIndigenous, pd, np, pp)
# df_AvgWeekHrsWrked_2013_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2013_ByIndigenous, pd, np, pp)
# df_AvgWeekHrsWrked_2016_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2016_ByIndigenous, pd, np, pp)
# df_AvgWeekHrsWrked_2019_ByIndigenous_Provinces = ProvinceAnalysis(df_AvgWeekHrsWrked_2019_ByIndigenous, pd, np, pp)

Filtered by provinces by "Hours Worked"

In [94]:
# By Hours workee and salaries worked categories by provinces.

# df_Hrs_Wrked_ByAge_Provinces = ProvinceAnalysis(df_Hrs_Wrked_ByAge, pd, np, pp)
# df_Hrs_Wrked_2010_ByAge_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2010_ByAge, pd, np, pp)
df_Hrs_Wrked_2013_ByAge_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2013_ByAge, pd, np, pp)
df_Hrs_Wrked_2016_ByAge_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2016_ByAge, pd, np, pp)
df_Hrs_Wrked_2019_ByAge_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2019_ByAge, pd, np, pp)

# df_Hrs_Wrked_ByGender_Provinces = ProvinceAnalysis(df_Hrs_Wrked_ByGender, pd, np, pp)
# df_Hrs_Wrked_2010_ByGender_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2010_ByGender, pd, np, pp)
df_Hrs_Wrked_2013_ByGender_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2013_ByGender, pd, np, pp)
df_Hrs_Wrked_2016_ByGender_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2016_ByGender, pd, np, pp)
df_Hrs_Wrked_2019_ByGender_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2019_ByGender, pd, np, pp)

# df_Hrs_Wrked_ByEducation_Provinces = ProvinceAnalysis(df_Hrs_Wrked_ByEducation, pd, np, pp)
# df_Hrs_Wrked_2010_ByEducation_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2010_ByEducation, pd, np, pp)
df_Hrs_Wrked_2013_ByEducation_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2013_ByEducation, pd, np, pp)
df_Hrs_Wrked_2016_ByEducation_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2016_ByEducation, pd, np, pp)
df_Hrs_Wrked_2019_ByEducation_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2019_ByEducation, pd, np, pp)

# df_Hrs_Wrked_ByImmigrant_Provinces = ProvinceAnalysis(df_Hrs_Wrked_ByImmigrant, pd, np, pp)
# df_Hrs_Wrked_2010_ByImmigrant_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2010_ByImmigrant, pd, np, pp)
df_Hrs_Wrked_2013_ByImmigrant_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2013_ByImmigrant, pd, np, pp)
df_Hrs_Wrked_2016_ByImmigrant_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2016_ByImmigrant, pd, np, pp)
df_Hrs_Wrked_2019_ByImmigrant_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2019_ByImmigrant, pd, np, pp)

# df_Hrs_Wrked_ByIndigenous_Provinces = ProvinceAnalysis(df_Hrs_Wrked_ByIndigenous, pd, np, pp)
# df_Hrs_Wrked_2010_ByIndigenous_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2010_ByIndigenous, pd, np, pp)
# df_Hrs_Wrked_2013_ByIndigenous_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2013_ByIndigenous, pd, np, pp)
# df_Hrs_Wrked_2016_ByIndigenous_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2016_ByIndigenous, pd, np, pp)
# df_Hrs_Wrked_2019_ByIndigenous_Provinces = ProvinceAnalysis(df_Hrs_Wrked_2019_ByIndigenous, pd, np, pp)

Filtered by provinces by "Number of jobs"

In [95]:
# By Number of jobs and salaries worked categories by provinces.

# df_NumOfJob_ByAge_Provinces = ProvinceAnalysis(df_NumOfJob_ByAge, pd, np, pp)
# df_NumOfJob_2010_ByAge_Provinces = ProvinceAnalysis(df_NumOfJob_2010_ByAge, pd, np, pp)
df_NumOfJob_2013_ByAge_Provinces = ProvinceAnalysis(df_NumOfJob_2013_ByAge, pd, np, pp)
df_NumOfJob_2016_ByAge_Provinces = ProvinceAnalysis(df_NumOfJob_2016_ByAge, pd, np, pp)
df_NumOfJob_2019_ByAge_Provinces = ProvinceAnalysis(df_NumOfJob_2019_ByAge, pd, np, pp)

# df_NumOfJob_ByGender_Provinces = ProvinceAnalysis(df_NumOfJob_ByGender, pd, np, pp)
# df_NumOfJob_2010_ByGender_Provinces = ProvinceAnalysis(df_NumOfJob_2010_ByGender, pd, np, pp)
df_NumOfJob_2013_ByGender_Provinces = ProvinceAnalysis(df_NumOfJob_2013_ByGender, pd, np, pp)
df_NumOfJob_2016_ByGender_Provinces = ProvinceAnalysis(df_NumOfJob_2016_ByGender, pd, np, pp)
df_NumOfJob_2019_ByGender_Provinces = ProvinceAnalysis(df_NumOfJob_2019_ByGender, pd, np, pp)

# df_NumOfJob_ByEducation_Provinces = ProvinceAnalysis(df_NumOfJob_ByEducation, pd, np, pp)
# df_NumOfJob_2010_ByEducation_Provinces = ProvinceAnalysis(df_NumOfJob_2010_ByEducation, pd, np, pp)
df_NumOfJob_2013_ByEducation_Provinces = ProvinceAnalysis(df_NumOfJob_2013_ByEducation, pd, np, pp)
df_NumOfJob_2016_ByEducation_Provinces = ProvinceAnalysis(df_NumOfJob_2016_ByEducation, pd, np, pp)
df_NumOfJob_2019_ByEducation_Provinces = ProvinceAnalysis(df_NumOfJob_2019_ByEducation, pd, np, pp)

# df_NumOfJob_ByImmigrant_Provinces = ProvinceAnalysis(df_NumOfJob_ByImmigrant, pd, np, pp)
# df_NumOfJob_2010_ByImmigrant_Provinces = ProvinceAnalysis(df_NumOfJob_2010_ByImmigrant, pd, np, pp)
df_NumOfJob_2013_ByImmigrant_Provinces = ProvinceAnalysis(df_NumOfJob_2013_ByImmigrant, pd, np, pp)
df_NumOfJob_2016_ByImmigrant_Provinces = ProvinceAnalysis(df_NumOfJob_2016_ByImmigrant, pd, np, pp)
df_NumOfJob_2019_ByImmigrant_Provinces = ProvinceAnalysis(df_NumOfJob_2019_ByImmigrant, pd, np, pp)

# df_NumOfJob_ByIndigenous_Provinces = ProvinceAnalysis(df_NumOfJob_ByIndigenous, pd, np, pp)
# df_NumOfJob_2010_ByIndigenous_Provinces = ProvinceAnalysis(df_NumOfJob_2010_ByIndigenous, pd, np, pp)
# df_NumOfJob_2013_ByIndigenous_Provinces = ProvinceAnalysis(df_NumOfJob_2013_ByIndigenous, pd, np, pp)
# df_NumOfJob_2016_ByIndigenous_Provinces = ProvinceAnalysis(df_NumOfJob_2016_ByIndigenous, pd, np, pp)
# df_NumOfJob_2019_ByIndigenous_Provinces = ProvinceAnalysis(df_NumOfJob_2019_ByIndigenous, pd, np, pp)

Filted by provinces by "Wages and Salaries"

In [96]:
# By Wages and Salaries worked categories by provinces.

# df_WagesAndSalaries_ByAge_Provinces = ProvinceAnalysis(df_WagesAndSalaries_ByAge, pd, np, pp)
# df_WagesAndSalaries_2010_ByAge_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2010_ByAge, pd, np, pp)
df_WagesAndSalaries_2013_ByAge_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2013_ByAge, pd, np, pp)
df_WagesAndSalaries_2016_ByAge_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2016_ByAge, pd, np, pp)
df_WagesAndSalaries_2019_ByAge_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2019_ByAge, pd, np, pp)

# df_WagesAndSalaries_ByGender_Provinces = ProvinceAnalysis(df_WagesAndSalaries_ByGender, pd, np, pp)
# df_WagesAndSalaries_2010_ByGender_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2010_ByGender, pd, np, pp)
df_WagesAndSalaries_2013_ByGender_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2013_ByGender, pd, np, pp)
df_WagesAndSalaries_2016_ByGender_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2016_ByGender, pd, np, pp)
df_WagesAndSalaries_2019_ByGender_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2019_ByGender, pd, np, pp)

# df_WagesAndSalaries_ByEducation_Provinces = ProvinceAnalysis(df_WagesAndSalaries_ByEducation, pd, np, pp)
# df_WagesAndSalaries_2010_ByEducation_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2010_ByEducation, pd, np, pp)
df_WagesAndSalaries_2013_ByEducation_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2013_ByEducation, pd, np, pp)
df_WagesAndSalaries_2016_ByEducation_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2016_ByEducation, pd, np, pp)
df_WagesAndSalaries_2019_ByEducation_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2019_ByEducation, pd, np, pp)

# df_WagesAndSalaries_ByImmigrant_Provinces = ProvinceAnalysis(df_WagesAndSalaries_ByImmigrant, pd, np, pp)
# df_WagesAndSalaries_2010_ByImmigrant_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2010_ByImmigrant, pd, np, pp)
df_WagesAndSalaries_2013_ByImmigrant_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2013_ByImmigrant, pd, np, pp)
df_WagesAndSalaries_2016_ByImmigrant_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2016_ByImmigrant, pd, np, pp)
df_WagesAndSalaries_2019_ByImmigrant_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2019_ByImmigrant, pd, np, pp)

# df_WagesAndSalaries_ByIndigenous_Provinces = ProvinceAnalysis(df_WagesAndSalaries_ByIndigenous, pd, np, pp)
# df_WagesAndSalaries_2010_ByIndigenous_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2010_ByIndigenous, pd, np, pp)
# df_WagesAndSalaries_2013_ByIndigenous_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2013_ByIndigenous, pd, np, pp)
# df_WagesAndSalaries_2016_ByIndigenous_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2016_ByIndigenous, pd, np, pp)
# df_WagesAndSalaries_2019_ByIndigenous_Provinces = ProvinceAnalysis(df_WagesAndSalaries_2019_ByIndigenous, pd, np, pp)

After data analysis of the data, the code below can output the result of the analysis.

Main class for outputting the analysis

In [97]:
# https://howtodoinjava.com/python-examples/python-print-to-file/


class OutputProvinceAnalysis:

    # Province :
    # -- ['Alberta',  'British Columbia',    'Canada' , 'Manitoba' , 'New Brunswick' 
    # 'Newfoundland and Labrador', 'Northwest Territories' , 'Nova Scotia' , 'Nunavut'
    # 'Ontario' , 'Prince Edward Island', 'Quebec', 'Saskatchewan', 'Yukon']

    def __init__(self, df, PC, yrs, pd, np, pp):

        self.df_output = df
        self.ProCode = PC
        self.YearOutput = yrs

    def OutputResult(self):
        print(str(self.YearOutput))
        self.df_output.outputList(self.ProCode, 20)
        self.df_output.outputAnalysis(self.ProCode)

    def OutputPandaProfiling(self):
        if self.YearOutput == '2010':
            print("Year 2010 is not valid at this moment")
            # self.df_output.outputPandaProfiling(self.ProCode,0,0)
        elif self.YearOutput == '2013':
            self.df_output.outputPandaProfiling(self.ProCode,0,3)
        elif self.YearOutput == '2016':
            self.df_output.outputPandaProfiling(self.ProCode,0,4)
        elif self.YearOutput == '2018':
            self.df_output.outputPandaProfiling(self.ProCode,0,5)
        else:
            print("Error!")

Filtering only Alberta.

Only finished "Average annual hours worked".

In [98]:
# # -- Alberta                     2193966.0   2031.450000   2695.836034  1080
# (Before)
# print("2016 - Overall")
# df_AvgAnnHrsWrk_above_2016_ByAge_Provinces.outputList(0, 20)
# df_AvgAnnHrsWrk_above_2016_ByAge_Provinces.outputAnalysis(0)
# print("2016")
# df_AvgAnnHrsWrk_2016_ByAge_Provinces.outputList(0, 20)
# df_AvgAnnHrsWrk_2016_ByAge_Provinces.outputAnalysis(0)
# print("2018")
# df_AvgAnnHrsWrk_2018_ByAge_Provinces.outputList(0, 20)
# df_AvgAnnHrsWrk_2018_ByAge_Provinces.outputAnalysis(0)
# print("2020")
# df_AvgAnnHrsWrk_2020_ByAge_Provinces.outputList(0, 20)
# df_AvgAnnHrsWrk_2020_ByAge_Provinces.outputAnalysis(0)

# print("2016 - Overall")
# df_AvgAnnHrsWrk_above_2016_ByGender_Provinces.outputList(0, 20)
# df_AvgAnnHrsWrk_above_2016_ByGender_Provinces.outputAnalysis(0)
# print("2016")
# df_AvgAnnHrsWrk_2016_ByGender_Provinces.outputList(0, 20)
# df_AvgAnnHrsWrk_2016_ByGender_Provinces.outputAnalysis(0)
# print("2018")
# df_AvgAnnHrsWrk_2018_ByGender_Provinces.outputList(0, 20)
# df_AvgAnnHrsWrk_2018_ByGender_Provinces.outputAnalysis(0)
# print("2020")
# df_AvgAnnHrsWrk_2020_ByGender_Provinces.outputList(0, 20)
# df_AvgAnnHrsWrk_2020_ByGender_Provinces.outputAnalysis(0)

# print("2016 - Overall")
# df_AvgAnnHrsWrk_above_2016_ByEducation_Provinces.outputList(0, 20)
# df_AvgAnnHrsWrk_above_2016_ByEducation_Provinces.outputAnalysis(0)
# print("2016")
# df_AvgAnnHrsWrk_2016_ByEducation_Provinces.outputList(0, 20)
# df_AvgAnnHrsWrk_2016_ByEducation_Provinces.outputAnalysis(0)
# print("2018")
# df_AvgAnnHrsWrk_2018_ByEducation_Provinces.outputList(0, 20)
# df_AvgAnnHrsWrk_2018_ByEducation_Provinces.outputAnalysis(0)
# print("2020")
# df_AvgAnnHrsWrk_2020_ByEducation_Provinces.outputList(0, 20)
# df_AvgAnnHrsWrk_2020_ByEducation_Provinces.outputAnalysis(0)

# print("2016 - Overall")
# df_AvgAnnHrsWrk_above_2016_ByImmigrant_Provinces.outputList(0, 20)
# df_AvgAnnHrsWrk_above_2016_ByImmigrant_Provinces.outputAnalysis(0)
# print("2016")
# df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces.outputList(0, 20)
# df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces.outputAnalysis(0)
# print("2018")
# df_AvgAnnHrsWrk_2018_ByImmigrant_Provinces.outputList(0, 20)
# df_AvgAnnHrsWrk_2018_ByImmigrant_Provinces.outputAnalysis(0)
# print("2020")
# df_AvgAnnHrsWrk_2020_ByImmigrant_Provinces.outputList(0, 20)
# df_AvgAnnHrsWrk_2020_ByImmigrant_Provinces.outputAnalysis(0)

In [99]:
# # -- Alberta                     2193966.0   2031.450000   2695.836034  1080
# (After using the class)

ProCode = 0

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

2013

Grab the dataset only in Alberta
       REF_DATE      GEO                                             Sector  \
32217      2013  Alberta                      Total non-profit institutions
32224      2013  Alberta                      Total non-profit institutions
32231      2013  Alberta                      Total non-profit institutions
32238      2013  Alberta                      Total non-profit institutions
32245      2013  Alberta                      Total non-profit institutions
32252      2013  Alberta                      Total non-profit institutions
32343      2013  Alberta  Total non-profit institutions excluding govern...
32350      2013  Alberta  Total non-profit institutions excluding govern...
32357      2013  Alberta  Total non-profit institutions excluding govern...
32364      2013  Alberta  Total non-profit institutions excluding govern...
32371      2013  Alberta  Total non-profit institutions excluding govern...
32378      2013  Alberta  Total non-profit institutions excluding govern...
32469      2013  Alberta  Non-profit institutions serving households (co...
32476      2013  Alberta  Non-profit institutions serving households (co...
32483      2013  Alberta  Non-profit institutions serving households (co...
32490      2013  Alberta  Non-profit institutions serving households (co...
32497      2013  Alberta  Non-profit institutions serving households (co...
32504      2013  Alberta  Non-profit institutions serving households (co...
32595      2013  Alberta                   Business non-profit institutions
32602      2013  Alberta                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
32217         15 to 24 years  Average annual hours worked  Hours
32224         25 to 34 years  Average annual hours worked  Hours
32231         35 to 44 years  Average annual hours worked  Hours
32238         45 to 54 years  Average annual hours worked  Hours
32245         55 to 64 years  Average annual hours worked  Hours
32252  65 years old and over  Average annual hours worked  Hours
32343         15 to 24 years  Average annual hours worked  Hours
32350         25 to 34 years  Average annual hours worked  Hours
32357         35 to 44 years  Average annual hours worked  Hours
32364         45 to 54 years  Average annual hours worked  Hours
32371         55 to 64 years  Average annual hours worked  Hours
32378  65 years old and over  Average annual hours worked  Hours
32469         15 to 24 years  Average annual hours worked  Hours
32476         25 to 34 years  Average annual hours worked  Hours
32483         35 to 44 years  Average annual hours worked  Hours
32490         45 to 54 years  Average annual hours worked  Hours
32497         55 to 64 years  Average annual hours worked  Hours
32504  65 years old and over  Average annual hours worked  Hours
32595         15 to 24 years  Average annual hours worked  Hours
32602         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
32217         units  1062.0
32224         units  1642.0
32231         units  1755.0
32238         units  1851.0
32245         units  1758.0
32252         units  1257.0
32343         units   991.0
32350         units  1723.0
32357         units  1803.0
32364         units  1876.0
32371         units  1795.0
32378         units  1234.0
32469         units   982.0
32476         units  1689.0
32483         units  1770.0
32490         units  1854.0
32497         units  1778.0
32504         units  1223.0
32595         units  1009.0
32602         units  1816.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 32217 to 50396
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Alberta
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         15084.0  1005.600000   955.0   991.0  1108.0    15
25 to 34 years         25163.0  1677.533333  1544.0  1675.0  1816.0    15
35 to 44 years         26725.0  1781.666667  1674.0  1760.0  1925.0    15
45 to 54 years         27952.0  1863.466667  1794.0  1851.0  1958.0    15
55 to 64 years         26549.0  1769.933333  1679.0  1766.0  1860.0    15
65 years old and over  18496.0  1233.066667  1178.0  1233.0  1285.0    15

Overall,
Sum :  139969.0
Mean :  1555.2111111111112
Min/median/max : 955.0 / 1712.0 / 1958.0
Skewnewss :  -0.700028969989986
Total size :  90
2016

Grab the dataset only in Alberta
       REF_DATE      GEO                                             Sector  \
58677      2016  Alberta                      Total non-profit institutions
58684      2016  Alberta                      Total non-profit institutions
58691      2016  Alberta                      Total non-profit institutions
58698      2016  Alberta                      Total non-profit institutions
58705      2016  Alberta                      Total non-profit institutions
58712      2016  Alberta                      Total non-profit institutions
58803      2016  Alberta  Total non-profit institutions excluding govern...
58810      2016  Alberta  Total non-profit institutions excluding govern...
58817      2016  Alberta  Total non-profit institutions excluding govern...
58824      2016  Alberta  Total non-profit institutions excluding govern...
58831      2016  Alberta  Total non-profit institutions excluding govern...
58838      2016  Alberta  Total non-profit institutions excluding govern...
58929      2016  Alberta  Non-profit institutions serving households (co...
58936      2016  Alberta  Non-profit institutions serving households (co...
58943      2016  Alberta  Non-profit institutions serving households (co...
58950      2016  Alberta  Non-profit institutions serving households (co...
58957      2016  Alberta  Non-profit institutions serving households (co...
58964      2016  Alberta  Non-profit institutions serving households (co...
59055      2016  Alberta                   Business non-profit institutions
59062      2016  Alberta                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
58677         15 to 24 years  Average annual hours worked  Hours
58684         25 to 34 years  Average annual hours worked  Hours
58691         35 to 44 years  Average annual hours worked  Hours
58698         45 to 54 years  Average annual hours worked  Hours
58705         55 to 64 years  Average annual hours worked  Hours
58712  65 years old and over  Average annual hours worked  Hours
58803         15 to 24 years  Average annual hours worked  Hours
58810         25 to 34 years  Average annual hours worked  Hours
58817         35 to 44 years  Average annual hours worked  Hours
58824         45 to 54 years  Average annual hours worked  Hours
58831         55 to 64 years  Average annual hours worked  Hours
58838  65 years old and over  Average annual hours worked  Hours
58929         15 to 24 years  Average annual hours worked  Hours
58936         25 to 34 years  Average annual hours worked  Hours
58943         35 to 44 years  Average annual hours worked  Hours
58950         45 to 54 years  Average annual hours worked  Hours
58957         55 to 64 years  Average annual hours worked  Hours
58964  65 years old and over  Average annual hours worked  Hours
59055         15 to 24 years  Average annual hours worked  Hours
59062         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
58677         units   988.0
58684         units  1588.0
58691         units  1713.0
58698         units  1820.0
58705         units  1712.0
58712         units  1200.0
58803         units   921.0
58810         units  1654.0
58817         units  1744.0
58824         units  1815.0
58831         units  1714.0
58838         units  1177.0
58929         units   921.0
58936         units  1619.0
58943         units  1711.0
58950         units  1793.0
58957         units  1697.0
58964         units  1170.0
59055         units   921.0
59062         units  1747.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 58677 to 76856
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Alberta
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         14319.0   954.600000   901.0   932.0  1038.0    15
25 to 34 years         24514.0  1634.266667  1520.0  1619.0  1767.0    15
35 to 44 years         26233.0  1748.866667  1666.0  1728.0  1882.0    15
45 to 54 years         27495.0  1833.000000  1772.0  1821.0  1930.0    15
55 to 64 years         25875.0  1725.000000  1657.0  1714.0  1812.0    15
65 years old and over  17962.0  1197.466667  1131.0  1201.0  1249.0    15

Overall,
Sum :  136398.0
Mean :  1515.5333333333333
Min/median/max : 901.0 / 1683.0 / 1930.0
Skewnewss :  -0.7145565988067903
Total size :  90
2019

Grab the dataset only in Alberta
       REF_DATE      GEO                                             Sector  \
85137      2019  Alberta                      Total non-profit institutions
85144      2019  Alberta                      Total non-profit institutions
85151      2019  Alberta                      Total non-profit institutions
85158      2019  Alberta                      Total non-profit institutions
85165      2019  Alberta                      Total non-profit institutions
85172      2019  Alberta                      Total non-profit institutions
85263      2019  Alberta  Total non-profit institutions excluding govern...
85270      2019  Alberta  Total non-profit institutions excluding govern...
85277      2019  Alberta  Total non-profit institutions excluding govern...
85284      2019  Alberta  Total non-profit institutions excluding govern...
85291      2019  Alberta  Total non-profit institutions excluding govern...
85298      2019  Alberta  Total non-profit institutions excluding govern...
85389      2019  Alberta  Non-profit institutions serving households (co...
85396      2019  Alberta  Non-profit institutions serving households (co...
85403      2019  Alberta  Non-profit institutions serving households (co...
85410      2019  Alberta  Non-profit institutions serving households (co...
85417      2019  Alberta  Non-profit institutions serving households (co...
85424      2019  Alberta  Non-profit institutions serving households (co...
85515      2019  Alberta                   Business non-profit institutions
85522      2019  Alberta                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
85137         15 to 24 years  Average annual hours worked  Hours
85144         25 to 34 years  Average annual hours worked  Hours
85151         35 to 44 years  Average annual hours worked  Hours
85158         45 to 54 years  Average annual hours worked  Hours
85165         55 to 64 years  Average annual hours worked  Hours
85172  65 years old and over  Average annual hours worked  Hours
85263         15 to 24 years  Average annual hours worked  Hours
85270         25 to 34 years  Average annual hours worked  Hours
85277         35 to 44 years  Average annual hours worked  Hours
85284         45 to 54 years  Average annual hours worked  Hours
85291         55 to 64 years  Average annual hours worked  Hours
85298  65 years old and over  Average annual hours worked  Hours
85389         15 to 24 years  Average annual hours worked  Hours
85396         25 to 34 years  Average annual hours worked  Hours
85403         35 to 44 years  Average annual hours worked  Hours
85410         45 to 54 years  Average annual hours worked  Hours
85417         55 to 64 years  Average annual hours worked  Hours
85424  65 years old and over  Average annual hours worked  Hours
85515         15 to 24 years  Average annual hours worked  Hours
85522         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
85137         units   931.0
85144         units  1541.0
85151         units  1684.0
85158         units  1790.0
85165         units  1679.0
85172         units  1156.0
85263         units   889.0
85270         units  1649.0
85277         units  1750.0
85284         units  1821.0
85291         units  1688.0
85298         units  1140.0
85389         units   876.0
85396         units  1605.0
85403         units  1703.0
85410         units  1783.0
85417         units  1650.0
85424         units  1112.0
85515         units   922.0
85522         units  1779.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 85137 to 103316
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Alberta
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         13715.0   914.333333   857.0   917.0   997.0    15
25 to 34 years         24107.0  1607.133333  1480.0  1595.0  1779.0    15
35 to 44 years         25949.0  1729.933333  1633.0  1717.0  1897.0    15
45 to 54 years         27198.0  1813.200000  1728.0  1817.0  1943.0    15
55 to 64 years         25353.0  1690.200000  1592.0  1685.0  1810.0    15
65 years old and over  17491.0  1166.066667  1092.0  1170.0  1242.0    15

Overall,
Sum :  133813.0
Mean :  1486.8111111111111
Min/median/max : 857.0 / 1648.5 / 1943.0
Skewnewss :  -0.6872641804087184
Total size :  90
2013

Grab the dataset only in Alberta
       REF_DATE      GEO                                             Sector  \
32133      2013  Alberta                      Total non-profit institutions
32140      2013  Alberta                      Total non-profit institutions
32259      2013  Alberta  Total non-profit institutions excluding govern...
32266      2013  Alberta  Total non-profit institutions excluding govern...
32385      2013  Alberta  Non-profit institutions serving households (co...
32392      2013  Alberta  Non-profit institutions serving households (co...
32511      2013  Alberta                   Business non-profit institutions
32518      2013  Alberta                   Business non-profit institutions
32637      2013  Alberta                 Government non-profit institutions
32644      2013  Alberta                 Government non-profit institutions
40953      2014  Alberta                      Total non-profit institutions
40960      2014  Alberta                      Total non-profit institutions
41079      2014  Alberta  Total non-profit institutions excluding govern...
41086      2014  Alberta  Total non-profit institutions excluding govern...
41205      2014  Alberta  Non-profit institutions serving households (co...
41212      2014  Alberta  Non-profit institutions serving households (co...
41331      2014  Alberta                   Business non-profit institutions
41338      2014  Alberta                   Business non-profit institutions
41457      2014  Alberta                 Government non-profit institutions
41464      2014  Alberta                 Government non-profit institutions

        Characteristics                   Indicators    UOM SCALAR_FACTOR  \
32133    Male employees  Average annual hours worked  Hours         units
32140  Female employees  Average annual hours worked  Hours         units
32259    Male employees  Average annual hours worked  Hours         units
32266  Female employees  Average annual hours worked  Hours         units
32385    Male employees  Average annual hours worked  Hours         units
32392  Female employees  Average annual hours worked  Hours         units
32511    Male employees  Average annual hours worked  Hours         units
32518  Female employees  Average annual hours worked  Hours         units
32637    Male employees  Average annual hours worked  Hours         units
32644  Female employees  Average annual hours worked  Hours         units
40953    Male employees  Average annual hours worked  Hours         units
40960  Female employees  Average annual hours worked  Hours         units
41079    Male employees  Average annual hours worked  Hours         units
41086  Female employees  Average annual hours worked  Hours         units
41205    Male employees  Average annual hours worked  Hours         units
41212  Female employees  Average annual hours worked  Hours         units
41331    Male employees  Average annual hours worked  Hours         units
41338  Female employees  Average annual hours worked  Hours         units
41457    Male employees  Average annual hours worked  Hours         units
41464  Female employees  Average annual hours worked  Hours         units

        VALUE
32133  1799.0
32140  1592.0
32259  1791.0
32266  1565.0
32385  1785.0
32392  1558.0
32511  1802.0
32518  1593.0
32637  1804.0
32644  1602.0
40953  1772.0
40960  1566.0
41079  1767.0
41086  1552.0
41205  1762.0
41212  1545.0
41331  1778.0
41338  1579.0
41457  1775.0
41464  1572.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 32133 to 50284
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         30 non-null     int64
 1   GEO              30 non-null     object
 2   Sector           30 non-null     object
 3   Characteristics  30 non-null     object
 4   Indicators       30 non-null     object
 5   UOM              30 non-null     object
 6   SCALAR_FACTOR    30 non-null     object
 7   VALUE            30 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.1+ KB
None

Grab the dataset only in Alberta
                      sum         mean    amin  median    amax  size
Characteristics
Female employees  23452.0  1563.466667  1531.0  1565.0  1602.0    15
Male employees    26681.0  1778.733333  1739.0  1778.0  1804.0    15

Overall,
Sum :  50133.0
Mean :  1671.1
Min/median/max : 1531.0 / 1670.5 / 1804.0
Skewnewss :  -0.028869011932438186
Total size :  30
2016

Grab the dataset only in Alberta
       REF_DATE      GEO                                             Sector  \
58593      2016  Alberta                      Total non-profit institutions
58600      2016  Alberta                      Total non-profit institutions
58719      2016  Alberta  Total non-profit institutions excluding govern...
58726      2016  Alberta  Total non-profit institutions excluding govern...
58845      2016  Alberta  Non-profit institutions serving households (co...
58852      2016  Alberta  Non-profit institutions serving households (co...
58971      2016  Alberta                   Business non-profit institutions

Panda Profiling for Final Result for Alberta

In [100]:
# ProCode = 0
# (Before)
# df_AvgAnnHrsWrk_above_2016_ByAge_Provinces.outputPandaProfiling(ProCode,0,2)
# df_AvgAnnHrsWrk_above_2016_ByGender_Provinces.outputPandaProfiling(ProCode,0,2)
# df_AvgAnnHrsWrk_above_2016_ByEducation_Provinces.outputPandaProfiling(ProCode,0,2)
# df_AvgAnnHrsWrk_above_2016_ByImmigrant_Provinces.outputPandaProfiling(ProCode,0,2)

# df_AvgAnnHrsWrk_2016_ByAge_Provinces.outputPandaProfiling(ProCode,0,3)
# df_AvgAnnHrsWrk_2016_ByGender_Provinces.outputPandaProfiling(ProCode,0,3)
# df_AvgAnnHrsWrk_2016_ByEducation_Provinces.outputPandaProfiling(ProCode,0,3)
# df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces.outputPandaProfiling(ProCode,0,3)

# df_AvgAnnHrsWrk_2018_ByAge_Provinces.outputPandaProfiling(ProCode,0,4)
# df_AvgAnnHrsWrk_2018_ByGender_Provinces.outputPandaProfiling(ProCode,0,4)
# df_AvgAnnHrsWrk_2018_ByEducation_Provinces.outputPandaProfiling(ProCode,0,4)
# df_AvgAnnHrsWrk_2018_ByImmigrant_Provinces.outputPandaProfiling(ProCode,0,4)

# df_AvgAnnHrsWrk_2020_ByAge_Provinces.outputPandaProfiling(ProCode,0,5)
# df_AvgAnnHrsWrk_2020_ByGender_Provinces.outputPandaProfiling(ProCode,0,5)
# df_AvgAnnHrsWrk_2020_ByEducation_Provinces.outputPandaProfiling(ProCode,0,5)
# df_AvgAnnHrsWrk_2020_ByImmigrant_Provinces.outputPandaProfiling(ProCode,0,5)

In [101]:
# After

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputPandaProfiling()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputPandaProfiling()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputPandaProfiling()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputPandaProfiling()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputPandaProfiling()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputPandaProfiling()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputPandaProfiling()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputPandaProfiling()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputPandaProfiling()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputPandaProfiling()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputPandaProfiling()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputPandaProfiling()

Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 15.17it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.32s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.57it/s]

File name will be saved under Average annual hours worked 2013 in Alberta.html

Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 16.12it/s, Completed]
Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.22s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.80it/s]

File name will be saved under Average annual hours worked 2016 in Alberta.html
Error!

Summarize dataset: 100%|██████████| 18/18 [00:00<00:00, 19.07it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.23s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.69it/s]

File name will be saved under Average annual hours worked 2013 in Alberta.html

Summarize dataset: 100%|██████████| 18/18 [00:00<00:00, 20.56it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [11:45<00:00, 705.99s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.36s/it]

File name will be saved under Average annual hours worked 2016 in Alberta.html
Error!

Summarize dataset: 100%|██████████| 18/18 [00:02<00:00,  8.64it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:04<00:00,  4.18s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  3.05it/s]

File name will be saved under Average annual hours worked 2013 in Alberta.html

Summarize dataset: 100%|██████████| 18/18 [00:01<00:00, 16.21it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.04s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.95it/s]

File name will be saved under Average annual hours worked 2016 in Alberta.html
Error!

Summarize dataset: 100%|██████████| 18/18 [00:00<00:00, 20.70it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.07s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.76it/s]

File name will be saved under Average annual hours worked 2013 in Alberta.html

Summarize dataset: 100%|██████████| 18/18 [00:00<00:00, 22.11it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.32s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.76it/s]

File name will be saved under Average annual hours worked 2016 in Alberta.html
Error!

Filtering only British Columbia.

Only finished "Average annual hours worked".

In [102]:
# -- British Columbia            2401296.0   2223.422222   2804.925187  1080

ProCode = 1

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

2013

Grab the dataset only in British Columbia
       REF_DATE               GEO  \
32847      2013  British Columbia
32854      2013  British Columbia
32861      2013  British Columbia
32868      2013  British Columbia
32875      2013  British Columbia
32882      2013  British Columbia
32973      2013  British Columbia
32980      2013  British Columbia
32987      2013  British Columbia
32994      2013  British Columbia
33001      2013  British Columbia
33008      2013  British Columbia
33099      2013  British Columbia
33106      2013  British Columbia
33113      2013  British Columbia
33120      2013  British Columbia
33127      2013  British Columbia
33134      2013  British Columbia
33225      2013  British Columbia
33232      2013  British Columbia

                                                  Sector  \
32847                      Total non-profit institutions
32854                      Total non-profit institutions
32861                      Total non-profit institutions
32868                      Total non-profit institutions
32875                      Total non-profit institutions
32882                      Total non-profit institutions
32973  Total non-profit institutions excluding govern...
32980  Total non-profit institutions excluding govern...
32987  Total non-profit institutions excluding govern...
32994  Total non-profit institutions excluding govern...
33001  Total non-profit institutions excluding govern...
33008  Total non-profit institutions excluding govern...
33099  Non-profit institutions serving households (co...
33106  Non-profit institutions serving households (co...
33113  Non-profit institutions serving households (co...
33120  Non-profit institutions serving households (co...
33127  Non-profit institutions serving households (co...
33134  Non-profit institutions serving households (co...
33225                   Business non-profit institutions
33232                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
32847         15 to 24 years  Average annual hours worked  Hours
32854         25 to 34 years  Average annual hours worked  Hours
32861         35 to 44 years  Average annual hours worked  Hours
32868         45 to 54 years  Average annual hours worked  Hours
32875         55 to 64 years  Average annual hours worked  Hours
32882  65 years old and over  Average annual hours worked  Hours
32973         15 to 24 years  Average annual hours worked  Hours
32980         25 to 34 years  Average annual hours worked  Hours
32987         35 to 44 years  Average annual hours worked  Hours
32994         45 to 54 years  Average annual hours worked  Hours
33001         55 to 64 years  Average annual hours worked  Hours
33008  65 years old and over  Average annual hours worked  Hours
33099         15 to 24 years  Average annual hours worked  Hours
33106         25 to 34 years  Average annual hours worked  Hours
33113         35 to 44 years  Average annual hours worked  Hours
33120         45 to 54 years  Average annual hours worked  Hours
33127         55 to 64 years  Average annual hours worked  Hours
33134  65 years old and over  Average annual hours worked  Hours
33225         15 to 24 years  Average annual hours worked  Hours
33232         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
32847         units   925.0
32854         units  1558.0
32861         units  1678.0
32868         units  1765.0
32875         units  1631.0
32882         units   989.0
32973         units   912.0
32980         units  1602.0
32987         units  1700.0
32994         units  1760.0
33001         units  1625.0
33008         units   983.0
33099         units   903.0
33106         units  1568.0
33113         units  1655.0
33120         units  1727.0
33127         units  1601.0
33134         units   967.0
33225         units   928.0
33232         units  1699.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 32847 to 51026
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in British Columbia
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         13854.0   923.600000   903.0   923.0   946.0    15
25 to 34 years         23898.0  1593.200000  1516.0  1568.0  1705.0    15
35 to 44 years         25599.0  1706.600000  1641.0  1676.0  1849.0    15
45 to 54 years         26772.0  1784.800000  1727.0  1768.0  1880.0    15
55 to 64 years         24680.0  1645.333333  1601.0  1633.0  1718.0    15
65 years old and over  15637.0  1042.466667   967.0  1027.0  1126.0    15

Overall,
Sum :  130440.0
Mean :  1449.3333333333333
Min/median/max : 903.0 / 1621.0 / 1880.0
Skewnewss :  -0.6089665500201625
Total size :  90
2016

Grab the dataset only in British Columbia
       REF_DATE               GEO  \
59307      2016  British Columbia
59314      2016  British Columbia
59321      2016  British Columbia
59328      2016  British Columbia
59335      2016  British Columbia
59342      2016  British Columbia
59433      2016  British Columbia
59440      2016  British Columbia
59447      2016  British Columbia
59454      2016  British Columbia
59461      2016  British Columbia
59468      2016  British Columbia
59559      2016  British Columbia
59566      2016  British Columbia
59573      2016  British Columbia
59580      2016  British Columbia
59587      2016  British Columbia
59594      2016  British Columbia
59685      2016  British Columbia
59692      2016  British Columbia

                                                  Sector  \
59307                      Total non-profit institutions
59314                      Total non-profit institutions
59321                      Total non-profit institutions
59328                      Total non-profit institutions
59335                      Total non-profit institutions
59342                      Total non-profit institutions
59433  Total non-profit institutions excluding govern...
59440  Total non-profit institutions excluding govern...
59447  Total non-profit institutions excluding govern...
59454  Total non-profit institutions excluding govern...
59461  Total non-profit institutions excluding govern...
59468  Total non-profit institutions excluding govern...
59559  Non-profit institutions serving households (co...
59566  Non-profit institutions serving households (co...
59573  Non-profit institutions serving households (co...
59580  Non-profit institutions serving households (co...
59587  Non-profit institutions serving households (co...
59594  Non-profit institutions serving households (co...
59685                   Business non-profit institutions
59692                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
59307         15 to 24 years  Average annual hours worked  Hours
59314         25 to 34 years  Average annual hours worked  Hours
59321         35 to 44 years  Average annual hours worked  Hours
59328         45 to 54 years  Average annual hours worked  Hours
59335         55 to 64 years  Average annual hours worked  Hours
59342  65 years old and over  Average annual hours worked  Hours
59433         15 to 24 years  Average annual hours worked  Hours
59440         25 to 34 years  Average annual hours worked  Hours
59447         35 to 44 years  Average annual hours worked  Hours
59454         45 to 54 years  Average annual hours worked  Hours
59461         55 to 64 years  Average annual hours worked  Hours
59468  65 years old and over  Average annual hours worked  Hours
59559         15 to 24 years  Average annual hours worked  Hours
59566         25 to 34 years  Average annual hours worked  Hours
59573         35 to 44 years  Average annual hours worked  Hours
59580         45 to 54 years  Average annual hours worked  Hours
59587         55 to 64 years  Average annual hours worked  Hours
59594  65 years old and over  Average annual hours worked  Hours
59685         15 to 24 years  Average annual hours worked  Hours
59692         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
59307         units   907.0
59314         units  1544.0
59321         units  1663.0
59328         units  1766.0
59335         units  1641.0
59342         units  1085.0
59433         units   910.0
59440         units  1596.0
59447         units  1689.0
59454         units  1768.0
59461         units  1623.0
59468         units  1049.0
59559         units   893.0
59566         units  1553.0
59573         units  1639.0
59580         units  1731.0
59587         units  1595.0
59594         units  1024.0
59685         units   946.0
59692         units  1707.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 59307 to 77486
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in British Columbia
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         13716.0   914.400000   877.0   914.0   946.0    15
25 to 34 years         23740.0  1582.666667  1506.0  1566.0  1717.0    15
35 to 44 years         25415.0  1694.333333  1607.0  1670.0  1841.0    15
45 to 54 years         26709.0  1780.600000  1694.0  1766.0  1896.0    15
55 to 64 years         24675.0  1645.000000  1555.0  1641.0  1734.0    15
65 years old and over  16305.0  1087.000000   997.0  1091.0  1155.0    15

Overall,
Sum :  130560.0
Mean :  1450.6666666666667
Min/median/max : 877.0 / 1610.5 / 1896.0
Skewnewss :  -0.6246610673731635
Total size :  90
2019

Grab the dataset only in British Columbia
       REF_DATE               GEO  \
85767      2019  British Columbia
85774      2019  British Columbia
85781      2019  British Columbia
85788      2019  British Columbia
85795      2019  British Columbia
85802      2019  British Columbia
85893      2019  British Columbia
85900      2019  British Columbia
85907      2019  British Columbia
85914      2019  British Columbia
85921      2019  British Columbia
85928      2019  British Columbia
86019      2019  British Columbia
86026      2019  British Columbia
86033      2019  British Columbia
86040      2019  British Columbia
86047      2019  British Columbia
86054      2019  British Columbia
86145      2019  British Columbia
86152      2019  British Columbia

                                                  Sector  \
85767                      Total non-profit institutions
85774                      Total non-profit institutions
85781                      Total non-profit institutions
85788                      Total non-profit institutions
85795                      Total non-profit institutions
85802                      Total non-profit institutions
85893  Total non-profit institutions excluding govern...
85900  Total non-profit institutions excluding govern...
85907  Total non-profit institutions excluding govern...
85914  Total non-profit institutions excluding govern...
85921  Total non-profit institutions excluding govern...
85928  Total non-profit institutions excluding govern...
86019  Non-profit institutions serving households (co...
86026  Non-profit institutions serving households (co...
86033  Non-profit institutions serving households (co...
86040  Non-profit institutions serving households (co...
86047  Non-profit institutions serving households (co...
86054  Non-profit institutions serving households (co...
86145                   Business non-profit institutions
86152                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
85767         15 to 24 years  Average annual hours worked  Hours
85774         25 to 34 years  Average annual hours worked  Hours
85781         35 to 44 years  Average annual hours worked  Hours
85788         45 to 54 years  Average annual hours worked  Hours
85795         55 to 64 years  Average annual hours worked  Hours
85802  65 years old and over  Average annual hours worked  Hours
85893         15 to 24 years  Average annual hours worked  Hours
85900         25 to 34 years  Average annual hours worked  Hours
85907         35 to 44 years  Average annual hours worked  Hours
85914         45 to 54 years  Average annual hours worked  Hours
85921         55 to 64 years  Average annual hours worked  Hours
85928  65 years old and over  Average annual hours worked  Hours
86019         15 to 24 years  Average annual hours worked  Hours
86026         25 to 34 years  Average annual hours worked  Hours
86033         35 to 44 years  Average annual hours worked  Hours
86040         45 to 54 years  Average annual hours worked  Hours
86047         55 to 64 years  Average annual hours worked  Hours
86054  65 years old and over  Average annual hours worked  Hours
86145         15 to 24 years  Average annual hours worked  Hours
86152         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
85767         units   905.0
85774         units  1536.0
85781         units  1656.0
85788         units  1753.0
85795         units  1632.0
85802         units  1085.0
85893         units   899.0
85900         units  1575.0
85907         units  1676.0
85914         units  1754.0
85921         units  1616.0
85928         units  1057.0
86019         units   892.0
86026         units  1537.0
86033         units  1633.0
86040         units  1718.0
86047         units  1587.0
86054         units  1035.0
86145         units   915.0
86152         units  1676.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 85767 to 103946
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in British Columbia
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         13399.0   893.266667   863.0   892.0   938.0    15
25 to 34 years         23467.0  1564.466667  1485.0  1549.0  1676.0    15
35 to 44 years         25233.0  1682.200000  1627.0  1671.0  1795.0    15
45 to 54 years         26526.0  1768.400000  1718.0  1753.0  1861.0    15
55 to 64 years         24599.0  1639.933333  1587.0  1632.0  1701.0    15
65 years old and over  16372.0  1091.466667  1035.0  1096.0  1146.0    15

Overall,
Sum :  129596.0
Mean :  1439.9555555555555
Min/median/max : 863.0 / 1613.0 / 1861.0
Skewnewss :  -0.6668291804545202
Total size :  90
2013

Grab the dataset only in British Columbia
       REF_DATE               GEO  \
32763      2013  British Columbia
32770      2013  British Columbia
32889      2013  British Columbia
32896      2013  British Columbia
33015      2013  British Columbia
33022      2013  British Columbia
33141      2013  British Columbia
33148      2013  British Columbia
33267      2013  British Columbia
33274      2013  British Columbia
41583      2014  British Columbia
41590      2014  British Columbia
41709      2014  British Columbia
41716      2014  British Columbia
41835      2014  British Columbia
41842      2014  British Columbia
41961      2014  British Columbia
41968      2014  British Columbia
42087      2014  British Columbia
42094      2014  British Columbia

                                                  Sector   Characteristics  \
32763                      Total non-profit institutions    Male employees
32770                      Total non-profit institutions  Female employees
32889  Total non-profit institutions excluding govern...    Male employees
32896  Total non-profit institutions excluding govern...  Female employees
33015  Non-profit institutions serving households (co...    Male employees
33022  Non-profit institutions serving households (co...  Female employees
33141                   Business non-profit institutions    Male employees
33148                   Business non-profit institutions  Female employees
33267                 Government non-profit institutions    Male employees
33274                 Government non-profit institutions  Female employees
41583                      Total non-profit institutions    Male employees
41590                      Total non-profit institutions  Female employees
41709  Total non-profit institutions excluding govern...    Male employees
41716  Total non-profit institutions excluding govern...  Female employees
41835  Non-profit institutions serving households (co...    Male employees
41842  Non-profit institutions serving households (co...  Female employees
41961                   Business non-profit institutions    Male employees
41968                   Business non-profit institutions  Female employees
42087                 Government non-profit institutions    Male employees
42094                 Government non-profit institutions  Female employees

                        Indicators    UOM SCALAR_FACTOR   VALUE
32763  Average annual hours worked  Hours         units  1646.0
32770  Average annual hours worked  Hours         units  1518.0
32889  Average annual hours worked  Hours         units  1654.0
32896  Average annual hours worked  Hours         units  1473.0
33015  Average annual hours worked  Hours         units  1632.0
33022  Average annual hours worked  Hours         units  1461.0
33141  Average annual hours worked  Hours         units  1697.0
33148  Average annual hours worked  Hours         units  1516.0
33267  Average annual hours worked  Hours         units  1640.0
33274  Average annual hours worked  Hours         units  1539.0
41583  Average annual hours worked  Hours         units  1634.0
41590  Average annual hours worked  Hours         units  1510.0
41709  Average annual hours worked  Hours         units  1661.0
41716  Average annual hours worked  Hours         units  1478.0
41835  Average annual hours worked  Hours         units  1639.0
41842  Average annual hours worked  Hours         units  1465.0
41961  Average annual hours worked  Hours         units  1705.0
41968  Average annual hours worked  Hours         units  1528.0
42087  Average annual hours worked  Hours         units  1614.0
42094  Average annual hours worked  Hours         units  1525.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 32763 to 50914
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         30 non-null     int64
 1   GEO              30 non-null     object
 2   Sector           30 non-null     object
 3   Characteristics  30 non-null     object
 4   Indicators       30 non-null     object
 5   UOM              30 non-null     object
 6   SCALAR_FACTOR    30 non-null     object

Panda Profiling for Final Result for BC

In [103]:
# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

Filtering if "GEO" levelled as "Canada" ONLY.

Only finished "Average annual hours worked".

In [104]:
# -- Canada                     18252439.0  16900.406481  22232.852533  1080

ProCode = 2 # Canada

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

2013

Grab the dataset only in Canada
       REF_DATE     GEO                                             Sector  \
26547      2013  Canada                      Total non-profit institutions
26554      2013  Canada                      Total non-profit institutions
26561      2013  Canada                      Total non-profit institutions
26568      2013  Canada                      Total non-profit institutions
26575      2013  Canada                      Total non-profit institutions
26582      2013  Canada                      Total non-profit institutions
26673      2013  Canada  Total non-profit institutions excluding govern...
26680      2013  Canada  Total non-profit institutions excluding govern...
26687      2013  Canada  Total non-profit institutions excluding govern...
26694      2013  Canada  Total non-profit institutions excluding govern...
26701      2013  Canada  Total non-profit institutions excluding govern...
26708      2013  Canada  Total non-profit institutions excluding govern...
26799      2013  Canada  Non-profit institutions serving households (co...
26806      2013  Canada  Non-profit institutions serving households (co...
26813      2013  Canada  Non-profit institutions serving households (co...
26820      2013  Canada  Non-profit institutions serving households (co...
26827      2013  Canada  Non-profit institutions serving households (co...
26834      2013  Canada  Non-profit institutions serving households (co...
26925      2013  Canada                   Business non-profit institutions
26932      2013  Canada                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
26547         15 to 24 years  Average annual hours worked  Hours
26554         25 to 34 years  Average annual hours worked  Hours
26561         35 to 44 years  Average annual hours worked  Hours
26568         45 to 54 years  Average annual hours worked  Hours
26575         55 to 64 years  Average annual hours worked  Hours
26582  65 years old and over  Average annual hours worked  Hours
26673         15 to 24 years  Average annual hours worked  Hours
26680         25 to 34 years  Average annual hours worked  Hours
26687         35 to 44 years  Average annual hours worked  Hours
26694         45 to 54 years  Average annual hours worked  Hours
26701         55 to 64 years  Average annual hours worked  Hours
26708  65 years old and over  Average annual hours worked  Hours
26799         15 to 24 years  Average annual hours worked  Hours
26806         25 to 34 years  Average annual hours worked  Hours
26813         35 to 44 years  Average annual hours worked  Hours
26820         45 to 54 years  Average annual hours worked  Hours
26827         55 to 64 years  Average annual hours worked  Hours
26834  65 years old and over  Average annual hours worked  Hours
26925         15 to 24 years  Average annual hours worked  Hours
26932         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
26547         units   906.0
26554         units  1559.0
26561         units  1725.0
26568         units  1799.0
26575         units  1645.0
26582         units  1008.0
26673         units   874.0
26680         units  1633.0
26687         units  1759.0
26694         units  1820.0
26701         units  1657.0
26708         units  1030.0
26799         units   872.0
26806         units  1594.0
26813         units  1718.0
26820         units  1787.0
26827         units  1630.0
26834         units  1013.0
26925         units   880.0
26932         units  1753.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 26547 to 44726
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Canada
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         13274.0   884.933333   858.0   874.0   929.0    15
25 to 34 years         24138.0  1609.200000  1517.0  1590.0  1755.0    15
35 to 44 years         26373.0  1758.200000  1697.0  1719.0  1902.0    15
45 to 54 years         27368.0  1824.533333  1781.0  1796.0  1942.0    15
55 to 64 years         25002.0  1666.800000  1629.0  1645.0  1773.0    15
65 years old and over  15745.0  1049.666667   994.0  1042.0  1150.0    15

Overall,
Sum :  131900.0
Mean :  1465.5555555555557
Min/median/max : 858.0 / 1634.0 / 1942.0
Skewnewss :  -0.6044783460487682
Total size :  90
2016

Grab the dataset only in Canada
       REF_DATE     GEO                                             Sector  \
53007      2016  Canada                      Total non-profit institutions
53014      2016  Canada                      Total non-profit institutions
53021      2016  Canada                      Total non-profit institutions
53028      2016  Canada                      Total non-profit institutions
53035      2016  Canada                      Total non-profit institutions
53042      2016  Canada                      Total non-profit institutions
53133      2016  Canada  Total non-profit institutions excluding govern...
53140      2016  Canada  Total non-profit institutions excluding govern...
53147      2016  Canada  Total non-profit institutions excluding govern...
53154      2016  Canada  Total non-profit institutions excluding govern...
53161      2016  Canada  Total non-profit institutions excluding govern...
53168      2016  Canada  Total non-profit institutions excluding govern...
53259      2016  Canada  Non-profit institutions serving households (co...
53266      2016  Canada  Non-profit institutions serving households (co...
53273      2016  Canada  Non-profit institutions serving households (co...
53280      2016  Canada  Non-profit institutions serving households (co...
53287      2016  Canada  Non-profit institutions serving households (co...
53294      2016  Canada  Non-profit institutions serving households (co...
53385      2016  Canada                   Business non-profit institutions
53392      2016  Canada                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
53007         15 to 24 years  Average annual hours worked  Hours
53014         25 to 34 years  Average annual hours worked  Hours
53021         35 to 44 years  Average annual hours worked  Hours
53028         45 to 54 years  Average annual hours worked  Hours
53035         55 to 64 years  Average annual hours worked  Hours
53042  65 years old and over  Average annual hours worked  Hours
53133         15 to 24 years  Average annual hours worked  Hours
53140         25 to 34 years  Average annual hours worked  Hours
53147         35 to 44 years  Average annual hours worked  Hours
53154         45 to 54 years  Average annual hours worked  Hours
53161         55 to 64 years  Average annual hours worked  Hours
53168  65 years old and over  Average annual hours worked  Hours
53259         15 to 24 years  Average annual hours worked  Hours
53266         25 to 34 years  Average annual hours worked  Hours
53273         35 to 44 years  Average annual hours worked  Hours
53280         45 to 54 years  Average annual hours worked  Hours
53287         55 to 64 years  Average annual hours worked  Hours
53294  65 years old and over  Average annual hours worked  Hours
53385         15 to 24 years  Average annual hours worked  Hours
53392         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
53007         units   901.0
53014         units  1559.0
53021         units  1721.0
53028         units  1802.0
53035         units  1654.0
53042         units  1047.0
53133         units   863.0
53140         units  1616.0
53147         units  1742.0
53154         units  1809.0
53161         units  1649.0
53168         units  1049.0
53259         units   859.0
53266         units  1573.0
53273         units  1698.0
53280         units  1771.0
53287         units  1617.0
53294         units  1031.0
53385         units   871.0
53392         units  1740.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 53007 to 71186
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Canada
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         13354.0   890.266667   858.0   878.0   945.0    15
25 to 34 years         23995.0  1599.666667  1522.0  1573.0  1740.0    15
35 to 44 years         26194.0  1746.266667  1689.0  1721.0  1882.0    15
45 to 54 years         27336.0  1822.400000  1764.0  1802.0  1930.0    15
55 to 64 years         24968.0  1664.533333  1603.0  1651.0  1755.0    15
65 years old and over  15724.0  1048.266667  1005.0  1036.0  1121.0    15

Overall,
Sum :  131571.0
Mean :  1461.9
Min/median/max : 858.0 / 1628.0 / 1930.0
Skewnewss :  -0.6045165653686267
Total size :  90
2019

Grab the dataset only in Canada
       REF_DATE     GEO                                             Sector  \
79467      2019  Canada                      Total non-profit institutions
79474      2019  Canada                      Total non-profit institutions
79481      2019  Canada                      Total non-profit institutions
79488      2019  Canada                      Total non-profit institutions
79495      2019  Canada                      Total non-profit institutions
79502      2019  Canada                      Total non-profit institutions
79593      2019  Canada  Total non-profit institutions excluding govern...
79600      2019  Canada  Total non-profit institutions excluding govern...
79607      2019  Canada  Total non-profit institutions excluding govern...
79614      2019  Canada  Total non-profit institutions excluding govern...
79621      2019  Canada  Total non-profit institutions excluding govern...
79628      2019  Canada  Total non-profit institutions excluding govern...
79719      2019  Canada  Non-profit institutions serving households (co...
79726      2019  Canada  Non-profit institutions serving households (co...
79733      2019  Canada  Non-profit institutions serving households (co...
79740      2019  Canada  Non-profit institutions serving households (co...
79747      2019  Canada  Non-profit institutions serving households (co...
79754      2019  Canada  Non-profit institutions serving households (co...
79845      2019  Canada                   Business non-profit institutions
79852      2019  Canada                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
79467         15 to 24 years  Average annual hours worked  Hours
79474         25 to 34 years  Average annual hours worked  Hours
79481         35 to 44 years  Average annual hours worked  Hours
79488         45 to 54 years  Average annual hours worked  Hours
79495         55 to 64 years  Average annual hours worked  Hours
79502  65 years old and over  Average annual hours worked  Hours
79593         15 to 24 years  Average annual hours worked  Hours
79600         25 to 34 years  Average annual hours worked  Hours
79607         35 to 44 years  Average annual hours worked  Hours
79614         45 to 54 years  Average annual hours worked  Hours
79621         55 to 64 years  Average annual hours worked  Hours
79628  65 years old and over  Average annual hours worked  Hours
79719         15 to 24 years  Average annual hours worked  Hours
79726         25 to 34 years  Average annual hours worked  Hours
79733         35 to 44 years  Average annual hours worked  Hours
79740         45 to 54 years  Average annual hours worked  Hours
79747         55 to 64 years  Average annual hours worked  Hours
79754  65 years old and over  Average annual hours worked  Hours
79845         15 to 24 years  Average annual hours worked  Hours
79852         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
79467         units   914.0
79474         units  1548.0
79481         units  1708.0
79488         units  1801.0
79495         units  1654.0
79502         units  1036.0
79593         units   875.0
79600         units  1601.0
79607         units  1730.0
79614         units  1809.0
79621         units  1646.0
79628         units  1032.0
79719         units   874.0
79726         units  1560.0
79733         units  1688.0
79740         units  1772.0
79747         units  1612.0
79754         units  1011.0
79845         units   878.0
79852         units  1725.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 79467 to 97646
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Canada
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         13539.0   902.600000   861.0   898.0   973.0    15
25 to 34 years         23812.0  1587.466667  1515.0  1567.0  1725.0    15
35 to 44 years         25953.0  1730.200000  1651.0  1708.0  1864.0    15
45 to 54 years         27249.0  1816.600000  1733.0  1801.0  1933.0    15
55 to 64 years         24974.0  1664.933333  1585.0  1654.0  1756.0    15
65 years old and over  15832.0  1055.466667  1004.0  1046.0  1133.0    15

Overall,
Sum :  131359.0
Mean :  1459.5444444444445
Min/median/max : 861.0 / 1623.0 / 1933.0
Skewnewss :  -0.5986113111025179
Total size :  90
2013

Grab the dataset only in Canada
       REF_DATE     GEO                                             Sector  \
26463      2013  Canada                      Total non-profit institutions
26470      2013  Canada                      Total non-profit institutions
26589      2013  Canada  Total non-profit institutions excluding govern...
26596      2013  Canada  Total non-profit institutions excluding govern...
26715      2013  Canada  Non-profit institutions serving households (co...
26722      2013  Canada  Non-profit institutions serving households (co...
26841      2013  Canada                   Business non-profit institutions
26848      2013  Canada                   Business non-profit institutions
26967      2013  Canada                 Government non-profit institutions
26974      2013  Canada                 Government non-profit institutions
35283      2014  Canada                      Total non-profit institutions
35290      2014  Canada                      Total non-profit institutions
35409      2014  Canada  Total non-profit institutions excluding govern...
35416      2014  Canada  Total non-profit institutions excluding govern...
35535      2014  Canada  Non-profit institutions serving households (co...
35542      2014  Canada  Non-profit institutions serving households (co...
35661      2014  Canada                   Business non-profit institutions
35668      2014  Canada                   Business non-profit institutions
35787      2014  Canada                 Government non-profit institutions
35794      2014  Canada                 Government non-profit institutions

        Characteristics                   Indicators    UOM SCALAR_FACTOR  \
26463    Male employees  Average annual hours worked  Hours         units
26470  Female employees  Average annual hours worked  Hours         units
26589    Male employees  Average annual hours worked  Hours         units
26596  Female employees  Average annual hours worked  Hours         units
26715    Male employees  Average annual hours worked  Hours         units
26722  Female employees  Average annual hours worked  Hours         units
26841    Male employees  Average annual hours worked  Hours         units
26848  Female employees  Average annual hours worked  Hours         units
26967    Male employees  Average annual hours worked  Hours         units
26974  Female employees  Average annual hours worked  Hours         units
35283    Male employees  Average annual hours worked  Hours         units
35290  Female employees  Average annual hours worked  Hours         units
35409    Male employees  Average annual hours worked  Hours         units
35416  Female employees  Average annual hours worked  Hours         units
35535    Male employees  Average annual hours worked  Hours         units
35542  Female employees  Average annual hours worked  Hours         units
35661    Male employees  Average annual hours worked  Hours         units
35668  Female employees  Average annual hours worked  Hours         units
35787    Male employees  Average annual hours worked  Hours         units
35794  Female employees  Average annual hours worked  Hours         units

        VALUE
26463  1622.0
26470  1543.0
26589  1662.0
26596  1511.0
26715  1642.0
26722  1495.0
26841  1702.0
26848  1577.0
26967  1597.0
26974  1557.0
35283  1611.0
35290  1537.0
35409  1655.0
35416  1509.0
35535  1637.0
35542  1495.0
35661  1694.0
35668  1564.0
35787  1583.0
35794  1550.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 26463 to 44614
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         30 non-null     int64
 1   GEO              30 non-null     object
 2   Sector           30 non-null     object
 3   Characteristics  30 non-null     object
 4   Indicators       30 non-null     object
 5   UOM              30 non-null     object
 6   SCALAR_FACTOR    30 non-null     object
 7   VALUE            30 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.1+ KB
None

Grab the dataset only in Canada
                      sum    mean    amin  median    amax  size
Characteristics
Female employees  23010.0  1534.0  1492.0  1539.0  1579.0    15
Male employees    24621.0  1641.4  1583.0  1637.0  1720.0    15

Overall,
Sum :  47631.0
Mean :  1587.7
Min/median/max : 1492.0 / 1581.0 / 1720.0
Skewnewss :  0.2891902560473917
Total size :  30
2016

Grab the dataset only in Canada
       REF_DATE     GEO                                             Sector  \
52923      2016  Canada                      Total non-profit institutions
52930      2016  Canada                      Total non-profit institutions
53049      2016  Canada  Total non-profit institutions excluding govern...
53056      2016  Canada  Total non-profit institutions excluding govern...
53175      2016  Canada  Non-profit institutions serving households (co...
53182      2016  Canada  Non-profit institutions serving households (co...
53301      2016  Canada                   Business non-profit institutions
53308      2016  Canada                   Business non-profit institutions
53427      2016  Canada                 Government non-profit institutions

Min/median/max : 1250.0 / 1542.0 / 1776.0
Skewnewss :  -0.23893215242347804
Total size :  45
2016

Grab the dataset only in Canada
       REF_DATE     GEO                                             Sector  \
52979      2016  Canada                      Total non-profit institutions
52986      2016  Canada                      Total non-profit institutions
53000      2016  Canada                      Total non-profit institutions
53105      2016  Canada  Total non-profit institutions excluding govern...
53112      2016  Canada  Total non-profit institutions excluding govern...
53126      2016  Canada  Total non-profit institutions excluding govern...
53231      2016  Canada  Non-profit institutions serving households (co...
53238      2016  Canada  Non-profit institutions serving households (co...
53252      2016  Canada  Non-profit institutions serving households (co...
53357      2016  Canada                   Business non-profit institutions
53364      2016  Canada                   Business non-profit institutions
53378      2016  Canada                   Business non-profit institutions
53483      2016  Canada                 Government non-profit institutions
53490      2016  Canada                 Government non-profit institutions
53504      2016  Canada                 Government non-profit institutions
61799      2017  Canada                      Total non-profit institutions
61806      2017  Canada                      Total non-profit institutions
61820      2017  Canada                      Total non-profit institutions
61925      2017  Canada  Total non-profit institutions excluding govern...
61932      2017  Canada  Total non-profit institutions excluding govern...

                    Characteristics                   Indicators    UOM  \
52979  High school diploma and less  Average annual hours worked  Hours
52986             Trade certificate  Average annual hours worked  Hours
53000  University degree and higher  Average annual hours worked  Hours
53105  High school diploma and less  Average annual hours worked  Hours
53112             Trade certificate  Average annual hours worked  Hours
53126  University degree and higher  Average annual hours worked  Hours
53231  High school diploma and less  Average annual hours worked  Hours
53238             Trade certificate  Average annual hours worked  Hours
53252  University degree and higher  Average annual hours worked  Hours
53357  High school diploma and less  Average annual hours worked  Hours
53364             Trade certificate  Average annual hours worked  Hours
53378  University degree and higher  Average annual hours worked  Hours
53483  High school diploma and less  Average annual hours worked  Hours
53490             Trade certificate  Average annual hours worked  Hours
53504  University degree and higher  Average annual hours worked  Hours
61799  High school diploma and less  Average annual hours worked  Hours
61806             Trade certificate  Average annual hours worked  Hours
61820  University degree and higher  Average annual hours worked  Hours
61925  High school diploma and less  Average annual hours worked  Hours
61932             Trade certificate  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
52979         units  1300.0
52986         units  1541.0
53000         units  1661.0
53105         units  1280.0
53112         units  1544.0
53126         units  1692.0
53231         units  1230.0
53238         units  1473.0
53252         units  1672.0
53357         units  1402.0
53364         units  1731.0
53378         units  1762.0
53483         units  1317.0
53490         units  1541.0
53504         units  1647.0
61799         units  1289.0
61806         units  1532.0
61820         units  1648.0
61925         units  1267.0
61932         units  1521.0
<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 52979 to 71144
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         45 non-null     int64
 1   GEO              45 non-null     object
 2   Sector           45 non-null     object
 3   Characteristics  45 non-null     object
 4   Indicators       45 non-null     object
 5   UOM              45 non-null     object
 6   SCALAR_FACTOR    45 non-null     object
 7   VALUE            45 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 3.2+ KB
None

Grab the dataset only in Canada
                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  19520.0  1301.333333  1213.0  1297.0  1403.0
Trade certificate             23376.0  1558.400000  1453.0  1541.0  1731.0
University degree and higher  25263.0  1684.200000  1633.0  1672.0  1766.0

                              size
Characteristics
High school diploma and less    15
Trade certificate               15
University degree and higher    15

Overall,
Sum :  68159.0
Mean :  1514.6444444444444
Min/median/max : 1213.0 / 1541.0 / 1766.0
Skewnewss :  -0.3039077605248043
Total size :  45
2019

Grab the dataset only in Canada
       REF_DATE     GEO                                             Sector  \
79439      2019  Canada                      Total non-profit institutions
79446      2019  Canada                      Total non-profit institutions
79460      2019  Canada                      Total non-profit institutions
79565      2019  Canada  Total non-profit institutions excluding govern...
79572      2019  Canada  Total non-profit institutions excluding govern...
79586      2019  Canada  Total non-profit institutions excluding govern...
79691      2019  Canada  Non-profit institutions serving households (co...
79698      2019  Canada  Non-profit institutions serving households (co...
79712      2019  Canada  Non-profit institutions serving households (co...
79817      2019  Canada                   Business non-profit institutions
79824      2019  Canada                   Business non-profit institutions
79838      2019  Canada                   Business non-profit institutions
79943      2019  Canada                 Government non-profit institutions
79950      2019  Canada                 Government non-profit institutions
79964      2019  Canada                 Government non-profit institutions
88259      2020  Canada                      Total non-profit institutions
88266      2020  Canada                      Total non-profit institutions
88280      2020  Canada                      Total non-profit institutions
88385      2020  Canada  Total non-profit institutions excluding govern...
88392      2020  Canada  Total non-profit institutions excluding govern...

                    Characteristics                   Indicators    UOM  \
79439  High school diploma and less  Average annual hours worked  Hours
79446             Trade certificate  Average annual hours worked  Hours
79460  University degree and higher  Average annual hours worked  Hours
79565  High school diploma and less  Average annual hours worked  Hours
79572             Trade certificate  Average annual hours worked  Hours
79586  University degree and higher  Average annual hours worked  Hours
79691  High school diploma and less  Average annual hours worked  Hours
79698             Trade certificate  Average annual hours worked  Hours
79712  University degree and higher  Average annual hours worked  Hours
79817  High school diploma and less  Average annual hours worked  Hours
79824             Trade certificate  Average annual hours worked  Hours
79838  University degree and higher  Average annual hours worked  Hours
79943  High school diploma and less  Average annual hours worked  Hours
79950             Trade certificate  Average annual hours worked  Hours
79964  University degree and higher  Average annual hours worked  Hours
88259  High school diploma and less  Average annual hours worked  Hours
88266             Trade certificate  Average annual hours worked  Hours
88280  University degree and higher  Average annual hours worked  Hours
88385  High school diploma and less  Average annual hours worked  Hours
88392             Trade certificate  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
79439         units  1287.0
79446         units  1546.0
79460         units  1649.0
79565         units  1268.0
79572         units  1520.0
79586         units  1686.0
79691         units  1218.0
79698         units  1450.0
79712         units  1661.0
79817         units  1397.0
79824         units  1707.0
79838         units  1769.0
79943         units  1303.0
79950         units  1556.0
79964         units  1632.0
88259         units  1282.0
88266         units  1519.0
88280         units  1638.0
88385         units  1256.0
88392         units  1493.0
<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 79439 to 97604
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         45 non-null     int64
 1   GEO              45 non-null     object
 2   Sector           45 non-null     object
 3   Characteristics  45 non-null     object
 4   Indicators       45 non-null     object
 5   UOM              45 non-null     object
 6   SCALAR_FACTOR    45 non-null     object
 7   VALUE            45 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 3.2+ KB
None

Grab the dataset only in Canada
                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  19456.0  1297.066667  1211.0  1287.0  1397.0
Trade certificate             23189.0  1545.933333  1432.0  1528.0  1707.0
University degree and higher  25185.0  1679.000000  1627.0  1671.0  1769.0

                              size
Characteristics
High school diploma and less    15
Trade certificate               15
University degree and higher    15

Overall,
Sum :  67830.0
Mean :  1507.3333333333333
Min/median/max : 1211.0 / 1528.0 / 1769.0
Skewnewss :  -0.2637605275689323
Total size :  45
2013

Grab the dataset only in Canada
       REF_DATE     GEO                                             Sector  \
26519      2013  Canada                      Total non-profit institutions
26526      2013  Canada                      Total non-profit institutions
26540      2013  Canada                      Total non-profit institutions
26645      2013  Canada  Total non-profit institutions excluding govern...
26652      2013  Canada  Total non-profit institutions excluding govern...
26666      2013  Canada  Total non-profit institutions excluding govern...
26771      2013  Canada  Non-profit institutions serving households (co...
26778      2013  Canada  Non-profit institutions serving households (co...
26792      2013  Canada  Non-profit institutions serving households (co...
26897      2013  Canada                   Business non-profit institutions
26904      2013  Canada                   Business non-profit institutions
26918      2013  Canada                   Business non-profit institutions
27023      2013  Canada                 Government non-profit institutions
27030      2013  Canada                 Government non-profit institutions
27044      2013  Canada                 Government non-profit institutions
35339      2014  Canada                      Total non-profit institutions
35346      2014  Canada                      Total non-profit institutions
35360      2014  Canada                      Total non-profit institutions
35465      2014  Canada  Total non-profit institutions excluding govern...
35472      2014  Canada  Total non-profit institutions excluding govern...

                    Characteristics                   Indicators    UOM  \
26519  High school diploma and less  Average annual hours worked  Hours
26526             Trade certificate  Average annual hours worked  Hours
26540  University degree and higher  Average annual hours worked  Hours
26645  High school diploma and less  Average annual hours worked  Hours
26652             Trade certificate  Average annual hours worked  Hours
26666  University degree and higher  Average annual hours worked  Hours
26771  High school diploma and less  Average annual hours worked  Hours
26778             Trade certificate  Average annual hours worked  Hours
26792  University degree and higher  Average annual hours worked  Hours
26897  High school diploma and less  Average annual hours worked  Hours
26904             Trade certificate  Average annual hours worked  Hours
26918  University degree and higher  Average annual hours worked  Hours
27023  High school diploma and less  Average annual hours worked  Hours
27030             Trade certificate  Average annual hours worked  Hours
27044  University degree and higher  Average annual hours worked  Hours
35339  High school diploma and less  Average annual hours worked  Hours
35346             Trade certificate  Average annual hours worked  Hours
35360  University degree and higher  Average annual hours worked  Hours
35465  High school diploma and less  Average annual hours worked  Hours
35472             Trade certificate  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
26519         units  1313.0
26526         units  1545.0
26540         units  1662.0
26645         units  1299.0
26652         units  1567.0
26666         units  1713.0
26771         units  1253.0
26778         units  1501.0
26792         units  1697.0
26897         units  1408.0
26904         units  1740.0
26918         units  1774.0
27023         units  1324.0
27030         units  1536.0
27044         units  1639.0
35339         units  1307.0
35346         units  1542.0
35360         units  1651.0
35465         units  1293.0
35472         units  1562.0
<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 26519 to 44684
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         45 non-null     int64
 1   GEO              45 non-null     object
 2   Sector           45 non-null     object
 3   Characteristics  45 non-null     object
 4   Indicators       45 non-null     object
 5   UOM              45 non-null     object
 6   SCALAR_FACTOR    45 non-null     object
 7   VALUE            45 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 3.2+ KB
None

Grab the dataset only in Canada
                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  19753.0  1316.866667  1250.0  1310.0  1418.0
Trade certificate             23646.0  1576.400000  1492.0  1542.0  1758.0
University degree and higher  25389.0  1692.600000  1625.0  1695.0  1776.0

                              size
Characteristics
High school diploma and less    15
Trade certificate               15
University degree and higher    15

Overall,
Sum :  68788.0
Mean :  1528.6222222222223
Min/median/max : 1250.0 / 1542.0 / 1776.0
Skewnewss :  -0.23893215242347804
Total size :  45
2016

Grab the dataset only in Canada
       REF_DATE     GEO                                             Sector  \
52937      2016  Canada                      Total non-profit institutions
52944      2016  Canada                      Total non-profit institutions
53063      2016  Canada  Total non-profit institutions excluding govern...
53070      2016  Canada  Total non-profit institutions excluding govern...
53189      2016  Canada  Non-profit institutions serving households (co...
53196      2016  Canada  Non-profit institutions serving households (co...
53315      2016  Canada                   Business non-profit institutions
53322      2016  Canada                   Business non-profit institutions
53441      2016  Canada                 Government non-profit institutions
53448      2016  Canada                 Government non-profit institutions
61757      2017  Canada                      Total non-profit institutions
61764      2017  Canada                      Total non-profit institutions
61883      2017  Canada  Total non-profit institutions excluding govern...
61890      2017  Canada  Total non-profit institutions excluding govern...
62009      2017  Canada  Non-profit institutions serving households (co...
62016      2017  Canada  Non-profit institutions serving households (co...
62135      2017  Canada                   Business non-profit institutions
62142      2017  Canada                   Business non-profit institutions
62261      2017  Canada                 Government non-profit institutions
62268      2017  Canada                 Government non-profit institutions

               Characteristics                   Indicators    UOM  \
52937      Immigrant employees  Average annual hours worked  Hours
52944  Non-immigrant employees  Average annual hours worked  Hours
53063      Immigrant employees  Average annual hours worked  Hours
53070  Non-immigrant employees  Average annual hours worked  Hours
53189      Immigrant employees  Average annual hours worked  Hours
53196  Non-immigrant employees  Average annual hours worked  Hours
53315      Immigrant employees  Average annual hours worked  Hours
53322  Non-immigrant employees  Average annual hours worked  Hours
53441      Immigrant employees  Average annual hours worked  Hours
53448  Non-immigrant employees  Average annual hours worked  Hours
61757      Immigrant employees  Average annual hours worked  Hours
61764  Non-immigrant employees  Average annual hours worked  Hours
61883      Immigrant employees  Average annual hours worked  Hours
61890  Non-immigrant employees  Average annual hours worked  Hours
62009      Immigrant employees  Average annual hours worked  Hours
62016  Non-immigrant employees  Average annual hours worked  Hours
62135      Immigrant employees  Average annual hours worked  Hours
62142  Non-immigrant employees  Average annual hours worked  Hours
62261      Immigrant employees  Average annual hours worked  Hours
62268  Non-immigrant employees  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
52937         units  1580.0
52944         units  1559.0
53063         units  1564.0
53070         units  1541.0
53189         units  1531.0
53196         units  1516.0
53315         units  1665.0
53322         units  1621.0
53441         units  1588.0
53448         units  1569.0
61757         units  1568.0
61764         units  1549.0
61883         units  1551.0
61890         units  1532.0
62009         units  1518.0
62016         units  1505.0
62135         units  1653.0
62142         units  1620.0
62261         units  1577.0
62268         units  1558.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 52937 to 71088
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         30 non-null     int64
 1   GEO              30 non-null     object
 2   Sector           30 non-null     object
 3   Characteristics  30 non-null     object
 4   Indicators       30 non-null     object
 5   UOM              30 non-null     object
 6   SCALAR_FACTOR    30 non-null     object
 7   VALUE            30 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.1+ KB
None

Grab the dataset only in Canada
                             sum         mean    amin  median    amax  size
Characteristics
Immigrant employees      23724.0  1581.600000  1518.0  1577.0  1665.0    15
Non-immigrant employees  23402.0  1560.133333  1505.0  1558.0  1627.0    15

Overall,
Sum :  47126.0
Mean :  1570.8666666666666
Min/median/max : 1505.0 / 1564.0 / 1665.0
Skewnewss :  0.6958752542272613
Total size :  30
2019

Grab the dataset only in Canada
       REF_DATE     GEO                                             Sector  \
79439      2019  Canada                      Total non-profit institutions
79446      2019  Canada                      Total non-profit institutions

Panda Profiling for Final Result for GEO = Canada

In [105]:
# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

Filtering only Manitoba.

Only finished "Average annual hours worked".

In [106]:
# -- Manitoba                     767802.0    710.927778    915.637659  1080

ProCode = 3

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

2013

Grab the dataset only in Manitoba
       REF_DATE       GEO                                             Sector  \
30957      2013  Manitoba                      Total non-profit institutions
30964      2013  Manitoba                      Total non-profit institutions
30971      2013  Manitoba                      Total non-profit institutions
30978      2013  Manitoba                      Total non-profit institutions
30985      2013  Manitoba                      Total non-profit institutions
30992      2013  Manitoba                      Total non-profit institutions
31083      2013  Manitoba  Total non-profit institutions excluding govern...
31090      2013  Manitoba  Total non-profit institutions excluding govern...
31097      2013  Manitoba  Total non-profit institutions excluding govern...
31104      2013  Manitoba  Total non-profit institutions excluding govern...
31111      2013  Manitoba  Total non-profit institutions excluding govern...
31118      2013  Manitoba  Total non-profit institutions excluding govern...
31209      2013  Manitoba  Non-profit institutions serving households (co...
31216      2013  Manitoba  Non-profit institutions serving households (co...
31223      2013  Manitoba  Non-profit institutions serving households (co...
31230      2013  Manitoba  Non-profit institutions serving households (co...
31237      2013  Manitoba  Non-profit institutions serving households (co...
31244      2013  Manitoba  Non-profit institutions serving households (co...
31335      2013  Manitoba                   Business non-profit institutions
31342      2013  Manitoba                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
30957         15 to 24 years  Average annual hours worked  Hours
30964         25 to 34 years  Average annual hours worked  Hours
30971         35 to 44 years  Average annual hours worked  Hours
30978         45 to 54 years  Average annual hours worked  Hours
30985         55 to 64 years  Average annual hours worked  Hours
30992  65 years old and over  Average annual hours worked  Hours
31083         15 to 24 years  Average annual hours worked  Hours
31090         25 to 34 years  Average annual hours worked  Hours
31097         35 to 44 years  Average annual hours worked  Hours
31104         45 to 54 years  Average annual hours worked  Hours
31111         55 to 64 years  Average annual hours worked  Hours
31118  65 years old and over  Average annual hours worked  Hours
31209         15 to 24 years  Average annual hours worked  Hours
31216         25 to 34 years  Average annual hours worked  Hours
31223         35 to 44 years  Average annual hours worked  Hours
31230         45 to 54 years  Average annual hours worked  Hours
31237         55 to 64 years  Average annual hours worked  Hours
31244  65 years old and over  Average annual hours worked  Hours
31335         15 to 24 years  Average annual hours worked  Hours
31342         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
30957         units   965.0
30964         units  1545.0
30971         units  1698.0
30978         units  1781.0
30985         units  1634.0
30992         units  1034.0
31083         units   921.0
31090         units  1620.0
31097         units  1724.0
31104         units  1805.0
31111         units  1622.0
31118         units  1048.0
31209         units   921.0
31216         units  1593.0
31223         units  1699.0
31230         units  1784.0
31237         units  1610.0
31244         units  1039.0
31335         units   921.0
31342         units  1759.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 30957 to 49136
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Manitoba
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         14317.0   954.466667   897.0   958.0  1019.0    15
25 to 34 years         24492.0  1632.800000  1513.0  1614.0  1778.0    15
35 to 44 years         26560.0  1770.666667  1687.0  1754.0  1901.0    15
45 to 54 years         27584.0  1838.933333  1771.0  1827.0  1962.0    15
55 to 64 years         25102.0  1673.466667  1610.0  1691.0  1737.0    15
65 years old and over  16135.0  1075.666667  1026.0  1062.0  1149.0    15

Overall,
Sum :  134190.0
Mean :  1491.0
Min/median/max : 897.0 / 1643.5 / 1962.0
Skewnewss :  -0.5815428634138992
Total size :  90
2016

Grab the dataset only in Manitoba
       REF_DATE       GEO                                             Sector  \
57417      2016  Manitoba                      Total non-profit institutions
57424      2016  Manitoba                      Total non-profit institutions
57431      2016  Manitoba                      Total non-profit institutions
57438      2016  Manitoba                      Total non-profit institutions
57445      2016  Manitoba                      Total non-profit institutions
57452      2016  Manitoba                      Total non-profit institutions
57543      2016  Manitoba  Total non-profit institutions excluding govern...
57550      2016  Manitoba  Total non-profit institutions excluding govern...
57557      2016  Manitoba  Total non-profit institutions excluding govern...
57564      2016  Manitoba  Total non-profit institutions excluding govern...
57571      2016  Manitoba  Total non-profit institutions excluding govern...
57578      2016  Manitoba  Total non-profit institutions excluding govern...
57669      2016  Manitoba  Non-profit institutions serving households (co...
57676      2016  Manitoba  Non-profit institutions serving households (co...
57683      2016  Manitoba  Non-profit institutions serving households (co...
57690      2016  Manitoba  Non-profit institutions serving households (co...
57697      2016  Manitoba  Non-profit institutions serving households (co...
57704      2016  Manitoba  Non-profit institutions serving households (co...
57795      2016  Manitoba                   Business non-profit institutions
57802      2016  Manitoba                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
57417         15 to 24 years  Average annual hours worked  Hours
57424         25 to 34 years  Average annual hours worked  Hours
57431         35 to 44 years  Average annual hours worked  Hours
57438         45 to 54 years  Average annual hours worked  Hours
57445         55 to 64 years  Average annual hours worked  Hours
57452  65 years old and over  Average annual hours worked  Hours
57543         15 to 24 years  Average annual hours worked  Hours
57550         25 to 34 years  Average annual hours worked  Hours
57557         35 to 44 years  Average annual hours worked  Hours
57564         45 to 54 years  Average annual hours worked  Hours
57571         55 to 64 years  Average annual hours worked  Hours
57578  65 years old and over  Average annual hours worked  Hours
57669         15 to 24 years  Average annual hours worked  Hours
57676         25 to 34 years  Average annual hours worked  Hours
57683         35 to 44 years  Average annual hours worked  Hours
57690         45 to 54 years  Average annual hours worked  Hours
57697         55 to 64 years  Average annual hours worked  Hours
57704  65 years old and over  Average annual hours worked  Hours
57795         15 to 24 years  Average annual hours worked  Hours
57802         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
57417         units   962.0
57424         units  1565.0
57431         units  1728.0
57438         units  1803.0
57445         units  1659.0
57452         units  1052.0
57543         units   941.0
57550         units  1629.0
57557         units  1757.0
57564         units  1818.0
57571         units  1667.0
57578         units  1074.0
57669         units   944.0
57676         units  1603.0
57683         units  1732.0
57690         units  1794.0
57697         units  1657.0
57704         units  1065.0
57795         units   926.0
57802         units  1757.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 57417 to 75596
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Manitoba
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         14162.0   944.133333   906.0   944.0   979.0    15
25 to 34 years         23936.0  1595.733333  1512.0  1567.0  1757.0    15
35 to 44 years         26218.0  1747.866667  1685.0  1728.0  1908.0    15
45 to 54 years         27327.0  1821.800000  1766.0  1796.0  1964.0    15
55 to 64 years         24877.0  1658.466667  1612.0  1656.0  1740.0    15
65 years old and over  15640.0  1042.666667   951.0  1040.0  1127.0    15

Overall,
Sum :  132160.0
Mean :  1468.4444444444443
Min/median/max : 906.0 / 1634.0 / 1964.0
Skewnewss :  -0.5544798756700609
Total size :  90
2019

Grab the dataset only in Manitoba
       REF_DATE       GEO                                             Sector  \
83877      2019  Manitoba                      Total non-profit institutions
83884      2019  Manitoba                      Total non-profit institutions
83891      2019  Manitoba                      Total non-profit institutions
83898      2019  Manitoba                      Total non-profit institutions
83905      2019  Manitoba                      Total non-profit institutions
83912      2019  Manitoba                      Total non-profit institutions
84003      2019  Manitoba  Total non-profit institutions excluding govern...
84010      2019  Manitoba  Total non-profit institutions excluding govern...
84017      2019  Manitoba  Total non-profit institutions excluding govern...
84024      2019  Manitoba  Total non-profit institutions excluding govern...
84031      2019  Manitoba  Total non-profit institutions excluding govern...
84038      2019  Manitoba  Total non-profit institutions excluding govern...
84129      2019  Manitoba  Non-profit institutions serving households (co...
84136      2019  Manitoba  Non-profit institutions serving households (co...
84143      2019  Manitoba  Non-profit institutions serving households (co...
84150      2019  Manitoba  Non-profit institutions serving households (co...
84157      2019  Manitoba  Non-profit institutions serving households (co...
84164      2019  Manitoba  Non-profit institutions serving households (co...
84255      2019  Manitoba                   Business non-profit institutions
84262      2019  Manitoba                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
83877         15 to 24 years  Average annual hours worked  Hours
83884         25 to 34 years  Average annual hours worked  Hours
83891         35 to 44 years  Average annual hours worked  Hours
83898         45 to 54 years  Average annual hours worked  Hours
83905         55 to 64 years  Average annual hours worked  Hours
83912  65 years old and over  Average annual hours worked  Hours
84003         15 to 24 years  Average annual hours worked  Hours
84010         25 to 34 years  Average annual hours worked  Hours
84017         35 to 44 years  Average annual hours worked  Hours
84024         45 to 54 years  Average annual hours worked  Hours
84031         55 to 64 years  Average annual hours worked  Hours
84038  65 years old and over  Average annual hours worked  Hours
84129         15 to 24 years  Average annual hours worked  Hours
84136         25 to 34 years  Average annual hours worked  Hours
84143         35 to 44 years  Average annual hours worked  Hours
84150         45 to 54 years  Average annual hours worked  Hours
84157         55 to 64 years  Average annual hours worked  Hours
84164  65 years old and over  Average annual hours worked  Hours
84255         15 to 24 years  Average annual hours worked  Hours
84262         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
83877         units   960.0
83884         units  1543.0
83891         units  1710.0
83898         units  1813.0
83905         units  1659.0
83912         units  1044.0
84003         units   926.0
84010         units  1571.0
84017         units  1713.0
84024         units  1801.0
84031         units  1637.0
84038         units   967.0
84129         units   928.0
84136         units  1552.0
84143         units  1690.0
84150         units  1785.0
84157         units  1627.0
84164         units   952.0
84255         units   915.0
84262         units  1661.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 83877 to 102056
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Manitoba
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         14250.0   950.000000   898.0   953.0   990.0    15
25 to 34 years         23572.0  1571.466667  1500.0  1558.0  1670.0    15
35 to 44 years         26097.0  1739.800000  1680.0  1713.0  1869.0    15
45 to 54 years         27499.0  1833.266667  1785.0  1818.0  1927.0    15
55 to 64 years         25094.0  1672.933333  1627.0  1669.0  1728.0    15
65 years old and over  15762.0  1050.800000   952.0  1057.0  1121.0    15

Overall,
Sum :  132274.0
Mean :  1469.7111111111112
Min/median/max : 898.0 / 1641.5 / 1927.0
Skewnewss :  -0.5575412160390797
Total size :  90
2013

Grab the dataset only in Manitoba
       REF_DATE       GEO                                             Sector  \
30873      2013  Manitoba                      Total non-profit institutions
30880      2013  Manitoba                      Total non-profit institutions
30999      2013  Manitoba  Total non-profit institutions excluding govern...
31006      2013  Manitoba  Total non-profit institutions excluding govern...
31125      2013  Manitoba  Non-profit institutions serving households (co...
31132      2013  Manitoba  Non-profit institutions serving households (co...
31251      2013  Manitoba                   Business non-profit institutions
31258      2013  Manitoba                   Business non-profit institutions
31377      2013  Manitoba                 Government non-profit institutions
31384      2013  Manitoba                 Government non-profit institutions
39693      2014  Manitoba                      Total non-profit institutions
39700      2014  Manitoba                      Total non-profit institutions
39819      2014  Manitoba  Total non-profit institutions excluding govern...
39826      2014  Manitoba  Total non-profit institutions excluding govern...
39945      2014  Manitoba  Non-profit institutions serving households (co...
39952      2014  Manitoba  Non-profit institutions serving households (co...
40071      2014  Manitoba                   Business non-profit institutions
40078      2014  Manitoba                   Business non-profit institutions
40197      2014  Manitoba                 Government non-profit institutions
40204      2014  Manitoba                 Government non-profit institutions

        Characteristics                   Indicators    UOM SCALAR_FACTOR  \
30873    Male employees  Average annual hours worked  Hours         units
30880  Female employees  Average annual hours worked  Hours         units
30999    Male employees  Average annual hours worked  Hours         units
31006  Female employees  Average annual hours worked  Hours         units
31125    Male employees  Average annual hours worked  Hours         units
31132  Female employees  Average annual hours worked  Hours         units
31251    Male employees  Average annual hours worked  Hours         units
31258  Female employees  Average annual hours worked  Hours         units
31377    Male employees  Average annual hours worked  Hours         units
31384  Female employees  Average annual hours worked  Hours         units
39693    Male employees  Average annual hours worked  Hours         units
39700  Female employees  Average annual hours worked  Hours         units
39819    Male employees  Average annual hours worked  Hours         units
39826  Female employees  Average annual hours worked  Hours         units
39945    Male employees  Average annual hours worked  Hours         units
39952  Female employees  Average annual hours worked  Hours         units
40071    Male employees  Average annual hours worked  Hours         units
40078  Female employees  Average annual hours worked  Hours         units
40197    Male employees  Average annual hours worked  Hours         units
40204  Female employees  Average annual hours worked  Hours         units

        VALUE
30873  1610.0
30880  1534.0
30999  1647.0
31006  1463.0
31125  1635.0
31132  1456.0
31251  1690.0
31258  1515.0
31377  1589.0
31384  1563.0
39693  1635.0
39700  1580.0
39819  1659.0
39826  1485.0
39945  1646.0
39952  1477.0
40071  1704.0
40078  1536.0
40197  1622.0
40204  1618.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 30873 to 49024
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         30 non-null     int64
 1   GEO              30 non-null     object
 2   Sector           30 non-null     object
 3   Characteristics  30 non-null     object
 4   Indicators       30 non-null     object
 5   UOM              30 non-null     object
 6   SCALAR_FACTOR    30 non-null     object
 7   VALUE            30 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.1+ KB
None

Grab the dataset only in Manitoba
                      sum         mean    amin  median    amax  size
Characteristics
Female employees  23034.0  1535.600000  1456.0  1534.0  1618.0    15
Male employees    24835.0  1655.666667  1589.0  1647.0  1710.0    15

Overall,
Sum :  47869.0
Mean :  1595.6333333333334
Min/median/max : 1456.0 / 1614.0 / 1710.0
Skewnewss :  -0.2160921306545881
Total size :  30
2016

Grab the dataset only in Manitoba
       REF_DATE       GEO                                             Sector  \
57333      2016  Manitoba                      Total non-profit institutions
57340      2016  Manitoba                      Total non-profit institutions
57459      2016  Manitoba  Total non-profit institutions excluding govern...
57466      2016  Manitoba  Total non-profit institutions excluding govern...
57585      2016  Manitoba  Non-profit institutions serving households (co...
57592      2016  Manitoba  Non-profit institutions serving households (co...

Panda Profiling for Final Result for Manitoba

In [107]:
# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

Filtering only New Brunswick.

Only finished "Average annual hours worked".

In [108]:
# -- New Brunswick                359320.0    332.703704    530.962762  1080

ProCode = 4

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

2013

Grab the dataset only in New Brunswick
       REF_DATE            GEO  \
29067      2013  New Brunswick
29074      2013  New Brunswick
29081      2013  New Brunswick
29088      2013  New Brunswick
29095      2013  New Brunswick
29102      2013  New Brunswick
29193      2013  New Brunswick
29200      2013  New Brunswick
29207      2013  New Brunswick
29214      2013  New Brunswick
29221      2013  New Brunswick
29228      2013  New Brunswick
29319      2013  New Brunswick
29326      2013  New Brunswick
29333      2013  New Brunswick
29340      2013  New Brunswick
29347      2013  New Brunswick
29354      2013  New Brunswick
29445      2013  New Brunswick
29452      2013  New Brunswick

                                                  Sector  \
29067                      Total non-profit institutions
29074                      Total non-profit institutions
29081                      Total non-profit institutions
29088                      Total non-profit institutions
29095                      Total non-profit institutions
29102                      Total non-profit institutions
29193  Total non-profit institutions excluding govern...
29200  Total non-profit institutions excluding govern...
29207  Total non-profit institutions excluding govern...
29214  Total non-profit institutions excluding govern...
29221  Total non-profit institutions excluding govern...
29228  Total non-profit institutions excluding govern...
29319  Non-profit institutions serving households (co...
29326  Non-profit institutions serving households (co...
29333  Non-profit institutions serving households (co...
29340  Non-profit institutions serving households (co...
29347  Non-profit institutions serving households (co...
29354  Non-profit institutions serving households (co...
29445                   Business non-profit institutions
29452                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
29067         15 to 24 years  Average annual hours worked  Hours
29074         25 to 34 years  Average annual hours worked  Hours
29081         35 to 44 years  Average annual hours worked  Hours
29088         45 to 54 years  Average annual hours worked  Hours
29095         55 to 64 years  Average annual hours worked  Hours
29102  65 years old and over  Average annual hours worked  Hours
29193         15 to 24 years  Average annual hours worked  Hours
29200         25 to 34 years  Average annual hours worked  Hours
29207         35 to 44 years  Average annual hours worked  Hours
29214         45 to 54 years  Average annual hours worked  Hours
29221         55 to 64 years  Average annual hours worked  Hours
29228  65 years old and over  Average annual hours worked  Hours
29319         15 to 24 years  Average annual hours worked  Hours
29326         25 to 34 years  Average annual hours worked  Hours
29333         35 to 44 years  Average annual hours worked  Hours
29340         45 to 54 years  Average annual hours worked  Hours
29347         55 to 64 years  Average annual hours worked  Hours
29354  65 years old and over  Average annual hours worked  Hours
29445         15 to 24 years  Average annual hours worked  Hours
29452         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
29067         units   958.0
29074         units  1711.0
29081         units  1908.0
29088         units  1922.0
29095         units  1716.0
29102         units  1020.0
29193         units   903.0
29200         units  1761.0
29207         units  1971.0
29214         units  1947.0
29221         units  1716.0
29228         units  1097.0
29319         units   899.0
29326         units  1732.0
29333         units  1945.0
29340         units  1908.0
29347         units  1716.0
29354         units  1086.0
29445         units   914.0
29452         units  1850.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 29067 to 47246
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in New Brunswick
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         13941.0   929.400000   861.0   912.0  1006.0    15
25 to 34 years         26060.0  1737.333333  1653.0  1732.0  1850.0    15
35 to 44 years         29148.0  1943.200000  1824.0  1945.0  2078.0    15
45 to 54 years         29173.0  1944.866667  1860.0  1922.0  2091.0    15
55 to 64 years         25741.0  1716.066667  1656.0  1716.0  1790.0    15
65 years old and over  16373.0  1091.533333   920.0  1097.0  1232.0    15

Overall,
Sum :  140436.0
Mean :  1560.4
Min/median/max : 861.0 / 1717.5 / 2091.0
Skewnewss :  -0.585718507481045
Total size :  90
2016

Grab the dataset only in New Brunswick
       REF_DATE            GEO  \
55527      2016  New Brunswick
55534      2016  New Brunswick
55541      2016  New Brunswick
55548      2016  New Brunswick
55555      2016  New Brunswick
55562      2016  New Brunswick
55653      2016  New Brunswick
55660      2016  New Brunswick
55667      2016  New Brunswick
55674      2016  New Brunswick
55681      2016  New Brunswick
55688      2016  New Brunswick
55779      2016  New Brunswick
55786      2016  New Brunswick
55793      2016  New Brunswick
55800      2016  New Brunswick
55807      2016  New Brunswick
55814      2016  New Brunswick
55905      2016  New Brunswick
55912      2016  New Brunswick

                                                  Sector  \
55527                      Total non-profit institutions
55534                      Total non-profit institutions
55541                      Total non-profit institutions
55548                      Total non-profit institutions
55555                      Total non-profit institutions
55562                      Total non-profit institutions
55653  Total non-profit institutions excluding govern...
55660  Total non-profit institutions excluding govern...
55667  Total non-profit institutions excluding govern...
55674  Total non-profit institutions excluding govern...
55681  Total non-profit institutions excluding govern...
55688  Total non-profit institutions excluding govern...
55779  Non-profit institutions serving households (co...
55786  Non-profit institutions serving households (co...
55793  Non-profit institutions serving households (co...
55800  Non-profit institutions serving households (co...
55807  Non-profit institutions serving households (co...
55814  Non-profit institutions serving households (co...
55905                   Business non-profit institutions
55912                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
55527         15 to 24 years  Average annual hours worked  Hours
55534         25 to 34 years  Average annual hours worked  Hours
55541         35 to 44 years  Average annual hours worked  Hours
55548         45 to 54 years  Average annual hours worked  Hours
55555         55 to 64 years  Average annual hours worked  Hours
55562  65 years old and over  Average annual hours worked  Hours
55653         15 to 24 years  Average annual hours worked  Hours
55660         25 to 34 years  Average annual hours worked  Hours
55667         35 to 44 years  Average annual hours worked  Hours
55674         45 to 54 years  Average annual hours worked  Hours
55681         55 to 64 years  Average annual hours worked  Hours
55688  65 years old and over  Average annual hours worked  Hours
55779         15 to 24 years  Average annual hours worked  Hours
55786         25 to 34 years  Average annual hours worked  Hours
55793         35 to 44 years  Average annual hours worked  Hours
55800         45 to 54 years  Average annual hours worked  Hours
55807         55 to 64 years  Average annual hours worked  Hours
55814  65 years old and over  Average annual hours worked  Hours
55905         15 to 24 years  Average annual hours worked  Hours
55912         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
55527         units   995.0
55534         units  1691.0
55541         units  1857.0
55548         units  1892.0
55555         units  1702.0
55562         units  1055.0
55653         units   951.0
55660         units  1763.0
55667         units  1970.0
55674         units  1970.0
55681         units  1742.0
55688         units  1168.0
55779         units   935.0
55786         units  1728.0
55793         units  1932.0
55800         units  1926.0
55807         units  1733.0
55814         units  1156.0
55905         units   998.0
55912         units  1869.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 55527 to 73706
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in New Brunswick
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         14660.0   977.333333   932.0   951.0  1064.0    15
25 to 34 years         25969.0  1731.266667  1661.0  1728.0  1869.0    15
35 to 44 years         28681.0  1912.066667  1818.0  1901.0  2080.0    15
45 to 54 years         29113.0  1940.866667  1869.0  1921.0  2106.0    15
55 to 64 years         25765.0  1717.666667  1665.0  1714.0  1775.0    15
65 years old and over  16626.0  1108.400000   982.0  1109.0  1237.0    15

Overall,
Sum :  140814.0
Mean :  1564.6
Min/median/max : 932.0 / 1721.0 / 2106.0
Skewnewss :  -0.5656841892272024
Total size :  90
2019

Grab the dataset only in New Brunswick
       REF_DATE            GEO  \
81987      2019  New Brunswick
81994      2019  New Brunswick
82001      2019  New Brunswick
82008      2019  New Brunswick
82015      2019  New Brunswick
82022      2019  New Brunswick
82113      2019  New Brunswick
82120      2019  New Brunswick
82127      2019  New Brunswick
82134      2019  New Brunswick
82141      2019  New Brunswick
82148      2019  New Brunswick
82239      2019  New Brunswick
82246      2019  New Brunswick
82253      2019  New Brunswick
82260      2019  New Brunswick
82267      2019  New Brunswick
82274      2019  New Brunswick
82365      2019  New Brunswick
82372      2019  New Brunswick

                                                  Sector  \
81987                      Total non-profit institutions
81994                      Total non-profit institutions
82001                      Total non-profit institutions
82008                      Total non-profit institutions
82015                      Total non-profit institutions
82022                      Total non-profit institutions
82113  Total non-profit institutions excluding govern...
82120  Total non-profit institutions excluding govern...
82127  Total non-profit institutions excluding govern...
82134  Total non-profit institutions excluding govern...
82141  Total non-profit institutions excluding govern...
82148  Total non-profit institutions excluding govern...
82239  Non-profit institutions serving households (co...
82246  Non-profit institutions serving households (co...
82253  Non-profit institutions serving households (co...
82260  Non-profit institutions serving households (co...
82267  Non-profit institutions serving households (co...
82274  Non-profit institutions serving households (co...
82365                   Business non-profit institutions
82372                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
81987         15 to 24 years  Average annual hours worked  Hours
81994         25 to 34 years  Average annual hours worked  Hours
82001         35 to 44 years  Average annual hours worked  Hours
82008         45 to 54 years  Average annual hours worked  Hours
82015         55 to 64 years  Average annual hours worked  Hours
82022  65 years old and over  Average annual hours worked  Hours
82113         15 to 24 years  Average annual hours worked  Hours
82120         25 to 34 years  Average annual hours worked  Hours
82127         35 to 44 years  Average annual hours worked  Hours
82134         45 to 54 years  Average annual hours worked  Hours
82141         55 to 64 years  Average annual hours worked  Hours
82148  65 years old and over  Average annual hours worked  Hours
82239         15 to 24 years  Average annual hours worked  Hours
82246         25 to 34 years  Average annual hours worked  Hours
82253         35 to 44 years  Average annual hours worked  Hours
82260         45 to 54 years  Average annual hours worked  Hours
82267         55 to 64 years  Average annual hours worked  Hours
82274  65 years old and over  Average annual hours worked  Hours
82365         15 to 24 years  Average annual hours worked  Hours
82372         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
81987         units  1033.0
81994         units  1698.0
82001         units  1860.0
82008         units  1916.0
82015         units  1740.0
82022         units  1095.0
82113         units   990.0
82120         units  1805.0
82127         units  1953.0
82134         units  1994.0
82141         units  1732.0
82148         units  1141.0
82239         units   999.0
82246         units  1790.0
82253         units  1921.0
82260         units  1953.0
82267         units  1704.0
82274         units  1116.0
82365         units   959.0
82372         units  1860.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 81987 to 100166
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in New Brunswick
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         14919.0   994.600000   896.0   991.0  1080.0    15
25 to 34 years         25878.0  1725.200000  1629.0  1715.0  1860.0    15
35 to 44 years         28238.0  1882.533333  1799.0  1860.0  2052.0    15
45 to 54 years         29115.0  1941.000000  1857.0  1916.0  2129.0    15
55 to 64 years         25873.0  1724.866667  1618.0  1724.0  1843.0    15
65 years old and over  16857.0  1123.800000  1061.0  1103.0  1270.0    15

Overall,
Sum :  140880.0
Mean :  1565.3333333333333
Min/median/max : 896.0 / 1722.0 / 2129.0
Skewnewss :  -0.5596985297482784
Total size :  90
2013

Grab the dataset only in New Brunswick

       REF_DATE            GEO  \
28983      2013  New Brunswick
28990      2013  New Brunswick
29109      2013  New Brunswick
29116      2013  New Brunswick
29235      2013  New Brunswick
29242      2013  New Brunswick
29361      2013  New Brunswick
29368      2013  New Brunswick
29487      2013  New Brunswick
29494      2013  New Brunswick
37803      2014  New Brunswick
37810      2014  New Brunswick
37929      2014  New Brunswick
37936      2014  New Brunswick
38055      2014  New Brunswick
38062      2014  New Brunswick
38181      2014  New Brunswick
38188      2014  New Brunswick
38307      2014  New Brunswick
38314      2014  New Brunswick

                                                  Sector   Characteristics  \
28983                      Total non-profit institutions    Male employees
28990                      Total non-profit institutions  Female employees
29109  Total non-profit institutions excluding govern...    Male employees
29116  Total non-profit institutions excluding govern...  Female employees
29235  Non-profit institutions serving households (co...    Male employees
29242  Non-profit institutions serving households (co...  Female employees
29361                   Business non-profit institutions    Male employees
29368                   Business non-profit institutions  Female employees
29487                 Government non-profit institutions    Male employees
29494                 Government non-profit institutions  Female employees
37803                      Total non-profit institutions    Male employees
37810                      Total non-profit institutions  Female employees
37929  Total non-profit institutions excluding govern...    Male employees
37936  Total non-profit institutions excluding govern...  Female employees
38055  Non-profit institutions serving households (co...    Male employees
38062  Non-profit institutions serving households (co...  Female employees
38181                   Business non-profit institutions    Male employees
38188                   Business non-profit institutions  Female employees
38307                 Government non-profit institutions    Male employees
38314                 Government non-profit institutions  Female employees

                        Indicators    UOM SCALAR_FACTOR   VALUE
28983  Average annual hours worked  Hours         units  1751.0
28990  Average annual hours worked  Hours         units  1655.0
29109  Average annual hours worked  Hours         units  1762.0
29116  Average annual hours worked  Hours         units  1561.0
29235  Average annual hours worked  Hours         units  1757.0
29242  Average annual hours worked  Hours         units  1544.0
29361  Average annual hours worked  Hours         units  1775.0
29368  Average annual hours worked  Hours         units  1631.0
29487  Average annual hours worked  Hours         units  1744.0
29494  Average annual hours worked  Hours         units  1683.0
37803  Average annual hours worked  Hours         units  1728.0
37810  Average annual hours worked  Hours         units  1606.0
37929  Average annual hours worked  Hours         units  1760.0
37936  Average annual hours worked  Hours         units  1562.0
38055  Average annual hours worked  Hours         units  1772.0
38062  Average annual hours worked  Hours         units  1550.0
38181  Average annual hours worked  Hours         units  1730.0
38188  Average annual hours worked  Hours         units  1610.0
38307  Average annual hours worked  Hours         units  1709.0
38314  Average annual hours worked  Hours         units  1620.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 28983 to 47134
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         30 non-null     int64
 1   GEO              30 non-null     object
 2   Sector           30 non-null     object
 3   Characteristics  30 non-null     object
 4   Indicators       30 non-null     object
 5   UOM              30 non-null     object
 6   SCALAR_FACTOR    30 non-null     object
 7   VALUE            30 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.1+ KB
None

Grab the dataset only in New Brunswick
                      sum         mean    amin  median    amax  size
Characteristics
Female employees  24116.0  1607.733333  1544.0  1610.0  1683.0    15
Male employees    26399.0  1759.933333  1709.0  1758.0  1824.0    15

Overall,
Sum :  50515.0
Mean :  1683.8333333333333
Min/median/max : 1544.0 / 1696.0 / 1824.0
Skewnewss :  -0.13526057290725768
Total size :  30
2016

Grab the dataset only in New Brunswick
       REF_DATE            GEO  \
55443      2016  New Brunswick
55450      2016  New Brunswick
55569      2016  New Brunswick
55576      2016  New Brunswick
55695      2016  New Brunswick
55702      2016  New Brunswick
55821      2016  New Brunswick
55828      2016  New Brunswick
55947      2016  New Brunswick
55954      2016  New Brunswick
64263      2017  New Brunswick
64270      2017  New Brunswick
64389      2017  New Brunswick
64396      2017  New Brunswick
64515      2017  New Brunswick
64522      2017  New Brunswick
64641      2017  New Brunswick
64648      2017  New Brunswick
64767      2017  New Brunswick
64774      2017  New Brunswick

                                                  Sector   Characteristics  \
55443                      Total non-profit institutions    Male employees
55450                      Total non-profit institutions  Female employees
55569  Total non-profit institutions excluding govern...    Male employees
55576  Total non-profit institutions excluding govern...  Female employees
55695  Non-profit institutions serving households (co...    Male employees
55702  Non-profit institutions serving households (co...  Female employees
55821                   Business non-profit institutions    Male employees
55828                   Business non-profit institutions  Female employees
55947                 Government non-profit institutions    Male employees
55954                 Government non-profit institutions  Female employees
64263                      Total non-profit institutions    Male employees
64270                      Total non-profit institutions  Female employees
64389  Total non-profit institutions excluding govern...    Male employees
64396  Total non-profit institutions excluding govern...  Female employees
64515  Non-profit institutions serving households (co...    Male employees
64522  Non-profit institutions serving households (co...  Female employees
64641                   Business non-profit institutions    Male employees
64648                   Business non-profit institutions  Female employees
64767                 Government non-profit institutions    Male employees
64774                 Government non-profit institutions  Female employees

                        Indicators    UOM SCALAR_FACTOR   VALUE
55443  Average annual hours worked  Hours         units  1734.0
55450  Average annual hours worked  Hours         units  1631.0
55569  Average annual hours worked  Hours         units  1787.0
55576  Average annual hours worked  Hours         units  1588.0
55695  Average annual hours worked  Hours         units  1775.0
55702  Average annual hours worked  Hours         units  1556.0
55821  Average annual hours worked  Hours         units  1816.0
55828  Average annual hours worked  Hours         units  1717.0
55947  Average annual hours worked  Hours         units  1705.0
55954  Average annual hours worked  Hours         units  1645.0
64263  Average annual hours worked  Hours         units  1719.0
64270  Average annual hours worked  Hours         units  1631.0
64389  Average annual hours worked  Hours         units  1747.0
64396  Average annual hours worked  Hours         units  1570.0
64515  Average annual hours worked  Hours         units  1739.0
64522  Average annual hours worked  Hours         units  1546.0
64641  Average annual hours worked  Hours         units  1768.0
64648  Average annual hours worked  Hours         units  1668.0
64767  Average annual hours worked  Hours         units  1703.0
64774  Average annual hours worked  Hours         units  1651.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 55443 to 73594
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         30 non-null     int64
 1   GEO              30 non-null     object
 2   Sector           30 non-null     object
 3   Characteristics  30 non-null     object
 4   Indicators       30 non-null     object
 5   UOM              30 non-null     object
 6   SCALAR_FACTOR    30 non-null     object
 7   VALUE            30 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.1+ KB
None

Grab the dataset only in New Brunswick
                      sum         mean    amin  median    amax  size
Characteristics
Female employees  24229.0  1615.266667  1525.0  1631.0  1717.0    15
Male employees    26002.0  1733.466667  1677.0  1734.0  1816.0    15

Overall,
Sum :  50231.0
Mean :  1674.3666666666666
Min/median/max : 1525.0 / 1686.0 / 1816.0
Skewnewss :  -0.31192377569054247
Total size :  30
2019

Grab the dataset only in New Brunswick
       REF_DATE            GEO  \
81903      2019  New Brunswick
81910      2019  New Brunswick
82029      2019  New Brunswick
82036      2019  New Brunswick
82155      2019  New Brunswick
82162      2019  New Brunswick
82281      2019  New Brunswick
82288      2019  New Brunswick
82407      2019  New Brunswick
82414      2019  New Brunswick
90723      2020  New Brunswick
90730      2020  New Brunswick
90849      2020  New Brunswick
90856      2020  New Brunswick
90975      2020  New Brunswick
90982      2020  New Brunswick
91101      2020  New Brunswick
91108      2020  New Brunswick
91227      2020  New Brunswick
91234      2020  New Brunswick

                                                  Sector   Characteristics  \
81903                      Total non-profit institutions    Male employees
81910                      Total non-profit institutions  Female employees
82029  Total non-profit institutions excluding govern...    Male employees
82036  Total non-profit institutions excluding govern...  Female employees
82155  Non-profit institutions serving households (co...    Male employees
82162  Non-profit institutions serving households (co...  Female employees
82281                   Business non-profit institutions    Male employees
82288                   Business non-profit institutions  Female employees
82407                 Government non-profit institutions    Male employees
82414                 Government non-profit institutions  Female employees
90723                      Total non-profit institutions    Male employees
90730                      Total non-profit institutions  Female employees
90849  Total non-profit institutions excluding govern...    Male employees
90856  Total non-profit institutions excluding govern...  Female employees
90975  Non-profit institutions serving households (co...    Male employees
90982  Non-profit institutions serving households (co...  Female employees
91101                   Business non-profit institutions    Male employees
91108                   Business non-profit institutions  Female employees
91227                 Government non-profit institutions    Male employees
91234                 Government non-profit institutions  Female employees

                        Indicators    UOM SCALAR_FACTOR   VALUE
81903  Average annual hours worked  Hours         units  1718.0
81910  Average annual hours worked  Hours         units  1656.0
82029  Average annual hours worked  Hours         units  1752.0
82036  Average annual hours worked  Hours         units  1608.0
82155  Average annual hours worked  Hours         units  1726.0
82162  Average annual hours worked  Hours         units  1584.0
82281  Average annual hours worked  Hours         units  1821.0
82288  Average annual hours worked  Hours         units  1719.0
82407  Average annual hours worked  Hours         units  1699.0
82414  Average annual hours worked  Hours         units  1672.0
90723  Average annual hours worked  Hours         units  1663.0
90730  Average annual hours worked  Hours         units  1624.0
90849  Average annual hours worked  Hours         units  1676.0
90856  Average annual hours worked  Hours         units  1526.0
90975  Average annual hours worked  Hours         units  1659.0
90982  Average annual hours worked  Hours         units  1498.0
91101  Average annual hours worked  Hours         units  1721.0
91108  Average annual hours worked  Hours         units  1639.0
91227  Average annual hours worked  Hours         units  1657.0
91234  Average annual hours worked  Hours         units  1653.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 81903 to 100054
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         30 non-null     int64
 1   GEO              30 non-null     object
 2   Sector           30 non-null     object
 3   Characteristics  30 non-null     object
 4   Indicators       30 non-null     object
 5   UOM              30 non-null     object
 6   SCALAR_FACTOR    30 non-null     object
 7   VALUE            30 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.1+ KB
None

Grab the dataset only in New Brunswick
                      sum         mean    amin  median    amax  size
Characteristics
Female employees  24287.0  1619.133333  1498.0  1637.0  1719.0    15
Male employees    25621.0  1708.066667  1657.0  1713.0  1821.0    15

Overall,
Sum :  49908.0
Mean :  1663.6
Min/median/max : 1498.0 / 1662.0 / 1821.0
Skewnewss :  -0.40272071566382883
Total size :  30
2013

Grab the dataset only in New Brunswick
       REF_DATE            GEO  \
29039      2013  New Brunswick
29046      2013  New Brunswick
29060      2013  New Brunswick
29165      2013  New Brunswick
29172      2013  New Brunswick
29186      2013  New Brunswick
29291      2013  New Brunswick
29298      2013  New Brunswick
29312      2013  New Brunswick
29417      2013  New Brunswick
29424      2013  New Brunswick
29438      2013  New Brunswick
29543      2013  New Brunswick
29550      2013  New Brunswick
29564      2013  New Brunswick
37859      2014  New Brunswick
37866      2014  New Brunswick
37880      2014  New Brunswick
37985      2014  New Brunswick
37992      2014  New Brunswick

                                                  Sector  \
29039                      Total non-profit institutions
29046                      Total non-profit institutions
29060                      Total non-profit institutions
29165  Total non-profit institutions excluding govern...
29172  Total non-profit institutions excluding govern...
29186  Total non-profit institutions excluding govern...
29291  Non-profit institutions serving households (co...
29298  Non-profit institutions serving households (co...
29312  Non-profit institutions serving households (co...
29417                   Business non-profit institutions
29424                   Business non-profit institutions
29438                   Business non-profit institutions
29543                 Government non-profit institutions
29550                 Government non-profit institutions
29564                 Government non-profit institutions
37859                      Total non-profit institutions
37866                      Total non-profit institutions
37880                      Total non-profit institutions
37985  Total non-profit institutions excluding govern...
37992  Total non-profit institutions excluding govern...

                    Characteristics                   Indicators    UOM  \
29039  High school diploma and less  Average annual hours worked  Hours
29046             Trade certificate  Average annual hours worked  Hours
29060  University degree and higher  Average annual hours worked  Hours
29165  High school diploma and less  Average annual hours worked  Hours
29172             Trade certificate  Average annual hours worked  Hours
29186  University degree and higher  Average annual hours worked  Hours
29291  High school diploma and less  Average annual hours worked  Hours
29298             Trade certificate  Average annual hours worked  Hours
29312  University degree and higher  Average annual hours worked  Hours
29417  High school diploma and less  Average annual hours worked  Hours
29424             Trade certificate  Average annual hours worked  Hours
29438  University degree and higher  Average annual hours worked  Hours
29543  High school diploma and less  Average annual hours worked  Hours
29550             Trade certificate  Average annual hours worked  Hours
29564  University degree and higher  Average annual hours worked  Hours
37859  High school diploma and less  Average annual hours worked  Hours
37866             Trade certificate  Average annual hours worked  Hours
37880  University degree and higher  Average annual hours worked  Hours
37985  High school diploma and less  Average annual hours worked  Hours
37992             Trade certificate  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
29039         units  1426.0
29046         units  1695.0
29060         units  1801.0
29165         units  1353.0
29172         units  1589.0
29186         units  1859.0
29291         units  1315.0
29298         units  1523.0
29312         units  1856.0
29417         units  1455.0
29424         units  1789.0
29438         units  1870.0
29543         units  1469.0
29550         units  1734.0
29564         units  1784.0
37859         units  1383.0
37866         units  1644.0
37880         units  1772.0
37985         units  1347.0
37992         units  1584.0
<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 29039 to 47204
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         45 non-null     int64
 1   GEO              45 non-null     object
 2   Sector           45 non-null     object
 3   Characteristics  45 non-null     object
 4   Indicators       45 non-null     object
 5   UOM              45 non-null     object
 6   SCALAR_FACTOR    45 non-null     object
 7   VALUE            45 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 3.2+ KB
None

Grab the dataset only in New Brunswick
                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  20962.0  1397.466667  1315.0  1405.0  1482.0
Trade certificate             24821.0  1654.733333  1523.0  1666.0  1789.0
University degree and higher  27529.0  1835.266667  1743.0  1856.0  1914.0

                              size
Characteristics
High school diploma and less    15
Trade certificate               15
University degree and higher    15

Overall,
Sum :  73312.0
Mean :  1629.1555555555556
Min/median/max : 1315.0 / 1666.0 / 1914.0
Skewnewss :  -0.15067041690391444
Total size :  45
2016

Grab the dataset only in New Brunswick
       REF_DATE            GEO  \
55499      2016  New Brunswick
55506      2016  New Brunswick
55520      2016  New Brunswick
55625      2016  New Brunswick
55632      2016  New Brunswick
55646      2016  New Brunswick
55751      2016  New Brunswick
55758      2016  New Brunswick
55772      2016  New Brunswick
55877      2016  New Brunswick
55884      2016  New Brunswick
55898      2016  New Brunswick
56003      2016  New Brunswick
56010      2016  New Brunswick
56024      2016  New Brunswick
64319      2017  New Brunswick
64326      2017  New Brunswick
64340      2017  New Brunswick
64445      2017  New Brunswick
64452      2017  New Brunswick

                                                  Sector  \
55499                      Total non-profit institutions

Panda Profiling for Final Result for New Brunswick

In [109]:
# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

Filtering only Newfoundland and Labrador.

Only finished "Average annual hours worked".

In [110]:
# -- Newfoundland and Labrador    315895.0    306.099806    482.634908  1032

ProCode = 5

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

2013

Grab the dataset only in Newfoundland and Labrador
       REF_DATE                        GEO  \
27177      2013  Newfoundland and Labrador
27184      2013  Newfoundland and Labrador
27191      2013  Newfoundland and Labrador
27198      2013  Newfoundland and Labrador
27205      2013  Newfoundland and Labrador
27212      2013  Newfoundland and Labrador
27303      2013  Newfoundland and Labrador
27310      2013  Newfoundland and Labrador
27317      2013  Newfoundland and Labrador
27324      2013  Newfoundland and Labrador
27331      2013  Newfoundland and Labrador
27338      2013  Newfoundland and Labrador
27429      2013  Newfoundland and Labrador
27436      2013  Newfoundland and Labrador
27443      2013  Newfoundland and Labrador
27450      2013  Newfoundland and Labrador
27457      2013  Newfoundland and Labrador
27464      2013  Newfoundland and Labrador
27555      2013  Newfoundland and Labrador
27562      2013  Newfoundland and Labrador

                                                  Sector  \
27177                      Total non-profit institutions
27184                      Total non-profit institutions
27191                      Total non-profit institutions
27198                      Total non-profit institutions
27205                      Total non-profit institutions
27212                      Total non-profit institutions
27303  Total non-profit institutions excluding govern...
27310  Total non-profit institutions excluding govern...
27317  Total non-profit institutions excluding govern...
27324  Total non-profit institutions excluding govern...
27331  Total non-profit institutions excluding govern...
27338  Total non-profit institutions excluding govern...
27429  Non-profit institutions serving households (co...
27436  Non-profit institutions serving households (co...
27443  Non-profit institutions serving households (co...
27450  Non-profit institutions serving households (co...
27457  Non-profit institutions serving households (co...
27464  Non-profit institutions serving households (co...
27555                   Business non-profit institutions
27562                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
27177         15 to 24 years  Average annual hours worked  Hours
27184         25 to 34 years  Average annual hours worked  Hours
27191         35 to 44 years  Average annual hours worked  Hours
27198         45 to 54 years  Average annual hours worked  Hours
27205         55 to 64 years  Average annual hours worked  Hours
27212  65 years old and over  Average annual hours worked  Hours
27303         15 to 24 years  Average annual hours worked  Hours
27310         25 to 34 years  Average annual hours worked  Hours
27317         35 to 44 years  Average annual hours worked  Hours
27324         45 to 54 years  Average annual hours worked  Hours
27331         55 to 64 years  Average annual hours worked  Hours
27338  65 years old and over  Average annual hours worked  Hours
27429         15 to 24 years  Average annual hours worked  Hours
27436         25 to 34 years  Average annual hours worked  Hours
27443         35 to 44 years  Average annual hours worked  Hours
27450         45 to 54 years  Average annual hours worked  Hours
27457         55 to 64 years  Average annual hours worked  Hours
27464  65 years old and over  Average annual hours worked  Hours
27555         15 to 24 years  Average annual hours worked  Hours
27562         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
27177         units   900.0
27184         units  1690.0
27191         units  1899.0
27198         units  1933.0
27205         units  1691.0
27212         units  1160.0
27303         units   747.0
27310         units  1859.0
27317         units  2029.0
27324         units  2116.0
27331         units  1778.0
27338         units  1191.0
27429         units   720.0
27436         units  1855.0
27443         units  2014.0
27450         units  2111.0
27457         units  1787.0
27464         units  1199.0
27555         units   827.0
27562         units  1875.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 27177 to 45356
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Newfoundland and Labrador
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         12244.0   816.266667   673.0   796.0   973.0    15
25 to 34 years         26738.0  1782.533333  1627.0  1839.0  1908.0    15
35 to 44 years         29539.0  1969.266667  1838.0  2008.0  2112.0    15
45 to 54 years         30369.0  2024.600000  1863.0  2095.0  2136.0    15
55 to 64 years         25831.0  1722.066667  1654.0  1735.0  1787.0    15
65 years old and over  17669.0  1177.933333  1124.0  1182.0  1252.0    15

Overall,
Sum :  142390.0
Mean :  1582.111111111111
Min/median/max : 673.0 / 1740.5 / 2136.0
Skewnewss :  -0.6706029875323214
Total size :  90
2016

Grab the dataset only in Newfoundland and Labrador
       REF_DATE                        GEO  \
53637      2016  Newfoundland and Labrador
53644      2016  Newfoundland and Labrador
53651      2016  Newfoundland and Labrador
53658      2016  Newfoundland and Labrador
53665      2016  Newfoundland and Labrador
53672      2016  Newfoundland and Labrador
53763      2016  Newfoundland and Labrador
53770      2016  Newfoundland and Labrador
53777      2016  Newfoundland and Labrador
53784      2016  Newfoundland and Labrador
53791      2016  Newfoundland and Labrador
53798      2016  Newfoundland and Labrador
53889      2016  Newfoundland and Labrador
53896      2016  Newfoundland and Labrador
53903      2016  Newfoundland and Labrador
53910      2016  Newfoundland and Labrador
53917      2016  Newfoundland and Labrador
53924      2016  Newfoundland and Labrador
54015      2016  Newfoundland and Labrador
54022      2016  Newfoundland and Labrador

                                                  Sector  \
53637                      Total non-profit institutions
53644                      Total non-profit institutions
53651                      Total non-profit institutions
53658                      Total non-profit institutions
53665                      Total non-profit institutions
53672                      Total non-profit institutions
53763  Total non-profit institutions excluding govern...
53770  Total non-profit institutions excluding govern...
53777  Total non-profit institutions excluding govern...
53784  Total non-profit institutions excluding govern...
53791  Total non-profit institutions excluding govern...
53798  Total non-profit institutions excluding govern...
53889  Non-profit institutions serving households (co...
53896  Non-profit institutions serving households (co...
53903  Non-profit institutions serving households (co...
53910  Non-profit institutions serving households (co...
53917  Non-profit institutions serving households (co...
53924  Non-profit institutions serving households (co...
54015                   Business non-profit institutions
54022                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
53637         15 to 24 years  Average annual hours worked  Hours
53644         25 to 34 years  Average annual hours worked  Hours
53651         35 to 44 years  Average annual hours worked  Hours
53658         45 to 54 years  Average annual hours worked  Hours
53665         55 to 64 years  Average annual hours worked  Hours
53672  65 years old and over  Average annual hours worked  Hours
53763         15 to 24 years  Average annual hours worked  Hours
53770         25 to 34 years  Average annual hours worked  Hours
53777         35 to 44 years  Average annual hours worked  Hours
53784         45 to 54 years  Average annual hours worked  Hours
53791         55 to 64 years  Average annual hours worked  Hours
53798  65 years old and over  Average annual hours worked  Hours
53889         15 to 24 years  Average annual hours worked  Hours
53896         25 to 34 years  Average annual hours worked  Hours
53903         35 to 44 years  Average annual hours worked  Hours
53910         45 to 54 years  Average annual hours worked  Hours
53917         55 to 64 years  Average annual hours worked  Hours
53924  65 years old and over  Average annual hours worked  Hours
54015         15 to 24 years  Average annual hours worked  Hours
54022         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
53637         units   905.0
53644         units  1686.0
53651         units  1889.0
53658         units  1935.0
53665         units  1699.0
53672         units  1150.0
53763         units   734.0
53770         units  1830.0
53777         units  2004.0
53784         units  2093.0
53791         units  1732.0
53798         units  1236.0
53889         units   695.0
53896         units  1812.0
53903         units  1978.0
53910         units  2086.0
53917         units  1733.0
53924         units  1240.0
54015         units   832.0
54022         units  1879.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 53637 to 71816
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Newfoundland and Labrador
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         12541.0   836.066667   691.0   824.0  1028.0    15
25 to 34 years         26330.0  1755.333333  1657.0  1756.0  1879.0    15
35 to 44 years         29219.0  1947.933333  1857.0  1944.0  2078.0    15
45 to 54 years         30358.0  2023.866667  1903.0  2050.0  2127.0    15
55 to 64 years         25543.0  1702.866667  1664.0  1701.0  1733.0    15
65 years old and over  17873.0  1191.533333  1047.0  1213.0  1268.0    15

Overall,
Sum :  141864.0
Mean :  1576.2666666666667
Min/median/max : 691.0 / 1709.0 / 2127.0
Skewnewss :  -0.6967235909325254
Total size :  90
2019

Grab the dataset only in Newfoundland and Labrador
       REF_DATE                        GEO  \
80097      2019  Newfoundland and Labrador
80104      2019  Newfoundland and Labrador
80111      2019  Newfoundland and Labrador
80118      2019  Newfoundland and Labrador
80125      2019  Newfoundland and Labrador
80132      2019  Newfoundland and Labrador
80223      2019  Newfoundland and Labrador
80230      2019  Newfoundland and Labrador
80237      2019  Newfoundland and Labrador
80244      2019  Newfoundland and Labrador
80251      2019  Newfoundland and Labrador
80258      2019  Newfoundland and Labrador
80349      2019  Newfoundland and Labrador
80356      2019  Newfoundland and Labrador
80363      2019  Newfoundland and Labrador
80370      2019  Newfoundland and Labrador
80377      2019  Newfoundland and Labrador
80384      2019  Newfoundland and Labrador
80475      2019  Newfoundland and Labrador
80482      2019  Newfoundland and Labrador

                                                  Sector  \
80097                      Total non-profit institutions
80104                      Total non-profit institutions
80111                      Total non-profit institutions
80118                      Total non-profit institutions
80125                      Total non-profit institutions
80132                      Total non-profit institutions
80223  Total non-profit institutions excluding govern...
80230  Total non-profit institutions excluding govern...
80237  Total non-profit institutions excluding govern...
80244  Total non-profit institutions excluding govern...
80251  Total non-profit institutions excluding govern...
80258  Total non-profit institutions excluding govern...
80349  Non-profit institutions serving households (co...
80356  Non-profit institutions serving households (co...
80363  Non-profit institutions serving households (co...
80370  Non-profit institutions serving households (co...
80377  Non-profit institutions serving households (co...
80384  Non-profit institutions serving households (co...
80475                   Business non-profit institutions
80482                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
80097         15 to 24 years  Average annual hours worked  Hours
80104         25 to 34 years  Average annual hours worked  Hours
80111         35 to 44 years  Average annual hours worked  Hours
80118         45 to 54 years  Average annual hours worked  Hours
80125         55 to 64 years  Average annual hours worked  Hours
80132  65 years old and over  Average annual hours worked  Hours
80223         15 to 24 years  Average annual hours worked  Hours
80230         25 to 34 years  Average annual hours worked  Hours
80237         35 to 44 years  Average annual hours worked  Hours
80244         45 to 54 years  Average annual hours worked  Hours
80251         55 to 64 years  Average annual hours worked  Hours
80258  65 years old and over  Average annual hours worked  Hours
80349         15 to 24 years  Average annual hours worked  Hours
80356         25 to 34 years  Average annual hours worked  Hours
80363         35 to 44 years  Average annual hours worked  Hours
80370         45 to 54 years  Average annual hours worked  Hours
80377         55 to 64 years  Average annual hours worked  Hours
80384  65 years old and over  Average annual hours worked  Hours
80475         15 to 24 years  Average annual hours worked  Hours
80482         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
80097         units   946.0
80104         units  1671.0
80111         units  1861.0
80118         units  1941.0
80125         units  1670.0
80132         units  1140.0
80223         units   746.0
80230         units  1762.0
80237         units  1973.0
80244         units  2110.0
80251         units  1699.0
80258         units  1291.0
80349         units   718.0
80356         units  1727.0
80363         units  1934.0
80370         units  2084.0
80377         units  1688.0
80384         units  1303.0
80475         units   821.0
80482         units  1855.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 80097 to 98276
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Newfoundland and Labrador
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         12920.0   861.333333   713.0   801.0  1093.0    15
25 to 34 years         25547.0  1703.133333  1609.0  1700.0  1855.0    15
35 to 44 years         28658.0  1910.533333  1810.0  1899.0  2092.0    15
45 to 54 years         30324.0  2021.600000  1904.0  1988.0  2191.0    15
55 to 64 years         25029.0  1668.600000  1598.0  1670.0  1739.0    15
65 years old and over  17914.0  1194.266667  1059.0  1202.0  1303.0    15

Overall,
Sum :  140392.0
Mean :  1559.911111111111
Min/median/max : 713.0 / 1672.5 / 2191.0
Skewnewss :  -0.6381989481212683
Total size :  90
2013

Grab the dataset only in Newfoundland and Labrador
       REF_DATE                        GEO  \
27093      2013  Newfoundland and Labrador
27100      2013  Newfoundland and Labrador
27219      2013  Newfoundland and Labrador
27226      2013  Newfoundland and Labrador
27345      2013  Newfoundland and Labrador
27352      2013  Newfoundland and Labrador
27471      2013  Newfoundland and Labrador
27478      2013  Newfoundland and Labrador
27597      2013  Newfoundland and Labrador
27604      2013  Newfoundland and Labrador
35913      2014  Newfoundland and Labrador
35920      2014  Newfoundland and Labrador
36039      2014  Newfoundland and Labrador
36046      2014  Newfoundland and Labrador
36165      2014  Newfoundland and Labrador
36172      2014  Newfoundland and Labrador
36291      2014  Newfoundland and Labrador
36298      2014  Newfoundland and Labrador
36417      2014  Newfoundland and Labrador
36424      2014  Newfoundland and Labrador

                                                  Sector   Characteristics  \
27093                      Total non-profit institutions    Male employees
27100                      Total non-profit institutions  Female employees
27219  Total non-profit institutions excluding govern...    Male employees
27226  Total non-profit institutions excluding govern...  Female employees
27345  Non-profit institutions serving households (co...    Male employees
27352  Non-profit institutions serving households (co...  Female employees
27471                   Business non-profit institutions    Male employees
27478                   Business non-profit institutions  Female employees
27597                 Government non-profit institutions    Male employees
27604                 Government non-profit institutions  Female employees
35913                      Total non-profit institutions    Male employees
35920                      Total non-profit institutions  Female employees
36039  Total non-profit institutions excluding govern...    Male employees
36046  Total non-profit institutions excluding govern...  Female employees
36165  Non-profit institutions serving households (co...    Male employees
36172  Non-profit institutions serving households (co...  Female employees
36291                   Business non-profit institutions    Male employees
36298                   Business non-profit institutions  Female employees
36417                 Government non-profit institutions    Male employees
36424                 Government non-profit institutions  Female employees

                        Indicators    UOM SCALAR_FACTOR   VALUE
27093  Average annual hours worked  Hours         units  1752.0
27100  Average annual hours worked  Hours         units  1682.0
27219  Average annual hours worked  Hours         units  1732.0
27226  Average annual hours worked  Hours         units  1705.0
27345  Average annual hours worked  Hours         units  1728.0
27352  Average annual hours worked  Hours         units  1706.0
27471  Average annual hours worked  Hours         units  1744.0
27478  Average annual hours worked  Hours         units  1700.0
27597  Average annual hours worked  Hours         units  1759.0
27604  Average annual hours worked  Hours         units  1677.0
35913  Average annual hours worked  Hours         units  1718.0
35920  Average annual hours worked  Hours         units  1656.0
36039  Average annual hours worked  Hours         units  1699.0
36046  Average annual hours worked  Hours         units  1674.0
36165  Average annual hours worked  Hours         units  1702.0

                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  20037.0  1335.800000  1178.0  1305.0  1507.0
Trade certificate             23932.0  1595.466667  1445.0  1615.0  1734.0
University degree and higher  28061.0  1870.733333  1726.0  1876.0  2018.0

                              size
Characteristics
High school diploma and less    15
Trade certificate               15
University degree and higher    15

Overall,
Sum :  72030.0
Mean :  1600.6666666666667
Min/median/max : 1178.0 / 1615.0 / 2018.0
Skewnewss :  -0.018789938513471514
Total size :  45
2013

Grab the dataset only in Newfoundland and Labrador
       REF_DATE                        GEO  \
27149      2013  Newfoundland and Labrador
27156      2013  Newfoundland and Labrador
27170      2013  Newfoundland and Labrador
27275      2013  Newfoundland and Labrador
27282      2013  Newfoundland and Labrador
27296      2013  Newfoundland and Labrador
27401      2013  Newfoundland and Labrador
27408      2013  Newfoundland and Labrador
27422      2013  Newfoundland and Labrador
27527      2013  Newfoundland and Labrador
27534      2013  Newfoundland and Labrador
27548      2013  Newfoundland and Labrador
27653      2013  Newfoundland and Labrador
27660      2013  Newfoundland and Labrador
27674      2013  Newfoundland and Labrador
35969      2014  Newfoundland and Labrador
35976      2014  Newfoundland and Labrador
35990      2014  Newfoundland and Labrador
36095      2014  Newfoundland and Labrador
36102      2014  Newfoundland and Labrador

                                                  Sector  \
27149                      Total non-profit institutions
27156                      Total non-profit institutions
27170                      Total non-profit institutions
27275  Total non-profit institutions excluding govern...
27282  Total non-profit institutions excluding govern...
27296  Total non-profit institutions excluding govern...
27401  Non-profit institutions serving households (co...
27408  Non-profit institutions serving households (co...
27422  Non-profit institutions serving households (co...
27527                   Business non-profit institutions
27534                   Business non-profit institutions
27548                   Business non-profit institutions
27653                 Government non-profit institutions
27660                 Government non-profit institutions
27674                 Government non-profit institutions
35969                      Total non-profit institutions
35976                      Total non-profit institutions
35990                      Total non-profit institutions
36095  Total non-profit institutions excluding govern...
36102  Total non-profit institutions excluding govern...

                    Characteristics                   Indicators    UOM  \
27149  High school diploma and less  Average annual hours worked  Hours
27156             Trade certificate  Average annual hours worked  Hours
27170  University degree and higher  Average annual hours worked  Hours
27275  High school diploma and less  Average annual hours worked  Hours
27282             Trade certificate  Average annual hours worked  Hours
27296  University degree and higher  Average annual hours worked  Hours
27401  High school diploma and less  Average annual hours worked  Hours
27408             Trade certificate  Average annual hours worked  Hours
27422  University degree and higher  Average annual hours worked  Hours
27527  High school diploma and less  Average annual hours worked  Hours
27534             Trade certificate  Average annual hours worked  Hours
27548  University degree and higher  Average annual hours worked  Hours
27653  High school diploma and less  Average annual hours worked  Hours
27660             Trade certificate  Average annual hours worked  Hours
27674  University degree and higher  Average annual hours worked  Hours
35969  High school diploma and less  Average annual hours worked  Hours
35976             Trade certificate  Average annual hours worked  Hours
35990  University degree and higher  Average annual hours worked  Hours
36095  High school diploma and less  Average annual hours worked  Hours
36102             Trade certificate  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
27149         units  1388.0
27156         units  1669.0
27170         units  1806.0
27275         units  1221.0
27282         units  1649.0
27296         units  2048.0
27401         units  1186.0
27408         units  1576.0
27422         units  2063.0
27527         units  1333.0
27534         units  1855.0
27548         units  1971.0
27653         units  1459.0
27660         units  1674.0
27674         units  1757.0
35969         units  1395.0
35976         units  1632.0
35990         units  1767.0
36095         units  1219.0
36102         units  1603.0
<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 27149 to 45314
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         45 non-null     int64
 1   GEO              45 non-null     object
 2   Sector           45 non-null     object
 3   Characteristics  45 non-null     object
 4   Indicators       45 non-null     object
 5   UOM              45 non-null     object
 6   SCALAR_FACTOR    45 non-null     object
 7   VALUE            45 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 3.2+ KB
None

Grab the dataset only in Newfoundland and Labrador
                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  19865.0  1324.333333  1186.0  1333.0  1477.0
Trade certificate             24795.0  1653.000000  1524.0  1640.0  1855.0
University degree and higher  28662.0  1910.800000  1707.0  1971.0  2063.0

                              size
Characteristics
High school diploma and less    15
Trade certificate               15
University degree and higher    15

Overall,
Sum :  73322.0
Mean :  1629.3777777777777
Min/median/max : 1186.0 / 1640.0 / 2063.0
Skewnewss :  -0.002860315150385357
Total size :  45
2016

Grab the dataset only in Newfoundland and Labrador
       REF_DATE                        GEO  \
53567      2016  Newfoundland and Labrador
53574      2016  Newfoundland and Labrador
53693      2016  Newfoundland and Labrador
53700      2016  Newfoundland and Labrador
53819      2016  Newfoundland and Labrador
53826      2016  Newfoundland and Labrador
53945      2016  Newfoundland and Labrador
53952      2016  Newfoundland and Labrador
54071      2016  Newfoundland and Labrador
54078      2016  Newfoundland and Labrador
62387      2017  Newfoundland and Labrador
62394      2017  Newfoundland and Labrador
62513      2017  Newfoundland and Labrador
62520      2017  Newfoundland and Labrador
62639      2017  Newfoundland and Labrador
62646      2017  Newfoundland and Labrador
62765      2017  Newfoundland and Labrador
62772      2017  Newfoundland and Labrador
62891      2017  Newfoundland and Labrador
62898      2017  Newfoundland and Labrador

                                                  Sector  \
53567                      Total non-profit institutions
53574                      Total non-profit institutions
53693  Total non-profit institutions excluding govern...
53700  Total non-profit institutions excluding govern...
53819  Non-profit institutions serving households (co...
53826  Non-profit institutions serving households (co...
53945                   Business non-profit institutions
53952                   Business non-profit institutions
54071                 Government non-profit institutions
54078                 Government non-profit institutions
62387                      Total non-profit institutions
62394                      Total non-profit institutions
62513  Total non-profit institutions excluding govern...
62520  Total non-profit institutions excluding govern...
62639  Non-profit institutions serving households (co...
62646  Non-profit institutions serving households (co...
62765                   Business non-profit institutions
62772                   Business non-profit institutions
62891                 Government non-profit institutions
62898                 Government non-profit institutions

               Characteristics                   Indicators    UOM  \
53567      Immigrant employees  Average annual hours worked  Hours
53574  Non-immigrant employees  Average annual hours worked  Hours
53693      Immigrant employees  Average annual hours worked  Hours
53700  Non-immigrant employees  Average annual hours worked  Hours
53819      Immigrant employees  Average annual hours worked  Hours
53826  Non-immigrant employees  Average annual hours worked  Hours
53945      Immigrant employees  Average annual hours worked  Hours
53952  Non-immigrant employees  Average annual hours worked  Hours
54071      Immigrant employees  Average annual hours worked  Hours
54078  Non-immigrant employees  Average annual hours worked  Hours
62387      Immigrant employees  Average annual hours worked  Hours
62394  Non-immigrant employees  Average annual hours worked  Hours
62513      Immigrant employees  Average annual hours worked  Hours
62520  Non-immigrant employees  Average annual hours worked  Hours
62639      Immigrant employees  Average annual hours worked  Hours
62646  Non-immigrant employees  Average annual hours worked  Hours
62765      Immigrant employees  Average annual hours worked  Hours
62772  Non-immigrant employees  Average annual hours worked  Hours
62891      Immigrant employees  Average annual hours worked  Hours
62898  Non-immigrant employees  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
53567         units  1687.0
53574         units  1694.0
53693         units  1802.0
53700         units  1679.0
53819         units  1813.0
53826         units  1670.0
53945         units  1756.0
53952         units  1710.0
54071         units  1675.0
54078         units  1698.0
62387         units  1700.0
62394         units  1712.0
62513         units  1715.0
62520         units  1663.0
62639         units  1705.0
62646         units  1645.0
62765         units  1723.0
62772         units  1724.0
62891         units  1698.0
62898         units  1726.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 53567 to 71718
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         30 non-null     int64
 1   GEO              30 non-null     object
 2   Sector           30 non-null     object
 3   Characteristics  30 non-null     object
 4   Indicators       30 non-null     object
 5   UOM              30 non-null     object
 6   SCALAR_FACTOR    30 non-null     object
 7   VALUE            30 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.1+ KB
None

Grab the dataset only in Newfoundland and Labrador
                             sum         mean    amin  median    amax  size
Characteristics
Immigrant employees      25720.0  1714.666667  1675.0  1698.0  1813.0    15
Non-immigrant employees  25301.0  1686.733333  1640.0  1693.0  1726.0    15

Overall,
Sum :  51021.0
Mean :  1700.7
Min/median/max : 1640.0 / 1696.0 / 1813.0
Skewnewss :  1.3810399806775475
Total size :  30
2019

Grab the dataset only in Newfoundland and Labrador
       REF_DATE                        GEO  \
80069      2019  Newfoundland and Labrador
80076      2019  Newfoundland and Labrador
80090      2019  Newfoundland and Labrador
80195      2019  Newfoundland and Labrador
80202      2019  Newfoundland and Labrador
80216      2019  Newfoundland and Labrador
80321      2019  Newfoundland and Labrador
80328      2019  Newfoundland and Labrador
80342      2019  Newfoundland and Labrador
80447      2019  Newfoundland and Labrador
80454      2019  Newfoundland and Labrador
80468      2019  Newfoundland and Labrador
80573      2019  Newfoundland and Labrador
80580      2019  Newfoundland and Labrador
80594      2019  Newfoundland and Labrador
88889      2020  Newfoundland and Labrador
88896      2020  Newfoundland and Labrador
88910      2020  Newfoundland and Labrador
89015      2020  Newfoundland and Labrador
89022      2020  Newfoundland and Labrador

                                                  Sector  \
80069                      Total non-profit institutions
80076                      Total non-profit institutions
80090                      Total non-profit institutions
80195  Total non-profit institutions excluding govern...
80202  Total non-profit institutions excluding govern...
80216  Total non-profit institutions excluding govern...
80321  Non-profit institutions serving households (co...
80328  Non-profit institutions serving households (co...
80342  Non-profit institutions serving households (co...
80447                   Business non-profit institutions
80454                   Business non-profit institutions
80468                   Business non-profit institutions
80573                 Government non-profit institutions
80580                 Government non-profit institutions
80594                 Government non-profit institutions
88889                      Total non-profit institutions
88896                      Total non-profit institutions
88910                      Total non-profit institutions
89015  Total non-profit institutions excluding govern...
89022  Total non-profit institutions excluding govern...

                    Characteristics                   Indicators    UOM  \
80069  High school diploma and less  Average annual hours worked  Hours
80076             Trade certificate  Average annual hours worked  Hours
80090  University degree and higher  Average annual hours worked  Hours
80195  High school diploma and less  Average annual hours worked  Hours
80202             Trade certificate  Average annual hours worked  Hours
80216  University degree and higher  Average annual hours worked  Hours
80321  High school diploma and less  Average annual hours worked  Hours
80328             Trade certificate  Average annual hours worked  Hours
80342  University degree and higher  Average annual hours worked  Hours
80447  High school diploma and less  Average annual hours worked  Hours
80454             Trade certificate  Average annual hours worked  Hours
80468  University degree and higher  Average annual hours worked  Hours
80573  High school diploma and less  Average annual hours worked  Hours
80580             Trade certificate  Average annual hours worked  Hours
80594  University degree and higher  Average annual hours worked  Hours
88889  High school diploma and less  Average annual hours worked  Hours
88896             Trade certificate  Average annual hours worked  Hours
88910  University degree and higher  Average annual hours worked  Hours
89015  High school diploma and less  Average annual hours worked  Hours
89022             Trade certificate  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
80069         units  1408.0
80076         units  1619.0
80090         units  1772.0
80195         units  1260.0
80202         units  1576.0
80216         units  1993.0
80321         units  1230.0
80328         units  1514.0
80342         units  1987.0
80447         units  1353.0
80454         units  1734.0
80468         units  2018.0
80573         units  1475.0
80580         units  1632.0
80594         units  1726.0
88889         units  1411.0
88896         units  1608.0
88910         units  1754.0
89015         units  1200.0
89022         units  1490.0
<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 80069 to 98234
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         45 non-null     int64
 1   GEO              45 non-null     object
 2   Sector           45 non-null     object
 3   Characteristics  45 non-null     object
 4   Indicators       45 non-null     object
 5   UOM              45 non-null     object
 6   SCALAR_FACTOR    45 non-null     object
 7   VALUE            45 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 3.2+ KB
None

Grab the dataset only in Newfoundland and Labrador
                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  20037.0  1335.800000  1178.0  1305.0  1507.0
Trade certificate             23932.0  1595.466667  1445.0  1615.0  1734.0
University degree and higher  28061.0  1870.733333  1726.0  1876.0  2018.0

                              size
Characteristics
High school diploma and less    15
Trade certificate               15
University degree and higher    15

Overall,
Sum :  72030.0
Mean :  1600.6666666666667
Min/median/max : 1178.0 / 1615.0 / 2018.0
Skewnewss :  -0.018789938513471514
Total size :  45

Panda Profiling for Final Result for Newfoundland

In [111]:
# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

Filtering only Northwest Territories.

Only finished "Average annual hours worked".

In [112]:
# -- Northwest Territories         42804.0     41.476744     51.817046  1032

ProCode = 6

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

2013

Grab the dataset only in Northwest Territories
       REF_DATE                    GEO  \
34107      2013  Northwest Territories
34114      2013  Northwest Territories
34121      2013  Northwest Territories
34128      2013  Northwest Territories
34135      2013  Northwest Territories
34142      2013  Northwest Territories
34233      2013  Northwest Territories
34240      2013  Northwest Territories
34247      2013  Northwest Territories
34254      2013  Northwest Territories
34261      2013  Northwest Territories
34268      2013  Northwest Territories
34366      2013  Northwest Territories
34373      2013  Northwest Territories
34380      2013  Northwest Territories
34387      2013  Northwest Territories
34492      2013  Northwest Territories
34499      2013  Northwest Territories
34506      2013  Northwest Territories
34513      2013  Northwest Territories

                                                  Sector  \
34107                      Total non-profit institutions
34114                      Total non-profit institutions
34121                      Total non-profit institutions
34128                      Total non-profit institutions
34135                      Total non-profit institutions
34142                      Total non-profit institutions
34233  Total non-profit institutions excluding govern...
34240  Total non-profit institutions excluding govern...
34247  Total non-profit institutions excluding govern...
34254  Total non-profit institutions excluding govern...
34261  Total non-profit institutions excluding govern...
34268  Total non-profit institutions excluding govern...
34366  Non-profit institutions serving households (co...
34373  Non-profit institutions serving households (co...
34380  Non-profit institutions serving households (co...
34387  Non-profit institutions serving households (co...
34492                   Business non-profit institutions
34499                   Business non-profit institutions
34506                   Business non-profit institutions
34513                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
34107         15 to 24 years  Average annual hours worked  Hours
34114         25 to 34 years  Average annual hours worked  Hours
34121         35 to 44 years  Average annual hours worked  Hours
34128         45 to 54 years  Average annual hours worked  Hours
34135         55 to 64 years  Average annual hours worked  Hours
34142  65 years old and over  Average annual hours worked  Hours
34233         15 to 24 years  Average annual hours worked  Hours
34240         25 to 34 years  Average annual hours worked  Hours
34247         35 to 44 years  Average annual hours worked  Hours
34254         45 to 54 years  Average annual hours worked  Hours
34261         55 to 64 years  Average annual hours worked  Hours
34268  65 years old and over  Average annual hours worked  Hours
34366         25 to 34 years  Average annual hours worked  Hours
34373         35 to 44 years  Average annual hours worked  Hours
34380         45 to 54 years  Average annual hours worked  Hours
34387         55 to 64 years  Average annual hours worked  Hours
34492         25 to 34 years  Average annual hours worked  Hours
34499         35 to 44 years  Average annual hours worked  Hours
34506         45 to 54 years  Average annual hours worked  Hours
34513         55 to 64 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
34107         units   897.0
34114         units  1509.0
34121         units  1769.0
34128         units  1759.0
34135         units  1641.0
34142         units  1233.0
34233         units   782.0
34240         units  1378.0
34247         units  1779.0
34254         units  1682.0
34261         units  1688.0
34268         units  1250.0
34366         units  1330.0
34373         units  1728.0
34380         units  1653.0
34387         units  1673.0
34492         units  1647.0
34499         units  2023.0
34506         units  1814.0
34513         units  1765.0
<class 'pandas.core.frame.DataFrame'>
Index: 78 entries, 34107 to 52286
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         78 non-null     int64
 1   GEO              78 non-null     object
 2   Sector           78 non-null     object
 3   Characteristics  78 non-null     object
 4   Indicators       78 non-null     object
 5   UOM              78 non-null     object
 6   SCALAR_FACTOR    78 non-null     object
 7   VALUE            78 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 5.5+ KB
None

Grab the dataset only in Northwest Territories
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years          8121.0   902.333333   782.0   897.0  1016.0     9
25 to 34 years         21615.0  1441.000000  1236.0  1416.0  1667.0    15
35 to 44 years         26887.0  1792.466667  1675.0  1750.0  2024.0    15
45 to 54 years         25291.0  1686.066667  1523.0  1682.0  1833.0    15
55 to 64 years         24843.0  1656.200000  1528.0  1656.0  1765.0    15
65 years old and over  10594.0  1177.111111  1090.0  1185.0  1250.0     9

Overall,
Sum :  117351.0
Mean :  1504.5
Min/median/max : 782.0 / 1632.0 / 2024.0
Skewnewss :  -0.7876364712236495
Total size :  78
2016

Grab the dataset only in Northwest Territories
       REF_DATE                    GEO  \
60567      2016  Northwest Territories
60574      2016  Northwest Territories
60581      2016  Northwest Territories
60588      2016  Northwest Territories
60595      2016  Northwest Territories
60602      2016  Northwest Territories
60693      2016  Northwest Territories
60700      2016  Northwest Territories
60707      2016  Northwest Territories
60714      2016  Northwest Territories
60721      2016  Northwest Territories
60728      2016  Northwest Territories
60826      2016  Northwest Territories
60833      2016  Northwest Territories
60840      2016  Northwest Territories
60847      2016  Northwest Territories
60952      2016  Northwest Territories
60959      2016  Northwest Territories
60966      2016  Northwest Territories
60973      2016  Northwest Territories

                                                  Sector  \
60567                      Total non-profit institutions
60574                      Total non-profit institutions
60581                      Total non-profit institutions
60588                      Total non-profit institutions
60595                      Total non-profit institutions
60602                      Total non-profit institutions
60693  Total non-profit institutions excluding govern...
60700  Total non-profit institutions excluding govern...
60707  Total non-profit institutions excluding govern...
60714  Total non-profit institutions excluding govern...
60721  Total non-profit institutions excluding govern...
60728  Total non-profit institutions excluding govern...
60826  Non-profit institutions serving households (co...
60833  Non-profit institutions serving households (co...
60840  Non-profit institutions serving households (co...
60847  Non-profit institutions serving households (co...
60952                   Business non-profit institutions
60959                   Business non-profit institutions
60966                   Business non-profit institutions
60973                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
60567         15 to 24 years  Average annual hours worked  Hours
60574         25 to 34 years  Average annual hours worked  Hours
60581         35 to 44 years  Average annual hours worked  Hours
60588         45 to 54 years  Average annual hours worked  Hours
60595         55 to 64 years  Average annual hours worked  Hours
60602  65 years old and over  Average annual hours worked  Hours
60693         15 to 24 years  Average annual hours worked  Hours
60700         25 to 34 years  Average annual hours worked  Hours
60707         35 to 44 years  Average annual hours worked  Hours
60714         45 to 54 years  Average annual hours worked  Hours
60721         55 to 64 years  Average annual hours worked  Hours
60728  65 years old and over  Average annual hours worked  Hours
60826         25 to 34 years  Average annual hours worked  Hours
60833         35 to 44 years  Average annual hours worked  Hours
60840         45 to 54 years  Average annual hours worked  Hours
60847         55 to 64 years  Average annual hours worked  Hours
60952         25 to 34 years  Average annual hours worked  Hours
60959         35 to 44 years  Average annual hours worked  Hours
60966         45 to 54 years  Average annual hours worked  Hours
60973         55 to 64 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
60567         units   942.0
60574         units  1443.0
60581         units  1747.0
60588         units  1680.0
60595         units  1626.0
60602         units  1149.0
60693         units   856.0
60700         units  1360.0
60707         units  1747.0
60714         units  1605.0
60721         units  1695.0
60728         units  1210.0
60826         units  1311.0
60833         units  1691.0
60840         units  1575.0
60847         units  1677.0
60952         units  1610.0
60959         units  1957.0
60966         units  1717.0
60973         units  1789.0
<class 'pandas.core.frame.DataFrame'>
Index: 78 entries, 60567 to 78746
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         78 non-null     int64
 1   GEO              78 non-null     object
 2   Sector           78 non-null     object
 3   Characteristics  78 non-null     object
 4   Indicators       78 non-null     object
 5   UOM              78 non-null     object
 6   SCALAR_FACTOR    78 non-null     object
 7   VALUE            78 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 5.5+ KB
None

Grab the dataset only in Northwest Territories
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years          8580.0   953.333333   856.0   955.0  1027.0     9
25 to 34 years         21907.0  1460.466667  1311.0  1443.0  1721.0    15
35 to 44 years         26472.0  1764.800000  1638.0  1747.0  2000.0    15
45 to 54 years         25273.0  1684.866667  1575.0  1699.0  1844.0    15
55 to 64 years         25076.0  1671.733333  1578.0  1653.0  1828.0    15
65 years old and over  10296.0  1144.000000  1106.0  1137.0  1210.0     9

Overall,
Sum :  117604.0
Mean :  1507.7435897435898
Min/median/max : 856.0 / 1620.5 / 2000.0
Skewnewss :  -0.7411756712707891
Total size :  78
2019

Grab the dataset only in Northwest Territories
       REF_DATE                    GEO  \
87027      2019  Northwest Territories
87034      2019  Northwest Territories
87041      2019  Northwest Territories
87048      2019  Northwest Territories
87055      2019  Northwest Territories
87062      2019  Northwest Territories
87153      2019  Northwest Territories
87160      2019  Northwest Territories
87167      2019  Northwest Territories
87174      2019  Northwest Territories
87181      2019  Northwest Territories
87188      2019  Northwest Territories
87286      2019  Northwest Territories
87293      2019  Northwest Territories
87300      2019  Northwest Territories
87307      2019  Northwest Territories
87412      2019  Northwest Territories
87419      2019  Northwest Territories
87426      2019  Northwest Territories
87433      2019  Northwest Territories

                                                  Sector  \
87027                      Total non-profit institutions
87034                      Total non-profit institutions
87041                      Total non-profit institutions
87048                      Total non-profit institutions
87055                      Total non-profit institutions
87062                      Total non-profit institutions
87153  Total non-profit institutions excluding govern...
87160  Total non-profit institutions excluding govern...
87167  Total non-profit institutions excluding govern...
87174  Total non-profit institutions excluding govern...
87181  Total non-profit institutions excluding govern...
87188  Total non-profit institutions excluding govern...
87286  Non-profit institutions serving households (co...
87293  Non-profit institutions serving households (co...
87300  Non-profit institutions serving households (co...
87307  Non-profit institutions serving households (co...
87412                   Business non-profit institutions
87419                   Business non-profit institutions
87426                   Business non-profit institutions
87433                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
87027         15 to 24 years  Average annual hours worked  Hours
87034         25 to 34 years  Average annual hours worked  Hours
87041         35 to 44 years  Average annual hours worked  Hours
87048         45 to 54 years  Average annual hours worked  Hours
87055         55 to 64 years  Average annual hours worked  Hours
87062  65 years old and over  Average annual hours worked  Hours
87153         15 to 24 years  Average annual hours worked  Hours
87160         25 to 34 years  Average annual hours worked  Hours
87167         35 to 44 years  Average annual hours worked  Hours
87174         45 to 54 years  Average annual hours worked  Hours
87181         55 to 64 years  Average annual hours worked  Hours
87188  65 years old and over  Average annual hours worked  Hours
87286         25 to 34 years  Average annual hours worked  Hours
87293         35 to 44 years  Average annual hours worked  Hours
87300         45 to 54 years  Average annual hours worked  Hours
87307         55 to 64 years  Average annual hours worked  Hours
87412         25 to 34 years  Average annual hours worked  Hours
87419         35 to 44 years  Average annual hours worked  Hours
87426         45 to 54 years  Average annual hours worked  Hours
87433         55 to 64 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
87027         units   988.0
87034         units  1482.0
87041         units  1722.0
87048         units  1752.0
87055         units  1636.0
87062         units  1132.0
87153         units   974.0
87160         units  1433.0
87167         units  1663.0
87174         units  1650.0
87181         units  1629.0
87188         units  1149.0
87286         units  1405.0
87293         units  1628.0
87300         units  1612.0
87307         units  1613.0
87412         units  1674.0
87419         units  1921.0
87426         units  1871.0
87433         units  1800.0
<class 'pandas.core.frame.DataFrame'>
Index: 78 entries, 87027 to 105206
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         78 non-null     int64
 1   GEO              78 non-null     object
 2   Sector           78 non-null     object
 3   Characteristics  78 non-null     object
 4   Indicators       78 non-null     object
 5   UOM              78 non-null     object
 6   SCALAR_FACTOR    78 non-null     object
 7   VALUE            78 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 5.5+ KB
None

Grab the dataset only in Northwest Territories
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years          8928.0   992.000000   933.0   988.0  1053.0     9
25 to 34 years         22546.0  1503.066667  1385.0  1470.0  1674.0    15
35 to 44 years         25852.0  1723.466667  1577.0  1663.0  1923.0    15
45 to 54 years         26041.0  1736.066667  1541.0  1746.0  1921.0    15
55 to 64 years         24700.0  1646.666667  1532.0  1629.0  1800.0    15
65 years old and over  10051.0  1116.777778  1029.0  1132.0  1172.0     9

Overall,
Sum :  118118.0
Mean :  1514.3333333333333
Min/median/max : 933.0 / 1611.0 / 1923.0
Skewnewss :  -0.7095023931536831
Total size :  78
2013

Grab the dataset only in Northwest Territories
       REF_DATE                    GEO  \
34023      2013  Northwest Territories
34030      2013  Northwest Territories
34149      2013  Northwest Territories
34156      2013  Northwest Territories
34275      2013  Northwest Territories
34282      2013  Northwest Territories
34401      2013  Northwest Territories
34408      2013  Northwest Territories
34527      2013  Northwest Territories
34534      2013  Northwest Territories
42843      2014  Northwest Territories
42850      2014  Northwest Territories
42969      2014  Northwest Territories
42976      2014  Northwest Territories
43095      2014  Northwest Territories
43102      2014  Northwest Territories
43221      2014  Northwest Territories
43228      2014  Northwest Territories
43347      2014  Northwest Territories
43354      2014  Northwest Territories

                                                  Sector   Characteristics  \
34023                      Total non-profit institutions    Male employees
34030                      Total non-profit institutions  Female employees
34149  Total non-profit institutions excluding govern...    Male employees
34156  Total non-profit institutions excluding govern...  Female employees
34275  Non-profit institutions serving households (co...    Male employees
34282  Non-profit institutions serving households (co...  Female employees
34401                   Business non-profit institutions    Male employees
34408                   Business non-profit institutions  Female employees
34527                 Government non-profit institutions    Male employees
34534                 Government non-profit institutions  Female employees
42843                      Total non-profit institutions    Male employees
42850                      Total non-profit institutions  Female employees
42969  Total non-profit institutions excluding govern...    Male employees
42976  Total non-profit institutions excluding govern...  Female employees
43095  Non-profit institutions serving households (co...    Male employees
43102  Non-profit institutions serving households (co...  Female employees
43221                   Business non-profit institutions    Male employees
43228                   Business non-profit institutions  Female employees
43347                 Government non-profit institutions    Male employees
43354                 Government non-profit institutions  Female employees

                        Indicators    UOM SCALAR_FACTOR   VALUE
34023  Average annual hours worked  Hours         units  1575.0
34030  Average annual hours worked  Hours         units  1544.0
34149  Average annual hours worked  Hours         units  1521.0
34156  Average annual hours worked  Hours         units  1411.0
34275  Average annual hours worked  Hours         units  1453.0
34282  Average annual hours worked  Hours         units  1380.0
34401  Average annual hours worked  Hours         units  1774.0
34408  Average annual hours worked  Hours         units  1607.0
34527  Average annual hours worked  Hours         units  1624.0
34534  Average annual hours worked  Hours         units  1601.0
42843  Average annual hours worked  Hours         units  1514.0
42850  Average annual hours worked  Hours         units  1462.0
42969  Average annual hours worked  Hours         units  1498.0
42976  Average annual hours worked  Hours         units  1349.0
43095  Average annual hours worked  Hours         units  1431.0
43102  Average annual hours worked  Hours         units  1317.0
43221  Average annual hours worked  Hours         units  1779.0
43228  Average annual hours worked  Hours         units  1574.0
43347  Average annual hours worked  Hours         units  1530.0
43354  Average annual hours worked  Hours         units  1513.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 34023 to 52174

Panda Profiling for Final Result for Northwest Territories

In [113]:
# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

Filtering only Nova Scotia.

Only finished "Average annual hours worked".

In [114]:
# -- Nova Scotia                  531805.0    492.412037    757.119411  1080

ProCode = 7

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

2013

Grab the dataset only in Nova Scotia
       REF_DATE          GEO  \
28437      2013  Nova Scotia
28444      2013  Nova Scotia
28451      2013  Nova Scotia
28458      2013  Nova Scotia
28465      2013  Nova Scotia
28472      2013  Nova Scotia
28563      2013  Nova Scotia
28570      2013  Nova Scotia
28577      2013  Nova Scotia
28584      2013  Nova Scotia
28591      2013  Nova Scotia
28598      2013  Nova Scotia
28689      2013  Nova Scotia
28696      2013  Nova Scotia
28703      2013  Nova Scotia
28710      2013  Nova Scotia
28717      2013  Nova Scotia
28724      2013  Nova Scotia
28815      2013  Nova Scotia
28822      2013  Nova Scotia

                                                  Sector  \
28437                      Total non-profit institutions
28444                      Total non-profit institutions
28451                      Total non-profit institutions
28458                      Total non-profit institutions
28465                      Total non-profit institutions
28472                      Total non-profit institutions
28563  Total non-profit institutions excluding govern...
28570  Total non-profit institutions excluding govern...
28577  Total non-profit institutions excluding govern...
28584  Total non-profit institutions excluding govern...
28591  Total non-profit institutions excluding govern...
28598  Total non-profit institutions excluding govern...
28689  Non-profit institutions serving households (co...
28696  Non-profit institutions serving households (co...
28703  Non-profit institutions serving households (co...
28710  Non-profit institutions serving households (co...
28717  Non-profit institutions serving households (co...
28724  Non-profit institutions serving households (co...
28815                   Business non-profit institutions
28822                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
28437         15 to 24 years  Average annual hours worked  Hours
28444         25 to 34 years  Average annual hours worked  Hours
28451         35 to 44 years  Average annual hours worked  Hours
28458         45 to 54 years  Average annual hours worked  Hours
28465         55 to 64 years  Average annual hours worked  Hours
28472  65 years old and over  Average annual hours worked  Hours
28563         15 to 24 years  Average annual hours worked  Hours
28570         25 to 34 years  Average annual hours worked  Hours
28577         35 to 44 years  Average annual hours worked  Hours
28584         45 to 54 years  Average annual hours worked  Hours
28591         55 to 64 years  Average annual hours worked  Hours
28598  65 years old and over  Average annual hours worked  Hours
28689         15 to 24 years  Average annual hours worked  Hours
28696         25 to 34 years  Average annual hours worked  Hours
28703         35 to 44 years  Average annual hours worked  Hours
28710         45 to 54 years  Average annual hours worked  Hours
28717         55 to 64 years  Average annual hours worked  Hours
28724  65 years old and over  Average annual hours worked  Hours
28815         15 to 24 years  Average annual hours worked  Hours
28822         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
28437         units   886.0
28444         units  1606.0
28451         units  1802.0
28458         units  1849.0
28465         units  1681.0
28472         units   987.0
28563         units   828.0
28570         units  1664.0
28577         units  1849.0
28584         units  1872.0
28591         units  1728.0
28598         units  1077.0
28689         units   817.0
28696         units  1636.0
28703         units  1810.0
28710         units  1842.0
28717         units  1699.0
28724         units  1039.0
28815         units   865.0
28822         units  1787.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 28437 to 46616
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Nova Scotia
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         13130.0   875.333333   817.0   868.0   975.0    15
25 to 34 years         24931.0  1662.066667  1584.0  1644.0  1787.0    15
35 to 44 years         27720.0  1848.000000  1774.0  1822.0  2023.0    15
45 to 54 years         28269.0  1884.600000  1812.0  1870.0  2036.0    15
55 to 64 years         25959.0  1730.600000  1664.0  1707.0  1852.0    15
65 years old and over  16588.0  1105.866667   946.0  1077.0  1335.0    15

Overall,
Sum :  136597.0
Mean :  1517.7444444444445
Min/median/max : 817.0 / 1690.0 / 2036.0
Skewnewss :  -0.6761244717526232
Total size :  90
2016

Grab the dataset only in Nova Scotia
       REF_DATE          GEO  \
54897      2016  Nova Scotia
54904      2016  Nova Scotia
54911      2016  Nova Scotia
54918      2016  Nova Scotia
54925      2016  Nova Scotia
54932      2016  Nova Scotia
55023      2016  Nova Scotia
55030      2016  Nova Scotia
55037      2016  Nova Scotia
55044      2016  Nova Scotia
55051      2016  Nova Scotia
55058      2016  Nova Scotia
55149      2016  Nova Scotia
55156      2016  Nova Scotia
55163      2016  Nova Scotia
55170      2016  Nova Scotia
55177      2016  Nova Scotia
55184      2016  Nova Scotia
55275      2016  Nova Scotia
55282      2016  Nova Scotia

                                                  Sector  \
54897                      Total non-profit institutions
54904                      Total non-profit institutions
54911                      Total non-profit institutions
54918                      Total non-profit institutions
54925                      Total non-profit institutions
54932                      Total non-profit institutions
55023  Total non-profit institutions excluding govern...
55030  Total non-profit institutions excluding govern...
55037  Total non-profit institutions excluding govern...
55044  Total non-profit institutions excluding govern...
55051  Total non-profit institutions excluding govern...
55058  Total non-profit institutions excluding govern...
55149  Non-profit institutions serving households (co...
55156  Non-profit institutions serving households (co...
55163  Non-profit institutions serving households (co...
55170  Non-profit institutions serving households (co...
55177  Non-profit institutions serving households (co...
55184  Non-profit institutions serving households (co...
55275                   Business non-profit institutions
55282                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
54897         15 to 24 years  Average annual hours worked  Hours
54904         25 to 34 years  Average annual hours worked  Hours
54911         35 to 44 years  Average annual hours worked  Hours
54918         45 to 54 years  Average annual hours worked  Hours
54925         55 to 64 years  Average annual hours worked  Hours
54932  65 years old and over  Average annual hours worked  Hours
55023         15 to 24 years  Average annual hours worked  Hours
55030         25 to 34 years  Average annual hours worked  Hours
55037         35 to 44 years  Average annual hours worked  Hours
55044         45 to 54 years  Average annual hours worked  Hours
55051         55 to 64 years  Average annual hours worked  Hours
55058  65 years old and over  Average annual hours worked  Hours
55149         15 to 24 years  Average annual hours worked  Hours
55156         25 to 34 years  Average annual hours worked  Hours
55163         35 to 44 years  Average annual hours worked  Hours
55170         45 to 54 years  Average annual hours worked  Hours
55177         55 to 64 years  Average annual hours worked  Hours
55184  65 years old and over  Average annual hours worked  Hours
55275         15 to 24 years  Average annual hours worked  Hours
55282         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
54897         units   931.0
54904         units  1678.0
54911         units  1863.0
54918         units  1927.0
54925         units  1750.0
54932         units  1093.0
55023         units   861.0
55030         units  1634.0
55037         units  1793.0
55044         units  1850.0
55051         units  1689.0
55058         units  1123.0
55149         units   859.0
55156         units  1611.0
55163         units  1760.0
55170         units  1821.0
55177         units  1668.0
55184         units  1098.0
55275         units   867.0
55282         units  1722.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 54897 to 73076
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Nova Scotia
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         13656.0   910.400000   859.0   908.0   988.0    15
25 to 34 years         24697.0  1646.466667  1583.0  1634.0  1733.0    15
35 to 44 years         27409.0  1827.266667  1732.0  1804.0  1976.0    15
45 to 54 years         28430.0  1895.333333  1796.0  1891.0  2035.0    15
55 to 64 years         25613.0  1707.533333  1630.0  1689.0  1802.0    15
65 years old and over  16433.0  1095.533333   996.0  1078.0  1234.0    15

Overall,
Sum :  136238.0
Mean :  1513.7555555555555
Min/median/max : 859.0 / 1678.5 / 2035.0
Skewnewss :  -0.6082046234537549
Total size :  90
2019

Grab the dataset only in Nova Scotia
       REF_DATE          GEO  \
81357      2019  Nova Scotia
81364      2019  Nova Scotia
81371      2019  Nova Scotia
81378      2019  Nova Scotia
81385      2019  Nova Scotia
81392      2019  Nova Scotia
81483      2019  Nova Scotia
81490      2019  Nova Scotia
81497      2019  Nova Scotia
81504      2019  Nova Scotia
81511      2019  Nova Scotia
81518      2019  Nova Scotia
81609      2019  Nova Scotia
81616      2019  Nova Scotia
81623      2019  Nova Scotia
81630      2019  Nova Scotia
81637      2019  Nova Scotia
81644      2019  Nova Scotia
81735      2019  Nova Scotia
81742      2019  Nova Scotia

                                                  Sector  \
81357                      Total non-profit institutions
81364                      Total non-profit institutions
81371                      Total non-profit institutions
81378                      Total non-profit institutions
81385                      Total non-profit institutions
81392                      Total non-profit institutions
81483  Total non-profit institutions excluding govern...
81490  Total non-profit institutions excluding govern...
81497  Total non-profit institutions excluding govern...
81504  Total non-profit institutions excluding govern...
81511  Total non-profit institutions excluding govern...
81518  Total non-profit institutions excluding govern...
81609  Non-profit institutions serving households (co...
81616  Non-profit institutions serving households (co...
81623  Non-profit institutions serving households (co...
81630  Non-profit institutions serving households (co...
81637  Non-profit institutions serving households (co...
81644  Non-profit institutions serving households (co...
81735                   Business non-profit institutions
81742                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
81357         15 to 24 years  Average annual hours worked  Hours
81364         25 to 34 years  Average annual hours worked  Hours
81371         35 to 44 years  Average annual hours worked  Hours
81378         45 to 54 years  Average annual hours worked  Hours
81385         55 to 64 years  Average annual hours worked  Hours
81392  65 years old and over  Average annual hours worked  Hours
81483         15 to 24 years  Average annual hours worked  Hours
81490         25 to 34 years  Average annual hours worked  Hours
81497         35 to 44 years  Average annual hours worked  Hours
81504         45 to 54 years  Average annual hours worked  Hours
81511         55 to 64 years  Average annual hours worked  Hours
81518  65 years old and over  Average annual hours worked  Hours
81609         15 to 24 years  Average annual hours worked  Hours
81616         25 to 34 years  Average annual hours worked  Hours
81623         35 to 44 years  Average annual hours worked  Hours
81630         45 to 54 years  Average annual hours worked  Hours
81637         55 to 64 years  Average annual hours worked  Hours
81644  65 years old and over  Average annual hours worked  Hours
81735         15 to 24 years  Average annual hours worked  Hours
81742         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
81357         units   966.0
81364         units  1624.0
81371         units  1788.0
81378         units  1890.0
81385         units  1700.0
81392         units  1078.0
81483         units   918.0
81490         units  1635.0
81497         units  1831.0
81504         units  1923.0
81511         units  1701.0
81518         units  1127.0
81609         units   933.0
81616         units  1615.0
81623         units  1801.0
81630         units  1897.0
81637         units  1680.0
81644         units  1121.0
81735         units   878.0
81742         units  1711.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 81357 to 99536
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Nova Scotia
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         13970.0   931.333333   832.0   931.0  1020.0    15
25 to 34 years         24395.0  1626.333333  1521.0  1624.0  1711.0    15
35 to 44 years         27161.0  1810.733333  1708.0  1789.0  1958.0    15
45 to 54 years         28690.0  1912.666667  1818.0  1897.0  2031.0    15
55 to 64 years         25439.0  1695.933333  1595.0  1700.0  1783.0    15
65 years old and over  16397.0  1093.133333  1017.0  1083.0  1158.0    15

Overall,
Sum :  136052.0
Mean :  1511.6888888888889
Min/median/max : 832.0 / 1660.5 / 2031.0
Skewnewss :  -0.548394669821195
Total size :  90
2013

Grab the dataset only in Nova Scotia
       REF_DATE          GEO  \
28353      2013  Nova Scotia
28360      2013  Nova Scotia
28479      2013  Nova Scotia
28486      2013  Nova Scotia
28605      2013  Nova Scotia
28612      2013  Nova Scotia
28731      2013  Nova Scotia
28738      2013  Nova Scotia
28857      2013  Nova Scotia
28864      2013  Nova Scotia
37173      2014  Nova Scotia
37180      2014  Nova Scotia
37299      2014  Nova Scotia
37306      2014  Nova Scotia
37425      2014  Nova Scotia
37432      2014  Nova Scotia
37551      2014  Nova Scotia
37558      2014  Nova Scotia
37677      2014  Nova Scotia
37684      2014  Nova Scotia

                                                  Sector   Characteristics  \
28353                      Total non-profit institutions    Male employees
28360                      Total non-profit institutions  Female employees
28479  Total non-profit institutions excluding govern...    Male employees
28486  Total non-profit institutions excluding govern...  Female employees
28605  Non-profit institutions serving households (co...    Male employees
28612  Non-profit institutions serving households (co...  Female employees
28731                   Business non-profit institutions    Male employees
28738                   Business non-profit institutions  Female employees
28857                 Government non-profit institutions    Male employees
28864                 Government non-profit institutions  Female employees
37173                      Total non-profit institutions    Male employees
37180                      Total non-profit institutions  Female employees
37299  Total non-profit institutions excluding govern...    Male employees
37306  Total non-profit institutions excluding govern...  Female employees
37425  Non-profit institutions serving households (co...    Male employees
37432  Non-profit institutions serving households (co...  Female employees
37551                   Business non-profit institutions    Male employees
37558                   Business non-profit institutions  Female employees
37677                 Government non-profit institutions    Male employees
37684                 Government non-profit institutions  Female employees

                        Indicators    UOM SCALAR_FACTOR   VALUE
28353  Average annual hours worked  Hours         units  1624.0
28360  Average annual hours worked  Hours         units  1593.0
28479  Average annual hours worked  Hours         units  1667.0
28486  Average annual hours worked  Hours         units  1564.0
28605  Average annual hours worked  Hours         units  1635.0
28612  Average annual hours worked  Hours         units  1549.0
28731  Average annual hours worked  Hours         units  1754.0
28738  Average annual hours worked  Hours         units  1647.0
28857  Average annual hours worked  Hours         units  1604.0
28864  Average annual hours worked  Hours         units  1603.0
37173  Average annual hours worked  Hours         units  1659.0
37180  Average annual hours worked  Hours         units  1618.0
37299  Average annual hours worked  Hours         units  1646.0
37306  Average annual hours worked  Hours         units  1545.0
37425  Average annual hours worked  Hours         units  1619.0
37432  Average annual hours worked  Hours         units  1539.0
37551  Average annual hours worked  Hours         units  1727.0
37558  Average annual hours worked  Hours         units  1584.0
37677  Average annual hours worked  Hours         units  1665.0
37684  Average annual hours worked  Hours         units  1642.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 28353 to 46504
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         30 non-null     int64
 1   GEO              30 non-null     object
 2   Sector           30 non-null     object
 3   Characteristics  30 non-null     object
 4   Indicators       30 non-null     object
 5   UOM              30 non-null     object
 6   SCALAR_FACTOR    30 non-null     object
 7   VALUE            30 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.1+ KB
None

Grab the dataset only in Nova Scotia
                      sum         mean    amin  median    amax  size
Characteristics
Female employees  23902.0  1593.466667  1539.0  1593.0  1647.0    15
Male employees    25092.0  1672.800000  1604.0  1665.0  1774.0    15

Overall,
Sum :  48994.0
Mean :  1633.1333333333334
Min/median/max : 1539.0 / 1629.0 / 1774.0

                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  19633.0  1308.866667  1192.0  1318.0  1429.0
Trade certificate             24443.0  1629.533333  1512.0  1622.0  1805.0
University degree and higher  26653.0  1776.866667  1673.0  1770.0  1894.0

                              size
Characteristics
High school diploma and less    15
Trade certificate               15
University degree and higher    15

Overall,
Sum :  70729.0
Mean :  1571.7555555555555
Min/median/max : 1192.0 / 1622.0 / 1894.0
Skewnewss :  -0.358085565941755
Total size :  45
2016

Grab the dataset only in Nova Scotia
       REF_DATE          GEO  \
54869      2016  Nova Scotia
54876      2016  Nova Scotia
54890      2016  Nova Scotia
54995      2016  Nova Scotia
55002      2016  Nova Scotia
55016      2016  Nova Scotia
55121      2016  Nova Scotia
55128      2016  Nova Scotia
55142      2016  Nova Scotia
55247      2016  Nova Scotia
55254      2016  Nova Scotia
55268      2016  Nova Scotia
55373      2016  Nova Scotia
55380      2016  Nova Scotia
55394      2016  Nova Scotia
63689      2017  Nova Scotia
63696      2017  Nova Scotia
63710      2017  Nova Scotia
63815      2017  Nova Scotia
63822      2017  Nova Scotia

                                                  Sector  \
54869                      Total non-profit institutions
54876                      Total non-profit institutions
54890                      Total non-profit institutions
54995  Total non-profit institutions excluding govern...
55002  Total non-profit institutions excluding govern...
55016  Total non-profit institutions excluding govern...
55121  Non-profit institutions serving households (co...
55128  Non-profit institutions serving households (co...
55142  Non-profit institutions serving households (co...
55247                   Business non-profit institutions
55254                   Business non-profit institutions
55268                   Business non-profit institutions
55373                 Government non-profit institutions
55380                 Government non-profit institutions
55394                 Government non-profit institutions
63689                      Total non-profit institutions
63696                      Total non-profit institutions
63710                      Total non-profit institutions
63815  Total non-profit institutions excluding govern...
63822  Total non-profit institutions excluding govern...

                    Characteristics                   Indicators    UOM  \
54869  High school diploma and less  Average annual hours worked  Hours
54876             Trade certificate  Average annual hours worked  Hours
54890  University degree and higher  Average annual hours worked  Hours
54995  High school diploma and less  Average annual hours worked  Hours
55002             Trade certificate  Average annual hours worked  Hours
55016  University degree and higher  Average annual hours worked  Hours
55121  High school diploma and less  Average annual hours worked  Hours
55128             Trade certificate  Average annual hours worked  Hours
55142  University degree and higher  Average annual hours worked  Hours
55247  High school diploma and less  Average annual hours worked  Hours
55254             Trade certificate  Average annual hours worked  Hours
55268  University degree and higher  Average annual hours worked  Hours
55373  High school diploma and less  Average annual hours worked  Hours
55380             Trade certificate  Average annual hours worked  Hours
55394  University degree and higher  Average annual hours worked  Hours
63689  High school diploma and less  Average annual hours worked  Hours
63696             Trade certificate  Average annual hours worked  Hours
63710  University degree and higher  Average annual hours worked  Hours
63815  High school diploma and less  Average annual hours worked  Hours
63822             Trade certificate  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
54869         units  1346.0
54876         units  1655.0
54890         units  1789.0
54995         units  1248.0
55002         units  1539.0
55016         units  1762.0
55121         units  1201.0
55128         units  1497.0
55142         units  1751.0
55247         units  1381.0
55254         units  1677.0
55268         units  1809.0
55373         units  1404.0
55380         units  1698.0
55394         units  1797.0
63689         units  1292.0
63696         units  1585.0
63710         units  1715.0
63815         units  1246.0
63822         units  1530.0
<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 54869 to 73034
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         45 non-null     int64
 1   GEO              45 non-null     object
 2   Sector           45 non-null     object
 3   Characteristics  45 non-null     object
 4   Indicators       45 non-null     object
 5   UOM              45 non-null     object
 6   SCALAR_FACTOR    45 non-null     object
 7   VALUE            45 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 3.2+ KB
None

Grab the dataset only in Nova Scotia
                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  19593.0  1306.200000  1192.0  1316.0  1417.0
Trade certificate             23963.0  1597.533333  1481.0  1605.0  1698.0
University degree and higher  26379.0  1758.600000  1709.0  1751.0  1852.0

                              size
Characteristics
High school diploma and less    15
Trade certificate               15
University degree and higher    15

Overall,
Sum :  69935.0
Mean :  1554.111111111111
Min/median/max : 1192.0 / 1605.0 / 1852.0
Skewnewss :  -0.40096981546518
Total size :  45
2019

Grab the dataset only in Nova Scotia
       REF_DATE          GEO  \
81329      2019  Nova Scotia
81336      2019  Nova Scotia
81350      2019  Nova Scotia
81455      2019  Nova Scotia
81462      2019  Nova Scotia
81476      2019  Nova Scotia
81581      2019  Nova Scotia
81588      2019  Nova Scotia
81602      2019  Nova Scotia
81707      2019  Nova Scotia
81714      2019  Nova Scotia
81728      2019  Nova Scotia
81833      2019  Nova Scotia
81840      2019  Nova Scotia
81854      2019  Nova Scotia
90149      2020  Nova Scotia
90156      2020  Nova Scotia
90170      2020  Nova Scotia
90275      2020  Nova Scotia
90282      2020  Nova Scotia

                                                  Sector  \
81329                      Total non-profit institutions
81336                      Total non-profit institutions
81350                      Total non-profit institutions
81455  Total non-profit institutions excluding govern...
81462  Total non-profit institutions excluding govern...
81476  Total non-profit institutions excluding govern...
81581  Non-profit institutions serving households (co...
81588  Non-profit institutions serving households (co...
81602  Non-profit institutions serving households (co...
81707                   Business non-profit institutions
81714                   Business non-profit institutions
81728                   Business non-profit institutions
81833                 Government non-profit institutions
81840                 Government non-profit institutions
81854                 Government non-profit institutions
90149                      Total non-profit institutions
90156                      Total non-profit institutions
90170                      Total non-profit institutions
90275  Total non-profit institutions excluding govern...
90282  Total non-profit institutions excluding govern...

                    Characteristics                   Indicators    UOM  \
81329  High school diploma and less  Average annual hours worked  Hours
81336             Trade certificate  Average annual hours worked  Hours
81350  University degree and higher  Average annual hours worked  Hours
81455  High school diploma and less  Average annual hours worked  Hours
81462             Trade certificate  Average annual hours worked  Hours
81476  University degree and higher  Average annual hours worked  Hours
81581  High school diploma and less  Average annual hours worked  Hours
81588             Trade certificate  Average annual hours worked  Hours
81602  University degree and higher  Average annual hours worked  Hours
81707  High school diploma and less  Average annual hours worked  Hours
81714             Trade certificate  Average annual hours worked  Hours
81728  University degree and higher  Average annual hours worked  Hours
81833  High school diploma and less  Average annual hours worked  Hours
81840             Trade certificate  Average annual hours worked  Hours
81854  University degree and higher  Average annual hours worked  Hours
90149  High school diploma and less  Average annual hours worked  Hours
90156             Trade certificate  Average annual hours worked  Hours
90170  University degree and higher  Average annual hours worked  Hours
90275  High school diploma and less  Average annual hours worked  Hours
90282             Trade certificate  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
81329         units  1324.0
81336         units  1612.0
81350         units  1724.0
81455         units  1279.0
81462         units  1575.0
81476         units  1783.0
81581         units  1240.0
81588         units  1541.0
81602         units  1771.0
81707         units  1388.0
81714         units  1688.0
81728         units  1837.0
81833         units  1348.0
81840         units  1626.0
81854         units  1705.0
90149         units  1329.0
90156         units  1613.0
90170         units  1757.0
90275         units  1217.0
90282         units  1494.0
<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 81329 to 99494
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         45 non-null     int64
 1   GEO              45 non-null     object
 2   Sector           45 non-null     object
 3   Characteristics  45 non-null     object
 4   Indicators       45 non-null     object
 5   UOM              45 non-null     object
 6   SCALAR_FACTOR    45 non-null     object
 7   VALUE            45 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 3.2+ KB
None

Grab the dataset only in Nova Scotia
                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  19503.0  1300.200000  1178.0  1324.0  1388.0
Trade certificate             23734.0  1582.266667  1462.0  1607.0  1688.0
University degree and higher  26268.0  1751.200000  1689.0  1733.0  1837.0

                              size
Characteristics
High school diploma and less    15
Trade certificate               15
University degree and higher    15

Overall,
Sum :  69505.0
Mean :  1544.5555555555557
Min/median/max : 1178.0 / 1607.0 / 1837.0
Skewnewss :  -0.32747583947326697
Total size :  45
2013

Grab the dataset only in Nova Scotia
       REF_DATE          GEO  \
28409      2013  Nova Scotia
28416      2013  Nova Scotia
28430      2013  Nova Scotia
28535      2013  Nova Scotia
28542      2013  Nova Scotia
28556      2013  Nova Scotia
28661      2013  Nova Scotia
28668      2013  Nova Scotia
28682      2013  Nova Scotia
28787      2013  Nova Scotia
28794      2013  Nova Scotia
28808      2013  Nova Scotia
28913      2013  Nova Scotia
28920      2013  Nova Scotia
28934      2013  Nova Scotia
37229      2014  Nova Scotia
37236      2014  Nova Scotia
37250      2014  Nova Scotia
37355      2014  Nova Scotia
37362      2014  Nova Scotia

                                                  Sector  \
28409                      Total non-profit institutions
28416                      Total non-profit institutions
28430                      Total non-profit institutions
28535  Total non-profit institutions excluding govern...
28542  Total non-profit institutions excluding govern...
28556  Total non-profit institutions excluding govern...
28661  Non-profit institutions serving households (co...
28668  Non-profit institutions serving households (co...
28682  Non-profit institutions serving households (co...
28787                   Business non-profit institutions
28794                   Business non-profit institutions
28808                   Business non-profit institutions
28913                 Government non-profit institutions
28920                 Government non-profit institutions
28934                 Government non-profit institutions
37229                      Total non-profit institutions
37236                      Total non-profit institutions
37250                      Total non-profit institutions
37355  Total non-profit institutions excluding govern...
37362  Total non-profit institutions excluding govern...

                    Characteristics                   Indicators    UOM  \
28409  High school diploma and less  Average annual hours worked  Hours
28416             Trade certificate  Average annual hours worked  Hours
28430  University degree and higher  Average annual hours worked  Hours
28535  High school diploma and less  Average annual hours worked  Hours
28542             Trade certificate  Average annual hours worked  Hours
28556  University degree and higher  Average annual hours worked  Hours
28661  High school diploma and less  Average annual hours worked  Hours
28668             Trade certificate  Average annual hours worked  Hours
28682  University degree and higher  Average annual hours worked  Hours
28787  High school diploma and less  Average annual hours worked  Hours
28794             Trade certificate  Average annual hours worked  Hours
28808  University degree and higher  Average annual hours worked  Hours
28913  High school diploma and less  Average annual hours worked  Hours
28920             Trade certificate  Average annual hours worked  Hours
28934  University degree and higher  Average annual hours worked  Hours
37229  High school diploma and less  Average annual hours worked  Hours
37236             Trade certificate  Average annual hours worked  Hours
37250  University degree and higher  Average annual hours worked  Hours
37355  High school diploma and less  Average annual hours worked  Hours
37362             Trade certificate  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
28409         units  1296.0
28416         units  1618.0
28430         units  1706.0
28535         units  1249.0
28542         units  1605.0
28556         units  1805.0
28661         units  1192.0
28668         units  1547.0
28682         units  1787.0
28787         units  1421.0
28794         units  1805.0
28808         units  1894.0
28913         units  1322.0
28920         units  1622.0
28934         units  1673.0
37229         units  1318.0
37236         units  1625.0
37250         units  1745.0
37355         units  1242.0
37362         units  1564.0
<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 28409 to 46574
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         45 non-null     int64
 1   GEO              45 non-null     object
 2   Sector           45 non-null     object
 3   Characteristics  45 non-null     object
 4   Indicators       45 non-null     object
 5   UOM              45 non-null     object
 6   SCALAR_FACTOR    45 non-null     object
 7   VALUE            45 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 3.2+ KB
None

Grab the dataset only in Nova Scotia
                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  19633.0  1308.866667  1192.0  1318.0  1429.0
Trade certificate             24443.0  1629.533333  1512.0  1622.0  1805.0
University degree and higher  26653.0  1776.866667  1673.0  1770.0  1894.0

                              size
Characteristics
High school diploma and less    15
Trade certificate               15
University degree and higher    15

Overall,
Sum :  70729.0
Mean :  1571.7555555555555
Min/median/max : 1192.0 / 1622.0 / 1894.0
Skewnewss :  -0.358085565941755
Total size :  45
2016

Grab the dataset only in Nova Scotia
       REF_DATE          GEO  \
54827      2016  Nova Scotia
54834      2016  Nova Scotia
54953      2016  Nova Scotia
54960      2016  Nova Scotia
55079      2016  Nova Scotia
55086      2016  Nova Scotia
55205      2016  Nova Scotia
55212      2016  Nova Scotia
55331      2016  Nova Scotia
55338      2016  Nova Scotia
63647      2017  Nova Scotia
63654      2017  Nova Scotia
63773      2017  Nova Scotia
63780      2017  Nova Scotia
63899      2017  Nova Scotia
63906      2017  Nova Scotia
64025      2017  Nova Scotia
64032      2017  Nova Scotia
64151      2017  Nova Scotia
64158      2017  Nova Scotia

                                                  Sector  \
54827                      Total non-profit institutions
54834                      Total non-profit institutions
54953  Total non-profit institutions excluding govern...
54960  Total non-profit institutions excluding govern...
55079  Non-profit institutions serving households (co...
55086  Non-profit institutions serving households (co...
55205                   Business non-profit institutions
55212                   Business non-profit institutions
55331                 Government non-profit institutions
55338                 Government non-profit institutions
63647                      Total non-profit institutions
63654                      Total non-profit institutions
63773  Total non-profit institutions excluding govern...
63780  Total non-profit institutions excluding govern...
63899  Non-profit institutions serving households (co...
63906  Non-profit institutions serving households (co...
64025                   Business non-profit institutions
64032                   Business non-profit institutions
64151                 Government non-profit institutions
64158                 Government non-profit institutions

               Characteristics                   Indicators    UOM  \
54827      Immigrant employees  Average annual hours worked  Hours
54834  Non-immigrant employees  Average annual hours worked  Hours
54953      Immigrant employees  Average annual hours worked  Hours
54960  Non-immigrant employees  Average annual hours worked  Hours
55079      Immigrant employees  Average annual hours worked  Hours
55086  Non-immigrant employees  Average annual hours worked  Hours
55205      Immigrant employees  Average annual hours worked  Hours
55212  Non-immigrant employees  Average annual hours worked  Hours
55331      Immigrant employees  Average annual hours worked  Hours
55338  Non-immigrant employees  Average annual hours worked  Hours
63647      Immigrant employees  Average annual hours worked  Hours
63654  Non-immigrant employees  Average annual hours worked  Hours
63773      Immigrant employees  Average annual hours worked  Hours
63780  Non-immigrant employees  Average annual hours worked  Hours
63899      Immigrant employees  Average annual hours worked  Hours
63906  Non-immigrant employees  Average annual hours worked  Hours
64025      Immigrant employees  Average annual hours worked  Hours
64032  Non-immigrant employees  Average annual hours worked  Hours
64151      Immigrant employees  Average annual hours worked  Hours
64158  Non-immigrant employees  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
54827         units  1727.0
54834         units  1663.0
54953         units  1576.0
54960         units  1574.0
55079         units  1561.0
55086         units  1557.0
55205         units  1634.0
55212         units  1637.0
55331         units  1765.0
55338         units  1699.0
63647         units  1640.0
63654         units  1599.0
63773         units  1552.0

Panda Profiling for Final Result for Nova Scotia

In [115]:
# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

Filtering only Nunavut.

Only finished "Average annual hours worked".

In [116]:
# -- Nunavut                       14235.0     15.208333     14.752372   936

ProCode = 8

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

2013

Grab the dataset only in Nunavut
       REF_DATE      GEO                                             Sector  \
34737      2013  Nunavut                      Total non-profit institutions
34744      2013  Nunavut                      Total non-profit institutions
34751      2013  Nunavut                      Total non-profit institutions
34758      2013  Nunavut                      Total non-profit institutions
34765      2013  Nunavut                      Total non-profit institutions
34772      2013  Nunavut                      Total non-profit institutions
34863      2013  Nunavut  Total non-profit institutions excluding govern...
34870      2013  Nunavut  Total non-profit institutions excluding govern...
34877      2013  Nunavut  Total non-profit institutions excluding govern...
34884      2013  Nunavut  Total non-profit institutions excluding govern...
34891      2013  Nunavut  Total non-profit institutions excluding govern...
34898      2013  Nunavut  Total non-profit institutions excluding govern...
34996      2013  Nunavut  Non-profit institutions serving households (co...
35003      2013  Nunavut  Non-profit institutions serving households (co...
35010      2013  Nunavut  Non-profit institutions serving households (co...
35017      2013  Nunavut  Non-profit institutions serving households (co...
35122      2013  Nunavut                   Business non-profit institutions
35129      2013  Nunavut                   Business non-profit institutions
35136      2013  Nunavut                   Business non-profit institutions
35143      2013  Nunavut                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
34737         15 to 24 years  Average annual hours worked  Hours
34744         25 to 34 years  Average annual hours worked  Hours
34751         35 to 44 years  Average annual hours worked  Hours
34758         45 to 54 years  Average annual hours worked  Hours
34765         55 to 64 years  Average annual hours worked  Hours
34772  65 years old and over  Average annual hours worked  Hours
34863         15 to 24 years  Average annual hours worked  Hours
34870         25 to 34 years  Average annual hours worked  Hours
34877         35 to 44 years  Average annual hours worked  Hours
34884         45 to 54 years  Average annual hours worked  Hours
34891         55 to 64 years  Average annual hours worked  Hours
34898  65 years old and over  Average annual hours worked  Hours
34996         25 to 34 years  Average annual hours worked  Hours
35003         35 to 44 years  Average annual hours worked  Hours
35010         45 to 54 years  Average annual hours worked  Hours
35017         55 to 64 years  Average annual hours worked  Hours
35122         25 to 34 years  Average annual hours worked  Hours
35129         35 to 44 years  Average annual hours worked  Hours
35136         45 to 54 years  Average annual hours worked  Hours
35143         55 to 64 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
34737         units   959.0
34744         units  1549.0
34751         units  1743.0
34758         units  1912.0
34765         units  1745.0
34772         units  1353.0
34863         units   956.0
34870         units  1512.0
34877         units  1720.0
34884         units  1919.0
34891         units  1786.0
34898         units  1273.0
34996         units  1478.0
35003         units  1709.0
35010         units  1880.0
35017         units  1778.0
35122         units  1710.0
35129         units  1781.0
35136         units  2050.0
35143         units  1833.0
<class 'pandas.core.frame.DataFrame'>
Index: 78 entries, 34737 to 52916
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         78 non-null     int64
 1   GEO              78 non-null     object
 2   Sector           78 non-null     object
 3   Characteristics  78 non-null     object
 4   Indicators       78 non-null     object
 5   UOM              78 non-null     object
 6   SCALAR_FACTOR    78 non-null     object
 7   VALUE            78 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 5.5+ KB
None

Grab the dataset only in Nunavut
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years          8577.0   953.000000   905.0   962.0   971.0     9
25 to 34 years         23268.0  1551.200000  1451.0  1532.0  1710.0    15
35 to 44 years         25722.0  1714.800000  1620.0  1709.0  1798.0    15
45 to 54 years         28570.0  1904.666667  1725.0  1904.0  2071.0    15
55 to 64 years         26564.0  1770.933333  1595.0  1770.0  2000.0    15
65 years old and over  12105.0  1345.000000  1273.0  1315.0  1500.0     9

Overall,
Sum :  124806.0
Mean :  1600.076923076923
Min/median/max : 905.0 / 1694.0 / 2071.0
Skewnewss :  -0.9423562698067877
Total size :  78
2016

Grab the dataset only in Nunavut
       REF_DATE      GEO                                             Sector  \
61197      2016  Nunavut                      Total non-profit institutions
61204      2016  Nunavut                      Total non-profit institutions
61211      2016  Nunavut                      Total non-profit institutions
61218      2016  Nunavut                      Total non-profit institutions
61225      2016  Nunavut                      Total non-profit institutions
61232      2016  Nunavut                      Total non-profit institutions
61323      2016  Nunavut  Total non-profit institutions excluding govern...
61330      2016  Nunavut  Total non-profit institutions excluding govern...
61337      2016  Nunavut  Total non-profit institutions excluding govern...
61344      2016  Nunavut  Total non-profit institutions excluding govern...
61351      2016  Nunavut  Total non-profit institutions excluding govern...
61358      2016  Nunavut  Total non-profit institutions excluding govern...
61456      2016  Nunavut  Non-profit institutions serving households (co...
61463      2016  Nunavut  Non-profit institutions serving households (co...
61470      2016  Nunavut  Non-profit institutions serving households (co...
61477      2016  Nunavut  Non-profit institutions serving households (co...
61582      2016  Nunavut                   Business non-profit institutions
61589      2016  Nunavut                   Business non-profit institutions
61596      2016  Nunavut                   Business non-profit institutions
61603      2016  Nunavut                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
61197         15 to 24 years  Average annual hours worked  Hours
61204         25 to 34 years  Average annual hours worked  Hours
61211         35 to 44 years  Average annual hours worked  Hours
61218         45 to 54 years  Average annual hours worked  Hours
61225         55 to 64 years  Average annual hours worked  Hours
61232  65 years old and over  Average annual hours worked  Hours
61323         15 to 24 years  Average annual hours worked  Hours
61330         25 to 34 years  Average annual hours worked  Hours
61337         35 to 44 years  Average annual hours worked  Hours
61344         45 to 54 years  Average annual hours worked  Hours
61351         55 to 64 years  Average annual hours worked  Hours
61358  65 years old and over  Average annual hours worked  Hours
61456         25 to 34 years  Average annual hours worked  Hours
61463         35 to 44 years  Average annual hours worked  Hours
61470         45 to 54 years  Average annual hours worked  Hours
61477         55 to 64 years  Average annual hours worked  Hours
61582         25 to 34 years  Average annual hours worked  Hours
61589         35 to 44 years  Average annual hours worked  Hours
61596         45 to 54 years  Average annual hours worked  Hours
61603         55 to 64 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
61197         units   980.0
61204         units  1520.0
61211         units  1691.0
61218         units  1839.0
61225         units  1747.0
61232         units  1370.0
61323         units   974.0
61330         units  1510.0
61337         units  1735.0
61344         units  1917.0
61351         units  1851.0
61358         units  1424.0
61456         units  1483.0
61463         units  1730.0
61470         units  1897.0
61477         units  1811.0
61582         units  1654.0
61589         units  1773.0
61596         units  1941.0
61603         units  2000.0
<class 'pandas.core.frame.DataFrame'>
Index: 78 entries, 61197 to 79376
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         78 non-null     int64
 1   GEO              78 non-null     object
 2   Sector           78 non-null     object
 3   Characteristics  78 non-null     object
 4   Indicators       78 non-null     object
 5   UOM              78 non-null     object
 6   SCALAR_FACTOR    78 non-null     object
 7   VALUE            78 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 5.5+ KB
None

Grab the dataset only in Nunavut
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years          9042.0  1004.666667   946.0   984.0  1143.0     9
25 to 34 years         23230.0  1548.666667  1437.0  1511.0  1759.0    15
35 to 44 years         25614.0  1707.600000  1594.0  1714.0  1783.0    15
45 to 54 years         27396.0  1826.400000  1667.0  1828.0  1941.0    15
55 to 64 years         26989.0  1799.266667  1608.0  1807.0  2000.0    15
65 years old and over  12015.0  1335.000000  1208.0  1339.0  1424.0     9

Overall,
Sum :  124286.0
Mean :  1593.4102564102564
Min/median/max : 946.0 / 1684.5 / 2000.0
Skewnewss :  -0.94949798343025
Total size :  78
2019

Grab the dataset only in Nunavut
       REF_DATE      GEO                                             Sector  \
87657      2019  Nunavut                      Total non-profit institutions
87664      2019  Nunavut                      Total non-profit institutions
87671      2019  Nunavut                      Total non-profit institutions
87678      2019  Nunavut                      Total non-profit institutions
87685      2019  Nunavut                      Total non-profit institutions
87692      2019  Nunavut                      Total non-profit institutions
87783      2019  Nunavut  Total non-profit institutions excluding govern...
87790      2019  Nunavut  Total non-profit institutions excluding govern...
87797      2019  Nunavut  Total non-profit institutions excluding govern...
87804      2019  Nunavut  Total non-profit institutions excluding govern...
87811      2019  Nunavut  Total non-profit institutions excluding govern...
87818      2019  Nunavut  Total non-profit institutions excluding govern...
87916      2019  Nunavut  Non-profit institutions serving households (co...
87923      2019  Nunavut  Non-profit institutions serving households (co...
87930      2019  Nunavut  Non-profit institutions serving households (co...
87937      2019  Nunavut  Non-profit institutions serving households (co...
88042      2019  Nunavut                   Business non-profit institutions
88049      2019  Nunavut                   Business non-profit institutions
88056      2019  Nunavut                   Business non-profit institutions
88063      2019  Nunavut                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
87657         15 to 24 years  Average annual hours worked  Hours
87664         25 to 34 years  Average annual hours worked  Hours
87671         35 to 44 years  Average annual hours worked  Hours
87678         45 to 54 years  Average annual hours worked  Hours
87685         55 to 64 years  Average annual hours worked  Hours
87692  65 years old and over  Average annual hours worked  Hours
87783         15 to 24 years  Average annual hours worked  Hours
87790         25 to 34 years  Average annual hours worked  Hours
87797         35 to 44 years  Average annual hours worked  Hours
87804         45 to 54 years  Average annual hours worked  Hours
87811         55 to 64 years  Average annual hours worked  Hours
87818  65 years old and over  Average annual hours worked  Hours
87916         25 to 34 years  Average annual hours worked  Hours
87923         35 to 44 years  Average annual hours worked  Hours
87930         45 to 54 years  Average annual hours worked  Hours
87937         55 to 64 years  Average annual hours worked  Hours
88042         25 to 34 years  Average annual hours worked  Hours
88049         35 to 44 years  Average annual hours worked  Hours
88056         45 to 54 years  Average annual hours worked  Hours
88063         55 to 64 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
87657         units  1045.0
87664         units  1504.0
87671         units  1720.0
87678         units  1749.0
87685         units  1823.0
87692         units  1333.0
87783         units  1016.0
87790         units  1470.0
87797         units  1784.0
87804         units  1803.0
87811         units  1899.0
87818         units  1415.0
87916         units  1432.0
87923         units  1786.0
87930         units  1781.0
87937         units  1895.0
88042         units  1652.0
88049         units  1762.0
88056         units  1947.0
88063         units  1929.0
<class 'pandas.core.frame.DataFrame'>
Index: 78 entries, 87657 to 105836
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         78 non-null     int64
 1   GEO              78 non-null     object
 2   Sector           78 non-null     object
 3   Characteristics  78 non-null     object
 4   Indicators       78 non-null     object
 5   UOM              78 non-null     object
 6   SCALAR_FACTOR    78 non-null     object
 7   VALUE            78 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 5.5+ KB
None

Grab the dataset only in Nunavut
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years          9774.0  1086.000000   961.0  1045.0  1250.0     9
25 to 34 years         22902.0  1526.800000  1348.0  1502.0  1714.0    15
35 to 44 years         26076.0  1738.400000  1584.0  1752.0  1857.0    15
45 to 54 years         26522.0  1768.133333  1605.0  1749.0  1947.0    15
55 to 64 years         28160.0  1877.333333  1690.0  1899.0  2071.0    15
65 years old and over  11610.0  1290.000000  1111.0  1308.0  1415.0     9

Overall,
Sum :  125044.0
Mean :  1603.128205128205
Min/median/max : 961.0 / 1691.5 / 2071.0
Skewnewss :  -0.6933271516211263
Total size :  78
2013

Grab the dataset only in Nunavut
       REF_DATE      GEO                                             Sector  \
34653      2013  Nunavut                      Total non-profit institutions
34660      2013  Nunavut                      Total non-profit institutions
34779      2013  Nunavut  Total non-profit institutions excluding govern...
34786      2013  Nunavut  Total non-profit institutions excluding govern...
34905      2013  Nunavut  Non-profit institutions serving households (co...
34912      2013  Nunavut  Non-profit institutions serving households (co...
35031      2013  Nunavut                   Business non-profit institutions
35038      2013  Nunavut                   Business non-profit institutions
35157      2013  Nunavut                 Government non-profit institutions
35164      2013  Nunavut                 Government non-profit institutions
43473      2014  Nunavut                      Total non-profit institutions
43480      2014  Nunavut                      Total non-profit institutions
43599      2014  Nunavut  Total non-profit institutions excluding govern...
43606      2014  Nunavut  Total non-profit institutions excluding govern...
43725      2014  Nunavut  Non-profit institutions serving households (co...
43732      2014  Nunavut  Non-profit institutions serving households (co...
43851      2014  Nunavut                   Business non-profit institutions
43858      2014  Nunavut                   Business non-profit institutions
43977      2014  Nunavut                 Government non-profit institutions
43984      2014  Nunavut                 Government non-profit institutions

        Characteristics                   Indicators    UOM SCALAR_FACTOR  \
34653    Male employees  Average annual hours worked  Hours         units
34660  Female employees  Average annual hours worked  Hours         units
34779    Male employees  Average annual hours worked  Hours         units
34786  Female employees  Average annual hours worked  Hours         units
34905    Male employees  Average annual hours worked  Hours         units
34912  Female employees  Average annual hours worked  Hours         units
35031    Male employees  Average annual hours worked  Hours         units
35038  Female employees  Average annual hours worked  Hours         units
35157    Male employees  Average annual hours worked  Hours         units
35164  Female employees  Average annual hours worked  Hours         units
43473    Male employees  Average annual hours worked  Hours         units
43480  Female employees  Average annual hours worked  Hours         units
43599    Male employees  Average annual hours worked  Hours         units
43606  Female employees  Average annual hours worked  Hours         units
43725    Male employees  Average annual hours worked  Hours         units
43732  Female employees  Average annual hours worked  Hours         units
43851    Male employees  Average annual hours worked  Hours         units
43858  Female employees  Average annual hours worked  Hours         units
43977    Male employees  Average annual hours worked  Hours         units
43984  Female employees  Average annual hours worked  Hours         units

        VALUE
34653  1681.0
34660  1550.0
34779  1666.0
34786  1495.0
34905  1640.0
34912  1474.0
35031  1768.0
35038  1706.0
35157  1721.0
35164  1655.0
43473  1638.0
43480  1533.0
43599  1618.0
43606  1519.0
43725  1578.0
43732  1494.0
43851  1746.0
43858  1720.0
43977  1709.0
43984  1556.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 34653 to 52804
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         30 non-null     int64
 1   GEO              30 non-null     object
 2   Sector           30 non-null     object
 3   Characteristics  30 non-null     object
 4   Indicators       30 non-null     object
 5   UOM              30 non-null     object
 6   SCALAR_FACTOR    30 non-null     object
 7   VALUE            30 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.1+ KB
None

Grab the dataset only in Nunavut
                      sum         mean    amin  median    amax  size
Characteristics
Female employees  23364.0  1557.600000  1474.0  1521.0  1720.0    15
Male employees    24860.0  1657.333333  1527.0  1666.0  1768.0    15

Overall,
Sum :  48224.0
Mean :  1607.4666666666667
Min/median/max : 1474.0 / 1608.0 / 1768.0
Skewnewss :  0.16270756860286553
Total size :  30
2016

Grab the dataset only in Nunavut
       REF_DATE      GEO                                             Sector  \
61113      2016  Nunavut                      Total non-profit institutions
61120      2016  Nunavut                      Total non-profit institutions
61239      2016  Nunavut  Total non-profit institutions excluding govern...
61246      2016  Nunavut  Total non-profit institutions excluding govern...
61365      2016  Nunavut  Non-profit institutions serving households (co...
61372      2016  Nunavut  Non-profit institutions serving households (co...
61491      2016  Nunavut                   Business non-profit institutions

       REF_DATE      GEO                                             Sector  \
87629      2019  Nunavut                      Total non-profit institutions
87636      2019  Nunavut                      Total non-profit institutions
87650      2019  Nunavut                      Total non-profit institutions
87755      2019  Nunavut  Total non-profit institutions excluding govern...
87762      2019  Nunavut  Total non-profit institutions excluding govern...
87776      2019  Nunavut  Total non-profit institutions excluding govern...
87881      2019  Nunavut  Non-profit institutions serving households (co...
88007      2019  Nunavut                   Business non-profit institutions
88133      2019  Nunavut                 Government non-profit institutions
88140      2019  Nunavut                 Government non-profit institutions
88154      2019  Nunavut                 Government non-profit institutions
96449      2020  Nunavut                      Total non-profit institutions
96456      2020  Nunavut                      Total non-profit institutions
96470      2020  Nunavut                      Total non-profit institutions
96575      2020  Nunavut  Total non-profit institutions excluding govern...
96582      2020  Nunavut  Total non-profit institutions excluding govern...
96596      2020  Nunavut  Total non-profit institutions excluding govern...
96701      2020  Nunavut  Non-profit institutions serving households (co...
96827      2020  Nunavut                   Business non-profit institutions
96953      2020  Nunavut                 Government non-profit institutions

                    Characteristics                   Indicators    UOM  \
87629  High school diploma and less  Average annual hours worked  Hours
87636             Trade certificate  Average annual hours worked  Hours
87650  University degree and higher  Average annual hours worked  Hours
87755  High school diploma and less  Average annual hours worked  Hours
87762             Trade certificate  Average annual hours worked  Hours
87776  University degree and higher  Average annual hours worked  Hours
87881  High school diploma and less  Average annual hours worked  Hours
88007  High school diploma and less  Average annual hours worked  Hours
88133  High school diploma and less  Average annual hours worked  Hours
88140             Trade certificate  Average annual hours worked  Hours
88154  University degree and higher  Average annual hours worked  Hours
96449  High school diploma and less  Average annual hours worked  Hours
96456             Trade certificate  Average annual hours worked  Hours
96470  University degree and higher  Average annual hours worked  Hours
96575  High school diploma and less  Average annual hours worked  Hours
96582             Trade certificate  Average annual hours worked  Hours
96596  University degree and higher  Average annual hours worked  Hours
96701  High school diploma and less  Average annual hours worked  Hours
96827  High school diploma and less  Average annual hours worked  Hours
96953  High school diploma and less  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
87629         units  1430.0
87636         units  1708.0
87650         units  1837.0
87755         units  1437.0
87762         units  1714.0
87776         units  1985.0
87881         units  1415.0
88007         units  1593.0
88133         units  1415.0
88140         units  1652.0
88154         units  1687.0
96449         units  1392.0
96456         units  1646.0
96470         units  1827.0
96575         units  1373.0
96582         units  1634.0
96596         units  1951.0
96701         units  1345.0
96827         units  1644.0
96953         units  1452.0
<class 'pandas.core.frame.DataFrame'>
Index: 33 entries, 87629 to 105794
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         33 non-null     int64
 1   GEO              33 non-null     object
 2   Sector           33 non-null     object
 3   Characteristics  33 non-null     object
 4   Indicators       33 non-null     object
 5   UOM              33 non-null     object
 6   SCALAR_FACTOR    33 non-null     object
 7   VALUE            33 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.3+ KB
None

Grab the dataset only in Nunavut
                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  21934.0  1462.266667  1345.0  1437.0  1667.0
Trade certificate             15055.0  1672.777778  1634.0  1667.0  1714.0
University degree and higher  16486.0  1831.777778  1652.0  1837.0  2000.0

                              size
Characteristics
High school diploma and less    15
Trade certificate                9
University degree and higher     9

Overall,
Sum :  53475.0
Mean :  1620.4545454545455
Min/median/max : 1345.0 / 1646.0 / 2000.0
Skewnewss :  0.35755238545180545
Total size :  33
2013

Grab the dataset only in Nunavut
       REF_DATE      GEO                                             Sector  \
34709      2013  Nunavut                      Total non-profit institutions
34716      2013  Nunavut                      Total non-profit institutions
34730      2013  Nunavut                      Total non-profit institutions
34835      2013  Nunavut  Total non-profit institutions excluding govern...
34842      2013  Nunavut  Total non-profit institutions excluding govern...
34856      2013  Nunavut  Total non-profit institutions excluding govern...
34961      2013  Nunavut  Non-profit institutions serving households (co...
35087      2013  Nunavut                   Business non-profit institutions
35213      2013  Nunavut                 Government non-profit institutions
35220      2013  Nunavut                 Government non-profit institutions
35234      2013  Nunavut                 Government non-profit institutions
43529      2014  Nunavut                      Total non-profit institutions
43536      2014  Nunavut                      Total non-profit institutions
43550      2014  Nunavut                      Total non-profit institutions
43655      2014  Nunavut  Total non-profit institutions excluding govern...
43662      2014  Nunavut  Total non-profit institutions excluding govern...
43676      2014  Nunavut  Total non-profit institutions excluding govern...
43781      2014  Nunavut  Non-profit institutions serving households (co...
43907      2014  Nunavut                   Business non-profit institutions
44033      2014  Nunavut                 Government non-profit institutions

                    Characteristics                   Indicators    UOM  \
34709  High school diploma and less  Average annual hours worked  Hours
34716             Trade certificate  Average annual hours worked  Hours
34730  University degree and higher  Average annual hours worked  Hours
34835  High school diploma and less  Average annual hours worked  Hours
34842             Trade certificate  Average annual hours worked  Hours
34856  University degree and higher  Average annual hours worked  Hours
34961  High school diploma and less  Average annual hours worked  Hours
35087  High school diploma and less  Average annual hours worked  Hours
35213  High school diploma and less  Average annual hours worked  Hours
35220             Trade certificate  Average annual hours worked  Hours
35234  University degree and higher  Average annual hours worked  Hours
43529  High school diploma and less  Average annual hours worked  Hours
43536             Trade certificate  Average annual hours worked  Hours
43550  University degree and higher  Average annual hours worked  Hours
43655  High school diploma and less  Average annual hours worked  Hours
43662             Trade certificate  Average annual hours worked  Hours
43676  University degree and higher  Average annual hours worked  Hours
43781  High school diploma and less  Average annual hours worked  Hours
43907  High school diploma and less  Average annual hours worked  Hours
44033  High school diploma and less  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
34709         units  1434.0
34716         units  1651.0
34730         units  1931.0
34835         units  1410.0
34842         units  1581.0
34856         units  2008.0
34961         units  1377.0
35087         units  1645.0
35213         units  1503.0
35220         units  1800.0
35234         units  1856.0
43529         units  1412.0
43536         units  1610.0
43550         units  1893.0
43655         units  1409.0
43662         units  1538.0
43676         units  2009.0
43781         units  1374.0
43907         units  1603.0
44033         units  1420.0
<class 'pandas.core.frame.DataFrame'>
Index: 33 entries, 34709 to 52874
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         33 non-null     int64
 1   GEO              33 non-null     object
 2   Sector           33 non-null     object
 3   Characteristics  33 non-null     object
 4   Indicators       33 non-null     object
 5   UOM              33 non-null     object
 6   SCALAR_FACTOR    33 non-null     object
 7   VALUE            33 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.3+ KB
None

Grab the dataset only in Nunavut
                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  21619.0  1441.266667  1353.0  1410.0  1645.0
Trade certificate             15056.0  1672.888889  1513.0  1632.0  1889.0
University degree and higher  17122.0  1902.444444  1750.0  1893.0  2009.0

                              size
Characteristics
High school diploma and less    15
Trade certificate                9
University degree and higher     9

Overall,
Sum :  53797.0
Mean :  1630.2121212121212
Min/median/max : 1353.0 / 1603.0 / 2009.0
Skewnewss :  0.33343067558816875
Total size :  33
2016

Grab the dataset only in Nunavut
       REF_DATE      GEO                                             Sector  \
61127      2016  Nunavut                      Total non-profit institutions
61134      2016  Nunavut                      Total non-profit institutions
61253      2016  Nunavut  Total non-profit institutions excluding govern...
61260      2016  Nunavut  Total non-profit institutions excluding govern...
61631      2016  Nunavut                 Government non-profit institutions
61638      2016  Nunavut                 Government non-profit institutions
69947      2017  Nunavut                      Total non-profit institutions
69954      2017  Nunavut                      Total non-profit institutions
70073      2017  Nunavut  Total non-profit institutions excluding govern...
70080      2017  Nunavut  Total non-profit institutions excluding govern...
70451      2017  Nunavut                 Government non-profit institutions
70458      2017  Nunavut                 Government non-profit institutions
78767      2018  Nunavut                      Total non-profit institutions
78774      2018  Nunavut                      Total non-profit institutions
78893      2018  Nunavut  Total non-profit institutions excluding govern...
78900      2018  Nunavut  Total non-profit institutions excluding govern...
79271      2018  Nunavut                 Government non-profit institutions
79278      2018  Nunavut                 Government non-profit institutions

               Characteristics                   Indicators    UOM  \
61127      Immigrant employees  Average annual hours worked  Hours
61134  Non-immigrant employees  Average annual hours worked  Hours
61253      Immigrant employees  Average annual hours worked  Hours
61260  Non-immigrant employees  Average annual hours worked  Hours
61631      Immigrant employees  Average annual hours worked  Hours
61638  Non-immigrant employees  Average annual hours worked  Hours
69947      Immigrant employees  Average annual hours worked  Hours
69954  Non-immigrant employees  Average annual hours worked  Hours
70073      Immigrant employees  Average annual hours worked  Hours
70080  Non-immigrant employees  Average annual hours worked  Hours
70451      Immigrant employees  Average annual hours worked  Hours
70458  Non-immigrant employees  Average annual hours worked  Hours
78767      Immigrant employees  Average annual hours worked  Hours
78774  Non-immigrant employees  Average annual hours worked  Hours
78893      Immigrant employees  Average annual hours worked  Hours
78900  Non-immigrant employees  Average annual hours worked  Hours
79271      Immigrant employees  Average annual hours worked  Hours
79278  Non-immigrant employees  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
61127         units  1812.0
61134         units  1566.0
61253         units  1805.0
61260         units  1577.0
61631         units  1826.0
61638         units  1545.0
69947         units  1743.0
69954         units  1541.0
70073         units  1756.0
70080         units  1546.0
70451         units  1792.0
70458         units  1527.0
78767         units  1778.0
78774         units  1562.0
78893         units  1804.0
78900         units  1562.0
79271         units  1800.0
79278         units  1563.0
<class 'pandas.core.frame.DataFrame'>
Index: 18 entries, 61127 to 79278
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         18 non-null     int64
 1   GEO              18 non-null     object
 2   Sector           18 non-null     object
 3   Characteristics  18 non-null     object
 4   Indicators       18 non-null     object
 5   UOM              18 non-null     object
 6   SCALAR_FACTOR    18 non-null     object
 7   VALUE            18 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 1.3+ KB
None

Grab the dataset only in Nunavut
                             sum         mean    amin  median    amax  size
Characteristics
Immigrant employees      16116.0  1790.666667  1743.0  1800.0  1826.0     9
Non-immigrant employees  13989.0  1554.333333  1527.0  1562.0  1577.0     9

Overall,
Sum :  30105.0
Mean :  1672.5
Min/median/max : 1527.0 / 1660.0 / 1826.0
Skewnewss :  0.04488893716483184
Total size :  18
2019

Grab the dataset only in Nunavut
       REF_DATE      GEO                                             Sector  \
87629      2019  Nunavut                      Total non-profit institutions
87636      2019  Nunavut                      Total non-profit institutions
87650      2019  Nunavut                      Total non-profit institutions
87755      2019  Nunavut  Total non-profit institutions excluding govern...
87762      2019  Nunavut  Total non-profit institutions excluding govern...
87776      2019  Nunavut  Total non-profit institutions excluding govern...
87881      2019  Nunavut  Non-profit institutions serving households (co...
88007      2019  Nunavut                   Business non-profit institutions
88133      2019  Nunavut                 Government non-profit institutions
88140      2019  Nunavut                 Government non-profit institutions
88154      2019  Nunavut                 Government non-profit institutions
96449      2020  Nunavut                      Total non-profit institutions
96456      2020  Nunavut                      Total non-profit institutions
96470      2020  Nunavut                      Total non-profit institutions
96575      2020  Nunavut  Total non-profit institutions excluding govern...
96582      2020  Nunavut  Total non-profit institutions excluding govern...
96596      2020  Nunavut  Total non-profit institutions excluding govern...
96701      2020  Nunavut  Non-profit institutions serving households (co...
96827      2020  Nunavut                   Business non-profit institutions
96953      2020  Nunavut                 Government non-profit institutions

                    Characteristics                   Indicators    UOM  \
87629  High school diploma and less  Average annual hours worked  Hours
87636             Trade certificate  Average annual hours worked  Hours
87650  University degree and higher  Average annual hours worked  Hours
87755  High school diploma and less  Average annual hours worked  Hours
87762             Trade certificate  Average annual hours worked  Hours
87776  University degree and higher  Average annual hours worked  Hours
87881  High school diploma and less  Average annual hours worked  Hours
88007  High school diploma and less  Average annual hours worked  Hours
88133  High school diploma and less  Average annual hours worked  Hours
88140             Trade certificate  Average annual hours worked  Hours
88154  University degree and higher  Average annual hours worked  Hours
96449  High school diploma and less  Average annual hours worked  Hours
96456             Trade certificate  Average annual hours worked  Hours
96470  University degree and higher  Average annual hours worked  Hours
96575  High school diploma and less  Average annual hours worked  Hours
96582             Trade certificate  Average annual hours worked  Hours
96596  University degree and higher  Average annual hours worked  Hours
96701  High school diploma and less  Average annual hours worked  Hours
96827  High school diploma and less  Average annual hours worked  Hours
96953  High school diploma and less  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
87629         units  1430.0
87636         units  1708.0
87650         units  1837.0
87755         units  1437.0
87762         units  1714.0
87776         units  1985.0
87881         units  1415.0
88007         units  1593.0
88133         units  1415.0
88140         units  1652.0
88154         units  1687.0
96449         units  1392.0
96456         units  1646.0
96470         units  1827.0
96575         units  1373.0
96582         units  1634.0
96596         units  1951.0
96701         units  1345.0
96827         units  1644.0
96953         units  1452.0
<class 'pandas.core.frame.DataFrame'>
Index: 33 entries, 87629 to 105794
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         33 non-null     int64
 1   GEO              33 non-null     object
 2   Sector           33 non-null     object
 3   Characteristics  33 non-null     object
 4   Indicators       33 non-null     object
 5   UOM              33 non-null     object
 6   SCALAR_FACTOR    33 non-null     object
 7   VALUE            33 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.3+ KB
None

Grab the dataset only in Nunavut
                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  21934.0  1462.266667  1345.0  1437.0  1667.0
Trade certificate             15055.0  1672.777778  1634.0  1667.0  1714.0
University degree and higher  16486.0  1831.777778  1652.0  1837.0  2000.0

                              size
Characteristics
High school diploma and less    15
Trade certificate                9
University degree and higher     9

Overall,
Sum :  53475.0
Mean :  1620.4545454545455
Min/median/max : 1345.0 / 1646.0 / 2000.0
Skewnewss :  0.35755238545180545
Total size :  33

Panda Profiling for Final Result for Nunavut

In [117]:
# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

Filtered by Ontario

Only finished "Average annual hours worked".

In [118]:
# -- Ontario                     6601634.0   6112.624074   7594.433779  1080

ProCode = 9

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

2013

Grab the dataset only in Ontario
       REF_DATE      GEO                                             Sector  \
30327      2013  Ontario                      Total non-profit institutions
30334      2013  Ontario                      Total non-profit institutions
30341      2013  Ontario                      Total non-profit institutions
30348      2013  Ontario                      Total non-profit institutions
30355      2013  Ontario                      Total non-profit institutions
30362      2013  Ontario                      Total non-profit institutions
30453      2013  Ontario  Total non-profit institutions excluding govern...
30460      2013  Ontario  Total non-profit institutions excluding govern...
30467      2013  Ontario  Total non-profit institutions excluding govern...
30474      2013  Ontario  Total non-profit institutions excluding govern...
30481      2013  Ontario  Total non-profit institutions excluding govern...
30488      2013  Ontario  Total non-profit institutions excluding govern...
30579      2013  Ontario  Non-profit institutions serving households (co...
30586      2013  Ontario  Non-profit institutions serving households (co...
30593      2013  Ontario  Non-profit institutions serving households (co...
30600      2013  Ontario  Non-profit institutions serving households (co...
30607      2013  Ontario  Non-profit institutions serving households (co...
30614      2013  Ontario  Non-profit institutions serving households (co...
30705      2013  Ontario                   Business non-profit institutions
30712      2013  Ontario                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
30327         15 to 24 years  Average annual hours worked  Hours
30334         25 to 34 years  Average annual hours worked  Hours
30341         35 to 44 years  Average annual hours worked  Hours
30348         45 to 54 years  Average annual hours worked  Hours
30355         55 to 64 years  Average annual hours worked  Hours
30362  65 years old and over  Average annual hours worked  Hours
30453         15 to 24 years  Average annual hours worked  Hours
30460         25 to 34 years  Average annual hours worked  Hours
30467         35 to 44 years  Average annual hours worked  Hours
30474         45 to 54 years  Average annual hours worked  Hours
30481         55 to 64 years  Average annual hours worked  Hours
30488  65 years old and over  Average annual hours worked  Hours
30579         15 to 24 years  Average annual hours worked  Hours
30586         25 to 34 years  Average annual hours worked  Hours
30593         35 to 44 years  Average annual hours worked  Hours
30600         45 to 54 years  Average annual hours worked  Hours
30607         55 to 64 years  Average annual hours worked  Hours
30614  65 years old and over  Average annual hours worked  Hours
30705         15 to 24 years  Average annual hours worked  Hours
30712         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
30327         units   835.0
30334         units  1580.0
30341         units  1774.0
30348         units  1837.0
30355         units  1702.0
30362         units  1041.0
30453         units   845.0
30460         units  1669.0
30467         units  1806.0
30474         units  1863.0
30481         units  1717.0
30488         units  1060.0
30579         units   839.0
30586         units  1628.0
30593         units  1763.0
30600         units  1830.0
30607         units  1691.0
30614         units  1044.0
30705         units   857.0
30712         units  1788.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 30327 to 48506
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Ontario
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         12561.0   837.400000   824.0   836.0   857.0    15
25 to 34 years         24473.0  1631.533333  1527.0  1611.0  1788.0    15
35 to 44 years         26974.0  1798.266667  1731.0  1769.0  1941.0    15
45 to 54 years         27822.0  1854.800000  1795.0  1831.0  1967.0    15
55 to 64 years         25858.0  1723.866667  1679.0  1713.0  1822.0    15
65 years old and over  16363.0  1090.866667  1027.0  1092.0  1192.0    15

Overall,
Sum :  134051.0
Mean :  1489.4555555555555
Min/median/max : 824.0 / 1693.0 / 1967.0
Skewnewss :  -0.6827679863947949
Total size :  90
2016

Grab the dataset only in Ontario
       REF_DATE      GEO                                             Sector  \
56787      2016  Ontario                      Total non-profit institutions
56794      2016  Ontario                      Total non-profit institutions
56801      2016  Ontario                      Total non-profit institutions
56808      2016  Ontario                      Total non-profit institutions
56815      2016  Ontario                      Total non-profit institutions
56822      2016  Ontario                      Total non-profit institutions
56913      2016  Ontario  Total non-profit institutions excluding govern...
56920      2016  Ontario  Total non-profit institutions excluding govern...
56927      2016  Ontario  Total non-profit institutions excluding govern...
56934      2016  Ontario  Total non-profit institutions excluding govern...
56941      2016  Ontario  Total non-profit institutions excluding govern...
56948      2016  Ontario  Total non-profit institutions excluding govern...
57039      2016  Ontario  Non-profit institutions serving households (co...
57046      2016  Ontario  Non-profit institutions serving households (co...
57053      2016  Ontario  Non-profit institutions serving households (co...
57060      2016  Ontario  Non-profit institutions serving households (co...
57067      2016  Ontario  Non-profit institutions serving households (co...
57074      2016  Ontario  Non-profit institutions serving households (co...
57165      2016  Ontario                   Business non-profit institutions
57172      2016  Ontario                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
56787         15 to 24 years  Average annual hours worked  Hours
56794         25 to 34 years  Average annual hours worked  Hours
56801         35 to 44 years  Average annual hours worked  Hours
56808         45 to 54 years  Average annual hours worked  Hours
56815         55 to 64 years  Average annual hours worked  Hours
56822  65 years old and over  Average annual hours worked  Hours
56913         15 to 24 years  Average annual hours worked  Hours
56920         25 to 34 years  Average annual hours worked  Hours
56927         35 to 44 years  Average annual hours worked  Hours
56934         45 to 54 years  Average annual hours worked  Hours
56941         55 to 64 years  Average annual hours worked  Hours
56948  65 years old and over  Average annual hours worked  Hours
57039         15 to 24 years  Average annual hours worked  Hours
57046         25 to 34 years  Average annual hours worked  Hours
57053         35 to 44 years  Average annual hours worked  Hours
57060         45 to 54 years  Average annual hours worked  Hours
57067         55 to 64 years  Average annual hours worked  Hours
57074  65 years old and over  Average annual hours worked  Hours
57165         15 to 24 years  Average annual hours worked  Hours
57172         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
56787         units   849.0
56794         units  1595.0
56801         units  1773.0
56808         units  1841.0
56815         units  1717.0
56822         units  1083.0
56913         units   839.0
56920         units  1649.0
56927         units  1782.0
56934         units  1841.0
56941         units  1707.0
56948         units  1073.0
57039         units   832.0
57046         units  1604.0
57053         units  1734.0
57060         units  1801.0
57067         units  1673.0
57074         units  1054.0
57165         units   856.0
57172         units  1775.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 56787 to 74966
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Ontario
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         12772.0   851.466667   832.0   854.0   875.0    15
25 to 34 years         24540.0  1636.000000  1561.0  1604.0  1775.0    15
35 to 44 years         26880.0  1792.000000  1728.0  1773.0  1929.0    15
45 to 54 years         27896.0  1859.733333  1801.0  1842.0  1965.0    15
55 to 64 years         25896.0  1726.400000  1653.0  1717.0  1816.0    15
65 years old and over  16172.0  1078.133333  1015.0  1069.0  1157.0    15

Overall,
Sum :  134156.0
Mean :  1490.6222222222223
Min/median/max : 832.0 / 1682.0 / 1965.0
Skewnewss :  -0.6698748437878889
Total size :  90
2019

Grab the dataset only in Ontario
       REF_DATE      GEO                                             Sector  \
83247      2019  Ontario                      Total non-profit institutions
83254      2019  Ontario                      Total non-profit institutions
83261      2019  Ontario                      Total non-profit institutions
83268      2019  Ontario                      Total non-profit institutions
83275      2019  Ontario                      Total non-profit institutions
83282      2019  Ontario                      Total non-profit institutions
83373      2019  Ontario  Total non-profit institutions excluding govern...
83380      2019  Ontario  Total non-profit institutions excluding govern...
83387      2019  Ontario  Total non-profit institutions excluding govern...
83394      2019  Ontario  Total non-profit institutions excluding govern...
83401      2019  Ontario  Total non-profit institutions excluding govern...
83408      2019  Ontario  Total non-profit institutions excluding govern...
83499      2019  Ontario  Non-profit institutions serving households (co...
83506      2019  Ontario  Non-profit institutions serving households (co...
83513      2019  Ontario  Non-profit institutions serving households (co...
83520      2019  Ontario  Non-profit institutions serving households (co...
83527      2019  Ontario  Non-profit institutions serving households (co...
83534      2019  Ontario  Non-profit institutions serving households (co...
83625      2019  Ontario                   Business non-profit institutions
83632      2019  Ontario                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
83247         15 to 24 years  Average annual hours worked  Hours
83254         25 to 34 years  Average annual hours worked  Hours
83261         35 to 44 years  Average annual hours worked  Hours
83268         45 to 54 years  Average annual hours worked  Hours
83275         55 to 64 years  Average annual hours worked  Hours
83282  65 years old and over  Average annual hours worked  Hours
83373         15 to 24 years  Average annual hours worked  Hours
83380         25 to 34 years  Average annual hours worked  Hours
83387         35 to 44 years  Average annual hours worked  Hours
83394         45 to 54 years  Average annual hours worked  Hours
83401         55 to 64 years  Average annual hours worked  Hours
83408  65 years old and over  Average annual hours worked  Hours
83499         15 to 24 years  Average annual hours worked  Hours
83506         25 to 34 years  Average annual hours worked  Hours
83513         35 to 44 years  Average annual hours worked  Hours
83520         45 to 54 years  Average annual hours worked  Hours
83527         55 to 64 years  Average annual hours worked  Hours
83534  65 years old and over  Average annual hours worked  Hours
83625         15 to 24 years  Average annual hours worked  Hours
83632         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
83247         units   865.0
83254         units  1579.0
83261         units  1745.0
83268         units  1831.0
83275         units  1708.0
83282         units  1056.0
83373         units   847.0
83380         units  1631.0
83387         units  1757.0
83394         units  1830.0
83401         units  1690.0
83408         units  1060.0
83499         units   843.0
83506         units  1589.0
83513         units  1716.0
83520         units  1794.0
83527         units  1657.0
83534         units  1038.0
83625         units   856.0
83632         units  1755.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 83247 to 101426
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Ontario
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         13099.0   873.266667   823.0   872.0   932.0    15
25 to 34 years         24347.0  1623.133333  1529.0  1600.0  1765.0    15
35 to 44 years         26457.0  1763.800000  1647.0  1755.0  1884.0    15
45 to 54 years         27665.0  1844.333333  1722.0  1832.0  1945.0    15
55 to 64 years         25732.0  1715.466667  1592.0  1708.0  1806.0    15
65 years old and over  16252.0  1083.466667  1005.0  1071.0  1192.0    15

Overall,
Sum :  133552.0
Mean :  1483.911111111111
Min/median/max : 823.0 / 1652.0 / 1945.0
Skewnewss :  -0.6561285966673744
Total size :  90
2013

Grab the dataset only in Ontario
       REF_DATE      GEO                                             Sector  \
30243      2013  Ontario                      Total non-profit institutions
30250      2013  Ontario                      Total non-profit institutions
30369      2013  Ontario  Total non-profit institutions excluding govern...
30376      2013  Ontario  Total non-profit institutions excluding govern...
30495      2013  Ontario  Non-profit institutions serving households (co...
30502      2013  Ontario  Non-profit institutions serving households (co...
30621      2013  Ontario                   Business non-profit institutions
30628      2013  Ontario                   Business non-profit institutions
30747      2013  Ontario                 Government non-profit institutions
30754      2013  Ontario                 Government non-profit institutions
39063      2014  Ontario                      Total non-profit institutions
39070      2014  Ontario                      Total non-profit institutions
39189      2014  Ontario  Total non-profit institutions excluding govern...
39196      2014  Ontario  Total non-profit institutions excluding govern...
39315      2014  Ontario  Non-profit institutions serving households (co...
39322      2014  Ontario  Non-profit institutions serving households (co...
39441      2014  Ontario                   Business non-profit institutions
39448      2014  Ontario                   Business non-profit institutions
39567      2014  Ontario                 Government non-profit institutions
39574      2014  Ontario                 Government non-profit institutions

        Characteristics                   Indicators    UOM SCALAR_FACTOR  \
30243    Male employees  Average annual hours worked  Hours         units
30250  Female employees  Average annual hours worked  Hours         units
30369    Male employees  Average annual hours worked  Hours         units
30376  Female employees  Average annual hours worked  Hours         units
30495    Male employees  Average annual hours worked  Hours         units
30502  Female employees  Average annual hours worked  Hours         units
30621    Male employees  Average annual hours worked  Hours         units
30628  Female employees  Average annual hours worked  Hours         units
30747    Male employees  Average annual hours worked  Hours         units
30754  Female employees  Average annual hours worked  Hours         units
39063    Male employees  Average annual hours worked  Hours         units
39070  Female employees  Average annual hours worked  Hours         units
39189    Male employees  Average annual hours worked  Hours         units
39196  Female employees  Average annual hours worked  Hours         units
39315    Male employees  Average annual hours worked  Hours         units
39322  Female employees  Average annual hours worked  Hours         units
39441    Male employees  Average annual hours worked  Hours         units
39448  Female employees  Average annual hours worked  Hours         units
39567    Male employees  Average annual hours worked  Hours         units
39574  Female employees  Average annual hours worked  Hours         units

        VALUE
30243  1619.0
30250  1569.0
30369  1681.0
30376  1558.0
30495  1667.0
30502  1539.0
30621  1712.0
30628  1629.0
30747  1572.0
30754  1575.0
39063  1613.0
39070  1565.0
39189  1666.0
39196  1550.0
39315  1650.0
39322  1538.0
39441  1699.0
39448  1598.0
39567  1572.0
39574  1574.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 30243 to 48394
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         30 non-null     int64
 1   GEO              30 non-null     object
 2   Sector           30 non-null     object
 3   Characteristics  30 non-null     object
 4   Indicators       30 non-null     object
 5   UOM              30 non-null     object
 6   SCALAR_FACTOR    30 non-null     object
 7   VALUE            30 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.1+ KB
None

Grab the dataset only in Ontario
                      sum         mean    amin  median    amax  size
Characteristics
Female employees  23558.0  1570.533333  1526.0  1569.0  1629.0    15
Male employees    24668.0  1644.533333  1572.0  1650.0  1728.0    15

Overall,
Sum :  48226.0
Mean :  1607.5333333333333
Min/median/max : 1526.0 / 1595.5 / 1728.0
Skewnewss :  0.5866021538529981
Total size :  30
2016

Grab the dataset only in Ontario
       REF_DATE      GEO                                             Sector  \
56703      2016  Ontario                      Total non-profit institutions
56710      2016  Ontario                      Total non-profit institutions
56829      2016  Ontario  Total non-profit institutions excluding govern...
56836      2016  Ontario  Total non-profit institutions excluding govern...
56955      2016  Ontario  Non-profit institutions serving households (co...
56962      2016  Ontario  Non-profit institutions serving households (co...
57081      2016  Ontario                   Business non-profit institutions

Sum :  68408.0
Mean :  1520.1777777777777
Min/median/max : 1194.0 / 1533.0 / 1804.0
Skewnewss :  -0.3107123670831418
Total size :  45
2019

Grab the dataset only in Ontario
       REF_DATE      GEO                                             Sector  \
83219      2019  Ontario                      Total non-profit institutions
83226      2019  Ontario                      Total non-profit institutions
83240      2019  Ontario                      Total non-profit institutions
83345      2019  Ontario  Total non-profit institutions excluding govern...
83352      2019  Ontario  Total non-profit institutions excluding govern...
83366      2019  Ontario  Total non-profit institutions excluding govern...
83471      2019  Ontario  Non-profit institutions serving households (co...
83478      2019  Ontario  Non-profit institutions serving households (co...
83492      2019  Ontario  Non-profit institutions serving households (co...
83597      2019  Ontario                   Business non-profit institutions
83604      2019  Ontario                   Business non-profit institutions
83618      2019  Ontario                   Business non-profit institutions
83723      2019  Ontario                 Government non-profit institutions
83730      2019  Ontario                 Government non-profit institutions
83744      2019  Ontario                 Government non-profit institutions
92039      2020  Ontario                      Total non-profit institutions
92046      2020  Ontario                      Total non-profit institutions
92060      2020  Ontario                      Total non-profit institutions
92165      2020  Ontario  Total non-profit institutions excluding govern...
92172      2020  Ontario  Total non-profit institutions excluding govern...

                    Characteristics                   Indicators    UOM  \
83219  High school diploma and less  Average annual hours worked  Hours
83226             Trade certificate  Average annual hours worked  Hours
83240  University degree and higher  Average annual hours worked  Hours
83345  High school diploma and less  Average annual hours worked  Hours
83352             Trade certificate  Average annual hours worked  Hours
83366  University degree and higher  Average annual hours worked  Hours
83471  High school diploma and less  Average annual hours worked  Hours
83478             Trade certificate  Average annual hours worked  Hours
83492  University degree and higher  Average annual hours worked  Hours
83597  High school diploma and less  Average annual hours worked  Hours
83604             Trade certificate  Average annual hours worked  Hours
83618  University degree and higher  Average annual hours worked  Hours
83723  High school diploma and less  Average annual hours worked  Hours
83730             Trade certificate  Average annual hours worked  Hours
83744  University degree and higher  Average annual hours worked  Hours
92039  High school diploma and less  Average annual hours worked  Hours
92046             Trade certificate  Average annual hours worked  Hours
92060  University degree and higher  Average annual hours worked  Hours
92165  High school diploma and less  Average annual hours worked  Hours
92172             Trade certificate  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
83219         units  1245.0
83226         units  1499.0
83240         units  1670.0
83345         units  1251.0
83352         units  1513.0
83366         units  1706.0
83471         units  1197.0
83478         units  1454.0
83492         units  1680.0
83597         units  1386.0
83604         units  1669.0
83618         units  1792.0
83723         units  1238.0
83730         units  1486.0
83744         units  1649.0
92039         units  1248.0
92046         units  1482.0
92060         units  1673.0
92165         units  1234.0
92172         units  1459.0
<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 83219 to 101384
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         45 non-null     int64
 1   GEO              45 non-null     object
 2   Sector           45 non-null     object
 3   Characteristics  45 non-null     object
 4   Indicators       45 non-null     object
 5   UOM              45 non-null     object
 6   SCALAR_FACTOR    45 non-null     object
 7   VALUE            45 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 3.2+ KB
None

Grab the dataset only in Ontario
                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  19132.0  1275.466667  1171.0  1251.0  1423.0
Trade certificate             22756.0  1517.066667  1396.0  1499.0  1669.0
University degree and higher  25550.0  1703.333333  1615.0  1688.0  1808.0

                              size
Characteristics
High school diploma and less    15
Trade certificate               15
University degree and higher    15

Overall,
Sum :  67438.0
Mean :  1498.6222222222223
Min/median/max : 1171.0 / 1499.0 / 1808.0
Skewnewss :  -0.16058488152240866
Total size :  45
2013

Grab the dataset only in Ontario
       REF_DATE      GEO                                             Sector  \
30299      2013  Ontario                      Total non-profit institutions
30306      2013  Ontario                      Total non-profit institutions
30320      2013  Ontario                      Total non-profit institutions
30425      2013  Ontario  Total non-profit institutions excluding govern...
30432      2013  Ontario  Total non-profit institutions excluding govern...
30446      2013  Ontario  Total non-profit institutions excluding govern...
30551      2013  Ontario  Non-profit institutions serving households (co...
30558      2013  Ontario  Non-profit institutions serving households (co...
30572      2013  Ontario  Non-profit institutions serving households (co...
30677      2013  Ontario                   Business non-profit institutions
30684      2013  Ontario                   Business non-profit institutions
30698      2013  Ontario                   Business non-profit institutions
30803      2013  Ontario                 Government non-profit institutions
30810      2013  Ontario                 Government non-profit institutions
30824      2013  Ontario                 Government non-profit institutions
39119      2014  Ontario                      Total non-profit institutions
39126      2014  Ontario                      Total non-profit institutions
39140      2014  Ontario                      Total non-profit institutions
39245      2014  Ontario  Total non-profit institutions excluding govern...
39252      2014  Ontario  Total non-profit institutions excluding govern...

                    Characteristics                   Indicators    UOM  \
30299  High school diploma and less  Average annual hours worked  Hours
30306             Trade certificate  Average annual hours worked  Hours
30320  University degree and higher  Average annual hours worked  Hours
30425  High school diploma and less  Average annual hours worked  Hours
30432             Trade certificate  Average annual hours worked  Hours
30446  University degree and higher  Average annual hours worked  Hours
30551  High school diploma and less  Average annual hours worked  Hours
30558             Trade certificate  Average annual hours worked  Hours
30572  University degree and higher  Average annual hours worked  Hours
30677  High school diploma and less  Average annual hours worked  Hours
30684             Trade certificate  Average annual hours worked  Hours
30698  University degree and higher  Average annual hours worked  Hours
30803  High school diploma and less  Average annual hours worked  Hours
30810             Trade certificate  Average annual hours worked  Hours
30824  University degree and higher  Average annual hours worked  Hours
39119  High school diploma and less  Average annual hours worked  Hours
39126             Trade certificate  Average annual hours worked  Hours
39140  University degree and higher  Average annual hours worked  Hours
39245  High school diploma and less  Average annual hours worked  Hours
39252             Trade certificate  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
30299         units  1277.0
30306         units  1556.0
30320         units  1681.0
30425         units  1287.0
30432         units  1602.0
30446         units  1755.0
30551         units  1237.0
30558         units  1542.0
30572         units  1737.0
30677         units  1393.0
30684         units  1750.0
30698         units  1818.0
30803         units  1266.0
30810         units  1523.0
30824         units  1640.0
39119         units  1276.0
39126         units  1547.0
39140         units  1675.0
39245         units  1284.0
39252         units  1593.0
<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 30299 to 48464
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         45 non-null     int64
 1   GEO              45 non-null     object
 2   Sector           45 non-null     object
 3   Characteristics  45 non-null     object
 4   Indicators       45 non-null     object
 5   UOM              45 non-null     object
 6   SCALAR_FACTOR    45 non-null     object
 7   VALUE            45 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 3.2+ KB
None

Grab the dataset only in Ontario
                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  19402.0  1293.466667  1224.0  1284.0  1408.0
Trade certificate             23912.0  1594.133333  1514.0  1556.0  1766.0
University degree and higher  25764.0  1717.600000  1640.0  1725.0  1818.0

                              size
Characteristics
High school diploma and less    15
Trade certificate               15
University degree and higher    15

Overall,
Sum :  69078.0
Mean :  1535.0666666666666
Min/median/max : 1224.0 / 1556.0 / 1818.0
Skewnewss :  -0.31500011198904143
Total size :  45
2016

Grab the dataset only in Ontario
       REF_DATE      GEO                                             Sector  \
56717      2016  Ontario                      Total non-profit institutions
56724      2016  Ontario                      Total non-profit institutions
56843      2016  Ontario  Total non-profit institutions excluding govern...
56850      2016  Ontario  Total non-profit institutions excluding govern...
56969      2016  Ontario  Non-profit institutions serving households (co...
56976      2016  Ontario  Non-profit institutions serving households (co...
57095      2016  Ontario                   Business non-profit institutions
57102      2016  Ontario                   Business non-profit institutions
57221      2016  Ontario                 Government non-profit institutions
57228      2016  Ontario                 Government non-profit institutions
65537      2017  Ontario                      Total non-profit institutions
65544      2017  Ontario                      Total non-profit institutions
65663      2017  Ontario  Total non-profit institutions excluding govern...
65670      2017  Ontario  Total non-profit institutions excluding govern...
65789      2017  Ontario  Non-profit institutions serving households (co...
65796      2017  Ontario  Non-profit institutions serving households (co...
65915      2017  Ontario                   Business non-profit institutions
65922      2017  Ontario                   Business non-profit institutions
66041      2017  Ontario                 Government non-profit institutions
66048      2017  Ontario                 Government non-profit institutions

               Characteristics                   Indicators    UOM  \
56717      Immigrant employees  Average annual hours worked  Hours
56724  Non-immigrant employees  Average annual hours worked  Hours
56843      Immigrant employees  Average annual hours worked  Hours
56850  Non-immigrant employees  Average annual hours worked  Hours
56969      Immigrant employees  Average annual hours worked  Hours
56976  Non-immigrant employees  Average annual hours worked  Hours
57095      Immigrant employees  Average annual hours worked  Hours
57102  Non-immigrant employees  Average annual hours worked  Hours
57221      Immigrant employees  Average annual hours worked  Hours
57228  Non-immigrant employees  Average annual hours worked  Hours
65537      Immigrant employees  Average annual hours worked  Hours
65544  Non-immigrant employees  Average annual hours worked  Hours
65663      Immigrant employees  Average annual hours worked  Hours
65670  Non-immigrant employees  Average annual hours worked  Hours
65789      Immigrant employees  Average annual hours worked  Hours
65796  Non-immigrant employees  Average annual hours worked  Hours
65915      Immigrant employees  Average annual hours worked  Hours
65922  Non-immigrant employees  Average annual hours worked  Hours
66041      Immigrant employees  Average annual hours worked  Hours
66048  Non-immigrant employees  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
56717         units  1599.0
56724         units  1586.0
56843         units  1596.0
56850         units  1573.0
56969         units  1558.0
56976         units  1547.0
57095         units  1706.0
57102         units  1651.0
57221         units  1601.0
57228         units  1595.0
65537         units  1599.0
65544         units  1585.0
65663         units  1593.0
65670         units  1577.0
65789         units  1557.0
65796         units  1550.0
65915         units  1697.0
65922         units  1660.0
66041         units  1602.0
66048         units  1590.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 56717 to 74868
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         30 non-null     int64
 1   GEO              30 non-null     object
 2   Sector           30 non-null     object
 3   Characteristics  30 non-null     object
 4   Indicators       30 non-null     object
 5   UOM              30 non-null     object
 6   SCALAR_FACTOR    30 non-null     object
 7   VALUE            30 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.1+ KB
None

Grab the dataset only in Ontario
                             sum         mean    amin  median    amax  size
Characteristics
Immigrant employees      24132.0  1608.800000  1540.0  1599.0  1706.0    15
Non-immigrant employees  23879.0  1591.933333  1542.0  1586.0  1660.0    15

Overall,
Sum :  48011.0
Mean :  1600.3666666666666
Min/median/max : 1540.0 / 1594.0 / 1706.0
Skewnewss :  0.9632697618544546
Total size :  30
2019

Grab the dataset only in Ontario
       REF_DATE      GEO                                             Sector  \
83219      2019  Ontario                      Total non-profit institutions
83226      2019  Ontario                      Total non-profit institutions
83240      2019  Ontario                      Total non-profit institutions
83345      2019  Ontario  Total non-profit institutions excluding govern...
83352      2019  Ontario  Total non-profit institutions excluding govern...
83366      2019  Ontario  Total non-profit institutions excluding govern...
83471      2019  Ontario  Non-profit institutions serving households (co...
83478      2019  Ontario  Non-profit institutions serving households (co...
83492      2019  Ontario  Non-profit institutions serving households (co...
83597      2019  Ontario                   Business non-profit institutions
83604      2019  Ontario                   Business non-profit institutions
83618      2019  Ontario                   Business non-profit institutions
83723      2019  Ontario                 Government non-profit institutions
83730      2019  Ontario                 Government non-profit institutions
83744      2019  Ontario                 Government non-profit institutions
92039      2020  Ontario                      Total non-profit institutions
92046      2020  Ontario                      Total non-profit institutions
92060      2020  Ontario                      Total non-profit institutions
92165      2020  Ontario  Total non-profit institutions excluding govern...
92172      2020  Ontario  Total non-profit institutions excluding govern...

                    Characteristics                   Indicators    UOM  \
83219  High school diploma and less  Average annual hours worked  Hours
83226             Trade certificate  Average annual hours worked  Hours
83240  University degree and higher  Average annual hours worked  Hours
83345  High school diploma and less  Average annual hours worked  Hours
83352             Trade certificate  Average annual hours worked  Hours
83366  University degree and higher  Average annual hours worked  Hours
83471  High school diploma and less  Average annual hours worked  Hours
83478             Trade certificate  Average annual hours worked  Hours
83492  University degree and higher  Average annual hours worked  Hours
83597  High school diploma and less  Average annual hours worked  Hours
83604             Trade certificate  Average annual hours worked  Hours
83618  University degree and higher  Average annual hours worked  Hours
83723  High school diploma and less  Average annual hours worked  Hours
83730             Trade certificate  Average annual hours worked  Hours
83744  University degree and higher  Average annual hours worked  Hours
92039  High school diploma and less  Average annual hours worked  Hours
92046             Trade certificate  Average annual hours worked  Hours
92060  University degree and higher  Average annual hours worked  Hours
92165  High school diploma and less  Average annual hours worked  Hours
92172             Trade certificate  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
83219         units  1245.0
83226         units  1499.0
83240         units  1670.0
83345         units  1251.0
83352         units  1513.0
83366         units  1706.0
83471         units  1197.0
83478         units  1454.0
83492         units  1680.0
83597         units  1386.0
83604         units  1669.0
83618         units  1792.0
83723         units  1238.0
83730         units  1486.0
83744         units  1649.0
92039         units  1248.0
92046         units  1482.0
92060         units  1673.0
92165         units  1234.0
92172         units  1459.0
<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 83219 to 101384
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         45 non-null     int64
 1   GEO              45 non-null     object
 2   Sector           45 non-null     object
 3   Characteristics  45 non-null     object
 4   Indicators       45 non-null     object
 5   UOM              45 non-null     object
 6   SCALAR_FACTOR    45 non-null     object
 7   VALUE            45 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 3.2+ KB
None

Grab the dataset only in Ontario
                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  19132.0  1275.466667  1171.0  1251.0  1423.0
Trade certificate             22756.0  1517.066667  1396.0  1499.0  1669.0
University degree and higher  25550.0  1703.333333  1615.0  1688.0  1808.0

                              size
Characteristics
High school diploma and less    15
Trade certificate               15
University degree and higher    15

Overall,
Sum :  67438.0
Mean :  1498.6222222222223
Min/median/max : 1171.0 / 1499.0 / 1808.0
Skewnewss :  -0.16058488152240866
Total size :  45

Panda Profiling for Final Result for Ontario

In [119]:
# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

Filtering only Prince Edward Island.

Only finished "Average annual hours worked".

In [120]:
# -- Prince Edward Island          77931.0     75.514535    121.297367  1032

ProCode = 10

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

2013

Grab the dataset only in Prince Edward Island
       REF_DATE                   GEO  \
27807      2013  Prince Edward Island
27814      2013  Prince Edward Island
27821      2013  Prince Edward Island
27828      2013  Prince Edward Island
27835      2013  Prince Edward Island
27842      2013  Prince Edward Island
27933      2013  Prince Edward Island
27940      2013  Prince Edward Island
27947      2013  Prince Edward Island
27954      2013  Prince Edward Island
27961      2013  Prince Edward Island
27968      2013  Prince Edward Island
28059      2013  Prince Edward Island
28066      2013  Prince Edward Island
28073      2013  Prince Edward Island
28080      2013  Prince Edward Island
28087      2013  Prince Edward Island
28094      2013  Prince Edward Island
28185      2013  Prince Edward Island
28192      2013  Prince Edward Island

                                                  Sector  \
27807                      Total non-profit institutions
27814                      Total non-profit institutions
27821                      Total non-profit institutions
27828                      Total non-profit institutions
27835                      Total non-profit institutions
27842                      Total non-profit institutions
27933  Total non-profit institutions excluding govern...
27940  Total non-profit institutions excluding govern...
27947  Total non-profit institutions excluding govern...
27954  Total non-profit institutions excluding govern...
27961  Total non-profit institutions excluding govern...
27968  Total non-profit institutions excluding govern...
28059  Non-profit institutions serving households (co...
28066  Non-profit institutions serving households (co...
28073  Non-profit institutions serving households (co...
28080  Non-profit institutions serving households (co...
28087  Non-profit institutions serving households (co...
28094  Non-profit institutions serving households (co...
28185                   Business non-profit institutions
28192                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
27807         15 to 24 years  Average annual hours worked  Hours
27814         25 to 34 years  Average annual hours worked  Hours
27821         35 to 44 years  Average annual hours worked  Hours
27828         45 to 54 years  Average annual hours worked  Hours
27835         55 to 64 years  Average annual hours worked  Hours
27842  65 years old and over  Average annual hours worked  Hours
27933         15 to 24 years  Average annual hours worked  Hours
27940         25 to 34 years  Average annual hours worked  Hours
27947         35 to 44 years  Average annual hours worked  Hours
27954         45 to 54 years  Average annual hours worked  Hours
27961         55 to 64 years  Average annual hours worked  Hours
27968  65 years old and over  Average annual hours worked  Hours
28059         15 to 24 years  Average annual hours worked  Hours
28066         25 to 34 years  Average annual hours worked  Hours
28073         35 to 44 years  Average annual hours worked  Hours
28080         45 to 54 years  Average annual hours worked  Hours
28087         55 to 64 years  Average annual hours worked  Hours
28094  65 years old and over  Average annual hours worked  Hours
28185         15 to 24 years  Average annual hours worked  Hours
28192         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
27807         units   886.0
27814         units  1548.0
27821         units  1766.0
27828         units  1790.0
27835         units  1639.0
27842         units   985.0
27933         units   768.0
27940         units  1692.0
27947         units  1964.0
27954         units  1890.0
27961         units  1693.0
27968         units   894.0
28059         units   741.0
28066         units  1645.0
28073         units  1940.0
28080         units  1822.0
28087         units  1716.0
28094         units   882.0
28185         units   830.0
28192         units  1852.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 27807 to 45986
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Prince Edward Island
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         12434.0   828.933333   741.0   815.0   964.0    15
25 to 34 years         25215.0  1681.000000  1504.0  1692.0  1946.0    15
35 to 44 years         29087.0  1939.133333  1711.0  1964.0  2183.0    15
45 to 54 years         28795.0  1919.666667  1760.0  1890.0  2234.0    15
55 to 64 years         25001.0  1666.733333  1621.0  1663.0  1716.0    15
65 years old and over  14541.0   969.400000   863.0   943.0  1130.0    15

Overall,
Sum :  135073.0
Mean :  1500.8111111111111
Min/median/max : 741.0 / 1663.5 / 2234.0
Skewnewss :  -0.4057395793071024
Total size :  90
2016

Grab the dataset only in Prince Edward Island
       REF_DATE                   GEO  \
54267      2016  Prince Edward Island
54274      2016  Prince Edward Island
54281      2016  Prince Edward Island
54288      2016  Prince Edward Island
54295      2016  Prince Edward Island
54302      2016  Prince Edward Island
54393      2016  Prince Edward Island
54400      2016  Prince Edward Island
54407      2016  Prince Edward Island
54414      2016  Prince Edward Island
54421      2016  Prince Edward Island
54428      2016  Prince Edward Island
54519      2016  Prince Edward Island
54526      2016  Prince Edward Island
54533      2016  Prince Edward Island
54540      2016  Prince Edward Island
54547      2016  Prince Edward Island
54554      2016  Prince Edward Island
54645      2016  Prince Edward Island
54652      2016  Prince Edward Island

                                                  Sector  \
54267                      Total non-profit institutions
54274                      Total non-profit institutions
54281                      Total non-profit institutions
54288                      Total non-profit institutions
54295                      Total non-profit institutions
54302                      Total non-profit institutions
54393  Total non-profit institutions excluding govern...
54400  Total non-profit institutions excluding govern...
54407  Total non-profit institutions excluding govern...
54414  Total non-profit institutions excluding govern...
54421  Total non-profit institutions excluding govern...
54428  Total non-profit institutions excluding govern...
54519  Non-profit institutions serving households (co...
54526  Non-profit institutions serving households (co...
54533  Non-profit institutions serving households (co...
54540  Non-profit institutions serving households (co...
54547  Non-profit institutions serving households (co...
54554  Non-profit institutions serving households (co...
54645                   Business non-profit institutions
54652                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
54267         15 to 24 years  Average annual hours worked  Hours
54274         25 to 34 years  Average annual hours worked  Hours
54281         35 to 44 years  Average annual hours worked  Hours
54288         45 to 54 years  Average annual hours worked  Hours
54295         55 to 64 years  Average annual hours worked  Hours
54302  65 years old and over  Average annual hours worked  Hours
54393         15 to 24 years  Average annual hours worked  Hours
54400         25 to 34 years  Average annual hours worked  Hours
54407         35 to 44 years  Average annual hours worked  Hours
54414         45 to 54 years  Average annual hours worked  Hours
54421         55 to 64 years  Average annual hours worked  Hours
54428  65 years old and over  Average annual hours worked  Hours
54519         15 to 24 years  Average annual hours worked  Hours
54526         25 to 34 years  Average annual hours worked  Hours
54533         35 to 44 years  Average annual hours worked  Hours
54540         45 to 54 years  Average annual hours worked  Hours
54547         55 to 64 years  Average annual hours worked  Hours
54554  65 years old and over  Average annual hours worked  Hours
54645         15 to 24 years  Average annual hours worked  Hours
54652         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
54267         units   906.0
54274         units  1597.0
54281         units  1836.0
54288         units  1833.0
54295         units  1698.0
54302         units  1088.0
54393         units   823.0
54400         units  1760.0
54407         units  2071.0
54414         units  1950.0
54421         units  1713.0
54428         units   965.0
54519         units   793.0
54526         units  1693.0
54533         units  2048.0
54540         units  1881.0
54547         units  1714.0
54554         units   941.0
54645         units   885.0
54652         units  1967.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 54267 to 72446
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Prince Edward Island
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         13332.0   888.800000   793.0   899.0   956.0    15
25 to 34 years         25066.0  1671.066667  1531.0  1628.0  1967.0    15
35 to 44 years         28999.0  1933.266667  1745.0  1947.0  2156.0    15
45 to 54 years         28337.0  1889.133333  1779.0  1851.0  2152.0    15
55 to 64 years         25394.0  1692.933333  1613.0  1698.0  1761.0    15
65 years old and over  15507.0  1033.800000   927.0  1059.0  1153.0    15

Overall,
Sum :  136635.0
Mean :  1518.1666666666667
Min/median/max : 793.0 / 1688.0 / 2156.0
Skewnewss :  -0.4531169132913988
Total size :  90
2019

Grab the dataset only in Prince Edward Island
       REF_DATE                   GEO  \
80727      2019  Prince Edward Island
80734      2019  Prince Edward Island
80741      2019  Prince Edward Island
80748      2019  Prince Edward Island
80755      2019  Prince Edward Island
80762      2019  Prince Edward Island
80853      2019  Prince Edward Island
80860      2019  Prince Edward Island
80867      2019  Prince Edward Island
80874      2019  Prince Edward Island
80881      2019  Prince Edward Island
80888      2019  Prince Edward Island
80979      2019  Prince Edward Island
80986      2019  Prince Edward Island
80993      2019  Prince Edward Island
81000      2019  Prince Edward Island
81007      2019  Prince Edward Island
81014      2019  Prince Edward Island
81105      2019  Prince Edward Island
81112      2019  Prince Edward Island

                                                  Sector  \
80727                      Total non-profit institutions
80734                      Total non-profit institutions
80741                      Total non-profit institutions
80748                      Total non-profit institutions
80755                      Total non-profit institutions
80762                      Total non-profit institutions
80853  Total non-profit institutions excluding govern...
80860  Total non-profit institutions excluding govern...
80867  Total non-profit institutions excluding govern...
80874  Total non-profit institutions excluding govern...
80881  Total non-profit institutions excluding govern...
80888  Total non-profit institutions excluding govern...
80979  Non-profit institutions serving households (co...
80986  Non-profit institutions serving households (co...
80993  Non-profit institutions serving households (co...
81000  Non-profit institutions serving households (co...
81007  Non-profit institutions serving households (co...
81014  Non-profit institutions serving households (co...
81105                   Business non-profit institutions
81112                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
80727         15 to 24 years  Average annual hours worked  Hours
80734         25 to 34 years  Average annual hours worked  Hours
80741         35 to 44 years  Average annual hours worked  Hours
80748         45 to 54 years  Average annual hours worked  Hours
80755         55 to 64 years  Average annual hours worked  Hours
80762  65 years old and over  Average annual hours worked  Hours
80853         15 to 24 years  Average annual hours worked  Hours
80860         25 to 34 years  Average annual hours worked  Hours
80867         35 to 44 years  Average annual hours worked  Hours
80874         45 to 54 years  Average annual hours worked  Hours
80881         55 to 64 years  Average annual hours worked  Hours
80888  65 years old and over  Average annual hours worked  Hours
80979         15 to 24 years  Average annual hours worked  Hours
80986         25 to 34 years  Average annual hours worked  Hours
80993         35 to 44 years  Average annual hours worked  Hours
81000         45 to 54 years  Average annual hours worked  Hours
81007         55 to 64 years  Average annual hours worked  Hours
81014  65 years old and over  Average annual hours worked  Hours
81105         15 to 24 years  Average annual hours worked  Hours
81112         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
80727         units   954.0
80734         units  1578.0
80741         units  1831.0
80748         units  1839.0
80755         units  1728.0
80762         units  1100.0
80853         units   922.0
80860         units  1614.0
80867         units  1935.0
80874         units  1849.0
80881         units  1710.0
80888         units  1011.0
80979         units   922.0
80986         units  1560.0
80993         units  1923.0
81000         units  1792.0
81007         units  1715.0
81014         units   993.0
81105         units   921.0
81112         units  1795.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 80727 to 98906
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Prince Edward Island
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         14695.0   979.666667   921.0   983.0  1030.0    15
25 to 34 years         24342.0  1622.800000  1522.0  1594.0  1795.0    15
35 to 44 years         28515.0  1901.000000  1786.0  1923.0  1975.0    15
45 to 54 years         27999.0  1866.600000  1761.0  1839.0  2012.0    15
55 to 64 years         26192.0  1746.133333  1698.0  1734.0  1808.0    15
65 years old and over  16334.0  1088.933333   993.0  1100.0  1216.0    15

Overall,
Sum :  138077.0
Mean :  1534.1888888888889
Min/median/max : 921.0 / 1719.5 / 2012.0
Skewnewss :  -0.5201295354071885
Total size :  90
2013

Grab the dataset only in Prince Edward Island
       REF_DATE                   GEO  \
27723      2013  Prince Edward Island
27730      2013  Prince Edward Island
27849      2013  Prince Edward Island
27856      2013  Prince Edward Island
27975      2013  Prince Edward Island
27982      2013  Prince Edward Island
28101      2013  Prince Edward Island
28108      2013  Prince Edward Island
28227      2013  Prince Edward Island
28234      2013  Prince Edward Island
36543      2014  Prince Edward Island
36550      2014  Prince Edward Island
36669      2014  Prince Edward Island
36676      2014  Prince Edward Island
36795      2014  Prince Edward Island
36802      2014  Prince Edward Island
36921      2014  Prince Edward Island
36928      2014  Prince Edward Island
37047      2014  Prince Edward Island
37054      2014  Prince Edward Island

                                                  Sector   Characteristics  \
27723                      Total non-profit institutions    Male employees
27730                      Total non-profit institutions  Female employees
27849  Total non-profit institutions excluding govern...    Male employees
27856  Total non-profit institutions excluding govern...  Female employees
27975  Non-profit institutions serving households (co...    Male employees
27982  Non-profit institutions serving households (co...  Female employees
28101                   Business non-profit institutions    Male employees
28108                   Business non-profit institutions  Female employees
28227                 Government non-profit institutions    Male employees
28234                 Government non-profit institutions  Female employees
36543                      Total non-profit institutions    Male employees
36550                      Total non-profit institutions  Female employees
36669  Total non-profit institutions excluding govern...    Male employees
36676  Total non-profit institutions excluding govern...  Female employees
36795  Non-profit institutions serving households (co...    Male employees
36802  Non-profit institutions serving households (co...  Female employees
36921                   Business non-profit institutions    Male employees
36928                   Business non-profit institutions  Female employees
37047                 Government non-profit institutions    Male employees
37054                 Government non-profit institutions  Female employees

                        Indicators    UOM SCALAR_FACTOR   VALUE
27723  Average annual hours worked  Hours         units  1654.0
27730  Average annual hours worked  Hours         units  1519.0
27849  Average annual hours worked  Hours         units  1706.0
27856  Average annual hours worked  Hours         units  1450.0
27975  Average annual hours worked  Hours         units  1713.0
27982  Average annual hours worked  Hours         units  1434.0
28101  Average annual hours worked  Hours         units  1695.0
28108  Average annual hours worked  Hours         units  1508.0
28227  Average annual hours worked  Hours         units  1623.0
28234  Average annual hours worked  Hours         units  1538.0
36543  Average annual hours worked  Hours         units  1684.0
36550  Average annual hours worked  Hours         units  1547.0
36669  Average annual hours worked  Hours         units  1716.0
36676  Average annual hours worked  Hours         units  1500.0
36795  Average annual hours worked  Hours         units  1722.0
36802  Average annual hours worked  Hours         units  1479.0
36921  Average annual hours worked  Hours         units  1706.0
36928  Average annual hours worked  Hours         units  1577.0
37047  Average annual hours worked  Hours         units  1664.0
37054  Average annual hours worked  Hours         units  1560.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 27723 to 45874
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype

Panda Profiling for Final Result for Prince Edward Island

In [121]:
# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

Filtering only Quebec.

Only finished "Average annual hours worked".

In [122]:
# -- Quebec                      4271657.0   3955.237963   5580.294544  1080

ProCode = 11

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

2013

Grab the dataset only in Quebec
       REF_DATE     GEO                                             Sector  \
29697      2013  Quebec                      Total non-profit institutions
29704      2013  Quebec                      Total non-profit institutions
29711      2013  Quebec                      Total non-profit institutions
29718      2013  Quebec                      Total non-profit institutions
29725      2013  Quebec                      Total non-profit institutions
29732      2013  Quebec                      Total non-profit institutions
29823      2013  Quebec  Total non-profit institutions excluding govern...
29830      2013  Quebec  Total non-profit institutions excluding govern...
29837      2013  Quebec  Total non-profit institutions excluding govern...
29844      2013  Quebec  Total non-profit institutions excluding govern...
29851      2013  Quebec  Total non-profit institutions excluding govern...
29858      2013  Quebec  Total non-profit institutions excluding govern...
29949      2013  Quebec  Non-profit institutions serving households (co...
29956      2013  Quebec  Non-profit institutions serving households (co...
29963      2013  Quebec  Non-profit institutions serving households (co...
29970      2013  Quebec  Non-profit institutions serving households (co...
29977      2013  Quebec  Non-profit institutions serving households (co...
29984      2013  Quebec  Non-profit institutions serving households (co...
30075      2013  Quebec                   Business non-profit institutions
30082      2013  Quebec                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
29697         15 to 24 years  Average annual hours worked  Hours
29704         25 to 34 years  Average annual hours worked  Hours
29711         35 to 44 years  Average annual hours worked  Hours
29718         45 to 54 years  Average annual hours worked  Hours
29725         55 to 64 years  Average annual hours worked  Hours
29732  65 years old and over  Average annual hours worked  Hours
29823         15 to 24 years  Average annual hours worked  Hours
29830         25 to 34 years  Average annual hours worked  Hours
29837         35 to 44 years  Average annual hours worked  Hours
29844         45 to 54 years  Average annual hours worked  Hours
29851         55 to 64 years  Average annual hours worked  Hours
29858  65 years old and over  Average annual hours worked  Hours
29949         15 to 24 years  Average annual hours worked  Hours
29956         25 to 34 years  Average annual hours worked  Hours
29963         35 to 44 years  Average annual hours worked  Hours
29970         45 to 54 years  Average annual hours worked  Hours
29977         55 to 64 years  Average annual hours worked  Hours
29984  65 years old and over  Average annual hours worked  Hours
30075         15 to 24 years  Average annual hours worked  Hours
30082         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
29697         units   905.0
29704         units  1477.0
29711         units  1646.0
29718         units  1724.0
29725         units  1523.0
29732         units   843.0
29823         units   841.0
29830         units  1543.0
29837         units  1679.0
29844         units  1740.0
29851         units  1530.0
29858         units   917.0
29949         units   854.0
29956         units  1500.0
29963         units  1636.0
29970         units  1698.0
29977         units  1486.0
29984         units   893.0
30075         units   813.0
30082         units  1678.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 29697 to 47876
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Quebec
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         12815.0   854.333333   791.0   841.0   948.0    15
25 to 34 years         22941.0  1529.400000  1425.0  1503.0  1700.0    15
35 to 44 years         25333.0  1688.866667  1616.0  1646.0  1855.0    15
45 to 54 years         26338.0  1755.866667  1697.0  1720.0  1912.0    15
55 to 64 years         23210.0  1547.333333  1473.0  1519.0  1715.0    15
65 years old and over  13362.0   890.800000   788.0   893.0  1023.0    15

Overall,
Sum :  123999.0
Mean :  1377.7666666666667
Min/median/max : 788.0 / 1514.5 / 1912.0
Skewnewss :  -0.5118003083466407
Total size :  90
2016

Grab the dataset only in Quebec
       REF_DATE     GEO                                             Sector  \
56157      2016  Quebec                      Total non-profit institutions
56164      2016  Quebec                      Total non-profit institutions
56171      2016  Quebec                      Total non-profit institutions
56178      2016  Quebec                      Total non-profit institutions
56185      2016  Quebec                      Total non-profit institutions
56192      2016  Quebec                      Total non-profit institutions
56283      2016  Quebec  Total non-profit institutions excluding govern...
56290      2016  Quebec  Total non-profit institutions excluding govern...
56297      2016  Quebec  Total non-profit institutions excluding govern...
56304      2016  Quebec  Total non-profit institutions excluding govern...
56311      2016  Quebec  Total non-profit institutions excluding govern...
56318      2016  Quebec  Total non-profit institutions excluding govern...
56409      2016  Quebec  Non-profit institutions serving households (co...
56416      2016  Quebec  Non-profit institutions serving households (co...
56423      2016  Quebec  Non-profit institutions serving households (co...
56430      2016  Quebec  Non-profit institutions serving households (co...
56437      2016  Quebec  Non-profit institutions serving households (co...
56444      2016  Quebec  Non-profit institutions serving households (co...
56535      2016  Quebec                   Business non-profit institutions
56542      2016  Quebec                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
56157         15 to 24 years  Average annual hours worked  Hours
56164         25 to 34 years  Average annual hours worked  Hours
56171         35 to 44 years  Average annual hours worked  Hours
56178         45 to 54 years  Average annual hours worked  Hours
56185         55 to 64 years  Average annual hours worked  Hours
56192  65 years old and over  Average annual hours worked  Hours
56283         15 to 24 years  Average annual hours worked  Hours
56290         25 to 34 years  Average annual hours worked  Hours
56297         35 to 44 years  Average annual hours worked  Hours
56304         45 to 54 years  Average annual hours worked  Hours
56311         55 to 64 years  Average annual hours worked  Hours
56318  65 years old and over  Average annual hours worked  Hours
56409         15 to 24 years  Average annual hours worked  Hours
56416         25 to 34 years  Average annual hours worked  Hours
56423         35 to 44 years  Average annual hours worked  Hours
56430         45 to 54 years  Average annual hours worked  Hours
56437         55 to 64 years  Average annual hours worked  Hours
56444  65 years old and over  Average annual hours worked  Hours
56535         15 to 24 years  Average annual hours worked  Hours
56542         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
56157         units   900.0
56164         units  1478.0
56171         units  1656.0
56178         units  1731.0
56185         units  1540.0
56192         units   872.0
56283         units   818.0
56290         units  1535.0
56297         units  1678.0
56304         units  1743.0
56311         units  1537.0
56318         units   922.0
56409         units   826.0
56416         units  1487.0
56423         units  1631.0
56430         units  1696.0
56437         units  1490.0
56444         units   903.0
56535         units   802.0
56542         units  1678.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 56157 to 74336
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Quebec
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         13139.0   875.933333   802.0   850.0   977.0    15
25 to 34 years         22807.0  1520.466667  1453.0  1486.0  1678.0    15
35 to 44 years         25266.0  1684.400000  1629.0  1656.0  1830.0    15
45 to 54 years         26376.0  1758.400000  1694.0  1735.0  1896.0    15
55 to 64 years         23388.0  1559.200000  1476.0  1541.0  1696.0    15
65 years old and over  13385.0   892.333333   840.0   873.0  1001.0    15

Overall,
Sum :  124361.0
Mean :  1381.7888888888888
Min/median/max : 802.0 / 1531.0 / 1896.0
Skewnewss :  -0.5184482009556456
Total size :  90
2019

Grab the dataset only in Quebec
       REF_DATE     GEO                                             Sector  \
82617      2019  Quebec                      Total non-profit institutions
82624      2019  Quebec                      Total non-profit institutions
82631      2019  Quebec                      Total non-profit institutions
82638      2019  Quebec                      Total non-profit institutions
82645      2019  Quebec                      Total non-profit institutions
82652      2019  Quebec                      Total non-profit institutions
82743      2019  Quebec  Total non-profit institutions excluding govern...
82750      2019  Quebec  Total non-profit institutions excluding govern...
82757      2019  Quebec  Total non-profit institutions excluding govern...
82764      2019  Quebec  Total non-profit institutions excluding govern...
82771      2019  Quebec  Total non-profit institutions excluding govern...
82778      2019  Quebec  Total non-profit institutions excluding govern...
82869      2019  Quebec  Non-profit institutions serving households (co...
82876      2019  Quebec  Non-profit institutions serving households (co...
82883      2019  Quebec  Non-profit institutions serving households (co...
82890      2019  Quebec  Non-profit institutions serving households (co...
82897      2019  Quebec  Non-profit institutions serving households (co...
82904      2019  Quebec  Non-profit institutions serving households (co...
82995      2019  Quebec                   Business non-profit institutions
83002      2019  Quebec                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
82617         15 to 24 years  Average annual hours worked  Hours
82624         25 to 34 years  Average annual hours worked  Hours
82631         35 to 44 years  Average annual hours worked  Hours
82638         45 to 54 years  Average annual hours worked  Hours
82645         55 to 64 years  Average annual hours worked  Hours
82652  65 years old and over  Average annual hours worked  Hours
82743         15 to 24 years  Average annual hours worked  Hours
82750         25 to 34 years  Average annual hours worked  Hours
82757         35 to 44 years  Average annual hours worked  Hours
82764         45 to 54 years  Average annual hours worked  Hours
82771         55 to 64 years  Average annual hours worked  Hours
82778  65 years old and over  Average annual hours worked  Hours
82869         15 to 24 years  Average annual hours worked  Hours
82876         25 to 34 years  Average annual hours worked  Hours
82883         35 to 44 years  Average annual hours worked  Hours
82890         45 to 54 years  Average annual hours worked  Hours
82897         55 to 64 years  Average annual hours worked  Hours
82904  65 years old and over  Average annual hours worked  Hours
82995         15 to 24 years  Average annual hours worked  Hours
83002         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
82617         units   941.0
82624         units  1491.0
82631         units  1670.0
82638         units  1756.0
82645         units  1570.0
82652         units   886.0
82743         units   867.0
82750         units  1533.0
82757         units  1678.0
82764         units  1760.0
82771         units  1566.0
82778         units   891.0
82869         units   874.0
82876         units  1481.0
82883         units  1626.0
82890         units  1707.0
82897         units  1515.0
82904         units   867.0
82995         units   851.0
83002         units  1681.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 82617 to 100796
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Quebec
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         13667.0   911.133333   835.0   897.0   996.0    15
25 to 34 years         22878.0  1525.200000  1438.0  1491.0  1681.0    15
35 to 44 years         25276.0  1685.066667  1615.0  1670.0  1841.0    15
45 to 54 years         26585.0  1772.333333  1697.0  1756.0  1931.0    15
55 to 64 years         23864.0  1590.933333  1515.0  1572.0  1729.0    15
65 years old and over  13713.0   914.200000   867.0   893.0  1032.0    15

Overall,
Sum :  125983.0
Mean :  1399.8111111111111
Min/median/max : 835.0 / 1538.0 / 1931.0
Skewnewss :  -0.5048806522886445
Total size :  90
2013

Grab the dataset only in Quebec
       REF_DATE     GEO                                             Sector  \
29613      2013  Quebec                      Total non-profit institutions
29620      2013  Quebec                      Total non-profit institutions
29739      2013  Quebec  Total non-profit institutions excluding govern...
29746      2013  Quebec  Total non-profit institutions excluding govern...
29865      2013  Quebec  Non-profit institutions serving households (co...
29872      2013  Quebec  Non-profit institutions serving households (co...
29991      2013  Quebec                   Business non-profit institutions
29998      2013  Quebec                   Business non-profit institutions
30117      2013  Quebec                 Government non-profit institutions
30124      2013  Quebec                 Government non-profit institutions
38433      2014  Quebec                      Total non-profit institutions
38440      2014  Quebec                      Total non-profit institutions
38559      2014  Quebec  Total non-profit institutions excluding govern...
38566      2014  Quebec  Total non-profit institutions excluding govern...
38685      2014  Quebec  Non-profit institutions serving households (co...
38692      2014  Quebec  Non-profit institutions serving households (co...
38811      2014  Quebec                   Business non-profit institutions
38818      2014  Quebec                   Business non-profit institutions
38937      2014  Quebec                 Government non-profit institutions
38944      2014  Quebec                 Government non-profit institutions

        Characteristics                   Indicators    UOM SCALAR_FACTOR  \
29613    Male employees  Average annual hours worked  Hours         units
29620  Female employees  Average annual hours worked  Hours         units
29739    Male employees  Average annual hours worked  Hours         units
29746  Female employees  Average annual hours worked  Hours         units
29865    Male employees  Average annual hours worked  Hours         units
29872  Female employees  Average annual hours worked  Hours         units
29991    Male employees  Average annual hours worked  Hours         units
29998  Female employees  Average annual hours worked  Hours         units
30117    Male employees  Average annual hours worked  Hours         units
30124  Female employees  Average annual hours worked  Hours         units
38433    Male employees  Average annual hours worked  Hours         units
38440  Female employees  Average annual hours worked  Hours         units
38559    Male employees  Average annual hours worked  Hours         units
38566  Female employees  Average annual hours worked  Hours         units
38685    Male employees  Average annual hours worked  Hours         units
38692  Female employees  Average annual hours worked  Hours         units
38811    Male employees  Average annual hours worked  Hours         units
38818  Female employees  Average annual hours worked  Hours         units
38937    Male employees  Average annual hours worked  Hours         units
38944  Female employees  Average annual hours worked  Hours         units

        VALUE
29613  1517.0
29620  1480.0
29739  1558.0
29746  1447.0
29865  1523.0
29872  1428.0
29991  1627.0
29998  1523.0
30117  1495.0
30124  1495.0
38433  1495.0
38440  1472.0
38559  1559.0
38566  1445.0
38685  1526.0
38692  1427.0
38811  1626.0
38818  1524.0
38937  1462.0
38944  1484.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 29613 to 47764
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         30 non-null     int64
 1   GEO              30 non-null     object
 2   Sector           30 non-null     object
 3   Characteristics  30 non-null     object
 4   Indicators       30 non-null     object
 5   UOM              30 non-null     object
 6   SCALAR_FACTOR    30 non-null     object
 7   VALUE            30 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.1+ KB
None

Grab the dataset only in Quebec
                      sum         mean    amin  median    amax  size
Characteristics
Female employees  22063.0  1470.866667  1416.0  1472.0  1536.0    15
Male employees    23066.0  1537.733333  1462.0  1523.0  1662.0    15

Overall,
Sum :  45129.0
Mean :  1504.3
Min/median/max : 1416.0 / 1495.0 / 1662.0
Skewnewss :  0.954796322770564
Total size :  30
2016

Grab the dataset only in Quebec
       REF_DATE     GEO                                             Sector  \
56073      2016  Quebec                      Total non-profit institutions
56080      2016  Quebec                      Total non-profit institutions
56199      2016  Quebec  Total non-profit institutions excluding govern...
56206      2016  Quebec  Total non-profit institutions excluding govern...
56325      2016  Quebec  Non-profit institutions serving households (co...
56332      2016  Quebec  Non-profit institutions serving households (co...
56451      2016  Quebec                   Business non-profit institutions
56458      2016  Quebec                   Business non-profit institutions
56577      2016  Quebec                 Government non-profit institutions

<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 82589 to 100754
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         45 non-null     int64
 1   GEO              45 non-null     object
 2   Sector           45 non-null     object
 3   Characteristics  45 non-null     object
 4   Indicators       45 non-null     object
 5   UOM              45 non-null     object
 6   SCALAR_FACTOR    45 non-null     object
 7   VALUE            45 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 3.2+ KB
None

Grab the dataset only in Quebec
                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  19065.0  1271.000000  1188.0  1267.0  1365.0
Trade certificate             23118.0  1541.200000  1423.0  1527.0  1700.0
University degree and higher  24422.0  1628.133333  1544.0  1605.0  1755.0

                              size
Characteristics
High school diploma and less    15
Trade certificate               15
University degree and higher    15

Overall,
Sum :  66605.0
Mean :  1480.111111111111
Min/median/max : 1188.0 / 1527.0 / 1755.0
Skewnewss :  -0.26989790201404135
Total size :  45
2013

Grab the dataset only in Quebec
       REF_DATE     GEO                                             Sector  \
29669      2013  Quebec                      Total non-profit institutions
29676      2013  Quebec                      Total non-profit institutions
29690      2013  Quebec                      Total non-profit institutions
29795      2013  Quebec  Total non-profit institutions excluding govern...
29802      2013  Quebec  Total non-profit institutions excluding govern...
29816      2013  Quebec  Total non-profit institutions excluding govern...
29921      2013  Quebec  Non-profit institutions serving households (co...
29928      2013  Quebec  Non-profit institutions serving households (co...
29942      2013  Quebec  Non-profit institutions serving households (co...
30047      2013  Quebec                   Business non-profit institutions
30054      2013  Quebec                   Business non-profit institutions
30068      2013  Quebec                   Business non-profit institutions
30173      2013  Quebec                 Government non-profit institutions
30180      2013  Quebec                 Government non-profit institutions
30194      2013  Quebec                 Government non-profit institutions
38489      2014  Quebec                      Total non-profit institutions
38496      2014  Quebec                      Total non-profit institutions
38510      2014  Quebec                      Total non-profit institutions
38615      2014  Quebec  Total non-profit institutions excluding govern...
38622      2014  Quebec  Total non-profit institutions excluding govern...

                    Characteristics                   Indicators    UOM  \
29669  High school diploma and less  Average annual hours worked  Hours
29676             Trade certificate  Average annual hours worked  Hours
29690  University degree and higher  Average annual hours worked  Hours
29795  High school diploma and less  Average annual hours worked  Hours
29802             Trade certificate  Average annual hours worked  Hours
29816  University degree and higher  Average annual hours worked  Hours
29921  High school diploma and less  Average annual hours worked  Hours
29928             Trade certificate  Average annual hours worked  Hours
29942  University degree and higher  Average annual hours worked  Hours
30047  High school diploma and less  Average annual hours worked  Hours
30054             Trade certificate  Average annual hours worked  Hours
30068  University degree and higher  Average annual hours worked  Hours
30173  High school diploma and less  Average annual hours worked  Hours
30180             Trade certificate  Average annual hours worked  Hours
30194  University degree and higher  Average annual hours worked  Hours
38489  High school diploma and less  Average annual hours worked  Hours
38496             Trade certificate  Average annual hours worked  Hours
38510  University degree and higher  Average annual hours worked  Hours
38615  High school diploma and less  Average annual hours worked  Hours
38622             Trade certificate  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
29669         units  1271.0
29676         units  1507.0
29690         units  1579.0
29795         units  1257.0
29802         units  1510.0
29816         units  1616.0
29921         units  1220.0
29928         units  1447.0
29942         units  1586.0
30047         units  1354.0
30054         units  1694.0
30068         units  1717.0
30173         units  1281.0
30180         units  1505.0
30194         units  1563.0
38489         units  1254.0
38496         units  1508.0
38510         units  1558.0
38615         units  1237.0
38622         units  1505.0
<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 29669 to 47834
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         45 non-null     int64
 1   GEO              45 non-null     object
 2   Sector           45 non-null     object
 3   Characteristics  45 non-null     object
 4   Indicators       45 non-null     object
 5   UOM              45 non-null     object
 6   SCALAR_FACTOR    45 non-null     object
 7   VALUE            45 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 3.2+ KB
None

Grab the dataset only in Quebec
                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  18975.0  1265.000000  1191.0  1254.0  1375.0
Trade certificate             22979.0  1531.933333  1429.0  1505.0  1720.0
University degree and higher  24145.0  1609.666667  1527.0  1586.0  1735.0

                              size
Characteristics
High school diploma and less    15
Trade certificate               15
University degree and higher    15

Overall,
Sum :  66099.0
Mean :  1468.8666666666666
Min/median/max : 1191.0 / 1505.0 / 1735.0
Skewnewss :  -0.18858000026269586
Total size :  45
2016

Grab the dataset only in Quebec
       REF_DATE     GEO                                             Sector  \
56087      2016  Quebec                      Total non-profit institutions
56094      2016  Quebec                      Total non-profit institutions
56213      2016  Quebec  Total non-profit institutions excluding govern...
56220      2016  Quebec  Total non-profit institutions excluding govern...
56339      2016  Quebec  Non-profit institutions serving households (co...
56346      2016  Quebec  Non-profit institutions serving households (co...
56465      2016  Quebec                   Business non-profit institutions
56472      2016  Quebec                   Business non-profit institutions
56591      2016  Quebec                 Government non-profit institutions
56598      2016  Quebec                 Government non-profit institutions
64907      2017  Quebec                      Total non-profit institutions
64914      2017  Quebec                      Total non-profit institutions
65033      2017  Quebec  Total non-profit institutions excluding govern...
65040      2017  Quebec  Total non-profit institutions excluding govern...
65159      2017  Quebec  Non-profit institutions serving households (co...
65166      2017  Quebec  Non-profit institutions serving households (co...
65285      2017  Quebec                   Business non-profit institutions
65292      2017  Quebec                   Business non-profit institutions
65411      2017  Quebec                 Government non-profit institutions
65418      2017  Quebec                 Government non-profit institutions

               Characteristics                   Indicators    UOM  \
56087      Immigrant employees  Average annual hours worked  Hours
56094  Non-immigrant employees  Average annual hours worked  Hours
56213      Immigrant employees  Average annual hours worked  Hours
56220  Non-immigrant employees  Average annual hours worked  Hours
56339      Immigrant employees  Average annual hours worked  Hours
56346  Non-immigrant employees  Average annual hours worked  Hours
56465      Immigrant employees  Average annual hours worked  Hours
56472  Non-immigrant employees  Average annual hours worked  Hours
56591      Immigrant employees  Average annual hours worked  Hours
56598  Non-immigrant employees  Average annual hours worked  Hours
64907      Immigrant employees  Average annual hours worked  Hours
64914  Non-immigrant employees  Average annual hours worked  Hours
65033      Immigrant employees  Average annual hours worked  Hours
65040  Non-immigrant employees  Average annual hours worked  Hours
65159      Immigrant employees  Average annual hours worked  Hours
65166  Non-immigrant employees  Average annual hours worked  Hours
65285      Immigrant employees  Average annual hours worked  Hours
65292  Non-immigrant employees  Average annual hours worked  Hours
65411      Immigrant employees  Average annual hours worked  Hours
65418  Non-immigrant employees  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
56087         units  1484.0
56094         units  1498.0
56213         units  1452.0
56220         units  1483.0
56339         units  1414.0
56346         units  1452.0
56465         units  1575.0
56472         units  1577.0
56591         units  1498.0
56598         units  1506.0
64907         units  1475.0
64914         units  1494.0
65033         units  1436.0
65040         units  1469.0
65159         units  1400.0
65166         units  1438.0
65285         units  1551.0
65292         units  1561.0
65411         units  1493.0
65418         units  1507.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 56087 to 74238
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         30 non-null     int64
 1   GEO              30 non-null     object
 2   Sector           30 non-null     object
 3   Characteristics  30 non-null     object
 4   Indicators       30 non-null     object
 5   UOM              30 non-null     object
 6   SCALAR_FACTOR    30 non-null     object
 7   VALUE            30 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.1+ KB
None

Grab the dataset only in Quebec
                             sum         mean    amin  median    amax  size
Characteristics
Immigrant employees      22210.0  1480.666667  1400.0  1484.0  1575.0    15
Non-immigrant employees  22497.0  1499.800000  1438.0  1498.0  1577.0    15

Overall,
Sum :  44707.0
Mean :  1490.2333333333333
Min/median/max : 1400.0 / 1491.5 / 1577.0
Skewnewss :  0.22344983754018957
Total size :  30
2019

Grab the dataset only in Quebec
       REF_DATE     GEO                                             Sector  \
82589      2019  Quebec                      Total non-profit institutions
82596      2019  Quebec                      Total non-profit institutions
82610      2019  Quebec                      Total non-profit institutions
82715      2019  Quebec  Total non-profit institutions excluding govern...
82722      2019  Quebec  Total non-profit institutions excluding govern...
82736      2019  Quebec  Total non-profit institutions excluding govern...
82841      2019  Quebec  Non-profit institutions serving households (co...
82848      2019  Quebec  Non-profit institutions serving households (co...
82862      2019  Quebec  Non-profit institutions serving households (co...
82967      2019  Quebec                   Business non-profit institutions
82974      2019  Quebec                   Business non-profit institutions
82988      2019  Quebec                   Business non-profit institutions
83093      2019  Quebec                 Government non-profit institutions
83100      2019  Quebec                 Government non-profit institutions
83114      2019  Quebec                 Government non-profit institutions
91409      2020  Quebec                      Total non-profit institutions
91416      2020  Quebec                      Total non-profit institutions
91430      2020  Quebec                      Total non-profit institutions
91535      2020  Quebec  Total non-profit institutions excluding govern...
91542      2020  Quebec  Total non-profit institutions excluding govern...

                    Characteristics                   Indicators    UOM  \
82589  High school diploma and less  Average annual hours worked  Hours
82596             Trade certificate  Average annual hours worked  Hours
82610  University degree and higher  Average annual hours worked  Hours
82715  High school diploma and less  Average annual hours worked  Hours
82722             Trade certificate  Average annual hours worked  Hours
82736  University degree and higher  Average annual hours worked  Hours
82841  High school diploma and less  Average annual hours worked  Hours
82848             Trade certificate  Average annual hours worked  Hours
82862  University degree and higher  Average annual hours worked  Hours
82967  High school diploma and less  Average annual hours worked  Hours
82974             Trade certificate  Average annual hours worked  Hours
82988  University degree and higher  Average annual hours worked  Hours
83093  High school diploma and less  Average annual hours worked  Hours
83100             Trade certificate  Average annual hours worked  Hours
83114  University degree and higher  Average annual hours worked  Hours
91409  High school diploma and less  Average annual hours worked  Hours
91416             Trade certificate  Average annual hours worked  Hours
91430  University degree and higher  Average annual hours worked  Hours
91535  High school diploma and less  Average annual hours worked  Hours
91542             Trade certificate  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
82589         units  1267.0
82596         units  1549.0
82610         units  1602.0
82715         units  1236.0
82722         units  1494.0
82736         units  1632.0
82841         units  1188.0
82848         units  1423.0
82862         units  1592.0
82967         units  1365.0
82974         units  1700.0
82988         units  1752.0
83093         units  1289.0
83100         units  1567.0
83114         units  1588.0
91409         units  1263.0
91416         units  1520.0
91430         units  1569.0
91535         units  1246.0
91542         units  1490.0
<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 82589 to 100754
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         45 non-null     int64
 1   GEO              45 non-null     object
 2   Sector           45 non-null     object
 3   Characteristics  45 non-null     object
 4   Indicators       45 non-null     object
 5   UOM              45 non-null     object
 6   SCALAR_FACTOR    45 non-null     object
 7   VALUE            45 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 3.2+ KB
None

Grab the dataset only in Quebec
                                  sum         mean    amin  median    amax  \
Characteristics
High school diploma and less  19065.0  1271.000000  1188.0  1267.0  1365.0
Trade certificate             23118.0  1541.200000  1423.0  1527.0  1700.0
University degree and higher  24422.0  1628.133333  1544.0  1605.0  1755.0

                              size
Characteristics
High school diploma and less    15
Trade certificate               15
University degree and higher    15

Overall,
Sum :  66605.0
Mean :  1480.111111111111
Min/median/max : 1188.0 / 1527.0 / 1755.0
Skewnewss :  -0.26989790201404135
Total size :  45

Panda Profiling for Final Result for Quebec

In [123]:
# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

Filtering only Saskatchewan.

Only finished "Average annual hours worked".

In [124]:
# -- Saskatchewan                 650781.0    602.575000    876.896377  1080

ProCode = 12

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

2013

Grab the dataset only in Saskatchewan
       REF_DATE           GEO  \
31587      2013  Saskatchewan
31594      2013  Saskatchewan
31601      2013  Saskatchewan
31608      2013  Saskatchewan
31615      2013  Saskatchewan
31622      2013  Saskatchewan
31713      2013  Saskatchewan
31720      2013  Saskatchewan
31727      2013  Saskatchewan
31734      2013  Saskatchewan
31741      2013  Saskatchewan
31748      2013  Saskatchewan
31839      2013  Saskatchewan
31846      2013  Saskatchewan
31853      2013  Saskatchewan
31860      2013  Saskatchewan
31867      2013  Saskatchewan
31874      2013  Saskatchewan
31965      2013  Saskatchewan
31972      2013  Saskatchewan

                                                  Sector  \
31587                      Total non-profit institutions
31594                      Total non-profit institutions
31601                      Total non-profit institutions
31608                      Total non-profit institutions
31615                      Total non-profit institutions
31622                      Total non-profit institutions
31713  Total non-profit institutions excluding govern...
31720  Total non-profit institutions excluding govern...
31727  Total non-profit institutions excluding govern...
31734  Total non-profit institutions excluding govern...
31741  Total non-profit institutions excluding govern...
31748  Total non-profit institutions excluding govern...
31839  Non-profit institutions serving households (co...
31846  Non-profit institutions serving households (co...
31853  Non-profit institutions serving households (co...
31860  Non-profit institutions serving households (co...
31867  Non-profit institutions serving households (co...
31874  Non-profit institutions serving households (co...
31965                   Business non-profit institutions
31972                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
31587         15 to 24 years  Average annual hours worked  Hours
31594         25 to 34 years  Average annual hours worked  Hours
31601         35 to 44 years  Average annual hours worked  Hours
31608         45 to 54 years  Average annual hours worked  Hours
31615         55 to 64 years  Average annual hours worked  Hours
31622  65 years old and over  Average annual hours worked  Hours
31713         15 to 24 years  Average annual hours worked  Hours
31720         25 to 34 years  Average annual hours worked  Hours
31727         35 to 44 years  Average annual hours worked  Hours
31734         45 to 54 years  Average annual hours worked  Hours
31741         55 to 64 years  Average annual hours worked  Hours
31748  65 years old and over  Average annual hours worked  Hours
31839         15 to 24 years  Average annual hours worked  Hours
31846         25 to 34 years  Average annual hours worked  Hours
31853         35 to 44 years  Average annual hours worked  Hours
31860         45 to 54 years  Average annual hours worked  Hours
31867         55 to 64 years  Average annual hours worked  Hours
31874  65 years old and over  Average annual hours worked  Hours
31965         15 to 24 years  Average annual hours worked  Hours
31972         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
31587         units   976.0
31594         units  1548.0
31601         units  1719.0
31608         units  1804.0
31615         units  1648.0
31622         units  1050.0
31713         units   926.0
31720         units  1636.0
31727         units  1725.0
31734         units  1813.0
31741         units  1614.0
31748         units  1008.0
31839         units   906.0
31846         units  1590.0
31853         units  1678.0
31860         units  1783.0
31867         units  1593.0
31874         units   998.0
31965         units   988.0
31972         units  1817.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 31587 to 49766
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Saskatchewan
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         14459.0   963.933333   906.0   963.0  1005.0    15
25 to 34 years         24188.0  1612.533333  1481.0  1590.0  1817.0    15
35 to 44 years         26159.0  1743.933333  1677.0  1715.0  1928.0    15
45 to 54 years         27537.0  1835.800000  1768.0  1812.0  1988.0    15
55 to 64 years         24765.0  1651.000000  1593.0  1648.0  1714.0    15
65 years old and over  16024.0  1068.266667   998.0  1081.0  1101.0    15

Overall,
Sum :  133132.0
Mean :  1479.2444444444445
Min/median/max : 906.0 / 1635.0 / 1988.0
Skewnewss :  -0.503202623028347
Total size :  90
2016

Grab the dataset only in Saskatchewan
       REF_DATE           GEO  \
58047      2016  Saskatchewan
58054      2016  Saskatchewan
58061      2016  Saskatchewan
58068      2016  Saskatchewan
58075      2016  Saskatchewan
58082      2016  Saskatchewan
58173      2016  Saskatchewan
58180      2016  Saskatchewan
58187      2016  Saskatchewan
58194      2016  Saskatchewan
58201      2016  Saskatchewan
58208      2016  Saskatchewan
58299      2016  Saskatchewan
58306      2016  Saskatchewan
58313      2016  Saskatchewan
58320      2016  Saskatchewan
58327      2016  Saskatchewan
58334      2016  Saskatchewan
58425      2016  Saskatchewan
58432      2016  Saskatchewan

                                                  Sector  \
58047                      Total non-profit institutions
58054                      Total non-profit institutions
58061                      Total non-profit institutions
58068                      Total non-profit institutions
58075                      Total non-profit institutions
58082                      Total non-profit institutions
58173  Total non-profit institutions excluding govern...
58180  Total non-profit institutions excluding govern...
58187  Total non-profit institutions excluding govern...
58194  Total non-profit institutions excluding govern...
58201  Total non-profit institutions excluding govern...
58208  Total non-profit institutions excluding govern...
58299  Non-profit institutions serving households (co...
58306  Non-profit institutions serving households (co...
58313  Non-profit institutions serving households (co...
58320  Non-profit institutions serving households (co...
58327  Non-profit institutions serving households (co...
58334  Non-profit institutions serving households (co...
58425                   Business non-profit institutions
58432                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
58047         15 to 24 years  Average annual hours worked  Hours
58054         25 to 34 years  Average annual hours worked  Hours
58061         35 to 44 years  Average annual hours worked  Hours
58068         45 to 54 years  Average annual hours worked  Hours
58075         55 to 64 years  Average annual hours worked  Hours
58082  65 years old and over  Average annual hours worked  Hours
58173         15 to 24 years  Average annual hours worked  Hours
58180         25 to 34 years  Average annual hours worked  Hours
58187         35 to 44 years  Average annual hours worked  Hours
58194         45 to 54 years  Average annual hours worked  Hours
58201         55 to 64 years  Average annual hours worked  Hours
58208  65 years old and over  Average annual hours worked  Hours
58299         15 to 24 years  Average annual hours worked  Hours
58306         25 to 34 years  Average annual hours worked  Hours
58313         35 to 44 years  Average annual hours worked  Hours
58320         45 to 54 years  Average annual hours worked  Hours
58327         55 to 64 years  Average annual hours worked  Hours
58334  65 years old and over  Average annual hours worked  Hours
58425         15 to 24 years  Average annual hours worked  Hours
58432         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
58047         units   952.0
58054         units  1504.0
58061         units  1676.0
58068         units  1775.0
58075         units  1625.0
58082         units  1054.0
58173         units   925.0
58180         units  1605.0
58187         units  1714.0
58194         units  1838.0
58201         units  1624.0
58208         units  1055.0
58299         units   915.0
58306         units  1562.0
58313         units  1680.0
58320         units  1809.0
58327         units  1607.0
58334         units  1054.0
58425         units   961.0
58432         units  1787.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 58047 to 76226
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Saskatchewan
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         14158.0   943.866667   890.0   947.0  1010.0    15
25 to 34 years         23612.0  1574.133333  1473.0  1549.0  1787.0    15
35 to 44 years         25733.0  1715.533333  1644.0  1685.0  1872.0    15
45 to 54 years         27299.0  1819.933333  1749.0  1797.0  1971.0    15
55 to 64 years         24369.0  1624.600000  1554.0  1624.0  1699.0    15
65 years old and over  15679.0  1045.266667  1008.0  1054.0  1078.0    15

Overall,
Sum :  130850.0
Mean :  1453.888888888889
Min/median/max : 890.0 / 1605.5 / 1971.0
Skewnewss :  -0.4965142208647792
Total size :  90
2019

Grab the dataset only in Saskatchewan
       REF_DATE           GEO  \
84507      2019  Saskatchewan
84514      2019  Saskatchewan
84521      2019  Saskatchewan
84528      2019  Saskatchewan
84535      2019  Saskatchewan
84542      2019  Saskatchewan
84633      2019  Saskatchewan
84640      2019  Saskatchewan
84647      2019  Saskatchewan
84654      2019  Saskatchewan
84661      2019  Saskatchewan
84668      2019  Saskatchewan
84759      2019  Saskatchewan
84766      2019  Saskatchewan
84773      2019  Saskatchewan
84780      2019  Saskatchewan
84787      2019  Saskatchewan
84794      2019  Saskatchewan
84885      2019  Saskatchewan
84892      2019  Saskatchewan

                                                  Sector  \
84507                      Total non-profit institutions
84514                      Total non-profit institutions
84521                      Total non-profit institutions
84528                      Total non-profit institutions
84535                      Total non-profit institutions
84542                      Total non-profit institutions
84633  Total non-profit institutions excluding govern...
84640  Total non-profit institutions excluding govern...
84647  Total non-profit institutions excluding govern...
84654  Total non-profit institutions excluding govern...
84661  Total non-profit institutions excluding govern...
84668  Total non-profit institutions excluding govern...
84759  Non-profit institutions serving households (co...
84766  Non-profit institutions serving households (co...
84773  Non-profit institutions serving households (co...
84780  Non-profit institutions serving households (co...
84787  Non-profit institutions serving households (co...
84794  Non-profit institutions serving households (co...
84885                   Business non-profit institutions
84892                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
84507         15 to 24 years  Average annual hours worked  Hours
84514         25 to 34 years  Average annual hours worked  Hours
84521         35 to 44 years  Average annual hours worked  Hours
84528         45 to 54 years  Average annual hours worked  Hours
84535         55 to 64 years  Average annual hours worked  Hours
84542  65 years old and over  Average annual hours worked  Hours
84633         15 to 24 years  Average annual hours worked  Hours
84640         25 to 34 years  Average annual hours worked  Hours
84647         35 to 44 years  Average annual hours worked  Hours
84654         45 to 54 years  Average annual hours worked  Hours
84661         55 to 64 years  Average annual hours worked  Hours
84668  65 years old and over  Average annual hours worked  Hours
84759         15 to 24 years  Average annual hours worked  Hours
84766         25 to 34 years  Average annual hours worked  Hours
84773         35 to 44 years  Average annual hours worked  Hours
84780         45 to 54 years  Average annual hours worked  Hours
84787         55 to 64 years  Average annual hours worked  Hours
84794  65 years old and over  Average annual hours worked  Hours
84885         15 to 24 years  Average annual hours worked  Hours
84892         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
84507         units   981.0
84514         units  1533.0
84521         units  1702.0
84528         units  1804.0
84535         units  1650.0
84542         units  1052.0
84633         units   925.0
84640         units  1589.0
84647         units  1747.0
84654         units  1856.0
84661         units  1632.0
84668         units  1059.0
84759         units   927.0
84766         units  1562.0
84773         units  1726.0
84780         units  1845.0
84787         units  1625.0
84794         units  1065.0
84885         units   920.0
84892         units  1701.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 84507 to 102686
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Saskatchewan
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         14285.0   952.333333   904.0   925.0  1053.0    15
25 to 34 years         23609.0  1573.933333  1500.0  1554.0  1701.0    15
35 to 44 years         26024.0  1734.933333  1659.0  1723.0  1845.0    15
45 to 54 years         27466.0  1831.066667  1758.0  1822.0  1912.0    15
55 to 64 years         24602.0  1640.133333  1566.0  1641.0  1690.0    15
65 years old and over  15732.0  1048.800000   992.0  1058.0  1071.0    15

Overall,
Sum :  131718.0
Mean :  1463.5333333333333
Min/median/max : 904.0 / 1622.0 / 1912.0
Skewnewss :  -0.5344500399370813
Total size :  90
2013

Grab the dataset only in Saskatchewan
       REF_DATE           GEO  \
31503      2013  Saskatchewan
31510      2013  Saskatchewan
31629      2013  Saskatchewan
31636      2013  Saskatchewan
31755      2013  Saskatchewan
31762      2013  Saskatchewan
31881      2013  Saskatchewan
31888      2013  Saskatchewan
32007      2013  Saskatchewan
32014      2013  Saskatchewan
40323      2014  Saskatchewan
40330      2014  Saskatchewan
40449      2014  Saskatchewan
40456      2014  Saskatchewan
40575      2014  Saskatchewan
40582      2014  Saskatchewan
40701      2014  Saskatchewan
40708      2014  Saskatchewan
40827      2014  Saskatchewan
40834      2014  Saskatchewan

                                                  Sector   Characteristics  \
31503                      Total non-profit institutions    Male employees
31510                      Total non-profit institutions  Female employees
31629  Total non-profit institutions excluding govern...    Male employees
31636  Total non-profit institutions excluding govern...  Female employees
31755  Non-profit institutions serving households (co...    Male employees
31762  Non-profit institutions serving households (co...  Female employees
31881                   Business non-profit institutions    Male employees
31888                   Business non-profit institutions  Female employees
32007                 Government non-profit institutions    Male employees
32014                 Government non-profit institutions  Female employees
40323                      Total non-profit institutions    Male employees
40330                      Total non-profit institutions  Female employees
40449  Total non-profit institutions excluding govern...    Male employees
40456  Total non-profit institutions excluding govern...  Female employees
40575  Non-profit institutions serving households (co...    Male employees
40582  Non-profit institutions serving households (co...  Female employees
40701                   Business non-profit institutions    Male employees
40708                   Business non-profit institutions  Female employees
40827                 Government non-profit institutions    Male employees
40834                 Government non-profit institutions  Female employees

                        Indicators    UOM SCALAR_FACTOR   VALUE
31503  Average annual hours worked  Hours         units  1685.0
31510  Average annual hours worked  Hours         units  1528.0
31629  Average annual hours worked  Hours         units  1707.0
31636  Average annual hours worked  Hours         units  1415.0
31755  Average annual hours worked  Hours         units  1687.0
31762  Average annual hours worked  Hours         units  1401.0
31881  Average annual hours worked  Hours         units  1759.0
31888  Average annual hours worked  Hours         units  1493.0
32007  Average annual hours worked  Hours         units  1674.0
32014  Average annual hours worked  Hours         units  1560.0
40323  Average annual hours worked  Hours         units  1664.0
40330  Average annual hours worked  Hours         units  1532.0
40449  Average annual hours worked  Hours         units  1729.0
40456  Average annual hours worked  Hours         units  1452.0
40575  Average annual hours worked  Hours         units  1724.0
40582  Average annual hours worked  Hours         units  1445.0
40701  Average annual hours worked  Hours         units  1744.0
40708  Average annual hours worked  Hours         units  1492.0
40827  Average annual hours worked  Hours         units  1630.0
40834  Average annual hours worked  Hours         units  1555.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 31503 to 49654
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         30 non-null     int64
 1   GEO              30 non-null     object
 2   Sector           30 non-null     object
 3   Characteristics  30 non-null     object
 4   Indicators       30 non-null     object
 5   UOM              30 non-null     object
 6   SCALAR_FACTOR    30 non-null     object
 7   VALUE            30 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.1+ KB
None

Grab the dataset only in Saskatchewan
                      sum         mean    amin  median    amax  size
Characteristics
Female employees  22296.0  1486.400000  1401.0  1493.0  1560.0    15
Male employees    25442.0  1696.133333  1602.0  1707.0  1759.0    15


Panda Profiling for Final Result for Saskatchewan

In [125]:
# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

Filtering only Yukon.

Only finished "Average annual hours worked".

In [126]:
# -- Yukon                         16914.0     18.070513     20.188135   936

ProCode = 13

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

2013

Grab the dataset only in Yukon
       REF_DATE    GEO                                             Sector  \
33477      2013  Yukon                      Total non-profit institutions
33484      2013  Yukon                      Total non-profit institutions
33491      2013  Yukon                      Total non-profit institutions
33498      2013  Yukon                      Total non-profit institutions
33505      2013  Yukon                      Total non-profit institutions
33512      2013  Yukon                      Total non-profit institutions
33603      2013  Yukon  Total non-profit institutions excluding govern...
33610      2013  Yukon  Total non-profit institutions excluding govern...
33617      2013  Yukon  Total non-profit institutions excluding govern...
33624      2013  Yukon  Total non-profit institutions excluding govern...
33631      2013  Yukon  Total non-profit institutions excluding govern...
33638      2013  Yukon  Total non-profit institutions excluding govern...
33736      2013  Yukon  Non-profit institutions serving households (co...
33743      2013  Yukon  Non-profit institutions serving households (co...
33750      2013  Yukon  Non-profit institutions serving households (co...
33757      2013  Yukon  Non-profit institutions serving households (co...
33862      2013  Yukon                   Business non-profit institutions
33869      2013  Yukon                   Business non-profit institutions
33876      2013  Yukon                   Business non-profit institutions
33883      2013  Yukon                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
33477         15 to 24 years  Average annual hours worked  Hours
33484         25 to 34 years  Average annual hours worked  Hours
33491         35 to 44 years  Average annual hours worked  Hours
33498         45 to 54 years  Average annual hours worked  Hours
33505         55 to 64 years  Average annual hours worked  Hours
33512  65 years old and over  Average annual hours worked  Hours
33603         15 to 24 years  Average annual hours worked  Hours
33610         25 to 34 years  Average annual hours worked  Hours
33617         35 to 44 years  Average annual hours worked  Hours
33624         45 to 54 years  Average annual hours worked  Hours
33631         55 to 64 years  Average annual hours worked  Hours
33638  65 years old and over  Average annual hours worked  Hours
33736         25 to 34 years  Average annual hours worked  Hours
33743         35 to 44 years  Average annual hours worked  Hours
33750         45 to 54 years  Average annual hours worked  Hours
33757         55 to 64 years  Average annual hours worked  Hours
33862         25 to 34 years  Average annual hours worked  Hours
33869         35 to 44 years  Average annual hours worked  Hours
33876         45 to 54 years  Average annual hours worked  Hours
33883         55 to 64 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
33477         units   870.0
33484         units  1533.0
33491         units  1640.0
33498         units  1663.0
33505         units  1587.0
33512         units   819.0
33603         units   879.0
33610         units  1514.0
33617         units  1721.0
33624         units  1607.0
33631         units  1526.0
33638         units   772.0
33736         units  1490.0
33743         units  1715.0
33750         units  1577.0
33757         units  1525.0
33862         units  1882.0
33869         units  1778.0
33876         units  1933.0
33883         units  1538.0
<class 'pandas.core.frame.DataFrame'>
Index: 78 entries, 33477 to 51656
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         78 non-null     int64
 1   GEO              78 non-null     object
 2   Sector           78 non-null     object
 3   Characteristics  78 non-null     object
 4   Indicators       78 non-null     object
 5   UOM              78 non-null     object
 6   SCALAR_FACTOR    78 non-null     object
 7   VALUE            78 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 5.5+ KB
None

Grab the dataset only in Yukon
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years          7276.0   808.444444   462.0   876.0   953.0     9
25 to 34 years         23527.0  1568.466667  1408.0  1514.0  1882.0    15
35 to 44 years         25314.0  1687.600000  1477.0  1721.0  1864.0    15
45 to 54 years         26117.0  1741.133333  1577.0  1679.0  2294.0    15
55 to 64 years         23196.0  1546.400000  1390.0  1539.0  1673.0    15
65 years old and over   7438.0   826.444444   724.0   812.0   962.0     9

Overall,
Sum :  112868.0
Mean :  1447.025641025641
Min/median/max : 462.0 / 1567.5 / 2294.0
Skewnewss :  -0.8219440206627865
Total size :  78
2016

Grab the dataset only in Yukon
       REF_DATE    GEO                                             Sector  \
59937      2016  Yukon                      Total non-profit institutions
59944      2016  Yukon                      Total non-profit institutions
59951      2016  Yukon                      Total non-profit institutions
59958      2016  Yukon                      Total non-profit institutions
59965      2016  Yukon                      Total non-profit institutions
59972      2016  Yukon                      Total non-profit institutions
60063      2016  Yukon  Total non-profit institutions excluding govern...
60070      2016  Yukon  Total non-profit institutions excluding govern...
60077      2016  Yukon  Total non-profit institutions excluding govern...
60084      2016  Yukon  Total non-profit institutions excluding govern...
60091      2016  Yukon  Total non-profit institutions excluding govern...
60098      2016  Yukon  Total non-profit institutions excluding govern...
60196      2016  Yukon  Non-profit institutions serving households (co...
60203      2016  Yukon  Non-profit institutions serving households (co...
60210      2016  Yukon  Non-profit institutions serving households (co...
60217      2016  Yukon  Non-profit institutions serving households (co...
60322      2016  Yukon                   Business non-profit institutions
60329      2016  Yukon                   Business non-profit institutions
60336      2016  Yukon                   Business non-profit institutions
60343      2016  Yukon                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
59937         15 to 24 years  Average annual hours worked  Hours
59944         25 to 34 years  Average annual hours worked  Hours
59951         35 to 44 years  Average annual hours worked  Hours
59958         45 to 54 years  Average annual hours worked  Hours
59965         55 to 64 years  Average annual hours worked  Hours
59972  65 years old and over  Average annual hours worked  Hours
60063         15 to 24 years  Average annual hours worked  Hours
60070         25 to 34 years  Average annual hours worked  Hours
60077         35 to 44 years  Average annual hours worked  Hours
60084         45 to 54 years  Average annual hours worked  Hours
60091         55 to 64 years  Average annual hours worked  Hours
60098  65 years old and over  Average annual hours worked  Hours
60196         25 to 34 years  Average annual hours worked  Hours
60203         35 to 44 years  Average annual hours worked  Hours
60210         45 to 54 years  Average annual hours worked  Hours
60217         55 to 64 years  Average annual hours worked  Hours
60322         25 to 34 years  Average annual hours worked  Hours
60329         35 to 44 years  Average annual hours worked  Hours
60336         45 to 54 years  Average annual hours worked  Hours
60343         55 to 64 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
59937         units   908.0
59944         units  1482.0
59951         units  1601.0
59958         units  1693.0
59965         units  1515.0
59972         units   757.0
60063         units   924.0
60070         units  1449.0
60077         units  1774.0
60084         units  1665.0
60091         units  1417.0
60098         units   719.0
60196         units  1411.0
60203         units  1759.0
60210         units  1606.0
60217         units  1410.0
60322         units  1864.0
60329         units  1864.0
60336         units  2312.0
60343         units  1500.0
<class 'pandas.core.frame.DataFrame'>
Index: 78 entries, 59937 to 78116
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         78 non-null     int64
 1   GEO              78 non-null     object
 2   Sector           78 non-null     object
 3   Characteristics  78 non-null     object
 4   Indicators       78 non-null     object
 5   UOM              78 non-null     object
 6   SCALAR_FACTOR    78 non-null     object
 7   VALUE            78 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 5.5+ KB
None

Grab the dataset only in Yukon
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years          8722.0   969.111111   882.0   925.0  1185.0     9
25 to 34 years         22959.0  1530.600000  1343.0  1482.0  1864.0    15
35 to 44 years         25369.0  1691.266667  1436.0  1773.0  1864.0    15
45 to 54 years         26570.0  1771.333333  1595.0  1716.0  2312.0    15
55 to 64 years         22400.0  1493.333333  1410.0  1500.0  1608.0    15
65 years old and over   6811.0   756.777778   701.0   754.0   828.0     9

Overall,
Sum :  112831.0
Mean :  1446.551282051282
Min/median/max : 701.0 / 1503.5 / 2312.0
Skewnewss :  -0.6012574770654578
Total size :  78
2019

Grab the dataset only in Yukon
       REF_DATE    GEO                                             Sector  \
86397      2019  Yukon                      Total non-profit institutions
86404      2019  Yukon                      Total non-profit institutions
86411      2019  Yukon                      Total non-profit institutions
86418      2019  Yukon                      Total non-profit institutions
86425      2019  Yukon                      Total non-profit institutions
86432      2019  Yukon                      Total non-profit institutions
86523      2019  Yukon  Total non-profit institutions excluding govern...
86530      2019  Yukon  Total non-profit institutions excluding govern...
86537      2019  Yukon  Total non-profit institutions excluding govern...
86544      2019  Yukon  Total non-profit institutions excluding govern...
86551      2019  Yukon  Total non-profit institutions excluding govern...
86558      2019  Yukon  Total non-profit institutions excluding govern...
86656      2019  Yukon  Non-profit institutions serving households (co...
86663      2019  Yukon  Non-profit institutions serving households (co...
86670      2019  Yukon  Non-profit institutions serving households (co...
86677      2019  Yukon  Non-profit institutions serving households (co...
86782      2019  Yukon                   Business non-profit institutions
86789      2019  Yukon                   Business non-profit institutions
86796      2019  Yukon                   Business non-profit institutions
86803      2019  Yukon                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
86397         15 to 24 years  Average annual hours worked  Hours
86404         25 to 34 years  Average annual hours worked  Hours
86411         35 to 44 years  Average annual hours worked  Hours
86418         45 to 54 years  Average annual hours worked  Hours
86425         55 to 64 years  Average annual hours worked  Hours
86432  65 years old and over  Average annual hours worked  Hours
86523         15 to 24 years  Average annual hours worked  Hours
86530         25 to 34 years  Average annual hours worked  Hours
86537         35 to 44 years  Average annual hours worked  Hours
86544         45 to 54 years  Average annual hours worked  Hours
86551         55 to 64 years  Average annual hours worked  Hours
86558  65 years old and over  Average annual hours worked  Hours
86656         25 to 34 years  Average annual hours worked  Hours
86663         35 to 44 years  Average annual hours worked  Hours
86670         45 to 54 years  Average annual hours worked  Hours
86677         55 to 64 years  Average annual hours worked  Hours
86782         25 to 34 years  Average annual hours worked  Hours
86789         35 to 44 years  Average annual hours worked  Hours
86796         45 to 54 years  Average annual hours worked  Hours
86803         55 to 64 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
86397         units   987.0
86404         units  1416.0
86411         units  1602.0
86418         units  1749.0
86425         units  1453.0
86432         units   719.0
86523         units   913.0
86530         units  1363.0
86537         units  1794.0
86544         units  1640.0
86551         units  1419.0
86558         units   798.0
86656         units  1307.0
86663         units  1779.0
86670         units  1600.0
86677         units  1405.0
86782         units  1870.0
86789         units  1875.0
86796         units  2000.0
86803         units  1500.0
<class 'pandas.core.frame.DataFrame'>
Index: 78 entries, 86397 to 104576
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         78 non-null     int64
 1   GEO              78 non-null     object
 2   Sector           78 non-null     object
 3   Characteristics  78 non-null     object
 4   Indicators       78 non-null     object
 5   UOM              78 non-null     object
 6   SCALAR_FACTOR    78 non-null     object
 7   VALUE            78 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 5.5+ KB
None

Grab the dataset only in Yukon
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years          8712.0   968.000000   885.0   924.0  1281.0     9
25 to 34 years         22260.0  1484.000000  1292.0  1416.0  1870.0    15
35 to 44 years         25897.0  1726.466667  1424.0  1794.0  1957.0    15
45 to 54 years         26108.0  1740.533333  1600.0  1683.0  2000.0    15
55 to 64 years         22232.0  1482.133333  1377.0  1474.0  1728.0    15
65 years old and over   6443.0   715.888889   565.0   719.0   850.0     9

Overall,
Sum :  111652.0
Mean :  1431.4358974358975
Min/median/max : 565.0 / 1491.0 / 2000.0
Skewnewss :  -0.7102658286319622
Total size :  78
2013

Grab the dataset only in Yukon
       REF_DATE    GEO                                             Sector  \
33393      2013  Yukon                      Total non-profit institutions
33400      2013  Yukon                      Total non-profit institutions
33519      2013  Yukon  Total non-profit institutions excluding govern...
33526      2013  Yukon  Total non-profit institutions excluding govern...
33645      2013  Yukon  Non-profit institutions serving households (co...
33652      2013  Yukon  Non-profit institutions serving households (co...
33771      2013  Yukon                   Business non-profit institutions
33778      2013  Yukon                   Business non-profit institutions
33897      2013  Yukon                 Government non-profit institutions
33904      2013  Yukon                 Government non-profit institutions
42213      2014  Yukon                      Total non-profit institutions
42220      2014  Yukon                      Total non-profit institutions
42339      2014  Yukon  Total non-profit institutions excluding govern...
42346      2014  Yukon  Total non-profit institutions excluding govern...
42465      2014  Yukon  Non-profit institutions serving households (co...
42472      2014  Yukon  Non-profit institutions serving households (co...
42591      2014  Yukon                   Business non-profit institutions
42598      2014  Yukon                   Business non-profit institutions
42717      2014  Yukon                 Government non-profit institutions
42724      2014  Yukon                 Government non-profit institutions

        Characteristics                   Indicators    UOM SCALAR_FACTOR  \
33393    Male employees  Average annual hours worked  Hours         units
33400  Female employees  Average annual hours worked  Hours         units
33519    Male employees  Average annual hours worked  Hours         units
33526  Female employees  Average annual hours worked  Hours         units
33645    Male employees  Average annual hours worked  Hours         units
33652  Female employees  Average annual hours worked  Hours         units
33771    Male employees  Average annual hours worked  Hours         units
33778  Female employees  Average annual hours worked  Hours         units
33897    Male employees  Average annual hours worked  Hours         units
33904  Female employees  Average annual hours worked  Hours         units
42213    Male employees  Average annual hours worked  Hours         units
42220  Female employees  Average annual hours worked  Hours         units
42339    Male employees  Average annual hours worked  Hours         units
42346  Female employees  Average annual hours worked  Hours         units
42465    Male employees  Average annual hours worked  Hours         units
42472  Female employees  Average annual hours worked  Hours         units
42591    Male employees  Average annual hours worked  Hours         units
42598  Female employees  Average annual hours worked  Hours         units
42717    Male employees  Average annual hours worked  Hours         units
42724  Female employees  Average annual hours worked  Hours         units

        VALUE
33393  1780.0
33400  1386.0
33519  1689.0
33526  1315.0
33645  1669.0
33652  1304.0
33771  1778.0
33778  1511.0
33897  1908.0
33904  1466.0
42213  1809.0
42220  1353.0
42339  1702.0
42346  1268.0
42465  1698.0
42472  1253.0
42591  1684.0
42598  1500.0
42717  1977.0
42724  1449.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 33393 to 51544
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         30 non-null     int64
 1   GEO              30 non-null     object
 2   Sector           30 non-null     object
 3   Characteristics  30 non-null     object
 4   Indicators       30 non-null     object
 5   UOM              30 non-null     object
 6   SCALAR_FACTOR    30 non-null     object
 7   VALUE            30 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.1+ KB
None

Grab the dataset only in Yukon
                      sum         mean    amin  median    amax  size
Characteristics
Female employees  20611.0  1374.066667  1231.0  1353.0  1566.0    15
Male employees    26762.0  1784.133333  1669.0  1778.0  1977.0    15

Overall,
Sum :  47373.0
Mean :  1579.1
Min/median/max : 1231.0 / 1617.5 / 1977.0
Skewnewss :  -0.021048417396863577
Total size :  30
2016

Grab the dataset only in Yukon
       REF_DATE    GEO                                             Sector  \
59853      2016  Yukon                      Total non-profit institutions
59860      2016  Yukon                      Total non-profit institutions
59979      2016  Yukon  Total non-profit institutions excluding govern...
59986      2016  Yukon  Total non-profit institutions excluding govern...
60105      2016  Yukon  Non-profit institutions serving households (co...
60112      2016  Yukon  Non-profit institutions serving households (co...
60231      2016  Yukon                   Business non-profit institutions
60238      2016  Yukon                   Business non-profit institutions
60357      2016  Yukon                 Government non-profit institutions
60364      2016  Yukon                 Government non-profit institutions

Panda Profiling for Final Result for Yukon

In [127]:
# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByAge_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByAge_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByAge_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByAge_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByGende_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByGender_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByGender_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByGender_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByEducation_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2010_ByEducation_Provinces, ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2013_ByEducation_Provinces, ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces, ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(df_AvgAnnHrsWrk_2019_ByEducation_Provinces, ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

Display all of the indicators, characteristics, and provinces will display too much to analysis.<br />
Therefore, I made custom code below to display output for speciic province and the indicators<br />
Characteristics (Age, gender, education, immigrant) still display all of them.<br />
To use, enter province name (string) and the indicator (in numeric 0-6).<br />

In [128]:
# https://realpython.com/python-raise-exception/
# https://www.geeksforgeeks.org/check-multiple-conditions-in-if-statement-python/

list_of_province = ['Alberta',  'British Columbia', 'Canada', 'Manitoba', 'New Brunswick', 'Newfoundland and Labrador', 
                    'Northwest Territories' , 'Nova Scotia' , 'Nunavut', 'Ontario' , 
                    'Prince Edward Island', 'Quebec', 'Saskatchewan', 'Yukon']
categorized_province = input('Enter your province name:')
categorized_province = categorized_province.lower()
categorized_province_analysis = "Invalid"
for x in list_of_province:
    if (x.lower() == categorized_province) :
        categorized_province_analysis = x
        break

list_indicator = ["Average annual hours worked",
             "Average annual wages and salaries",
             "Average hourly wage",
             "Average weekly hours worked",
             "Hours Worked", 
             "Number of jobs", 
             "Wages and Salaries"]
categorized_indicator = ""
categorized_indcator_analysis = "Invalid"

if categorized_province_analysis == "Invalid":
    print("Run this code again, this province doesn't exist.")
    print("End of Program")

else:
    print("Enter your indicator attributes, ")
    print("0. Average annual hours worked")
    print("1. Average annual wages and salaries")
    print("2. Average hourly wage")
    print("3. Average weekly hours worked")
    print("4. Hours Worked")
    print("5. Number of jobs")
    print("6. Wages and Salaries")
    categorized_indicator = input('Enter your indicator number:')
    try:
        categorized_indicator = int(categorized_indicator)
    except ValueError:
        if not type(categorized_indicator) is int:
            print("Run this code again, invalid integer")
            print("End of Program")
    try:
        categorized_indicator_analysis = list_indicator[categorized_indicator]
    except IndexError:
        print("Run this code again, invalid range (0-6)")
        print("End of Program")

    if categorized_province_analysis == "Invalid":
        print("End of Program")
    else:
        num = 0
        for x in list_of_province:
            if (categorized_province_analysis == x) :
                ProCode = num
                break
            else:
                num = num + 1
        if categorized_indicator == 0:
            categorized_indicator_analysis = []
            categorized_indicator_analysis.append("") # df_AvgAnnHrsWrk_2010_ByAge_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnHrsWrk_2013_ByAge_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnHrsWrk_2016_ByAge_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnHrsWrk_2019_ByAge_Provinces)
            categorized_indicator_analysis.append("") # df_AvgAnnHrsWrk_2010_ByGender_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnHrsWrk_2013_ByGender_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnHrsWrk_2016_ByGender_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnHrsWrk_2019_ByGender_Provinces)
            categorized_indicator_analysis.append("") # df_AvgAnnHrsWrk_2010_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnHrsWrk_2013_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnHrsWrk_2016_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnHrsWrk_2019_ByEducation_Provinces)
            categorized_indicator_analysis.append("") # df_AvgAnnHrsWrk_2010_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnHrsWrk_2013_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnHrsWrk_2016_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnHrsWrk_2019_ByImmigrant_Provinces)
        elif categorized_indicator == 1:
            categorized_indicator_analysis = []
            categorized_indicator_analysis.append("") # df_AvgAnnWages_2010_ByAge_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnWages_2013_ByAge_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnWages_2016_ByAge_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnWages_2019_ByAge_Provinces)
            categorized_indicator_analysis.append("") # df_AvgAnnWages_2010_ByGender_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnWages_2013_ByGender_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnWages_2016_ByGender_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnWages_2019_ByGender_Provinces)
            categorized_indicator_analysis.append("") # df_AvgAnnWages_2010_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnWages_2013_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnWages_2016_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnWages_2019_ByEducation_Provinces)
            categorized_indicator_analysis.append("") # df_AvgAnnWages_2010_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnWages_2013_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnWages_2016_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_AvgAnnWages_2019_ByImmigrant_Provinces)
        elif categorized_indicator == 2:
            categorized_indicator_analysis = []
            categorized_indicator_analysis.append("") # df_AvgHrsWages_2010_ByAge_Provinces)
            categorized_indicator_analysis.append(df_AvgHrsWages_2013_ByAge_Provinces)
            categorized_indicator_analysis.append(df_AvgHrsWages_2016_ByAge_Provinces)
            categorized_indicator_analysis.append(df_AvgHrsWages_2019_ByAge_Provinces)
            categorized_indicator_analysis.append("") # df_AvgHrsWages_2010_ByGender_Provinces)
            categorized_indicator_analysis.append(df_AvgHrsWages_2013_ByGender_Provinces)
            categorized_indicator_analysis.append(df_AvgHrsWages_2016_ByGender_Provinces)
            categorized_indicator_analysis.append(df_AvgHrsWages_2019_ByGender_Provinces)
            categorized_indicator_analysis.append("") # df_AvgHrsWages_2010_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_AvgHrsWages_2013_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_AvgHrsWages_2016_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_AvgHrsWages_2019_ByEducation_Provinces)
            categorized_indicator_analysis.append("") # df_AvgHrsWages_2010_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_AvgHrsWages_2013_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_AvgHrsWages_2016_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_AvgHrsWages_2019_ByImmigrant_Provinces)
        elif categorized_indicator == 3:
            categorized_indicator_analysis = []
            categorized_indicator_analysis.append("") # df_AvgWeekHrsWrked_2010_ByAge_Provinces)
            categorized_indicator_analysis.append(df_AvgWeekHrsWrked_2013_ByAge_Provinces)
            categorized_indicator_analysis.append(df_AvgWeekHrsWrked_2016_ByAge_Provinces)
            categorized_indicator_analysis.append(df_AvgWeekHrsWrked_2019_ByAge_Provinces)
            categorized_indicator_analysis.append("") # df_AvgWeekHrsWrked_2010_ByGender_Provinces)
            categorized_indicator_analysis.append(df_AvgWeekHrsWrked_2013_ByGender_Provinces)
            categorized_indicator_analysis.append(df_AvgWeekHrsWrked_2016_ByGender_Provinces)
            categorized_indicator_analysis.append(df_AvgWeekHrsWrked_2019_ByGender_Provinces)
            categorized_indicator_analysis.append("") # df_AvgWeekHrsWrked_2010_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_AvgWeekHrsWrked_2013_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_AvgWeekHrsWrked_2016_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_AvgWeekHrsWrked_2019_ByEducation_Provinces)
            categorized_indicator_analysis.append("") # df_AvgWeekHrsWrked_2010_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_AvgWeekHrsWrked_2013_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_AvgWeekHrsWrked_2016_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_AvgWeekHrsWrked_2019_ByImmigrant_Provinces)
        elif categorized_indicator == 4:
            categorized_indicator_analysis = []
            categorized_indicator_analysis.append("") # df_Hrs_Wrked_2010_ByAge_Provinces)
            categorized_indicator_analysis.append(df_Hrs_Wrked_2013_ByAge_Provinces)
            categorized_indicator_analysis.append(df_Hrs_Wrked_2016_ByAge_Provinces)
            categorized_indicator_analysis.append(df_Hrs_Wrked_2019_ByAge_Provinces)
            categorized_indicator_analysis.append("") # df_Hrs_Wrked_2010_ByGender_Provinces)
            categorized_indicator_analysis.append(df_Hrs_Wrked_2013_ByGender_Provinces)
            categorized_indicator_analysis.append(df_Hrs_Wrked_2016_ByGender_Provinces)
            categorized_indicator_analysis.append(df_Hrs_Wrked_2019_ByGender_Provinces)
            categorized_indicator_analysis.append("") # df_Hrs_Wrked_2010_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_Hrs_Wrked_2013_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_Hrs_Wrked_2016_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_Hrs_Wrked_2019_ByEducation_Provinces)
            categorized_indicator_analysis.append("") # df_Hrs_Wrked_2010_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_Hrs_Wrked_2013_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_Hrs_Wrked_2016_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_Hrs_Wrked_2019_ByImmigrant_Provinces)
        elif categorized_indicator == 5:
            categorized_indicator_analysis = []
            categorized_indicator_analysis.append("") # df_NumOfJob_2010_ByAge_Provinces)
            categorized_indicator_analysis.append(df_NumOfJob_2013_ByAge_Provinces)
            categorized_indicator_analysis.append(df_NumOfJob_2016_ByAge_Provinces)
            categorized_indicator_analysis.append(df_NumOfJob_2019_ByAge_Provinces)
            categorized_indicator_analysis.append("") # df_NumOfJob_2010_ByGender_Provinces)
            categorized_indicator_analysis.append(df_NumOfJob_2013_ByGender_Provinces)
            categorized_indicator_analysis.append(df_NumOfJob_2016_ByGender_Provinces)
            categorized_indicator_analysis.append(df_NumOfJob_2019_ByGender_Provinces)
            categorized_indicator_analysis.append("") # df_NumOfJob_2010_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_NumOfJob_2013_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_NumOfJob_2016_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_NumOfJob_2019_ByEducation_Provinces)
            categorized_indicator_analysis.append("") # df_NumOfJob_2010_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_NumOfJob_2013_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_NumOfJob_2016_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_NumOfJob_2019_ByImmigrant_Provinces)
        elif categorized_indicator == 6:
            categorized_indicator_analysis = []
            categorized_indicator_analysis.append("") # df_WagesAndSalaries_2010_ByAge_Provinces)
            categorized_indicator_analysis.append(df_WagesAndSalaries_2013_ByAge_Provinces)
            categorized_indicator_analysis.append(df_WagesAndSalaries_2016_ByAge_Provinces)
            categorized_indicator_analysis.append(df_WagesAndSalaries_2019_ByAge_Provinces)
            categorized_indicator_analysis.append("") # df_WagesAndSalaries_2010_ByGender_Provinces)
            categorized_indicator_analysis.append(df_WagesAndSalaries_2013_ByGender_Provinces)
            categorized_indicator_analysis.append(df_WagesAndSalaries_2016_ByGender_Provinces)
            categorized_indicator_analysis.append(df_WagesAndSalaries_2019_ByGender_Provinces)
            categorized_indicator_analysis.append("") # df_WagesAndSalaries_2010_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_WagesAndSalaries_2013_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_WagesAndSalaries_2016_ByEducation_Provinces)
            categorized_indicator_analysis.append(df_WagesAndSalaries_2019_ByEducation_Provinces)
            categorized_indicator_analysis.append("") # df_WagesAndSalaries_2010_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_WagesAndSalaries_2013_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_WagesAndSalaries_2016_ByImmigrant_Provinces)
            categorized_indicator_analysis.append(df_WagesAndSalaries_2019_ByImmigrant_Provinces)
        else:
            pass
        print("The province name is "+categorized_province_analysis)
        print("The indicator name is "+list_indicator[categorized_indicator])
        print("From here, the ProCode will be "+str(ProCode))
        print("The array from categorized_indicator_analysis is")
        print(categorized_indicator_analysis)

Enter your indicator attributes,
0. Average annual hours worked
1. Average annual wages and salaries
2. Average hourly wage
3. Average weekly hours worked
4. Hours Worked
5. Number of jobs
6. Wages and Salaries
The province name is Ontario
The indicator name is Average annual hours worked
From here, the ProCode will be 9
The array from categorized_indicator_analysis is
['', <__main__.ProvinceAnalysis object at 0x00000282670046D0>, <__main__.ProvinceAnalysis object at 0x0000028267004370>, <__main__.ProvinceAnalysis object at 0x0000028267004E80>, '', <__main__.ProvinceAnalysis object at 0x0000028267004A30>, <__main__.ProvinceAnalysis object at 0x0000028266B1A520>, <__main__.ProvinceAnalysis object at 0x00000282653A1F40>, '', <__main__.ProvinceAnalysis object at 0x0000028266E56400>, <__main__.ProvinceAnalysis object at 0x00000282660DBAF0>, <__main__.ProvinceAnalysis object at 0x0000028266B1E7C0>, '', <__main__.ProvinceAnalysis object at 0x000002826649F370>, <__main__.ProvinceAnalysis object at 0x000002826617DFA0>, <__main__.ProvinceAnalysis object at 0x00000282665E80D0>]

Filtering based on ProCode and indicator given above. <br />
Must run the code above to run this code. <br />

In [129]:
# This code need code above.

# df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[0], ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[1], ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[2], ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[3], ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[4], ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[5], ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[6], ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[7], ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[8], ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[9], ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[10], ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[11], ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

# df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[12], ProCode, "2010", pd, np, pp)
# df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[13], ProCode, "2013", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[14], ProCode, "2016", pd, np, pp)
df_Display_Output_Result.OutputResult()
df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[15], ProCode, "2019", pd, np, pp)
df_Display_Output_Result.OutputResult()

2013

Grab the dataset only in Ontario
       REF_DATE      GEO                                             Sector  \
30327      2013  Ontario                      Total non-profit institutions
30334      2013  Ontario                      Total non-profit institutions
30341      2013  Ontario                      Total non-profit institutions
30348      2013  Ontario                      Total non-profit institutions
30355      2013  Ontario                      Total non-profit institutions
30362      2013  Ontario                      Total non-profit institutions
30453      2013  Ontario  Total non-profit institutions excluding govern...
30460      2013  Ontario  Total non-profit institutions excluding govern...
30467      2013  Ontario  Total non-profit institutions excluding govern...
30474      2013  Ontario  Total non-profit institutions excluding govern...
30481      2013  Ontario  Total non-profit institutions excluding govern...
30488      2013  Ontario  Total non-profit institutions excluding govern...
30579      2013  Ontario  Non-profit institutions serving households (co...
30586      2013  Ontario  Non-profit institutions serving households (co...
30593      2013  Ontario  Non-profit institutions serving households (co...
30600      2013  Ontario  Non-profit institutions serving households (co...
30607      2013  Ontario  Non-profit institutions serving households (co...
30614      2013  Ontario  Non-profit institutions serving households (co...
30705      2013  Ontario                   Business non-profit institutions
30712      2013  Ontario                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
30327         15 to 24 years  Average annual hours worked  Hours
30334         25 to 34 years  Average annual hours worked  Hours
30341         35 to 44 years  Average annual hours worked  Hours
30348         45 to 54 years  Average annual hours worked  Hours
30355         55 to 64 years  Average annual hours worked  Hours
30362  65 years old and over  Average annual hours worked  Hours
30453         15 to 24 years  Average annual hours worked  Hours
30460         25 to 34 years  Average annual hours worked  Hours
30467         35 to 44 years  Average annual hours worked  Hours
30474         45 to 54 years  Average annual hours worked  Hours
30481         55 to 64 years  Average annual hours worked  Hours
30488  65 years old and over  Average annual hours worked  Hours
30579         15 to 24 years  Average annual hours worked  Hours
30586         25 to 34 years  Average annual hours worked  Hours
30593         35 to 44 years  Average annual hours worked  Hours
30600         45 to 54 years  Average annual hours worked  Hours
30607         55 to 64 years  Average annual hours worked  Hours
30614  65 years old and over  Average annual hours worked  Hours
30705         15 to 24 years  Average annual hours worked  Hours
30712         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
30327         units   835.0
30334         units  1580.0
30341         units  1774.0
30348         units  1837.0
30355         units  1702.0
30362         units  1041.0
30453         units   845.0
30460         units  1669.0
30467         units  1806.0
30474         units  1863.0
30481         units  1717.0
30488         units  1060.0
30579         units   839.0
30586         units  1628.0
30593         units  1763.0
30600         units  1830.0
30607         units  1691.0
30614         units  1044.0
30705         units   857.0
30712         units  1788.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 30327 to 48506
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Ontario
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         12561.0   837.400000   824.0   836.0   857.0    15
25 to 34 years         24473.0  1631.533333  1527.0  1611.0  1788.0    15
35 to 44 years         26974.0  1798.266667  1731.0  1769.0  1941.0    15
45 to 54 years         27822.0  1854.800000  1795.0  1831.0  1967.0    15
55 to 64 years         25858.0  1723.866667  1679.0  1713.0  1822.0    15
65 years old and over  16363.0  1090.866667  1027.0  1092.0  1192.0    15

Overall,
Sum :  134051.0
Mean :  1489.4555555555555
Min/median/max : 824.0 / 1693.0 / 1967.0
Skewnewss :  -0.6827679863947949
Total size :  90
2016

Grab the dataset only in Ontario
       REF_DATE      GEO                                             Sector  \
56787      2016  Ontario                      Total non-profit institutions
56794      2016  Ontario                      Total non-profit institutions
56801      2016  Ontario                      Total non-profit institutions
56808      2016  Ontario                      Total non-profit institutions
56815      2016  Ontario                      Total non-profit institutions
56822      2016  Ontario                      Total non-profit institutions
56913      2016  Ontario  Total non-profit institutions excluding govern...
56920      2016  Ontario  Total non-profit institutions excluding govern...
56927      2016  Ontario  Total non-profit institutions excluding govern...
56934      2016  Ontario  Total non-profit institutions excluding govern...
56941      2016  Ontario  Total non-profit institutions excluding govern...
56948      2016  Ontario  Total non-profit institutions excluding govern...
57039      2016  Ontario  Non-profit institutions serving households (co...
57046      2016  Ontario  Non-profit institutions serving households (co...
57053      2016  Ontario  Non-profit institutions serving households (co...
57060      2016  Ontario  Non-profit institutions serving households (co...
57067      2016  Ontario  Non-profit institutions serving households (co...
57074      2016  Ontario  Non-profit institutions serving households (co...
57165      2016  Ontario                   Business non-profit institutions
57172      2016  Ontario                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
56787         15 to 24 years  Average annual hours worked  Hours
56794         25 to 34 years  Average annual hours worked  Hours
56801         35 to 44 years  Average annual hours worked  Hours
56808         45 to 54 years  Average annual hours worked  Hours
56815         55 to 64 years  Average annual hours worked  Hours
56822  65 years old and over  Average annual hours worked  Hours
56913         15 to 24 years  Average annual hours worked  Hours
56920         25 to 34 years  Average annual hours worked  Hours
56927         35 to 44 years  Average annual hours worked  Hours
56934         45 to 54 years  Average annual hours worked  Hours
56941         55 to 64 years  Average annual hours worked  Hours
56948  65 years old and over  Average annual hours worked  Hours
57039         15 to 24 years  Average annual hours worked  Hours
57046         25 to 34 years  Average annual hours worked  Hours
57053         35 to 44 years  Average annual hours worked  Hours
57060         45 to 54 years  Average annual hours worked  Hours
57067         55 to 64 years  Average annual hours worked  Hours
57074  65 years old and over  Average annual hours worked  Hours
57165         15 to 24 years  Average annual hours worked  Hours
57172         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
56787         units   849.0
56794         units  1595.0
56801         units  1773.0
56808         units  1841.0
56815         units  1717.0
56822         units  1083.0
56913         units   839.0
56920         units  1649.0
56927         units  1782.0
56934         units  1841.0
56941         units  1707.0
56948         units  1073.0
57039         units   832.0
57046         units  1604.0
57053         units  1734.0
57060         units  1801.0
57067         units  1673.0
57074         units  1054.0
57165         units   856.0
57172         units  1775.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 56787 to 74966
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Ontario
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         12772.0   851.466667   832.0   854.0   875.0    15
25 to 34 years         24540.0  1636.000000  1561.0  1604.0  1775.0    15
35 to 44 years         26880.0  1792.000000  1728.0  1773.0  1929.0    15
45 to 54 years         27896.0  1859.733333  1801.0  1842.0  1965.0    15
55 to 64 years         25896.0  1726.400000  1653.0  1717.0  1816.0    15
65 years old and over  16172.0  1078.133333  1015.0  1069.0  1157.0    15

Overall,
Sum :  134156.0
Mean :  1490.6222222222223
Min/median/max : 832.0 / 1682.0 / 1965.0
Skewnewss :  -0.6698748437878889
Total size :  90
2019

Grab the dataset only in Ontario
       REF_DATE      GEO                                             Sector  \
83247      2019  Ontario                      Total non-profit institutions
83254      2019  Ontario                      Total non-profit institutions
83261      2019  Ontario                      Total non-profit institutions
83268      2019  Ontario                      Total non-profit institutions
83275      2019  Ontario                      Total non-profit institutions
83282      2019  Ontario                      Total non-profit institutions
83373      2019  Ontario  Total non-profit institutions excluding govern...
83380      2019  Ontario  Total non-profit institutions excluding govern...
83387      2019  Ontario  Total non-profit institutions excluding govern...
83394      2019  Ontario  Total non-profit institutions excluding govern...
83401      2019  Ontario  Total non-profit institutions excluding govern...
83408      2019  Ontario  Total non-profit institutions excluding govern...
83499      2019  Ontario  Non-profit institutions serving households (co...
83506      2019  Ontario  Non-profit institutions serving households (co...
83513      2019  Ontario  Non-profit institutions serving households (co...
83520      2019  Ontario  Non-profit institutions serving households (co...
83527      2019  Ontario  Non-profit institutions serving households (co...
83534      2019  Ontario  Non-profit institutions serving households (co...
83625      2019  Ontario                   Business non-profit institutions
83632      2019  Ontario                   Business non-profit institutions

             Characteristics                   Indicators    UOM  \
83247         15 to 24 years  Average annual hours worked  Hours
83254         25 to 34 years  Average annual hours worked  Hours
83261         35 to 44 years  Average annual hours worked  Hours
83268         45 to 54 years  Average annual hours worked  Hours
83275         55 to 64 years  Average annual hours worked  Hours
83282  65 years old and over  Average annual hours worked  Hours
83373         15 to 24 years  Average annual hours worked  Hours
83380         25 to 34 years  Average annual hours worked  Hours
83387         35 to 44 years  Average annual hours worked  Hours
83394         45 to 54 years  Average annual hours worked  Hours
83401         55 to 64 years  Average annual hours worked  Hours
83408  65 years old and over  Average annual hours worked  Hours
83499         15 to 24 years  Average annual hours worked  Hours
83506         25 to 34 years  Average annual hours worked  Hours
83513         35 to 44 years  Average annual hours worked  Hours
83520         45 to 54 years  Average annual hours worked  Hours
83527         55 to 64 years  Average annual hours worked  Hours
83534  65 years old and over  Average annual hours worked  Hours
83625         15 to 24 years  Average annual hours worked  Hours
83632         25 to 34 years  Average annual hours worked  Hours

      SCALAR_FACTOR   VALUE
83247         units   865.0
83254         units  1579.0
83261         units  1745.0
83268         units  1831.0
83275         units  1708.0
83282         units  1056.0
83373         units   847.0
83380         units  1631.0
83387         units  1757.0
83394         units  1830.0
83401         units  1690.0
83408         units  1060.0
83499         units   843.0
83506         units  1589.0
83513         units  1716.0
83520         units  1794.0
83527         units  1657.0
83534         units  1038.0
83625         units   856.0
83632         units  1755.0
<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 83247 to 101426
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         90 non-null     int64
 1   GEO              90 non-null     object
 2   Sector           90 non-null     object
 3   Characteristics  90 non-null     object
 4   Indicators       90 non-null     object
 5   UOM              90 non-null     object
 6   SCALAR_FACTOR    90 non-null     object
 7   VALUE            90 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None

Grab the dataset only in Ontario
                           sum         mean    amin  median    amax  size
Characteristics
15 to 24 years         13099.0   873.266667   823.0   872.0   932.0    15
25 to 34 years         24347.0  1623.133333  1529.0  1600.0  1765.0    15
35 to 44 years         26457.0  1763.800000  1647.0  1755.0  1884.0    15
45 to 54 years         27665.0  1844.333333  1722.0  1832.0  1945.0    15
55 to 64 years         25732.0  1715.466667  1592.0  1708.0  1806.0    15
65 years old and over  16252.0  1083.466667  1005.0  1071.0  1192.0    15

Overall,
Sum :  133552.0
Mean :  1483.911111111111
Min/median/max : 823.0 / 1652.0 / 1945.0
Skewnewss :  -0.6561285966673744
Total size :  90
2013

Grab the dataset only in Ontario
       REF_DATE      GEO                                             Sector  \
30243      2013  Ontario                      Total non-profit institutions
30250      2013  Ontario                      Total non-profit institutions
30369      2013  Ontario  Total non-profit institutions excluding govern...
30376      2013  Ontario  Total non-profit institutions excluding govern...
30495      2013  Ontario  Non-profit institutions serving households (co...
30502      2013  Ontario  Non-profit institutions serving households (co...
30621      2013  Ontario                   Business non-profit institutions
30628      2013  Ontario                   Business non-profit institutions
30747      2013  Ontario                 Government non-profit institutions
30754      2013  Ontario                 Government non-profit institutions
39063      2014  Ontario                      Total non-profit institutions
39070      2014  Ontario                      Total non-profit institutions
39189      2014  Ontario  Total non-profit institutions excluding govern...
39196      2014  Ontario  Total non-profit institutions excluding govern...
39315      2014  Ontario  Non-profit institutions serving households (co...
39322      2014  Ontario  Non-profit institutions serving households (co...
39441      2014  Ontario                   Business non-profit institutions
39448      2014  Ontario                   Business non-profit institutions
39567      2014  Ontario                 Government non-profit institutions
39574      2014  Ontario                 Government non-profit institutions

        Characteristics                   Indicators    UOM SCALAR_FACTOR  \
30243    Male employees  Average annual hours worked  Hours         units
30250  Female employees  Average annual hours worked  Hours         units
30369    Male employees  Average annual hours worked  Hours         units
30376  Female employees  Average annual hours worked  Hours         units
30495    Male employees  Average annual hours worked  Hours         units
30502  Female employees  Average annual hours worked  Hours         units
30621    Male employees  Average annual hours worked  Hours         units
30628  Female employees  Average annual hours worked  Hours         units
30747    Male employees  Average annual hours worked  Hours         units
30754  Female employees  Average annual hours worked  Hours         units
39063    Male employees  Average annual hours worked  Hours         units
39070  Female employees  Average annual hours worked  Hours         units
39189    Male employees  Average annual hours worked  Hours         units
39196  Female employees  Average annual hours worked  Hours         units
39315    Male employees  Average annual hours worked  Hours         units
39322  Female employees  Average annual hours worked  Hours         units
39441    Male employees  Average annual hours worked  Hours         units
39448  Female employees  Average annual hours worked  Hours         units
39567    Male employees  Average annual hours worked  Hours         units
39574  Female employees  Average annual hours worked  Hours         units

        VALUE
30243  1619.0
30250  1569.0
30369  1681.0
30376  1558.0
30495  1667.0
30502  1539.0
30621  1712.0
30628  1629.0
30747  1572.0
30754  1575.0
39063  1613.0
39070  1565.0
39189  1666.0
39196  1550.0
39315  1650.0
39322  1538.0
39441  1699.0
39448  1598.0
39567  1572.0
39574  1574.0
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 30243 to 48394
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   REF_DATE         30 non-null     int64
 1   GEO              30 non-null     object
 2   Sector           30 non-null     object
 3   Characteristics  30 non-null     object
 4   Indicators       30 non-null     object
 5   UOM              30 non-null     object
 6   SCALAR_FACTOR    30 non-null     object
 7   VALUE            30 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.1+ KB
None

Grab the dataset only in Ontario
                      sum         mean    amin  median    amax  size
Characteristics
Female employees  23558.0  1570.533333  1526.0  1569.0  1629.0    15
Male employees    24668.0  1644.533333  1572.0  1650.0  1728.0    15

Overall,
Sum :  48226.0
Mean :  1607.5333333333333
Min/median/max : 1526.0 / 1595.5 / 1728.0
Skewnewss :  0.5866021538529981
Total size :  30
2016

Grab the dataset only in Ontario
       REF_DATE      GEO                                             Sector  \
56703      2016  Ontario                      Total non-profit institutions
56710      2016  Ontario                      Total non-profit institutions
56829      2016  Ontario  Total non-profit institutions excluding govern...
56836      2016  Ontario  Total non-profit institutions excluding govern...
56955      2016  Ontario  Non-profit institutions serving households (co...
56962      2016  Ontario  Non-profit institutions serving households (co...
57081      2016  Ontario                   Business non-profit institutions

Panda Profiling based on ProCode and indicator given above. <br />
Must run the code above to run this code. <br />

In [130]:
# # df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[0], ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[1], ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[2], ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[3], ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[4], ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[5], ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[6], ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[7], ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[8], ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[9], ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[10], ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[11], ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()

# # df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[12], ProCode, "2010", pd, np, pp)
# # df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[13], ProCode, "2013", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[14], ProCode, "2016", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()
# df_Display_Output_Result = OutputProvinceAnalysis(categorized_indicator_analysis[15], ProCode, "2019", pd, np, pp)
# df_Display_Output_Result.OutputPandaProfiling()